# AQUA20 Final Beat-Base Campaign — 04-07-2026 Plan

Official keyword: **04-07-2026 AQUA20 FINAL BEAT BASE PLAN**

Goal:
Beat the current AQUA20 YOLO result, especially YOLO26m-cls:
- Top-1 Accuracy: 92.68%
- Top-5 Accuracy: 99.64%
- Precision: 0.9388
- Recall: 0.9359
- F1-score: 0.9358

Rules:
- Use the same original train/val/test split for every experiment.
- Apply balancing/augmentation only to training data.
- Validation and test must remain unchanged.
- Save clean tables, figures, reports, XAI, ensemble results, and final package.

In [1]:
# ============================================================
# P100 FIX — Install compatible PyTorch
# Run this before importing torch
# ============================================================

import sys, subprocess, os

packages = [
    "torch==2.7.1",
    "torchvision==0.22.1",
    "torchaudio==2.7.1"
]

print("Uninstalling current torch packages...")
subprocess.run(
    [sys.executable, "-m", "pip", "uninstall", "-y", "torch", "torchvision", "torchaudio"],
    check=False
)

print("\nInstalling PyTorch CUDA 11.8 build...")
subprocess.run(
    [
        sys.executable, "-m", "pip", "install",
        "--no-cache-dir",
        "--force-reinstall",
        "torch==2.7.1",
        "torchvision==0.22.1",
        "torchaudio==2.7.1",
        "--index-url", "https://download.pytorch.org/whl/cu118"
    ],
    check=True
)

print("\n✅ Install command finished.")
print("Now DO NOT use Kaggle 'Restart session'.")
print("Use the next cell to restart the Python kernel safely.")

Uninstalling current torch packages...
Found existing installation: torch 2.10.0+cu128
Uninstalling torch-2.10.0+cu128:
  Successfully uninstalled torch-2.10.0+cu128
Found existing installation: torchvision 0.25.0+cu128
Uninstalling torchvision-0.25.0+cu128:
  Successfully uninstalled torchvision-0.25.0+cu128
Found existing installation: torchaudio 2.10.0+cu128
Uninstalling torchaudio-2.10.0+cu128:
  Successfully uninstalled torchaudio-2.10.0+cu128

Installing PyTorch CUDA 11.8 build...
Looking in indexes: https://download.pytorch.org/whl/cu118
Collecting torch==2.7.1
  Downloading https://download-r2.pytorch.org/whl/cu118/torch-2.7.1%2Bcu118-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (28 kB)
Collecting torchvision==0.22.1
  Downloading https://download-r2.pytorch.org/whl/cu118/torchvision-0.22.1%2Bcu118-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (6.1 kB)
Collecting torchaudio==2.7.1
  Downloading https://download-r2.pytorch.org/whl/cu118/torchaudio-2.7.1%2Bcu118-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting filelock (from torch==2.7.1)
  Downloading filelock-3.29.0-py3-none-any.whl.metadata (2.0 kB)
Collecting typing-extensions>=4.10.0 (from torch==2.7.1)
  Downloading https://download.pytorch.org/whl/typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting setuptools (from torch==2.7.1)
  Downloading https://download.pytorch.org/whl/setuptools-78.1.0-py3-none-any.whl.metadata (6.6 kB)
Collecting sympy>=1.13.3 (from torch==2.7.1)
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx (from torch==2.7.1)
  Downloading networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Collecting jinja2 (from torch==2.7.1)
  Downloading https://download.pytorch.org/whl/jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting fsspec (from torch==2.7.1)
  Downloading fsspec-2026.4.0-py3-none-any.whl.metadata (10 kB)
Collecting nvidia-cuda-nvrtc-cu11==11.8.89 (from torch==2.7.1)
  Downloading https://download.pytorch.org/whl/cu118/nvidia_cuda_nvrtc_cu11-11.8.89-py3-none-manylinux1_x86_64.whl (23.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.2/23.2 MB 282.7 MB/s eta 0:00:00
Collecting nvidia-cuda-runtime-cu11==11.8.89 (from torch==2.7.1)
  Downloading https://download.pytorch.org/whl/cu118/nvidia_cuda_runtime_cu11-11.8.89-py3-none-manylinux1_x86_64.whl (875 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 875.6/875.6 kB 342.5 MB/s eta 0:00:00
Collecting nvidia-cuda-cupti-cu11==11.8.87 (from torch==2.7.1)
  Downloading https://download.pytorch.org/whl/cu118/nvidia_cuda_cupti_cu11-11.8.87-py3-none-manylinux1_x86_64.whl (13.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 371.2 MB/s eta 0:00:00
Collecting nvidia-cudnn-cu11==9.1.0.70 (from torch==2.7.1)
  Downloading https://download.pytorch.org/whl/cu118/nvidia_cudnn_cu11-9.1.0.70-py3-none-manylinux2014_x86_64.whl (663.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 663.9/663.9 MB 369.4 MB/s eta 0:00:00
Collecting nvidia-cublas-cu11==11.11.3.6 (from torch==2.7.1)
  Downloading https://download.pytorch.org/whl/cu118/nvidia_cublas_cu11-11.11.3.6-py3-none-manylinux1_x86_64.whl (417.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 417.9/417.9 MB 355.0 MB/s eta 0:00:00
Collecting nvidia-cufft-cu11==10.9.0.58 (from torch==2.7.1)
  Downloading https://download.pytorch.org/whl/cu118/nvidia_cufft_cu11-10.9.0.58-py3-none-manylinux1_x86_64.whl (168.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 168.4/168.4 MB 272.7 MB/s eta 0:00:00
Collecting nvidia-curand-cu11==10.3.0.86 (from torch==2.7.1)
  Downloading https://download.pytorch.org/whl/cu118/nvidia_curand_cu11-10.3.0.86-py3-none-manylinux1_x86_64.whl (58.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.1/58.1 MB 268.9 MB/s eta 0:00:00
Collecting nvidia-cusolver-cu11==11.4.1.48 (from torch==2.7.1)
  Downloading https://download.pytorch.org/whl/cu118/nvidia_cusolver_cu11-11.4.1.48-py3-none-manylinux1_x86_64.whl (128.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.2/128.2 MB 248.5 MB/s eta 0:00:00
Collecting nvidia-cusparse-cu11==11.7.5.86 (from torch==2.7.1)
  Downloading https://download.pytorch.org/whl/cu118/nvidia_cusparse_cu11-11.7.5.86-py3-none-manylinux1_x86_64.whl (204.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 204.1/204.1 MB 306.2 MB/s eta 0:00:00
Collecting nvidia-nccl-cu11==2.21.5 (from torch==2.7.1)
  Downloading https://download.pytorch.org/whl/cu118/nvidia_nccl_cu11-2.21.5-py3-none-manylinux2014_x86_64.whl (147.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.8/147.8 MB 305.7 MB/s eta 0:00:00
Collecting nvidia-nvtx-cu11==11.8.86 (from torch==2.7.1)
  Downloading https://download.pytorch.org/whl/cu118/nvidia_nvtx_cu11-11.8.86-py3-none-manylinux1_x86_64.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 342.4 MB/s eta 0:00:00
Collecting triton==3.3.1 (from torch==2.7.1)
  Downloading https://download-r2.pytorch.org/whl/triton-3.3.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.5 kB)
Collecting numpy (from torchvision==0.22.1)
  Downloading numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting pillow!=8.3.*,>=5.3.0 (from torchvision==0.22.1)
  Downloading pillow-12.2.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.8 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch==2.7.1)
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch==2.7.1)
  Downloading https://download.pytorch.org/whl/markupsafe-3.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.7 kB)
Downloading https://download-r2.pytorch.org/whl/cu118/torch-2.7.1%2Bcu118-cp312-cp312-manylinux_2_28_x86_64.whl (905.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 905.2/905.2 MB 244.7 MB/s eta 0:00:00
Downloading https://download-r2.pytorch.org/whl/cu118/torchvision-0.22.1%2Bcu118-cp312-cp312-manylinux_2_28_x86_64.whl (6.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.7/6.7 MB 314.6 MB/s eta 0:00:00
Downloading https://download-r2.pytorch.org/whl/cu118/torchaudio-2.7.1%2Bcu118-cp312-cp312-manylinux_2_28_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 307.7 MB/s eta 0:00:00
Downloading https://download-r2.pytorch.org/whl/triton-3.3.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (155.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.7/155.7 MB 327.0 MB/s eta 0:00:00
Downloading pillow-12.2.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (7.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 18.6 MB/s eta 0:00:00
Downloading https://download.pytorch.org/whl/setuptools-78.1.0-py3-none-any.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 170.6 MB/s eta 0:00:00
Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 98.1 MB/s eta 0:00:00
Downloading https://download.pytorch.org/whl/typing_extensions-4.15.0-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.6/44.6 kB 248.1 MB/s eta 0:00:00
Downloading filelock-3.29.0-py3-none-any.whl (39 kB)
Downloading fsspec-2026.4.0-py3-none-any.whl (203 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.4/203.4 kB 345.8 MB/s eta 0:00:00
Downloading https://download.pytorch.org/whl/jinja2-3.1.6-py3-none-any.whl (134 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.9/134.9 kB 291.6 MB/s eta 0:00:00
Downloading networkx-3.6.1-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 311.6 MB/s eta 0:00:00
Downloading numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 82.8 MB/s eta 0:00:00
Downloading https://download.pytorch.org/whl/markupsafe-3.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (22 kB)
Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 301.1 MB/s eta 0:00:00
Installing collected packages: mpmath, typing-extensions, sympy, setuptools, pillow, nvidia-nvtx-cu11, nvidia-nccl-cu11, nvidia-cusparse-cu11, nvidia-curand-cu11, nvidia-cufft-cu11, nvidia-cuda-runtime-cu11, nvidia-cuda-nvrtc-cu11, nvidia-cuda-cupti-cu11, nvidia-cublas-cu11, numpy, networkx, MarkupSafe, fsspec, filelock, triton, nvidia-cusolver-cu11, nvidia-cudnn-cu11, jinja2, torch, torchvision, torchaudio
  Attempting uninstall: mpmath
    Found existing installation: mpmath 1.3.0
    Uninstalling mpmath-1.3.0:
      Successfully uninstalled mpmath-1.3.0
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.15.0
    Uninstalling typing_extensions-4.15.0:
      Successfully uninstalled typing_extensions-4.15.0
  Attempting uninstall: sympy
    Found existing installation: sympy 1.14.0
    Uninstalling sympy-1.14.0:
      Successfully uninstalled sympy-1.14.0
  Attempting uninstall: setuptools
    Found existing installation: setuptools 81.0.0
    Uninstalling setuptools-81.0.0:
      Successfully uninstalled setuptools-81.0.0
  Attempting uninstall: pillow
    Found existing installation: pillow 11.3.0
    Uninstalling pillow-11.3.0:
      Successfully uninstalled pillow-11.3.0
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: networkx
    Found existing installation: networkx 3.6.1
    Uninstalling networkx-3.6.1:
      Successfully uninstalled networkx-3.6.1
  Attempting uninstall: MarkupSafe
    Found existing installation: MarkupSafe 3.0.3
    Uninstalling MarkupSafe-3.0.3:
      Successfully uninstalled MarkupSafe-3.0.3
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.3.0
    Uninstalling fsspec-2025.3.0:
      Successfully uninstalled fsspec-2025.3.0
  Attempting uninstall: filelock
    Found existing installation: filelock 3.29.0
    Uninstalling filelock-3.29.0:
      Successfully uninstalled filelock-3.29.0
  Attempting uninstall: triton
    Found existing installation: triton 3.6.0
    Uninstalling triton-3.6.0:
      Successfully uninstalled triton-3.6.0
  Attempting uninstall: jinja2
    Found existing installation: Jinja2 3.1.6
    Uninstalling Jinja2-3.1.6:
      Successfully uninstalled Jinja2-3.1.6

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 2.39.0 requires google-cloud-bigquery-storage<3.0.0,>=2.30.0, which is not installed.
google-adk 1.29.0 requires google-cloud-bigquery-storage>=2.0.0, which is not installed.
ydata-profiling 4.18.4 requires numpy<2.4,>=1.22, but you have numpy 2.4.4 which is incompatible.
google-colab 1.0.0 requires jupyter-server==2.14.0, but you have jupyter-server 2.12.5 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.3.3 which is incompatible.
dopamine-rl 4.1.2 requires gym<=0.25.2, but you have gym 0.26.2 which is incompatible.
moviepy 1.0.3 requires decorator<5.0,>=4.0.2, but you have decorator 5.3.1 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.4.4 which is incompatible.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2026.4.0 which is incompatible.
gradio 5.50.0 requires pillow<12.0,>=8.0, but you have pillow 12.2.0 which is incompatible.

Successfully installed MarkupSafe-3.0.3 filelock-3.29.0 fsspec-2026.4.0 jinja2-3.1.6 mpmath-1.3.0 networkx-3.6.1 numpy-2.4.4 nvidia-cublas-cu11-11.11.3.6 nvidia-cuda-cupti-cu11-11.8.87 nvidia-cuda-nvrtc-cu11-11.8.89 nvidia-cuda-runtime-cu11-11.8.89 nvidia-cudnn-cu11-9.1.0.70 nvidia-cufft-cu11-10.9.0.58 nvidia-curand-cu11-10.3.0.86 nvidia-cusolver-cu11-11.4.1.48 nvidia-cusparse-cu11-11.7.5.86 nvidia-nccl-cu11-2.21.5 nvidia-nvtx-cu11-11.8.86 pillow-12.2.0 setuptools-78.1.0 sympy-1.14.0 torch-2.7.1+cu118 torchaudio-2.7.1+cu118 torchvision-0.22.1+cu118 triton-3.3.1 typing-extensions-4.15.0

✅ Install command finished.
Now DO NOT use Kaggle 'Restart session'.
Use the next cell to restart the Python kernel safely.

In [ ]:
# ============================================================
# Restart Python kernel after pip install
# Do not use Kaggle Restart Session button
# ============================================================

import os, sys
print("Restarting Python kernel now...")
os.execv(sys.executable, [sys.executable] + sys.argv)

In [1]:
# ============================================================
# P100 CUDA TEST AFTER INSTALL
# ============================================================

import torch
import torchvision
import platform

print("=" * 80)
print("P100 CUDA TEST AFTER INSTALL")
print("=" * 80)

print("Platform:", platform.platform())
print("Torch:", torch.__version__)
print("Torchvision:", torchvision.__version__)
print("Torch CUDA:", torch.version.cuda)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU count:", torch.cuda.device_count())
    print("GPU:", torch.cuda.get_device_name(0))
    print("Arch list:", torch.cuda.get_arch_list())

    props = torch.cuda.get_device_properties(0)
    print("Compute capability:", f"{props.major}.{props.minor}")
    print("Memory GB:", round(props.total_memory / 1024**3, 2))

    x = torch.randn(512, 512, device="cuda")
    y = x @ x
    print("✅ CUDA tensor test OK:", y.shape)
else:
    print("❌ CUDA is not available.")

================================================================================
P100 CUDA TEST AFTER INSTALL
================================================================================
Platform: Linux-6.12.90+-x86_64-with-glibc2.35
Torch: 2.7.1+cu118
Torchvision: 0.22.1+cu118
Torch CUDA: 11.8
CUDA available: True
GPU count: 1
GPU: Tesla P100-PCIE-16GB
Arch list: ['sm_50', 'sm_60', 'sm_70', 'sm_75', 'sm_80', 'sm_86', 'sm_37', 'sm_90']
Compute capability: 6.0
Memory GB: 15.89
✅ CUDA tensor test OK: torch.Size([512, 512])

In [2]:
# ============================================================
# CELL 1 — Official setup after P100 fix
# AQUA20 Final Beat-Base Campaign
# Keyword: 04-07-2026 AQUA20 FINAL BEAT BASE PLAN
# ============================================================

import os
import sys
import json
import math
import time
import shutil
import random
import zipfile
import hashlib
import platform
from pathlib import Path
from collections import Counter, defaultdict

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from PIL import Image, ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True

import torch
import torch.nn as nn
import torch.nn.functional as F

import torchvision
from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader, Dataset

from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support,
    classification_report,
    confusion_matrix
)

# -----------------------------
# Seed
# -----------------------------
SEED = 42

def seed_everything(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

    # Faster training; still stable enough for our campaign
    torch.backends.cudnn.deterministic = False
    torch.backends.cudnn.benchmark = True

seed_everything(SEED)

# -----------------------------
# Project folders
# -----------------------------
PROJECT_NAME = "AQUA20_FINAL_BEAT_BASE_04072026"
PROJECT_ROOT = Path("/kaggle/working") / PROJECT_NAME

DIRS = {
    "root": PROJECT_ROOT,
    "data_checks": PROJECT_ROOT / "data_checks",
    "balanced_train": PROJECT_ROOT / "balanced_train",
    "experiments": PROJECT_ROOT / "experiments",
    "tables": PROJECT_ROOT / "tables",
    "figures": PROJECT_ROOT / "figures",
    "xai": PROJECT_ROOT / "xai",
    "ensemble": PROJECT_ROOT / "ensemble",
    "packages": PROJECT_ROOT / "packages",
    "logs": PROJECT_ROOT / "logs",
}

for d in DIRS.values():
    d.mkdir(parents=True, exist_ok=True)

# -----------------------------
# Device check
# -----------------------------
assert torch.cuda.is_available(), "CUDA is not available. Stop and check GPU."

device = torch.device("cuda:0")
gpu_name = torch.cuda.get_device_name(0)
props = torch.cuda.get_device_properties(0)

print("=" * 80)
print("AQUA20 FINAL BEAT-BASE SETUP")
print("=" * 80)
print("Official plan keyword:", "04-07-2026 AQUA20 FINAL BEAT BASE PLAN")
print("Project root:", PROJECT_ROOT)
print("Seed:", SEED)
print("Python:", sys.version.split()[0])
print("Torch:", torch.__version__)
print("Torchvision:", torchvision.__version__)
print("Torch CUDA:", torch.version.cuda)
print("GPU:", gpu_name)
print("GPU memory GB:", round(props.total_memory / 1024**3, 2))
print("Compute capability:", f"{props.major}.{props.minor}")
print("Device:", device)

# Final CUDA sanity check
x = torch.randn(256, 256, device=device)
y = x @ x
print("CUDA sanity test:", y.shape, "✅")

# -----------------------------
# Save run config
# -----------------------------
RUN_CONFIG = {
    "project": PROJECT_NAME,
    "official_plan_keyword": "04-07-2026 AQUA20 FINAL BEAT BASE PLAN",
    "target_model_to_beat": "YOLO26m-cls",
    "target_top1_accuracy_percent": 92.68,
    "target_top5_accuracy_percent": 99.64,
    "target_precision": 0.9388,
    "target_recall": 0.9359,
    "target_f1": 0.9358,
    "seed": SEED,
    "gpu": gpu_name,
    "torch": torch.__version__,
    "torchvision": torchvision.__version__,
    "rule": "Use original train/val/test split. Balance/augment train only. Keep val/test unchanged.",
    "experiment_groups": {
        "G1": "Original train + CE/label smoothing",
        "G2": "Aug-200 train-only balancing",
        "G3": "Original train + Gentle Class-Balanced Focal Loss",
        "G4": "Aug-200 + Gentle Focal final optimistic method"
    },
    "priority_experiments": [
        "F00 data audit + Aug-200 creation",
        "F01 YOLO26m-cls + Aug-200",
        "F03 ConvNeXt-Small + Original + Gentle CB Focal",
        "F05 ConvNeXt-Small + Aug-200 + Gentle Focal",
        "F06 ConvNeXt-Small high-resolution fine-tune",
        "F07 ConvNeXt-Small high-resolution + TTA",
        "F10 ensemble best YOLO + best ConvNeXt + best EfficientNet"
    ]
}

config_path = DIRS["logs"] / "run_config_04072026.json"
with open(config_path, "w") as f:
    json.dump(RUN_CONFIG, f, indent=4)

print("\nSaved config:", config_path)

print("\nFolder structure:")
for name, path in DIRS.items():
    print(f"{name:<15}: {path}")

================================================================================
AQUA20 FINAL BEAT-BASE SETUP
================================================================================
Official plan keyword: 04-07-2026 AQUA20 FINAL BEAT BASE PLAN
Project root: /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026
Seed: 42
Python: 3.12.13
Torch: 2.7.1+cu118
Torchvision: 0.22.1+cu118
Torch CUDA: 11.8
GPU: Tesla P100-PCIE-16GB
GPU memory GB: 15.89
Compute capability: 6.0
Device: cuda:0
CUDA sanity test: torch.Size([256, 256]) ✅

Saved config: /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/logs/run_config_04072026.json

Folder structure:
root           : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026
data_checks    : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/data_checks
balanced_train : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/balanced_train
experiments    : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/experiments
tables         : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/tables
figures        : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/figures
xai            : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/xai
ensemble       : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/ensemble
packages       : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/packages
logs           : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/logs

## F00 — Step 1: Locate and verify original AQUA20 split

Purpose:
- Find the original AQUA20 dataset inside `/kaggle/input`
- Verify `train`, `val`, and `test` folders
- Confirm class folders match across all splits
- Save split summary tables

Important:
- Do not modify validation or test data.
- Do not create balanced data yet.

## F00 — Step 1B: Load AQUA20 from original Hugging Face source

Source:
- Hugging Face dataset: taufiktrf/AQUA20

Purpose:
- Load the original public AQUA20 dataset
- Check available splits
- Check class names and split counts
- Do not create augmented or balanced data yet

In [3]:
# F00 Step 1B — Load AQUA20 from original Hugging Face source

import sys
import subprocess
from pathlib import Path
import pandas as pd

HF_DATASET_ID = "taufiktrf/AQUA20"

PROJECT_ROOT = Path("/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026")
DATA_CHECKS_DIR = PROJECT_ROOT / "data_checks"
DATA_CHECKS_DIR.mkdir(parents=True, exist_ok=True)

# Install only if missing
try:
    from datasets import load_dataset
except ImportError:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "datasets"])
    from datasets import load_dataset

print("=" * 80)
print("Loading AQUA20 from original Hugging Face source")
print("=" * 80)
print("Dataset:", HF_DATASET_ID)

dataset = load_dataset(HF_DATASET_ID)

print("\nAvailable splits:")
print(dataset)

rows = []

for split_name in dataset.keys():
    ds = dataset[split_name]
    label_feature = ds.features["label"]
    class_names = label_feature.names

    counts = pd.Series(ds["label"]).value_counts().sort_index()

    for class_id, count in counts.items():
        rows.append({
            "split": split_name,
            "class_id": int(class_id),
            "class_name": class_names[int(class_id)],
            "image_count": int(count),
        })

dist_df = pd.DataFrame(rows)

summary_df = (
    dist_df.groupby("split")["image_count"]
    .sum()
    .reset_index()
    .sort_values("split")
)

class_df = pd.DataFrame({
    "class_id": list(range(len(class_names))),
    "class_name": class_names
})

print("\n" + "=" * 80)
print("Split summary")
print("=" * 80)
display(summary_df)

print("\n" + "=" * 80)
print("Class list")
print("=" * 80)
display(class_df)

print("\n" + "=" * 80)
print("Class distribution")
print("=" * 80)
display(dist_df)

# Save audit outputs
summary_df.to_csv(DATA_CHECKS_DIR / "f00_hf_original_split_summary.csv", index=False)
class_df.to_csv(DATA_CHECKS_DIR / "f00_hf_original_class_names.csv", index=False)
dist_df.to_csv(DATA_CHECKS_DIR / "f00_hf_original_class_distribution.csv", index=False)

with open(DATA_CHECKS_DIR / "f00_original_hf_dataset_id.txt", "w") as f:
    f.write(HF_DATASET_ID)

print("\nSaved:")
print(DATA_CHECKS_DIR / "f00_hf_original_split_summary.csv")
print(DATA_CHECKS_DIR / "f00_hf_original_class_names.csv")
print(DATA_CHECKS_DIR / "f00_hf_original_class_distribution.csv")
print(DATA_CHECKS_DIR / "f00_original_hf_dataset_id.txt")

================================================================================
Loading AQUA20 from original Hugging Face source
================================================================================
Dataset: taufiktrf/AQUA20

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/153M [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/46.8M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/6559 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1612 [00:00<?, ? examples/s]

Available splits:
DatasetDict({
    train: Dataset({
        features: ['image', 'label'],
        num_rows: 6559
    })
    test: Dataset({
        features: ['image', 'label'],
        num_rows: 1612
    })
})

================================================================================
Split summary
================================================================================

   split  image_count
0   test         1612
1  train         6559

================================================================================
Class list
================================================================================

    class_id      class_name
0          0           coral
1          1            crab
2          2           diver
3          3             eel
4          4            fish
5          5    fishInGroups
6          6        flatworm
7          7       jellyfish
8          8  marine_dolphin
9          9         octopus
10        10         rayfish
11        11      seaAnemone
12        12     seaCucumber
13        13         seaSlug
14        14       seaUrchin
15        15           shark
16        16          shrimp
17        17           squid
18        18        starfish
19        19          turtle

================================================================================
Class distribution
================================================================================

    split  class_id      class_name  image_count
0   train         0           coral         1562
1   train         1            crab           43
2   train         2           diver           51
3   train         3             eel          160
4   train         4            fish         2200
5   train         5    fishInGroups          272
6   train         6        flatworm           50
7   train         7       jellyfish           97
8   train         8  marine_dolphin           20
9   train         9         octopus           20
10  train        10         rayfish          382
11  train        11      seaAnemone          890
12  train        12     seaCucumber           35
13  train        13         seaSlug           79
14  train        14       seaUrchin          115
15  train        15           shark           71
16  train        16          shrimp           22
17  train        17           squid           24
18  train        18        starfish          166
19  train        19          turtle          300
20   test         0           coral          348
21   test         1            crab           11
22   test         2           diver           13
23   test         3             eel           41
24   test         4            fish          538
25   test         5    fishInGroups           72
26   test         6        flatworm           13
27   test         7       jellyfish           25
28   test         8  marine_dolphin           10
29   test         9         octopus           10
30   test        10         rayfish           95
31   test        11      seaAnemone          221
32   test        12     seaCucumber           10
33   test        13         seaSlug           20
34   test        14       seaUrchin           29
35   test        15           shark           19
36   test        16          shrimp           11
37   test        17           squid           10
38   test        18        starfish           40
39   test        19          turtle           76

Saved:
/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/data_checks/f00_hf_original_split_summary.csv
/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/data_checks/f00_hf_original_class_names.csv
/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/data_checks/f00_hf_original_class_distribution.csv
/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/data_checks/f00_original_hf_dataset_id.txt

## F00 — Step 2: Reconstruct official train/val/test manifest

Finding:
- Hugging Face source provides:
  - train = 6,559
  - test = 1,612

Official experiment split:
- train = 5,247
- val = 1,312
- test = 1,612

Method:
- Keep Hugging Face test unchanged.
- Split Hugging Face train into train/val using stratified 80/20 split.
- Seed = 42.
- Save manifest and class-distribution audit files.

No images are exported in this step.

In [4]:
# F00 Step 2 — Reconstruct official train/val/test manifest from HF source

from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
from pathlib import Path

HF_DATASET_ID = "taufiktrf/AQUA20"
SEED = 42

PROJECT_ROOT = Path("/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026")
DATA_CHECKS_DIR = PROJECT_ROOT / "data_checks"
DATA_CHECKS_DIR.mkdir(parents=True, exist_ok=True)

EXPECTED_COUNTS = {
    "train": 5247,
    "val": 1312,
    "test": 1612,
}

# dataset should already exist from previous cell
assert "dataset" in globals(), "Please run the Hugging Face loading cell first."

class_names = dataset["train"].features["label"].names

hf_train_labels = np.array(dataset["train"]["label"])
hf_train_indices = np.arange(len(hf_train_labels))

train_idx, val_idx = train_test_split(
    hf_train_indices,
    test_size=EXPECTED_COUNTS["val"],
    random_state=SEED,
    stratify=hf_train_labels,
    shuffle=True,
)

train_idx = sorted(train_idx.tolist())
val_idx = sorted(val_idx.tolist())

rows = []

for i in train_idx:
    label = int(hf_train_labels[i])
    rows.append({
        "hf_dataset_id": HF_DATASET_ID,
        "hf_split": "train",
        "hf_index": int(i),
        "official_split": "train",
        "class_id": label,
        "class_name": class_names[label],
        "source_key": f"hf_train_{i:06d}",
    })

for i in val_idx:
    label = int(hf_train_labels[i])
    rows.append({
        "hf_dataset_id": HF_DATASET_ID,
        "hf_split": "train",
        "hf_index": int(i),
        "official_split": "val",
        "class_id": label,
        "class_name": class_names[label],
        "source_key": f"hf_train_{i:06d}",
    })

hf_test_labels = np.array(dataset["test"]["label"])

for i, label in enumerate(hf_test_labels):
    label = int(label)
    rows.append({
        "hf_dataset_id": HF_DATASET_ID,
        "hf_split": "test",
        "hf_index": int(i),
        "official_split": "test",
        "class_id": label,
        "class_name": class_names[label],
        "source_key": f"hf_test_{i:06d}",
    })

manifest_df = pd.DataFrame(rows)

split_summary_df = (
    manifest_df.groupby("official_split")["source_key"]
    .count()
    .reset_index()
    .rename(columns={"source_key": "image_count"})
)

split_summary_df["expected_count"] = split_summary_df["official_split"].map(EXPECTED_COUNTS)
split_summary_df["matches_expected"] = split_summary_df["image_count"] == split_summary_df["expected_count"]

class_dist_df = (
    manifest_df.groupby(["official_split", "class_id", "class_name"])["source_key"]
    .count()
    .reset_index()
    .rename(columns={"source_key": "image_count"})
    .sort_values(["official_split", "class_id"])
)

print("=" * 80)
print("Official reconstructed split summary")
print("=" * 80)
display(split_summary_df)

print("\n" + "=" * 80)
print("Official reconstructed class distribution")
print("=" * 80)
display(class_dist_df)

all_counts_ok = split_summary_df["matches_expected"].all()
split_names_ok = set(split_summary_df["official_split"]) == {"train", "val", "test"}

print("\nChecks:")
print("Split counts match expected:", "✅" if all_counts_ok else "❌")
print("Split names valid:", "✅" if split_names_ok else "❌")
print("Number of classes:", len(class_names))

assert all_counts_ok, "Split count mismatch."
assert split_names_ok, "Missing train/val/test split."

manifest_path = DATA_CHECKS_DIR / "f00_official_reconstructed_manifest.csv"
summary_path = DATA_CHECKS_DIR / "f00_official_reconstructed_split_summary.csv"
dist_path = DATA_CHECKS_DIR / "f00_official_reconstructed_class_distribution.csv"

manifest_df.to_csv(manifest_path, index=False)
split_summary_df.to_csv(summary_path, index=False)
class_dist_df.to_csv(dist_path, index=False)

print("\nSaved:")
print(manifest_path)
print(summary_path)
print(dist_path)

================================================================================
Official reconstructed split summary
================================================================================

  official_split  image_count  expected_count  matches_expected
0           test         1612            1612              True
1          train         5247            5247              True
2            val         1312            1312              True

================================================================================
Official reconstructed class distribution
================================================================================

   official_split  class_id      class_name  image_count
0            test         0           coral          348
1            test         1            crab           11
2            test         2           diver           13
3            test         3             eel           41
4            test         4            fish          538
5            test         5    fishInGroups           72
6            test         6        flatworm           13
7            test         7       jellyfish           25
8            test         8  marine_dolphin           10
9            test         9         octopus           10
10           test        10         rayfish           95
11           test        11      seaAnemone          221
12           test        12     seaCucumber           10
13           test        13         seaSlug           20
14           test        14       seaUrchin           29
15           test        15           shark           19
16           test        16          shrimp           11
17           test        17           squid           10
18           test        18        starfish           40
19           test        19          turtle           76
20          train         0           coral         1249
21          train         1            crab           34
22          train         2           diver           41
23          train         3             eel          128
24          train         4            fish         1760
25          train         5    fishInGroups          218
26          train         6        flatworm           40
27          train         7       jellyfish           78
28          train         8  marine_dolphin           16
29          train         9         octopus           16
30          train        10         rayfish          305
31          train        11      seaAnemone          712
32          train        12     seaCucumber           28
33          train        13         seaSlug           63
34          train        14       seaUrchin           92
35          train        15           shark           57
36          train        16          shrimp           18
37          train        17           squid           19
38          train        18        starfish          133
39          train        19          turtle          240
40            val         0           coral          313
41            val         1            crab            9
42            val         2           diver           10
43            val         3             eel           32
44            val         4            fish          440
45            val         5    fishInGroups           54
46            val         6        flatworm           10
47            val         7       jellyfish           19
48            val         8  marine_dolphin            4
49            val         9         octopus            4
50            val        10         rayfish           77
51            val        11      seaAnemone          178
52            val        12     seaCucumber            7
53            val        13         seaSlug           16
54            val        14       seaUrchin           23
55            val        15           shark           14
56            val        16          shrimp            4
57            val        17           squid            5
58            val        18        starfish           33
59            val        19          turtle           60

Checks:
Split counts match expected: ✅
Split names valid: ✅
Number of classes: 20

Saved:
/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/data_checks/f00_official_reconstructed_manifest.csv
/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/data_checks/f00_official_reconstructed_split_summary.csv
/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/data_checks/f00_official_reconstructed_class_distribution.csv

## F00 — Step 3: Export official ImageFolder split

Purpose:
- Convert the reconstructed Hugging Face split into reusable folder format.
- Keep the official split fixed:
  - train = 5,247
  - val = 1,312
  - test = 1,612
- Use class folders with numeric prefixes to preserve correct class order.

Output format:
official_imagefolder/
├── train/
├── val/
└── test/

Important:
- This is the clean official split.
- Do not augment here.
- Do not include this folder in the final paper zip package.

In [5]:
# F00 Step 3 — Export official ImageFolder split

from pathlib import Path
from PIL import Image
import pandas as pd
from tqdm.auto import tqdm

PROJECT_ROOT = Path("/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026")
DATA_CHECKS_DIR = PROJECT_ROOT / "data_checks"
OFFICIAL_IMG_DIR = PROJECT_ROOT / "official_imagefolder"

EXPECTED_COUNTS = {
    "train": 5247,
    "val": 1312,
    "test": 1612,
}

manifest_path = DATA_CHECKS_DIR / "f00_official_reconstructed_manifest.csv"
assert manifest_path.exists(), "Manifest missing. Run Cell 3 first."

assert "dataset" in globals(), "Hugging Face dataset object missing. Run the HF loading cell first."

manifest_df = pd.read_csv(manifest_path)

class_df = (
    manifest_df[["class_id", "class_name"]]
    .drop_duplicates()
    .sort_values("class_id")
    .reset_index(drop=True)
)

class_df["folder_name"] = class_df.apply(
    lambda r: f"{int(r['class_id']):02d}_{r['class_name']}",
    axis=1
)

class_id_to_folder = dict(zip(class_df["class_id"], class_df["folder_name"]))

# Create folders
for split in ["train", "val", "test"]:
    for folder_name in class_df["folder_name"]:
        (OFFICIAL_IMG_DIR / split / folder_name).mkdir(parents=True, exist_ok=True)

export_rows = []

print("=" * 80)
print("Exporting official ImageFolder split")
print("=" * 80)
print("Output:", OFFICIAL_IMG_DIR)

for row in tqdm(manifest_df.itertuples(index=False), total=len(manifest_df)):
    split = row.official_split
    hf_split = row.hf_split
    hf_index = int(row.hf_index)
    class_id = int(row.class_id)
    class_name = row.class_name
    source_key = row.source_key

    folder_name = class_id_to_folder[class_id]
    out_path = OFFICIAL_IMG_DIR / split / folder_name / f"{source_key}.jpg"

    if not out_path.exists():
        image = dataset[hf_split][hf_index]["image"]

        if not isinstance(image, Image.Image):
            image = Image.fromarray(image)

        image = image.convert("RGB")
        image.save(out_path, quality=95)

    export_rows.append({
        "official_split": split,
        "class_id": class_id,
        "class_name": class_name,
        "folder_name": folder_name,
        "image_path": str(out_path),
        "hf_split": hf_split,
        "hf_index": hf_index,
        "source_key": source_key,
    })

export_manifest_df = pd.DataFrame(export_rows)

verify_df = (
    export_manifest_df.groupby("official_split")["image_path"]
    .count()
    .reset_index()
    .rename(columns={"image_path": "image_count"})
)

verify_df["expected_count"] = verify_df["official_split"].map(EXPECTED_COUNTS)
verify_df["matches_expected"] = verify_df["image_count"] == verify_df["expected_count"]

class_verify_df = (
    export_manifest_df.groupby(["official_split", "class_id", "class_name", "folder_name"])["image_path"]
    .count()
    .reset_index()
    .rename(columns={"image_path": "image_count"})
    .sort_values(["official_split", "class_id"])
)

print("\n" + "=" * 80)
print("ImageFolder split verification")
print("=" * 80)
display(verify_df)

print("\n" + "=" * 80)
print("Class folder mapping")
print("=" * 80)
display(class_df)

assert verify_df["matches_expected"].all(), "Exported ImageFolder count mismatch."

export_manifest_path = DATA_CHECKS_DIR / "f00_official_imagefolder_manifest.csv"
verify_path = DATA_CHECKS_DIR / "f00_official_imagefolder_split_verify.csv"
class_verify_path = DATA_CHECKS_DIR / "f00_official_imagefolder_class_distribution.csv"
class_map_path = DATA_CHECKS_DIR / "f00_class_id_folder_mapping.csv"

export_manifest_df.to_csv(export_manifest_path, index=False)
verify_df.to_csv(verify_path, index=False)
class_verify_df.to_csv(class_verify_path, index=False)
class_df.to_csv(class_map_path, index=False)

print("\nSaved:")
print(export_manifest_path)
print(verify_path)
print(class_verify_path)
print(class_map_path)

print("\n✅ Official ImageFolder split is ready.")

================================================================================
Exporting official ImageFolder split
================================================================================
Output: /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/official_imagefolder

  0%|          | 0/8171 [00:00<?, ?it/s]

================================================================================
ImageFolder split verification
================================================================================

  official_split  image_count  expected_count  matches_expected
0           test         1612            1612              True
1          train         5247            5247              True
2            val         1312            1312              True

================================================================================
Class folder mapping
================================================================================

    class_id      class_name        folder_name
0          0           coral           00_coral
1          1            crab            01_crab
2          2           diver           02_diver
3          3             eel             03_eel
4          4            fish            04_fish
5          5    fishInGroups    05_fishInGroups
6          6        flatworm        06_flatworm
7          7       jellyfish       07_jellyfish
8          8  marine_dolphin  08_marine_dolphin
9          9         octopus         09_octopus
10        10         rayfish         10_rayfish
11        11      seaAnemone      11_seaAnemone
12        12     seaCucumber     12_seaCucumber
13        13         seaSlug         13_seaSlug
14        14       seaUrchin       14_seaUrchin
15        15           shark           15_shark
16        16          shrimp          16_shrimp
17        17           squid           17_squid
18        18        starfish        18_starfish
19        19          turtle          19_turtle

Saved:
/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/data_checks/f00_official_imagefolder_manifest.csv
/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/data_checks/f00_official_imagefolder_split_verify.csv
/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/data_checks/f00_official_imagefolder_class_distribution.csv
/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/data_checks/f00_class_id_folder_mapping.csv

✅ Official ImageFolder split is ready.

## F00 — Step 4: Create Aug-200 train-only balanced split

Goal:
- Build the G2/G4 training split.
- Keep all original train images.
- For any class with fewer than 200 train images, generate augmented copies until that class reaches 200.
- Classes already above 200 are not downsampled.
- Validation and test are copied unchanged from the official split.

Rule:
- Augmentation is train-only.
- Val/test remain untouched.

In [6]:
# F00 Step 4 — Create Aug-200 train-only balanced ImageFolder

from pathlib import Path
from PIL import Image, ImageEnhance
import pandas as pd
import random
import shutil
from tqdm.auto import tqdm

SEED = 42
AUG_TARGET = 200

PROJECT_ROOT = Path("/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026")
DATA_CHECKS_DIR = PROJECT_ROOT / "data_checks"
OFFICIAL_IMG_DIR = PROJECT_ROOT / "official_imagefolder"
AUG200_IMG_DIR = PROJECT_ROOT / "balanced_train" / "aug200_imagefolder"

assert OFFICIAL_IMG_DIR.exists(), "Official ImageFolder split missing. Run Cell 4 first."

# Clean old Aug-200 output to avoid stale files
if AUG200_IMG_DIR.exists():
    shutil.rmtree(AUG200_IMG_DIR)

AUG200_IMG_DIR.mkdir(parents=True, exist_ok=True)

class_map_path = DATA_CHECKS_DIR / "f00_class_id_folder_mapping.csv"
class_df = pd.read_csv(class_map_path)

folder_to_class = {
    row.folder_name: (int(row.class_id), row.class_name)
    for row in class_df.itertuples(index=False)
}

def image_files(folder):
    exts = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}
    return sorted([p for p in folder.iterdir() if p.is_file() and p.suffix.lower() in exts])

def augment_pil_image(img, rng):
    img = img.convert("RGB")
    w, h = img.size

    # Random resized crop
    scale = rng.uniform(0.82, 1.00)
    crop_w, crop_h = int(w * scale), int(h * scale)
    left = rng.randint(0, max(0, w - crop_w))
    top = rng.randint(0, max(0, h - crop_h))
    img = img.crop((left, top, left + crop_w, top + crop_h)).resize((w, h), Image.BICUBIC)

    # Horizontal flip
    if rng.random() < 0.5:
        img = img.transpose(Image.FLIP_LEFT_RIGHT)

    # Small rotation
    angle = rng.uniform(-18, 18)
    img = img.rotate(angle, resample=Image.BICUBIC, expand=False)

    # Mild underwater-safe color changes
    img = ImageEnhance.Brightness(img).enhance(rng.uniform(0.82, 1.18))
    img = ImageEnhance.Contrast(img).enhance(rng.uniform(0.85, 1.20))
    img = ImageEnhance.Color(img).enhance(rng.uniform(0.80, 1.22))
    img = ImageEnhance.Sharpness(img).enhance(rng.uniform(0.85, 1.25))

    return img

manifest_rows = []

print("=" * 80)
print("Creating Aug-200 train-only balanced split")
print("=" * 80)
print("Official split:", OFFICIAL_IMG_DIR)
print("Aug-200 split :", AUG200_IMG_DIR)
print("Target minimum train images per class:", AUG_TARGET)

# Copy val/test unchanged
for split in ["val", "test"]:
    src_split = OFFICIAL_IMG_DIR / split
    dst_split = AUG200_IMG_DIR / split
    shutil.copytree(src_split, dst_split)

    for class_folder in sorted(dst_split.iterdir()):
        if not class_folder.is_dir():
            continue
        class_id, class_name = folder_to_class[class_folder.name]
        for img_path in image_files(class_folder):
            manifest_rows.append({
                "split": split,
                "class_id": class_id,
                "class_name": class_name,
                "folder_name": class_folder.name,
                "image_path": str(img_path),
                "source_image_path": str(img_path),
                "is_augmented": False,
                "aug_type": "unchanged_val_test",
            })

# Build augmented train
train_summary_rows = []

for class_folder in tqdm(sorted((OFFICIAL_IMG_DIR / "train").iterdir())):
    if not class_folder.is_dir():
        continue

    class_id, class_name = folder_to_class[class_folder.name]
    src_images = image_files(class_folder)

    dst_class_dir = AUG200_IMG_DIR / "train" / class_folder.name
    dst_class_dir.mkdir(parents=True, exist_ok=True)

    # Copy original train images
    for src_path in src_images:
        dst_path = dst_class_dir / src_path.name
        shutil.copy2(src_path, dst_path)

        manifest_rows.append({
            "split": "train",
            "class_id": class_id,
            "class_name": class_name,
            "folder_name": class_folder.name,
            "image_path": str(dst_path),
            "source_image_path": str(src_path),
            "is_augmented": False,
            "aug_type": "original_train",
        })

    original_count = len(src_images)
    aug_needed = max(0, AUG_TARGET - original_count)

    rng = random.Random(SEED + class_id * 1000)

    # Generate augmented copies only for minority classes
    for aug_i in range(aug_needed):
        src_path = src_images[aug_i % original_count]
        out_name = f"aug_{src_path.stem}_{aug_i:04d}.jpg"
        out_path = dst_class_dir / out_name

        img = Image.open(src_path)
        aug_img = augment_pil_image(img, rng)
        aug_img.save(out_path, quality=95)

        manifest_rows.append({
            "split": "train",
            "class_id": class_id,
            "class_name": class_name,
            "folder_name": class_folder.name,
            "image_path": str(out_path),
            "source_image_path": str(src_path),
            "is_augmented": True,
            "aug_type": "aug200_train_only",
        })

    train_summary_rows.append({
        "class_id": class_id,
        "class_name": class_name,
        "folder_name": class_folder.name,
        "original_train_count": original_count,
        "augmented_added": aug_needed,
        "final_train_count": original_count + aug_needed,
    })

aug_manifest_df = pd.DataFrame(manifest_rows)
train_aug_summary_df = pd.DataFrame(train_summary_rows).sort_values("class_id")

split_verify_df = (
    aug_manifest_df.groupby("split")["image_path"]
    .count()
    .reset_index()
    .rename(columns={"image_path": "image_count"})
)

class_verify_df = (
    aug_manifest_df.groupby(["split", "class_id", "class_name", "folder_name"])["image_path"]
    .count()
    .reset_index()
    .rename(columns={"image_path": "image_count"})
    .sort_values(["split", "class_id"])
)

print("\n" + "=" * 80)
print("Aug-200 train summary")
print("=" * 80)
display(train_aug_summary_df)

print("\n" + "=" * 80)
print("Aug-200 split verification")
print("=" * 80)
display(split_verify_df)

print("\nOriginal train images:", train_aug_summary_df["original_train_count"].sum())
print("Augmented train images added:", train_aug_summary_df["augmented_added"].sum())
print("Final Aug-200 train images:", train_aug_summary_df["final_train_count"].sum())

# Safety checks
assert split_verify_df.loc[split_verify_df["split"] == "val", "image_count"].item() == 1312
assert split_verify_df.loc[split_verify_df["split"] == "test", "image_count"].item() == 1612
assert train_aug_summary_df["final_train_count"].min() >= AUG_TARGET

# Save audit files
aug_manifest_path = DATA_CHECKS_DIR / "f00_aug200_imagefolder_manifest.csv"
train_summary_path = DATA_CHECKS_DIR / "f00_aug200_train_generation_summary.csv"
split_verify_path = DATA_CHECKS_DIR / "f00_aug200_split_verify.csv"
class_verify_path = DATA_CHECKS_DIR / "f00_aug200_class_distribution.csv"

aug_manifest_df.to_csv(aug_manifest_path, index=False)
train_aug_summary_df.to_csv(train_summary_path, index=False)
split_verify_df.to_csv(split_verify_path, index=False)
class_verify_df.to_csv(class_verify_path, index=False)

print("\nSaved:")
print(aug_manifest_path)
print(train_summary_path)
print(split_verify_path)
print(class_verify_path)

print("\n✅ Aug-200 train-only balanced split is ready.")

================================================================================
Creating Aug-200 train-only balanced split
================================================================================
Official split: /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/official_imagefolder
Aug-200 split : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/balanced_train/aug200_imagefolder
Target minimum train images per class: 200

  0%|          | 0/20 [00:00<?, ?it/s]

================================================================================
Aug-200 train summary
================================================================================

,class_id,class_name,folder_name,original_train_count,augmented_added,final_train_count
0,0,coral,00_coral,1249,0,1249
1,1,crab,01_crab,34,166,200
2,2,diver,02_diver,41,159,200
3,3,eel,03_eel,128,72,200
4,4,fish,04_fish,1760,0,1760
5,5,fishInGroups,05_fishInGroups,218,0,218
6,6,flatworm,06_flatworm,40,160,200
7,7,jellyfish,07_jellyfish,78,122,200
8,8,marine_dolphin,08_marine_dolphin,16,184,200
9,9,octopus,09_octopus,16,184,200
10,10,rayfish,10_rayfish,305,0,305
11,11,seaAnemone,11_seaAnemone,712,0,712
12,12,seaCucumber,12_seaCucumber,28,172,200
13,13,seaSlug,13_seaSlug,63,137,200
14,14,seaUrchin,14_seaUrchin,92,108,200
15,15,shark,15_shark,57,143,200
16,16,shrimp,16_shrimp,18,182,200
17,17,squid,17_squid,19,181,200
18,18,starfish,18_starfish,133,67,200
19,19,turtle,19_turtle,240,0,240

================================================================================
Aug-200 split verification
================================================================================

   split  image_count
0   test         1612
1  train         7284
2    val         1312

Original train images: 5247
Augmented train images added: 2037
Final Aug-200 train images: 7284

Saved:
/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/data_checks/f00_aug200_imagefolder_manifest.csv
/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/data_checks/f00_aug200_train_generation_summary.csv
/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/data_checks/f00_aug200_split_verify.csv
/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/data_checks/f00_aug200_class_distribution.csv

✅ Aug-200 train-only balanced split is ready.

## F00 — Step 5: Final PyTorch ImageFolder sanity check

Purpose:
- Confirm official split loads correctly with PyTorch ImageFolder.
- Confirm Aug-200 split loads correctly.
- Confirm class order is identical.
- Confirm val/test are unchanged between official and Aug-200 folders.
- Test one batch on GPU-ready transforms.

No training in this step.

In [7]:
# F00 Step 5 — Final PyTorch ImageFolder sanity check

from pathlib import Path
import pandas as pd
import torch
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

PROJECT_ROOT = Path("/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026")
DATA_CHECKS_DIR = PROJECT_ROOT / "data_checks"

OFFICIAL_IMG_DIR = PROJECT_ROOT / "official_imagefolder"
AUG200_IMG_DIR = PROJECT_ROOT / "balanced_train" / "aug200_imagefolder"

assert OFFICIAL_IMG_DIR.exists(), "Official ImageFolder missing."
assert AUG200_IMG_DIR.exists(), "Aug-200 ImageFolder missing."

EXPECTED_OFFICIAL = {
    "train": 5247,
    "val": 1312,
    "test": 1612,
}

EXPECTED_AUG200 = {
    "train": 7284,
    "val": 1312,
    "test": 1612,
}

sanity_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225],
    ),
])

def load_split(root, split):
    return datasets.ImageFolder(root / split, transform=sanity_transform)

official_ds = {
    split: load_split(OFFICIAL_IMG_DIR, split)
    for split in ["train", "val", "test"]
}

aug200_ds = {
    split: load_split(AUG200_IMG_DIR, split)
    for split in ["train", "val", "test"]
}

rows = []

for split in ["train", "val", "test"]:
    rows.append({
        "dataset_version": "official_original",
        "split": split,
        "image_count": len(official_ds[split]),
        "expected_count": EXPECTED_OFFICIAL[split],
        "matches_expected": len(official_ds[split]) == EXPECTED_OFFICIAL[split],
    })

for split in ["train", "val", "test"]:
    rows.append({
        "dataset_version": "aug200_train_only",
        "split": split,
        "image_count": len(aug200_ds[split]),
        "expected_count": EXPECTED_AUG200[split],
        "matches_expected": len(aug200_ds[split]) == EXPECTED_AUG200[split],
    })

sanity_df = pd.DataFrame(rows)

print("=" * 80)
print("Dataset sanity summary")
print("=" * 80)
display(sanity_df)

# Class-order consistency
base_class_to_idx = official_ds["train"].class_to_idx

for split in ["val", "test"]:
    assert official_ds[split].class_to_idx == base_class_to_idx, f"Official {split} class order mismatch."

for split in ["train", "val", "test"]:
    assert aug200_ds[split].class_to_idx == base_class_to_idx, f"Aug-200 {split} class order mismatch."

print("\nClass order consistency: ✅")

# Confirm val/test are unchanged between official and Aug-200
def relative_file_list(root, split):
    files = []
    split_dir = root / split
    for p in sorted(split_dir.rglob("*")):
        if p.is_file():
            files.append(str(p.relative_to(split_dir)))
    return files

for split in ["val", "test"]:
    official_files = relative_file_list(OFFICIAL_IMG_DIR, split)
    aug200_files = relative_file_list(AUG200_IMG_DIR, split)
    assert official_files == aug200_files, f"{split} changed between official and Aug-200."

print("Val/test unchanged between official and Aug-200: ✅")

# One-batch loader test
official_loader = DataLoader(
    official_ds["train"],
    batch_size=32,
    shuffle=True,
    num_workers=2,
    pin_memory=True,
)

aug200_loader = DataLoader(
    aug200_ds["train"],
    batch_size=32,
    shuffle=True,
    num_workers=2,
    pin_memory=True,
)

official_images, official_labels = next(iter(official_loader))
aug200_images, aug200_labels = next(iter(aug200_loader))

print("\n" + "=" * 80)
print("One-batch sanity check")
print("=" * 80)
print("Official train batch images:", official_images.shape)
print("Official train batch labels:", official_labels.shape)
print("Aug-200 train batch images:", aug200_images.shape)
print("Aug-200 train batch labels:", aug200_labels.shape)
print("Image dtype:", official_images.dtype)
print("Label dtype:", official_labels.dtype)

assert sanity_df["matches_expected"].all(), "Dataset count mismatch."
assert official_images.shape == torch.Size([32, 3, 224, 224])
assert aug200_images.shape == torch.Size([32, 3, 224, 224])

sanity_path = DATA_CHECKS_DIR / "f00_final_imagefolder_sanity_summary.csv"
sanity_df.to_csv(sanity_path, index=False)

print("\nSaved:")
print(sanity_path)

print("\n✅ F00 dataset sanity check passed.")

================================================================================
Dataset sanity summary
================================================================================

     dataset_version  split  image_count  expected_count  matches_expected
0  official_original  train         5247            5247              True
1  official_original    val         1312            1312              True
2  official_original   test         1612            1612              True
3  aug200_train_only  train         7284            7284              True
4  aug200_train_only    val         1312            1312              True
5  aug200_train_only   test         1612            1612              True

Class order consistency: ✅
Val/test unchanged between official and Aug-200: ✅

================================================================================
One-batch sanity check
================================================================================
Official train batch images: torch.Size([32, 3, 224, 224])
Official train batch labels: torch.Size([32])
Aug-200 train batch images: torch.Size([32, 3, 224, 224])
Aug-200 train batch labels: torch.Size([32])
Image dtype: torch.float32
Label dtype: torch.int64

Saved:
/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/data_checks/f00_final_imagefolder_sanity_summary.csv

✅ F00 dataset sanity check passed.

## F00 — Final clean handover package

Purpose:
- Package all F00 audit, manifest, configuration, and verification outputs.
- Exclude image datasets and generated Aug-200 image folders.
- Create a small reusable handover ZIP for the next session and co-author.

In [ ]:
# F00 Final — Create clean downloadable handover package

from pathlib import Path
import shutil
import json

PROJECT_ROOT = Path("/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026")
DATA_CHECKS_DIR = PROJECT_ROOT / "data_checks"
LOGS_DIR = PROJECT_ROOT / "logs"
PACKAGES_DIR = PROJECT_ROOT / "packages"

PACKAGE_NAME = "AQUA20_F00_DATA_AUDIT_AUG200_HANDOVER_04072026"
PACKAGE_DIR = PACKAGES_DIR / PACKAGE_NAME
ZIP_PATH = PACKAGES_DIR / f"{PACKAGE_NAME}.zip"

PACKAGES_DIR.mkdir(parents=True, exist_ok=True)

if PACKAGE_DIR.exists():
    shutil.rmtree(PACKAGE_DIR)

if ZIP_PATH.exists():
    ZIP_PATH.unlink()

PACKAGE_DIR.mkdir(parents=True, exist_ok=True)

# -------------------------------------------------------------------------
# Copy F00 audit outputs
# -------------------------------------------------------------------------
dst_checks = PACKAGE_DIR / "data_checks"
dst_checks.mkdir(parents=True, exist_ok=True)

f00_files = sorted(DATA_CHECKS_DIR.glob("f00_*"))

for src in f00_files:
    if src.is_file():
        shutil.copy2(src, dst_checks / src.name)

# -------------------------------------------------------------------------
# Copy run configuration
# -------------------------------------------------------------------------
dst_logs = PACKAGE_DIR / "logs"
dst_logs.mkdir(parents=True, exist_ok=True)

for src in sorted(LOGS_DIR.glob("run_config*.json")):
    shutil.copy2(src, dst_logs / src.name)

# -------------------------------------------------------------------------
# Save F00 completion metadata
# -------------------------------------------------------------------------
completion_info = {
    "plan_keyword": "04-07-2026 AQUA20 FINAL BEAT BASE PLAN",
    "stage": "F00",
    "status": "COMPLETED",
    "hf_dataset_id": "taufiktrf/AQUA20",
    "seed": 42,
    "official_split": {
        "train": 5247,
        "val": 1312,
        "test": 1612,
    },
    "aug200_split": {
        "train": 7284,
        "val": 1312,
        "test": 1612,
    },
    "original_train_images": 5247,
    "augmented_train_images_added": 2037,
    "augmentation_scope": "train_only",
    "validation_modified": False,
    "test_modified": False,
    "next_stage": "F01 YOLO26m-cls + Aug-200",
}

with open(PACKAGE_DIR / "F00_COMPLETION_SUMMARY.json", "w") as f:
    json.dump(completion_info, f, indent=2)

# -------------------------------------------------------------------------
# README
# -------------------------------------------------------------------------
readme = """AQUA20 F00 DATA AUDIT + AUG-200 HANDOVER
================================================

Official plan:
04-07-2026 AQUA20 FINAL BEAT BASE PLAN

F00 STATUS:
COMPLETED

SOURCE:
Hugging Face dataset: taufiktrf/AQUA20

ORIGINAL HF SPLITS:
train = 6559
test  = 1612

OFFICIAL RECONSTRUCTED SPLIT:
train = 5247
val   = 1312
test  = 1612

Split method:
Stratified train/validation reconstruction from the Hugging Face training
split using random seed 42.

The Hugging Face test split was preserved unchanged.

AUG-200 TRAIN-ONLY SPLIT:
train = 7284
val   = 1312
test  = 1612

Original train images:
5247

Synthetic augmented train images added:
2037

Aug-200 rule:
Classes with fewer than 200 training images were augmented until reaching
200 images. Classes already above 200 were retained without downsampling.

Validation and test were not augmented.

FINAL F00 CHECKS:
- Official split counts passed
- Aug-200 split counts passed
- 20 classes confirmed
- Class order consistency passed
- Validation unchanged passed
- Test unchanged passed
- PyTorch ImageFolder loading passed
- One-batch tensor sanity test passed

IMPORTANT:
This package intentionally excludes:
- official_imagefolder/
- balanced_train/aug200_imagefolder/

These image datasets are large and should be recreated from the source or
stored separately as a Kaggle dataset when needed.

NEXT EXPERIMENT:
F01 YOLO26m-cls + Aug-200
"""

with open(PACKAGE_DIR / "README_F00.txt", "w") as f:
    f.write(readme)

# -------------------------------------------------------------------------
# Create ZIP
# -------------------------------------------------------------------------
shutil.make_archive(
    str(ZIP_PATH.with_suffix("")),
    "zip",
    PACKAGE_DIR,
)

package_files = sorted([
    p.relative_to(PACKAGE_DIR)
    for p in PACKAGE_DIR.rglob("*")
    if p.is_file()
])

print("=" * 80)
print("F00 CLEAN HANDOVER PACKAGE")
print("=" * 80)
print("Package:", ZIP_PATH)
print("Size MB:", round(ZIP_PATH.stat().st_size / (1024 ** 2), 3))
print("Files:", len(package_files))

print("\nPackage contents:")
for p in package_files:
    print("-", p)

print("\n✅ F00 package created successfully.")
print("\nDownload this file from Kaggle Output:")
print(ZIP_PATH)

## Restore F00 handover package

Purpose:
- Detect the F00 handover ZIP from Kaggle Input.
- Restore the clean F00 project files into `/kaggle/working`.
- Verify the restored audit package.

This restores F00 metadata and audit outputs.

In [ ]:
# Restore F00 — Robust Kaggle Input detection and restore

from pathlib import Path
import zipfile
import shutil

INPUT_ROOT = Path("/kaggle/input")
PROJECT_ROOT = Path("/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026")

print("=" * 80)
print("F00 HANDOVER RESTORE")
print("=" * 80)

# -------------------------------------------------------------------------
# Detect package source
# -------------------------------------------------------------------------
summary_matches = list(INPUT_ROOT.rglob("F00_COMPLETION_SUMMARY.json"))
zip_matches = [
    p for p in INPUT_ROOT.rglob("*.zip")
    if "F00" in p.name.upper() and "HANDOVER" in p.name.upper()
]

if summary_matches:
    SOURCE_TYPE = "extracted"
    SOURCE_ROOT = summary_matches[0].parent

    print("Detected package type: extracted Kaggle Input")
    print("Source root:", SOURCE_ROOT)

elif zip_matches:
    SOURCE_TYPE = "zip"
    ZIP_PATH = zip_matches[0]

    print("Detected package type: ZIP")
    print("Source ZIP:", ZIP_PATH)

else:
    print("\nAvailable Kaggle Input files:")

    for p in sorted(INPUT_ROOT.rglob("*")):
        if p.is_file():
            print("-", p)

    raise FileNotFoundError(
        "F00 handover package could not be detected."
    )

# -------------------------------------------------------------------------
# Clean old restored audit files
# -------------------------------------------------------------------------
for name in [
    "data_checks",
    "logs",
    "F00_COMPLETION_SUMMARY.json",
    "README_F00.txt",
]:
    target = PROJECT_ROOT / name

    if target.is_dir():
        shutil.rmtree(target)
    elif target.is_file():
        target.unlink()

PROJECT_ROOT.mkdir(parents=True, exist_ok=True)

# -------------------------------------------------------------------------
# Restore package
# -------------------------------------------------------------------------
if SOURCE_TYPE == "zip":

    with zipfile.ZipFile(ZIP_PATH, "r") as zf:
        zf.extractall(PROJECT_ROOT)

else:

    for src in SOURCE_ROOT.iterdir():
        dst = PROJECT_ROOT / src.name

        if src.is_dir():
            shutil.copytree(src, dst)
        else:
            shutil.copy2(src, dst)

# -------------------------------------------------------------------------
# Verify restored F00 package
# -------------------------------------------------------------------------
required_files = [
    PROJECT_ROOT / "F00_COMPLETION_SUMMARY.json",
    PROJECT_ROOT / "README_F00.txt",
    PROJECT_ROOT / "data_checks" / "f00_official_reconstructed_manifest.csv",
    PROJECT_ROOT / "data_checks" / "f00_aug200_train_generation_summary.csv",
    PROJECT_ROOT / "data_checks" / "f00_final_imagefolder_sanity_summary.csv",
]

missing = [p for p in required_files if not p.exists()]

assert not missing, (
    "Restore incomplete. Missing:\n"
    + "\n".join(str(p) for p in missing)
)

print("\n" + "=" * 80)
print("RESTORE VERIFICATION")
print("=" * 80)

for path in required_files:
    print("✅", path.relative_to(PROJECT_ROOT))

print("\n✅ F00 handover restored successfully.")
print("Project root:", PROJECT_ROOT)

### F01 Step 1 — Environment and Aug-200 path verification

This step verifies the Kaggle runtime before training starts.

Checks included:

- GPU availability
- Python, Torch, Torchvision versions
- Ultralytics availability and version
- Aug-200 ImageFolder path
- train/val/test folder existence
- split image counts
- 20 class folders
- stable class order across train, val, and test

Training will not start until this verification passes.

In [ ]:
# F01 Step 1 — Environment and Aug-200 path verification

import os
import sys
import json
import random
import platform
import subprocess
from pathlib import Path

import numpy as np
import pandas as pd

SEED = 42

PROJECT_ROOT = Path("/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026")
EXP_NAME = "F01_YOLO26M_CLS_AUG200"
EXP_DIR = PROJECT_ROOT / "experiments" / EXP_NAME
TABLE_DIR = EXP_DIR / "tables"
FIG_DIR = EXP_DIR / "figures"
WEIGHTS_DIR = EXP_DIR / "weights"

for d in [PROJECT_ROOT, EXP_DIR, TABLE_DIR, FIG_DIR, WEIGHTS_DIR]:
    d.mkdir(parents=True, exist_ok=True)

random.seed(SEED)
np.random.seed(SEED)

print("=" * 80)
print("F01 Step 1 — Environment and Aug-200 path verification")
print("=" * 80)

# -------------------------------------------------------------------------
# Environment check
# -------------------------------------------------------------------------
print("\n" + "=" * 80)
print("Environment")
print("=" * 80)

print("Python:", sys.version.replace("\n", " "))
print("Platform:", platform.platform())
print("Working directory:", os.getcwd())
print("Project root:", PROJECT_ROOT)
print("Experiment dir:", EXP_DIR)

try:
    import torch
    print("Torch:", torch.__version__)
    print("CUDA available:", torch.cuda.is_available())
    print("CUDA device count:", torch.cuda.device_count())

    if torch.cuda.is_available():
        for i in range(torch.cuda.device_count()):
            props = torch.cuda.get_device_properties(i)
            total_gb = props.total_memory / (1024 ** 3)
            print(f"GPU {i}: {props.name} | {total_gb:.2f} GB")
    else:
        print("No GPU detected. Do not start YOLO training until GPU is enabled.")

except Exception as e:
    print("Torch check failed:", repr(e))

try:
    import torchvision
    print("Torchvision:", torchvision.__version__)
except Exception as e:
    print("Torchvision check failed:", repr(e))

try:
    import ultralytics
    from ultralytics import YOLO
    print("Ultralytics:", ultralytics.__version__)
    ULTRALYTICS_AVAILABLE = True
except Exception as e:
    print("Ultralytics not available:", repr(e))
    ULTRALYTICS_AVAILABLE = False

try:
    print("\nNVIDIA-SMI")
    print("-" * 80)
    result = subprocess.run(
        ["nvidia-smi"],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True
    )
    print(result.stdout if result.stdout else result.stderr)
except Exception as e:
    print("nvidia-smi check failed:", repr(e))


# -------------------------------------------------------------------------
# Locate Aug-200 ImageFolder
# -------------------------------------------------------------------------
print("\n" + "=" * 80)
print("Aug-200 ImageFolder path check")
print("=" * 80)

EXPECTED_COUNTS = {
    "train": 7284,
    "val": 1312,
    "test": 1612,
}

EXPECTED_NUM_CLASSES = 20

IMAGE_EXTENSIONS = {
    ".jpg", ".jpeg", ".png", ".bmp", ".webp", ".tif", ".tiff"
}

# Add more candidates here if your F00 output dataset has a different Kaggle input name.
AUG200_CANDIDATES = [
    PROJECT_ROOT / "balanced_train" / "aug200_imagefolder",
    Path("/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/balanced_train/aug200_imagefolder"),
    Path("/kaggle/input/AQUA20_FINAL_BEAT_BASE_04072026/balanced_train/aug200_imagefolder"),
    Path("/kaggle/input/aqua20-final-beat-base-04072026/balanced_train/aug200_imagefolder"),
    Path("/kaggle/input/aqua20-f00-final-beat-base-04072026/balanced_train/aug200_imagefolder"),
]

DATA_ROOT = None

for candidate in AUG200_CANDIDATES:
    if candidate.exists():
        DATA_ROOT = candidate
        break

print("Detected DATA_ROOT:", DATA_ROOT)

if DATA_ROOT is None:
    print("\nAUG-200 DATASET NOT FOUND.")
    print("Please attach the F00 output as a Kaggle dataset/input, or re-run the minimal F00 creation cells.")
    print("\nChecked candidate paths:")
    for p in AUG200_CANDIDATES:
        print("-", p)

    status = {
        "step": "F01 Step 1",
        "status": "FAILED",
        "reason": "Aug-200 ImageFolder root not found",
        "checked_paths": [str(p) for p in AUG200_CANDIDATES],
    }

    with open(TABLE_DIR / "f01_step1_status.json", "w") as f:
        json.dump(status, f, indent=2)

    raise FileNotFoundError("Aug-200 ImageFolder root was not found.")

print("DATA_ROOT exists:", DATA_ROOT.exists())
print("DATA_ROOT:", DATA_ROOT)


# -------------------------------------------------------------------------
# Split and class verification
# -------------------------------------------------------------------------
print("\n" + "=" * 80)
print("Split and class verification")
print("=" * 80)

def count_images(split_dir):
    count = 0
    for p in split_dir.rglob("*"):
        if p.is_file() and p.suffix.lower() in IMAGE_EXTENSIONS:
            count += 1
    return count

records = []
class_lists = {}

all_checks_passed = True

for split_name, expected_count in EXPECTED_COUNTS.items():
    split_dir = DATA_ROOT / split_name
    split_exists = split_dir.exists()

    if not split_exists:
        all_checks_passed = False
        image_count = 0
        class_names = []
    else:
        class_names = sorted([p.name for p in split_dir.iterdir() if p.is_dir()])
        image_count = count_images(split_dir)

    class_lists[split_name] = class_names

    count_passed = image_count == expected_count
    class_count_passed = len(class_names) == EXPECTED_NUM_CLASSES

    if not count_passed or not class_count_passed or not split_exists:
        all_checks_passed = False

    records.append({
        "split": split_name,
        "path": str(split_dir),
        "split_exists": split_exists,
        "image_count": image_count,
        "expected_image_count": expected_count,
        "image_count_passed": count_passed,
        "class_count": len(class_names),
        "expected_class_count": EXPECTED_NUM_CLASSES,
        "class_count_passed": class_count_passed,
    })

verify_df = pd.DataFrame(records)
display(verify_df)

verify_csv = TABLE_DIR / "f01_step1_aug200_split_verify.csv"
verify_df.to_csv(verify_csv, index=False)
print("Saved split verification:", verify_csv)


# -------------------------------------------------------------------------
# Class order stability check
# -------------------------------------------------------------------------
print("\n" + "=" * 80)
print("Class order stability")
print("=" * 80)

train_classes = class_lists.get("train", [])
val_classes = class_lists.get("val", [])
test_classes = class_lists.get("test", [])

class_order_stable = (
    train_classes == val_classes == test_classes
    and len(train_classes) == EXPECTED_NUM_CLASSES
)

if not class_order_stable:
    all_checks_passed = False

print("Class order stable:", class_order_stable)

mapping_df = pd.DataFrame({
    "class_id": list(range(len(train_classes))),
    "class_name": train_classes,
})

display(mapping_df)

mapping_csv = TABLE_DIR / "f01_step1_class_id_folder_mapping.csv"
mapping_df.to_csv(mapping_csv, index=False)
print("Saved class mapping:", mapping_csv)


# -------------------------------------------------------------------------
# Save final Step 1 status
# -------------------------------------------------------------------------
print("\n" + "=" * 80)
print("Final F01 Step 1 status")
print("=" * 80)

status = {
    "step": "F01 Step 1 — Environment and Aug-200 path verification",
    "status": "PASSED" if all_checks_passed else "FAILED",
    "seed": SEED,
    "project_root": str(PROJECT_ROOT),
    "exp_name": EXP_NAME,
    "exp_dir": str(EXP_DIR),
    "data_root": str(DATA_ROOT),
    "ultralytics_available": ULTRALYTICS_AVAILABLE,
    "class_order_stable": class_order_stable,
    "expected_counts": EXPECTED_COUNTS,
    "split_verify_csv": str(verify_csv),
    "class_mapping_csv": str(mapping_csv),
}

status_json = TABLE_DIR / "f01_step1_status.json"
with open(status_json, "w") as f:
    json.dump(status, f, indent=2)

path_txt = TABLE_DIR / "f01_step1_paths.txt"
with open(path_txt, "w") as f:
    f.write(f"PROJECT_ROOT={PROJECT_ROOT}\n")
    f.write(f"EXP_NAME={EXP_NAME}\n")
    f.write(f"EXP_DIR={EXP_DIR}\n")
    f.write(f"DATA_ROOT={DATA_ROOT}\n")
    f.write(f"TABLE_DIR={TABLE_DIR}\n")
    f.write(f"FIG_DIR={FIG_DIR}\n")
    f.write(f"WEIGHTS_DIR={WEIGHTS_DIR}\n")

print("Saved status:", status_json)
print("Saved paths:", path_txt)
print("Step 1 status:", status["status"])

if not all_checks_passed:
    raise RuntimeError("F01 Step 1 failed. Fix the dataset/path issue before training.")

print("\nF01 Step 1 passed. Do not train yet. Paste this output before moving to F01 Step 2.")

## F01 Step 1B — Install Ultralytics and verify YOLO26m-cls availability

F01 Step 1 confirmed that the Aug-200 ImageFolder dataset is ready.

This bridge step checks the missing YOLO dependency before training:

- installs Ultralytics if missing
- records Ultralytics version
- verifies that YOLO can import
- tests whether `yolo26m-cls.pt` is available/loadable
- falls back only for checking, not for final training

Training will not start in this cell.

In [ ]:
# # F01 Step 1B — Install Ultralytics and verify YOLO26m-cls availability

# import sys
# import json
# import subprocess
# from pathlib import Path

# SEED = 42

# PROJECT_ROOT = Path("/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026")
# EXP_NAME = "F01_YOLO26M_CLS_AUG200"
# EXP_DIR = PROJECT_ROOT / "experiments" / EXP_NAME
# TABLE_DIR = EXP_DIR / "tables"
# WEIGHTS_DIR = EXP_DIR / "weights"

# for d in [EXP_DIR, TABLE_DIR, WEIGHTS_DIR]:
#     d.mkdir(parents=True, exist_ok=True)

# print("=" * 80)
# print("F01 Step 1B — Install Ultralytics and verify YOLO26m-cls availability")
# print("=" * 80)

# # -------------------------------------------------------------------------
# # Install Ultralytics if missing
# # -------------------------------------------------------------------------
# print("\n" + "=" * 80)
# print("Ultralytics installation check")
# print("=" * 80)

# try:
#     import ultralytics
#     from ultralytics import YOLO
#     print("Ultralytics already installed:", ultralytics.__version__)
#     installed_now = False
# except Exception as e:
#     print("Ultralytics missing. Installing now...")
#     print("Reason:", repr(e))

#     cmd = [sys.executable, "-m", "pip", "install", "-q", "-U", "ultralytics"]
#     result = subprocess.run(
#         cmd,
#         stdout=subprocess.PIPE,
#         stderr=subprocess.PIPE,
#         text=True
#     )

#     print("pip stdout:")
#     print(result.stdout[-2000:] if result.stdout else "")

#     print("pip stderr:")
#     print(result.stderr[-2000:] if result.stderr else "")

#     if result.returncode != 0:
#         raise RuntimeError("Ultralytics installation failed. Check pip error above.")

#     import ultralytics
#     from ultralytics import YOLO
#     print("Ultralytics installed:", ultralytics.__version__)
#     installed_now = True


# # -------------------------------------------------------------------------
# # Verify YOLO26m-cls checkpoint availability
# # -------------------------------------------------------------------------
# print("\n" + "=" * 80)
# print("YOLO classification checkpoint availability check")
# print("=" * 80)

# MODEL_CANDIDATES = [
#     "yolo26m-cls.pt",
#     "yolo26s-cls.pt",
#     "yolo26n-cls.pt",
#     "yolo11m-cls.pt",
# ]

# model_check_records = []
# selected_model_name = None

# for model_name in MODEL_CANDIDATES:
#     print(f"\nChecking model: {model_name}")
#     try:
#         model = YOLO(model_name)
#         selected_model_name = model_name

#         model_check_records.append({
#             "model_name": model_name,
#             "loadable": True,
#             "error": "",
#         })

#         print(f"Load check PASSED: {model_name}")
#         break

#     except Exception as e:
#         model_check_records.append({
#             "model_name": model_name,
#             "loadable": False,
#             "error": repr(e),
#         })
#         print(f"Load check FAILED: {model_name}")
#         print("Error:", repr(e))

# if selected_model_name is None:
#     status = {
#         "step": "F01 Step 1B",
#         "status": "FAILED",
#         "ultralytics_version": ultralytics.__version__,
#         "installed_now": installed_now,
#         "selected_model_name": None,
#         "model_checks": model_check_records,
#     }

#     status_json = TABLE_DIR / "f01_step1b_yolo_model_availability_status.json"
#     with open(status_json, "w") as f:
#         json.dump(status, f, indent=2)

#     print("\nSaved status:", status_json)
#     raise RuntimeError("No YOLO classification checkpoint could be loaded.")

# status = {
#     "step": "F01 Step 1B — Install Ultralytics and verify YOLO26m-cls availability",
#     "status": "PASSED",
#     "ultralytics_version": ultralytics.__version__,
#     "installed_now": installed_now,
#     "selected_model_name": selected_model_name,
#     "target_model_name": "yolo26m-cls.pt",
#     "is_target_model_available": selected_model_name == "yolo26m-cls.pt",
#     "model_checks": model_check_records,
# }

# status_json = TABLE_DIR / "f01_step1b_yolo_model_availability_status.json"
# with open(status_json, "w") as f:
#     json.dump(status, f, indent=2)

# model_txt = TABLE_DIR / "f01_step1b_selected_model.txt"
# with open(model_txt, "w") as f:
#     f.write(f"selected_model_name={selected_model_name}\n")
#     f.write(f"target_model_name=yolo26m-cls.pt\n")
#     f.write(f"is_target_model_available={selected_model_name == 'yolo26m-cls.pt'}\n")
#     f.write(f"ultralytics_version={ultralytics.__version__}\n")

# print("\n" + "=" * 80)
# print("Final F01 Step 1B status")
# print("=" * 80)
# print("Ultralytics version:", ultralytics.__version__)
# print("Selected model:", selected_model_name)
# print("Target YOLO26m-cls available:", selected_model_name == "yolo26m-cls.pt")
# print("Saved status:", status_json)
# print("Saved selected model path text:", model_txt)

# if selected_model_name != "yolo26m-cls.pt":
#     print("\nWARNING:")
#     print("YOLO26m-cls was not loadable. A fallback was only detected for documentation.")
#     print("Do not continue to official F01 training until you decide whether to install a newer Ultralytics version or document fallback clearly.")
# else:
#     print("\nF01 Step 1B passed. YOLO26m-cls is available.")
#     print("Do not train yet. Paste this output before moving to F01 Step 2.")

## F01 Step 2 — Train YOLO26m-cls on Aug-200

This step starts the official F01 training run.

Configuration:

- Dataset: Aug-200 train-only balanced ImageFolder
- Model: `yolo26m-cls.pt`
- GPU: single P100, `device=0`
- Validation: unchanged official validation split
- Test: not used during training
- Selection: Ultralytics best checkpoint based on validation performance

After training finishes, this cell saves:

- training configuration
- training run path
- best checkpoint path
- last checkpoint path
- results CSV path if produced

In [ ]:
# F01 Step 1 — Environment and Aug-200 path verification

import os
import sys
import json
import subprocess
from pathlib import Path

# -------------------------------------------------------------------------
# Reproducibility environment configuration before Torch import
# -------------------------------------------------------------------------
SEED = 42

print("=" * 80)
print("F01 Step 1 — Environment and Aug-200 path verification")
print("=" * 80)

print("\n" + "=" * 80)
print("Reproducibility environment configuration")
print("=" * 80)

if "torch" in sys.modules:
    raise RuntimeError(
        "Torch was already imported before deterministic CUDA configuration. "
        "Restart the Kaggle session/kernel and run this cell first."
    )

os.environ["CUBLAS_WORKSPACE_CONFIG"] = ":4096:8"
os.environ["PYTHONHASHSEED"] = str(SEED)

print(
    "CUBLAS_WORKSPACE_CONFIG:",
    os.environ.get("CUBLAS_WORKSPACE_CONFIG")
)
print(
    "PYTHONHASHSEED:",
    os.environ.get("PYTHONHASHSEED")
)

print("\nConfiguration applied before Torch and Ultralytics import.")


# -------------------------------------------------------------------------
# Imports
# -------------------------------------------------------------------------
import torch
import torchvision
import ultralytics

from torchvision.datasets import ImageFolder


# -------------------------------------------------------------------------
# Constants
# -------------------------------------------------------------------------
PROJECT_ROOT = Path(
    "/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026"
)

EXP_NAME = "F01_YOLO26M_CLS_AUG200"

EXP_DIR = PROJECT_ROOT / "experiments" / EXP_NAME
TABLE_DIR = EXP_DIR / "tables"
FIG_DIR = EXP_DIR / "figures"
WEIGHTS_DIR = EXP_DIR / "weights"

EXPECTED_COUNTS = {
    "train": 7284,
    "val": 1312,
    "test": 1612,
}

EXPECTED_NUM_CLASSES = 20

VALID_IMAGE_EXTENSIONS = {
    ".jpg",
    ".jpeg",
    ".png",
    ".bmp",
    ".tif",
    ".tiff",
    ".webp",
}

for path in [
    PROJECT_ROOT,
    EXP_DIR,
    TABLE_DIR,
    FIG_DIR,
    WEIGHTS_DIR,
]:
    path.mkdir(parents=True, exist_ok=True)


# -------------------------------------------------------------------------
# Environment information
# -------------------------------------------------------------------------
print("\n" + "=" * 80)
print("Python and library environment")
print("=" * 80)

print("Python:", sys.version.replace("\n", " "))
print("PyTorch:", torch.__version__)
print("Torchvision:", torchvision.__version__)
print("Ultralytics:", ultralytics.__version__)
print("CUDA available:", torch.cuda.is_available())
print("CUDA runtime reported by Torch:", torch.version.cuda)
print("CUDA device count:", torch.cuda.device_count())

if not torch.cuda.is_available():
    raise RuntimeError(
        "CUDA GPU is not available. F01 must not start training on CPU."
    )

for device_id in range(torch.cuda.device_count()):
    print(
        f"GPU {device_id}:",
        torch.cuda.get_device_name(device_id)
    )

print("\n" + "-" * 80)
print("nvidia-smi")
print("-" * 80)

nvidia_result = subprocess.run(
    ["nvidia-smi"],
    capture_output=True,
    text=True,
    check=False,
)

if nvidia_result.returncode == 0:
    print(nvidia_result.stdout)
else:
    print("nvidia-smi could not be executed.")
    print(nvidia_result.stderr)


# -------------------------------------------------------------------------
# Locate Aug-200 ImageFolder dataset
# -------------------------------------------------------------------------
print("\n" + "=" * 80)
print("Searching for Aug-200 ImageFolder dataset")
print("=" * 80)

EXPECTED_RELATIVE_PATH = Path(
    "balanced_train/aug200_imagefolder"
)

DIRECT_CANDIDATES = [
    PROJECT_ROOT / EXPECTED_RELATIVE_PATH,
]

SEARCH_ROOTS = [
    Path("/kaggle/working"),
    Path("/kaggle/input"),
]

candidate_paths = []

for candidate in DIRECT_CANDIDATES:
    if candidate.exists():
        candidate_paths.append(candidate.resolve())

for search_root in SEARCH_ROOTS:
    if not search_root.exists():
        continue

    for candidate in search_root.rglob("aug200_imagefolder"):
        if candidate.is_dir():
            candidate_paths.append(candidate.resolve())

candidate_paths = sorted(set(candidate_paths))

print(f"Candidate Aug-200 folders found: {len(candidate_paths)}")

for candidate in candidate_paths:
    print(" -", candidate)

if not candidate_paths:
    raise FileNotFoundError(
        "No 'aug200_imagefolder' directory was found under "
        "/kaggle/working or /kaggle/input. "
        "Attach the saved F00 output dataset before continuing."
    )


# -------------------------------------------------------------------------
# Validate candidates and select exact F00 Aug-200 dataset
# -------------------------------------------------------------------------
print("\n" + "=" * 80)
print("Validating Aug-200 dataset candidates")
print("=" * 80)

valid_candidates = []

for candidate in candidate_paths:
    split_counts = {}
    candidate_ok = True

    for split_name, expected_count in EXPECTED_COUNTS.items():
        split_dir = candidate / split_name

        if not split_dir.is_dir():
            candidate_ok = False
            break

        image_count = sum(
            1
            for path in split_dir.rglob("*")
            if path.is_file()
            and path.suffix.lower() in VALID_IMAGE_EXTENSIONS
        )

        split_counts[split_name] = image_count

        if image_count != expected_count:
            candidate_ok = False

    if candidate_ok:
        valid_candidates.append(
            {
                "path": candidate,
                "counts": split_counts,
            }
        )

    print(
        f"{candidate} | "
        f"counts={split_counts} | "
        f"exact_match={candidate_ok}"
    )

if len(valid_candidates) == 0:
    raise RuntimeError(
        "Aug-200 folder candidate(s) were found, but none matched "
        "the expected train=7284, val=1312, test=1612 counts."
    )

if len(valid_candidates) > 1:
    raise RuntimeError(
        "More than one exact Aug-200 dataset candidate was found. "
        "Refusing to silently choose one.\n\n"
        + "\n".join(
            str(item["path"])
            for item in valid_candidates
        )
    )

DATA_ROOT = valid_candidates[0]["path"]

TRAIN_DIR = DATA_ROOT / "train"
VAL_DIR = DATA_ROOT / "val"
TEST_DIR = DATA_ROOT / "test"

print("\nSelected DATA_ROOT:")
print(DATA_ROOT)


# -------------------------------------------------------------------------
# ImageFolder class and class-order verification
# -------------------------------------------------------------------------
print("\n" + "=" * 80)
print("ImageFolder class-order verification")
print("=" * 80)

train_dataset = ImageFolder(TRAIN_DIR)
val_dataset = ImageFolder(VAL_DIR)
test_dataset = ImageFolder(TEST_DIR)

train_classes = train_dataset.classes
val_classes = val_dataset.classes
test_classes = test_dataset.classes

train_mapping = train_dataset.class_to_idx
val_mapping = val_dataset.class_to_idx
test_mapping = test_dataset.class_to_idx

print("Train images:", len(train_dataset))
print("Val images:", len(val_dataset))
print("Test images:", len(test_dataset))

print("\nTrain class folders:", len(train_classes))
print("Val class folders:", len(val_classes))
print("Test class folders:", len(test_classes))

if len(train_dataset) != EXPECTED_COUNTS["train"]:
    raise RuntimeError(
        f"Train count mismatch: {len(train_dataset)} "
        f"!= {EXPECTED_COUNTS['train']}"
    )

if len(val_dataset) != EXPECTED_COUNTS["val"]:
    raise RuntimeError(
        f"Validation count mismatch: {len(val_dataset)} "
        f"!= {EXPECTED_COUNTS['val']}"
    )

if len(test_dataset) != EXPECTED_COUNTS["test"]:
    raise RuntimeError(
        f"Test count mismatch: {len(test_dataset)} "
        f"!= {EXPECTED_COUNTS['test']}"
    )

if len(train_classes) != EXPECTED_NUM_CLASSES:
    raise RuntimeError(
        f"Expected {EXPECTED_NUM_CLASSES} train classes, "
        f"found {len(train_classes)}."
    )

if train_classes != val_classes:
    raise RuntimeError(
        "Train and validation class order do not match."
    )

if train_classes != test_classes:
    raise RuntimeError(
        "Train and test class order do not match."
    )

if train_mapping != val_mapping:
    raise RuntimeError(
        "Train and validation class_to_idx mappings do not match."
    )

if train_mapping != test_mapping:
    raise RuntimeError(
        "Train and test class_to_idx mappings do not match."
    )

print("Class count check: PASSED")
print("Class order consistency: PASSED")
print("class_to_idx consistency: PASSED")

print("\nStable class mapping:")

for class_name, class_id in train_mapping.items():
    print(f"{class_id:02d} -> {class_name}")


# -------------------------------------------------------------------------
# Save F01 Step 1 verification outputs
# -------------------------------------------------------------------------
verification_summary = {
    "experiment": EXP_NAME,
    "seed": SEED,
    "data_root": str(DATA_ROOT),
    "train_dir": str(TRAIN_DIR),
    "val_dir": str(VAL_DIR),
    "test_dir": str(TEST_DIR),
    "train_count": len(train_dataset),
    "val_count": len(val_dataset),
    "test_count": len(test_dataset),
    "num_classes": len(train_classes),
    "class_order_consistent": True,
    "class_mapping_consistent": True,
    "python_version": sys.version.replace("\n", " "),
    "torch_version": torch.__version__,
    "torchvision_version": torchvision.__version__,
    "ultralytics_version": ultralytics.__version__,
    "cuda_available": torch.cuda.is_available(),
    "cuda_version": torch.version.cuda,
    "cuda_device_count": torch.cuda.device_count(),
    "gpu_names": [
        torch.cuda.get_device_name(device_id)
        for device_id in range(torch.cuda.device_count())
    ],
    "cublas_workspace_config": os.environ.get(
        "CUBLAS_WORKSPACE_CONFIG"
    ),
    "pythonhashseed": os.environ.get("PYTHONHASHSEED"),
}

summary_path = (
    TABLE_DIR /
    "f01_step1_environment_data_verification.json"
)

mapping_path = TABLE_DIR / "f01_class_to_idx.json"
data_root_path = EXP_DIR / "f01_selected_data_root.txt"

with open(summary_path, "w", encoding="utf-8") as file:
    json.dump(
        verification_summary,
        file,
        indent=2,
        default=str,
    )

with open(mapping_path, "w", encoding="utf-8") as file:
    json.dump(
        train_mapping,
        file,
        indent=2,
    )

with open(data_root_path, "w", encoding="utf-8") as file:
    file.write(str(DATA_ROOT))

print("\n" + "=" * 80)
print("F01 Step 1 final status")
print("=" * 80)

print("Environment configuration: PASSED")
print("CUDA verification: PASSED")
print("Ultralytics import: PASSED")
print("Aug-200 exact dataset match: PASSED")
print("Train/val/test count verification: PASSED")
print("20-class verification: PASSED")
print("Class-order verification: PASSED")
print("Class-mapping verification: PASSED")

print("\nDATA_ROOT:")
print(DATA_ROOT)

print("\nSaved:")
print(summary_path)
print(mapping_path)
print(data_root_path)

print("\nF01 Step 1 completed successfully.")
print("Training has NOT started.")

# F01 Step 2 — Train YOLO26m-cls on Aug-200

Train pretrained YOLO26m-cls using the Aug-200 training dataset.

Experimental control:
- Aug-200 balancing is applied only to training data
- validation remains unchanged
- test remains unchanged
- no class-weighted loss
- no focal loss
- no additional label-smoothing intervention
- validation is used during training and checkpoint selection
- official test evaluation is performed only after training

Training configuration:
- Model: YOLO26m-cls
- Image size: 224
- Batch size: 64
- Maximum epochs: 200
- Early-stopping patience: 30
- GPU: Tesla P100, device 0
- Seed: 42

In [ ]:
# F01 Step 2 — Train YOLO26m-cls on Aug-200

import json
from pathlib import Path

import torch
from ultralytics import YOLO


# # -------------------------------------------------------------------------
# # Remove previous incomplete or non-official F01 training artifacts
# # -------------------------------------------------------------------------
# RUN_DIR = YOLO_RUN_DIR / YOLO_RUN_NAME

# OLD_SAFETY_DIR = Path(
#     "/kaggle/working/F01_YOLO26M_CLS_AUG200_SAFETY"
# )

# OLD_SAFETY_PACKAGE = Path(
#     "/kaggle/working/"
#     "F01_YOLO26M_CLS_AUG200_SAFETY_PACKAGE.zip"
# )

# print("\n" + "=" * 80)
# print("Cleaning previous F01 run artifacts")
# print("=" * 80)

# if RUN_DIR.exists():
#     print("Removing previous YOLO run:")
#     print(RUN_DIR)

#     shutil.rmtree(
#         RUN_DIR
#     )

# if OLD_SAFETY_DIR.exists():
#     print("\nRemoving previous active safety directory:")
#     print(OLD_SAFETY_DIR)

#     shutil.rmtree(
#         OLD_SAFETY_DIR
#     )

# if OLD_SAFETY_PACKAGE.exists():
#     print("\nRemoving previous active safety ZIP:")
#     print(OLD_SAFETY_PACKAGE)

#     OLD_SAFETY_PACKAGE.unlink()

# print("\nPrevious active F01 run artifacts removed.")
# print("Downloaded local safety package is unaffected.")

# -------------------------------------------------------------------------
# Experiment constants
# -------------------------------------------------------------------------
SEED = 42

PROJECT_ROOT = Path(
    "/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026"
)

DATA_ROOT = (
    PROJECT_ROOT
    / "balanced_train"
    / "aug200_imagefolder"
)

EXP_NAME = "F01_YOLO26M_CLS_AUG200"

EXP_DIR = (
    PROJECT_ROOT
    / "experiments"
    / EXP_NAME
)

TABLE_DIR = EXP_DIR / "tables"
FIG_DIR = EXP_DIR / "figures"
WEIGHTS_DIR = EXP_DIR / "weights"

YOLO_RUN_DIR = EXP_DIR / "yolo_runs"
YOLO_RUN_NAME = "train"

MODEL_NAME = "yolo26m-cls.pt"

IMGSZ = 224
BATCH_SIZE = 64
EPOCHS = 200
PATIENCE = 30
DEVICE = 0
WORKERS = 8


# -------------------------------------------------------------------------
# Verify critical paths and GPU
# -------------------------------------------------------------------------
print("=" * 80)
print("F01 Step 2 — Train YOLO26m-cls on Aug-200")
print("=" * 80)

for split_name in ["train", "val", "test"]:
    split_dir = DATA_ROOT / split_name

    if not split_dir.is_dir():
        raise FileNotFoundError(
            f"Missing required split directory: {split_dir}"
        )

if not torch.cuda.is_available():
    raise RuntimeError(
        "CUDA is not available. Refusing to train F01 on CPU."
    )

gpu_name = torch.cuda.get_device_name(DEVICE)

print("Experiment:", EXP_NAME)
print("Model:", MODEL_NAME)
print("Data root:", DATA_ROOT)
print("GPU:", gpu_name)
print("Device:", DEVICE)
print("Image size:", IMGSZ)
print("Batch size:", BATCH_SIZE)
print("Maximum epochs:", EPOCHS)
print("Patience:", PATIENCE)
print("Workers:", WORKERS)
print("Seed:", SEED)


# -------------------------------------------------------------------------
# Create experiment folders
# -------------------------------------------------------------------------
for path in [
    EXP_DIR,
    TABLE_DIR,
    FIG_DIR,
    WEIGHTS_DIR,
    YOLO_RUN_DIR,
]:
    path.mkdir(parents=True, exist_ok=True)


# -------------------------------------------------------------------------
# Save exact F01 training configuration before training
# -------------------------------------------------------------------------
training_config = {
    "experiment": EXP_NAME,
    "strategy": "Aug-200 train-only balancing",
    "model": MODEL_NAME,
    "data_root": str(DATA_ROOT),
    "train_split": str(DATA_ROOT / "train"),
    "val_split": str(DATA_ROOT / "val"),
    "test_split": str(DATA_ROOT / "test"),
    "imgsz": IMGSZ,
    "batch": BATCH_SIZE,
    "epochs": EPOCHS,
    "patience": PATIENCE,
    "device": DEVICE,
    "gpu_name": gpu_name,
    "workers": WORKERS,
    "seed": SEED,
    "deterministic": True,
    "pretrained": True,
    "optimizer": "auto",
    "amp": True,
    "cache": False,
    "label_smoothing": 0.0,
    "custom_class_weights": False,
    "custom_focal_loss": False,
    "project": str(YOLO_RUN_DIR),
    "name": YOLO_RUN_NAME,
}

config_path = (
    TABLE_DIR
    / "f01_step2_training_configuration.json"
)

with open(config_path, "w", encoding="utf-8") as file:
    json.dump(
        training_config,
        file,
        indent=2,
    )

print("\nTraining configuration saved:")
print(config_path)


# -------------------------------------------------------------------------
# Load pretrained YOLO26m-cls
# -------------------------------------------------------------------------
print("\n" + "=" * 80)
print("Loading pretrained YOLO26m-cls")
print("=" * 80)

model = YOLO(MODEL_NAME)

print("Model loaded successfully.")
print("Model task:", model.task)

if model.task != "classify":
    raise RuntimeError(
        f"Expected classification model, found task={model.task}"
    )


# -------------------------------------------------------------------------
# Train F01
# -------------------------------------------------------------------------
print("\n" + "=" * 80)
print("Starting F01 training")
print("=" * 80)

train_results = model.train(
    data=str(DATA_ROOT),
    epochs=EPOCHS,
    patience=PATIENCE,
    imgsz=IMGSZ,
    batch=BATCH_SIZE,
    device=DEVICE,
    workers=WORKERS,
    pretrained=True,
    optimizer="auto",
    seed=SEED,
    deterministic=True,
    amp=True,
    cache=False,
    label_smoothing=0.0,
    project=str(YOLO_RUN_DIR),
    name=YOLO_RUN_NAME,
    exist_ok=True,
    save=True,
    save_period=-1,
    plots=True,
    verbose=True,
)


# -------------------------------------------------------------------------
# Verify saved training outputs
# -------------------------------------------------------------------------
RUN_DIR = YOLO_RUN_DIR / YOLO_RUN_NAME

BEST_MODEL_PATH = RUN_DIR / "weights" / "best.pt"
LAST_MODEL_PATH = RUN_DIR / "weights" / "last.pt"
RESULTS_CSV_PATH = RUN_DIR / "results.csv"

print("\n" + "=" * 80)
print("F01 Step 2 training output verification")
print("=" * 80)

print("Run directory:", RUN_DIR)
print("Best model:", BEST_MODEL_PATH)
print("Last model:", LAST_MODEL_PATH)
print("Results CSV:", RESULTS_CSV_PATH)

if not BEST_MODEL_PATH.is_file():
    raise FileNotFoundError(
        f"Training finished but best.pt was not found: "
        f"{BEST_MODEL_PATH}"
    )

if not LAST_MODEL_PATH.is_file():
    raise FileNotFoundError(
        f"Training finished but last.pt was not found: "
        f"{LAST_MODEL_PATH}"
    )

if not RESULTS_CSV_PATH.is_file():
    raise FileNotFoundError(
        f"Training finished but results.csv was not found: "
        f"{RESULTS_CSV_PATH}"
    )


# -------------------------------------------------------------------------
# Save important output paths
# -------------------------------------------------------------------------
best_path_txt = EXP_DIR / "f01_best_model_path.txt"
last_path_txt = EXP_DIR / "f01_last_model_path.txt"
run_dir_txt = EXP_DIR / "f01_yolo_run_dir.txt"

best_path_txt.write_text(
    str(BEST_MODEL_PATH),
    encoding="utf-8",
)

last_path_txt.write_text(
    str(LAST_MODEL_PATH),
    encoding="utf-8",
)

run_dir_txt.write_text(
    str(RUN_DIR),
    encoding="utf-8",
)


print("\n" + "=" * 80)
print("F01 Step 2 completed successfully")
print("=" * 80)

print("Training completed.")
print("Best checkpoint verified.")
print("Last checkpoint verified.")
print("Training results CSV verified.")

print("\nBest checkpoint:")
print(BEST_MODEL_PATH)

print("\nOfficial test evaluation has NOT started.")

# F01 Step 2B — Immediate safety package and checkpoint preservation

Preserve the completed F01 training outputs before any further validation or test analysis.

This step:
- verifies the completed YOLO training run
- preserves the validation-selected `best.pt`
- preserves `results.csv`
- preserves the exact Ultralytics `args.yaml`
- preserves F01 configuration and audit files
- calculates SHA-256 hashes for important files
- creates a compact recovery package

The dataset and `last.pt` are not included in the safety package.

No validation, test evaluation, or retraining is performed.

In [ ]:
# F01 Step 2B — Immediate safety package and checkpoint preservation

import hashlib
import json
import shutil
import zipfile
from datetime import datetime, timezone
from pathlib import Path


# -------------------------------------------------------------------------
# Constants
# -------------------------------------------------------------------------
PROJECT_ROOT = Path(
    "/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026"
)

EXP_NAME = "F01_YOLO26M_CLS_AUG200"

EXP_DIR = (
    PROJECT_ROOT
    / "experiments"
    / EXP_NAME
)

TABLE_DIR = EXP_DIR / "tables"

RUN_DIR = (
    EXP_DIR
    / "yolo_runs"
    / "train"
)

BEST_MODEL_PATH = (
    RUN_DIR
    / "weights"
    / "best.pt"
)

LAST_MODEL_PATH = (
    RUN_DIR
    / "weights"
    / "last.pt"
)

RESULTS_CSV_PATH = (
    RUN_DIR
    / "results.csv"
)

ARGS_YAML_PATH = (
    RUN_DIR
    / "args.yaml"
)

TRAIN_CONFIG_PATH = (
    TABLE_DIR
    / "f01_step2_training_configuration.json"
)

STEP1_SUMMARY_PATH = (
    TABLE_DIR
    / "f01_step1_environment_data_verification.json"
)

CLASS_MAPPING_PATH = (
    TABLE_DIR
    / "f01_class_to_idx.json"
)

SELECTED_DATA_ROOT_PATH = (
    EXP_DIR
    / "f01_selected_data_root.txt"
)

BEST_PATH_TEXT = (
    EXP_DIR
    / "f01_best_model_path.txt"
)

LAST_PATH_TEXT = (
    EXP_DIR
    / "f01_last_model_path.txt"
)

RUN_DIR_TEXT = (
    EXP_DIR
    / "f01_yolo_run_dir.txt"
)


# -------------------------------------------------------------------------
# Safety package paths
# -------------------------------------------------------------------------
SAFETY_DIR = Path(
    "/kaggle/working/F01_YOLO26M_CLS_AUG200_SAFETY"
)

SAFETY_PACKAGE_PATH = Path(
    "/kaggle/working/"
    "F01_YOLO26M_CLS_AUG200_SAFETY_PACKAGE.zip"
)

MANIFEST_PATH = (
    SAFETY_DIR
    / "f01_safety_manifest.json"
)

README_PATH = (
    SAFETY_DIR
    / "README_F01_RECOVERY.txt"
)


# -------------------------------------------------------------------------
# Start
# -------------------------------------------------------------------------
print("=" * 80)
print("F01 Step 2B — Immediate safety package and checkpoint preservation")
print("=" * 80)


# -------------------------------------------------------------------------
# Verify essential completed-training files
# -------------------------------------------------------------------------
essential_files = {
    "best.pt": BEST_MODEL_PATH,
    "results.csv": RESULTS_CSV_PATH,
    "args.yaml": ARGS_YAML_PATH,
    "training_configuration": TRAIN_CONFIG_PATH,
}

print("\n" + "=" * 80)
print("COMPLETED TRAINING OUTPUT VERIFICATION")
print("=" * 80)

for file_name, file_path in essential_files.items():

    exists = file_path.is_file()

    print(
        f"{file_name:<28}: "
        f"{'FOUND' if exists else 'MISSING'}"
    )

    print(
        f"  {file_path}"
    )

    if not exists:
        raise FileNotFoundError(
            "Required completed-training file is missing:\n"
            f"{file_path}"
        )


# -------------------------------------------------------------------------
# Verify best checkpoint is non-empty
# -------------------------------------------------------------------------
best_model_size_mb = (
    BEST_MODEL_PATH.stat().st_size
    / (1024 ** 2)
)

results_csv_size_kb = (
    RESULTS_CSV_PATH.stat().st_size
    / 1024
)

if BEST_MODEL_PATH.stat().st_size == 0:
    raise RuntimeError(
        "best.pt exists but is empty."
    )

if RESULTS_CSV_PATH.stat().st_size == 0:
    raise RuntimeError(
        "results.csv exists but is empty."
    )

print()
print(
    f"best.pt size              : "
    f"{best_model_size_mb:.2f} MB"
)

print(
    f"results.csv size          : "
    f"{results_csv_size_kb:.2f} KB"
)

print()
print("Essential training outputs: PASSED")


# -------------------------------------------------------------------------
# Calculate SHA-256
# -------------------------------------------------------------------------
def calculate_sha256(file_path):
    sha256 = hashlib.sha256()

    with open(
        file_path,
        "rb",
    ) as file:
        while True:
            chunk = file.read(
                1024 * 1024
            )

            if not chunk:
                break

            sha256.update(
                chunk
            )

    return sha256.hexdigest()


print("\n" + "=" * 80)
print("CHECKPOINT INTEGRITY HASH")
print("=" * 80)

best_model_sha256 = calculate_sha256(
    BEST_MODEL_PATH
)

results_csv_sha256 = calculate_sha256(
    RESULTS_CSV_PATH
)

args_yaml_sha256 = calculate_sha256(
    ARGS_YAML_PATH
)

print(
    "best.pt SHA-256:"
)

print(
    best_model_sha256
)

print()

print(
    "results.csv SHA-256:"
)

print(
    results_csv_sha256
)


# -------------------------------------------------------------------------
# Create clean safety directory
# -------------------------------------------------------------------------
if SAFETY_DIR.exists():
    shutil.rmtree(
        SAFETY_DIR
    )

SAFETY_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

SAFETY_WEIGHTS_DIR = (
    SAFETY_DIR
    / "weights"
)

SAFETY_TABLE_DIR = (
    SAFETY_DIR
    / "tables"
)

SAFETY_RUN_DIR = (
    SAFETY_DIR
    / "training_run"
)

SAFETY_WEIGHTS_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

SAFETY_TABLE_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

SAFETY_RUN_DIR.mkdir(
    parents=True,
    exist_ok=True,
)


# -------------------------------------------------------------------------
# Copy essential checkpoint
# -------------------------------------------------------------------------
copied_files = []

destination = (
    SAFETY_WEIGHTS_DIR
    / "best.pt"
)

shutil.copy2(
    BEST_MODEL_PATH,
    destination,
)

copied_files.append(
    destination
)


# -------------------------------------------------------------------------
# Copy core YOLO training outputs
# -------------------------------------------------------------------------
run_files_to_copy = [
    RESULTS_CSV_PATH,
    ARGS_YAML_PATH,
]

optional_run_files = [
    RUN_DIR / "results.png",
    RUN_DIR / "train_batch0.jpg",
    RUN_DIR / "train_batch1.jpg",
    RUN_DIR / "train_batch2.jpg",
]

for source_path in run_files_to_copy:

    destination = (
        SAFETY_RUN_DIR
        / source_path.name
    )

    shutil.copy2(
        source_path,
        destination,
    )

    copied_files.append(
        destination
    )


for source_path in optional_run_files:

    if source_path.is_file():

        destination = (
            SAFETY_RUN_DIR
            / source_path.name
        )

        shutil.copy2(
            source_path,
            destination,
        )

        copied_files.append(
            destination
        )


# -------------------------------------------------------------------------
# Copy experiment audit/configuration files
# -------------------------------------------------------------------------
audit_files = [
    TRAIN_CONFIG_PATH,
    STEP1_SUMMARY_PATH,
    CLASS_MAPPING_PATH,
    SELECTED_DATA_ROOT_PATH,
    BEST_PATH_TEXT,
    LAST_PATH_TEXT,
    RUN_DIR_TEXT,
]

for source_path in audit_files:

    if not source_path.is_file():
        print(
            "Optional audit file missing:",
            source_path
        )
        continue

    destination = (
        SAFETY_TABLE_DIR
        / source_path.name
    )

    shutil.copy2(
        source_path,
        destination,
    )

    copied_files.append(
        destination
    )


# -------------------------------------------------------------------------
# Build safety manifest
# -------------------------------------------------------------------------
created_utc = datetime.now(
    timezone.utc
).isoformat()

manifest = {
    "experiment": EXP_NAME,
    "package_type": (
        "immediate post-training safety package"
    ),
    "created_utc": created_utc,
    "training_completed": True,
    "validation_analysis_completed": False,
    "official_test_evaluation_completed": False,
    "checkpoint_selection_source": (
        "Ultralytics validation during training"
    ),
    "preserved_checkpoint": "best.pt",
    "last_pt_included": False,
    "dataset_included": False,
    "best_model_original_path": str(
        BEST_MODEL_PATH
    ),
    "best_model_size_mb": (
        best_model_size_mb
    ),
    "best_model_sha256": (
        best_model_sha256
    ),
    "results_csv_sha256": (
        results_csv_sha256
    ),
    "args_yaml_sha256": (
        args_yaml_sha256
    ),
    "copied_files": [
        str(
            path.relative_to(
                SAFETY_DIR
            )
        )
        for path in copied_files
    ],
}

with open(
    MANIFEST_PATH,
    "w",
    encoding="utf-8",
) as file:
    json.dump(
        manifest,
        file,
        indent=2,
    )


# -------------------------------------------------------------------------
# Write recovery README
# -------------------------------------------------------------------------
recovery_text = f"""
F01 AQUA20 SAFETY PACKAGE
=========================

Experiment:
{EXP_NAME}

Package stage:
Immediately after completed training.

Preserved checkpoint:
weights/best.pt

Checkpoint selection:
Validation-based Ultralytics best checkpoint.

Original checkpoint path:
{BEST_MODEL_PATH}

best.pt SHA-256:
{best_model_sha256}

results.csv SHA-256:
{results_csv_sha256}

Important:
- The AQUA20 dataset is NOT included.
- last.pt is NOT included.
- No official test metrics are stored in this package yet.
- No test-based checkpoint selection was performed.
- Use weights/best.pt for F01 Step 3 and Step 4 recovery.

Created UTC:
{created_utc}
""".strip()

README_PATH.write_text(
    recovery_text,
    encoding="utf-8",
)


# -------------------------------------------------------------------------
# Create compact ZIP package
# -------------------------------------------------------------------------
if SAFETY_PACKAGE_PATH.exists():
    SAFETY_PACKAGE_PATH.unlink()

with zipfile.ZipFile(
    SAFETY_PACKAGE_PATH,
    mode="w",
    compression=zipfile.ZIP_DEFLATED,
    compresslevel=6,
) as zip_file:

    for file_path in sorted(
        SAFETY_DIR.rglob("*")
    ):

        if file_path.is_file():

            archive_name = (
                Path(
                    SAFETY_DIR.name
                )
                / file_path.relative_to(
                    SAFETY_DIR
                )
            )

            zip_file.write(
                file_path,
                arcname=str(
                    archive_name
                ),
            )


# -------------------------------------------------------------------------
# Verify ZIP
# -------------------------------------------------------------------------
if not SAFETY_PACKAGE_PATH.is_file():
    raise FileNotFoundError(
        "F01 safety ZIP was not created."
    )

zip_size_mb = (
    SAFETY_PACKAGE_PATH.stat().st_size
    / (1024 ** 2)
)

with zipfile.ZipFile(
    SAFETY_PACKAGE_PATH,
    mode="r",
) as zip_file:

    corrupt_member = (
        zip_file.testzip()
    )

    zip_members = (
        zip_file.namelist()
    )

if corrupt_member is not None:
    raise RuntimeError(
        "ZIP integrity check failed for:\n"
        f"{corrupt_member}"
    )

required_zip_suffixes = {
    "weights/best.pt",
    "training_run/results.csv",
    "training_run/args.yaml",
    "f01_safety_manifest.json",
    "README_F01_RECOVERY.txt",
}

for required_suffix in required_zip_suffixes:

    if not any(
        member.endswith(
            required_suffix
        )
        for member in zip_members
    ):
        raise RuntimeError(
            "Required file missing from ZIP:\n"
            f"{required_suffix}"
        )


# -------------------------------------------------------------------------
# Final clean status
# -------------------------------------------------------------------------
print("\n" + "=" * 80)
print("F01 SAFETY PACKAGE RESULT")
print("=" * 80)

print(
    f"Experiment           : "
    f"{EXP_NAME}"
)

print(
    "Training status      : COMPLETED"
)

print(
    "Preserved checkpoint : best.pt"
)

print(
    f"Checkpoint size      : "
    f"{best_model_size_mb:.2f} MB"
)

print(
    "Dataset included     : NO"
)

print(
    "last.pt included     : NO"
)

print()

print(
    f"Safety files copied  : "
    f"{len(copied_files)}"
)

print(
    f"ZIP members          : "
    f"{len(zip_members)}"
)

print(
    f"ZIP size             : "
    f"{zip_size_mb:.2f} MB"
)

print(
    "ZIP integrity        : PASSED"
)

print()

print(
    "best.pt SHA-256:"
)

print(
    best_model_sha256
)

print()

print(
    "SAFETY PACKAGE:"
)

print(
    SAFETY_PACKAGE_PATH
)

print()
print(
    "DO NOT continue to F01 Step 3 "
    "until this package is preserved."
)

print("=" * 80)
print("F01 Step 2B completed successfully")
print("=" * 80)

# F01 Step 2C — Final safety package audit

Audit the completed F01 safety package before validation and test analysis.

This step:
- lists every file stored in the safety ZIP
- verifies all required recovery files
- confirms `best.pt` integrity against the original checkpoint
- confirms `results.csv` integrity
- inspects the training-history structure
- inspects the saved training arguments
- verifies that the dataset and `last.pt` are excluded
- confirms the package can restore the completed F01 training run

No training, validation, or test evaluation is performed.

In [ ]:
# F01 Step 2C — Final safety package audit

import hashlib
import json
import zipfile
from pathlib import Path

import pandas as pd
import yaml


# -------------------------------------------------------------------------
# Constants
# -------------------------------------------------------------------------
PROJECT_ROOT = Path(
    "/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026"
)

EXP_NAME = "F01_YOLO26M_CLS_AUG200"

EXP_DIR = (
    PROJECT_ROOT
    / "experiments"
    / EXP_NAME
)

RUN_DIR = (
    EXP_DIR
    / "yolo_runs"
    / "train"
)

BEST_MODEL_PATH = (
    RUN_DIR
    / "weights"
    / "best.pt"
)

RESULTS_CSV_PATH = (
    RUN_DIR
    / "results.csv"
)

ARGS_YAML_PATH = (
    RUN_DIR
    / "args.yaml"
)

SAFETY_PACKAGE_PATH = Path(
    "/kaggle/working/"
    "F01_YOLO26M_CLS_AUG200_SAFETY_PACKAGE.zip"
)

EXPECTED_EXPERIMENT = (
    "F01_YOLO26M_CLS_AUG200"
)

EXPECTED_MODEL = (
    "yolo26m-cls.pt"
)

EXPECTED_DATA_ROOT = (
    "/kaggle/working/"
    "AQUA20_FINAL_BEAT_BASE_04072026/"
    "balanced_train/aug200_imagefolder"
)

EXPECTED_EPOCHS = 200
EXPECTED_PATIENCE = 30
EXPECTED_IMGSZ = 224
EXPECTED_BATCH = 64
EXPECTED_SEED = 42


# -------------------------------------------------------------------------
# SHA-256 helper
# -------------------------------------------------------------------------
def calculate_sha256(file_path):
    sha256 = hashlib.sha256()

    with open(
        file_path,
        "rb",
    ) as file:
        while True:
            chunk = file.read(
                1024 * 1024
            )

            if not chunk:
                break

            sha256.update(
                chunk
            )

    return sha256.hexdigest()


# -------------------------------------------------------------------------
# Start audit
# -------------------------------------------------------------------------
print("=" * 80)
print("F01 Step 2C — Final safety package audit")
print("=" * 80)


# -------------------------------------------------------------------------
# Verify source and package files
# -------------------------------------------------------------------------
required_source_files = {
    "best.pt": BEST_MODEL_PATH,
    "results.csv": RESULTS_CSV_PATH,
    "args.yaml": ARGS_YAML_PATH,
    "safety ZIP": SAFETY_PACKAGE_PATH,
}

print("\n" + "=" * 80)
print("SOURCE FILE VERIFICATION")
print("=" * 80)

for name, path in required_source_files.items():

    status = (
        "FOUND"
        if path.is_file()
        else "MISSING"
    )

    print(
        f"{name:<20}: {status}"
    )

    print(
        f"  {path}"
    )

    if not path.is_file():
        raise FileNotFoundError(
            f"Missing required file: {path}"
        )

print("\nSource file verification: PASSED")


# -------------------------------------------------------------------------
# Inspect ZIP members
# -------------------------------------------------------------------------
print("\n" + "=" * 80)
print("SAFETY ZIP CONTENTS")
print("=" * 80)

with zipfile.ZipFile(
    SAFETY_PACKAGE_PATH,
    mode="r",
) as zip_file:

    corrupt_member = zip_file.testzip()

    if corrupt_member is not None:
        raise RuntimeError(
            "ZIP integrity failure:\n"
            f"{corrupt_member}"
        )

    zip_info_list = zip_file.infolist()

    zip_members = [
        item.filename
        for item in zip_info_list
        if not item.is_dir()
    ]


for index, item in enumerate(
    zip_info_list,
    start=1,
):

    if item.is_dir():
        continue

    size_mb = (
        item.file_size
        / (1024 ** 2)
    )

    print(
        f"{index:02d}. "
        f"{item.filename}"
    )

    print(
        f"    Size: {size_mb:.4f} MB"
    )


print()
print(
    "ZIP file members:",
    len(zip_members)
)

print(
    "ZIP integrity    : PASSED"
)


# -------------------------------------------------------------------------
# Locate required recovery members
# -------------------------------------------------------------------------
required_suffixes = {
    "best_checkpoint": "weights/best.pt",
    "training_history": "training_run/results.csv",
    "training_arguments": "training_run/args.yaml",
    "training_configuration": (
        "tables/"
        "f01_step2_training_configuration.json"
    ),
    "safety_manifest": "f01_safety_manifest.json",
    "recovery_readme": "README_F01_RECOVERY.txt",
}


resolved_members = {}

print("\n" + "=" * 80)
print("REQUIRED RECOVERY FILE VERIFICATION")
print("=" * 80)

for logical_name, suffix in required_suffixes.items():

    matches = [
        member
        for member in zip_members
        if member.endswith(
            suffix
        )
    ]

    if len(matches) != 1:
        raise RuntimeError(
            f"Expected exactly one ZIP member "
            f"ending with '{suffix}', "
            f"found {len(matches)}."
        )

    resolved_members[
        logical_name
    ] = matches[0]

    print(
        f"{logical_name:<24}: FOUND"
    )

    print(
        f"  {matches[0]}"
    )


print("\nRequired recovery files: PASSED")


# -------------------------------------------------------------------------
# Verify excluded content
# -------------------------------------------------------------------------
print("\n" + "=" * 80)
print("PACKAGE EXCLUSION VERIFICATION")
print("=" * 80)

last_pt_members = [
    member
    for member in zip_members
    if member.endswith(
        "/last.pt"
    )
]

dataset_members = [
    member
    for member in zip_members
    if (
        "/aug200_imagefolder/" in member
        or "/train/" in member
        and (
            member.lower().endswith(".jpg")
            or member.lower().endswith(".jpeg")
            or member.lower().endswith(".png")
            or member.lower().endswith(".webp")
        )
    )
]

print(
    "last.pt members       :",
    len(last_pt_members)
)

print(
    "dataset image members :",
    len(dataset_members)
)

if last_pt_members:
    raise RuntimeError(
        "last.pt was unexpectedly included."
    )

if dataset_members:
    raise RuntimeError(
        "Dataset images were unexpectedly included."
    )

print("last.pt excluded       : PASSED")
print("Dataset excluded       : PASSED")


# -------------------------------------------------------------------------
# Compare ZIP best.pt with original best.pt
# -------------------------------------------------------------------------
print("\n" + "=" * 80)
print("BEST CHECKPOINT HASH VERIFICATION")
print("=" * 80)

source_best_sha256 = calculate_sha256(
    BEST_MODEL_PATH
)

with zipfile.ZipFile(
    SAFETY_PACKAGE_PATH,
    mode="r",
) as zip_file:

    zip_best_bytes = zip_file.read(
        resolved_members[
            "best_checkpoint"
        ]
    )

zip_best_sha256 = hashlib.sha256(
    zip_best_bytes
).hexdigest()


print("Original best.pt SHA-256:")
print(source_best_sha256)

print()

print("ZIP best.pt SHA-256:")
print(zip_best_sha256)

if (
    source_best_sha256
    != zip_best_sha256
):
    raise RuntimeError(
        "ZIP best.pt does not match "
        "the original trained checkpoint."
    )

print()
print("Checkpoint hash match : PASSED")


# -------------------------------------------------------------------------
# Compare ZIP results.csv with original results.csv
# -------------------------------------------------------------------------
print("\n" + "=" * 80)
print("TRAINING HISTORY HASH VERIFICATION")
print("=" * 80)

source_results_sha256 = calculate_sha256(
    RESULTS_CSV_PATH
)

with zipfile.ZipFile(
    SAFETY_PACKAGE_PATH,
    mode="r",
) as zip_file:

    zip_results_bytes = zip_file.read(
        resolved_members[
            "training_history"
        ]
    )

zip_results_sha256 = hashlib.sha256(
    zip_results_bytes
).hexdigest()


print("Original results.csv SHA-256:")
print(source_results_sha256)

print()

print("ZIP results.csv SHA-256:")
print(zip_results_sha256)

if (
    source_results_sha256
    != zip_results_sha256
):
    raise RuntimeError(
        "ZIP results.csv does not match "
        "the completed training history."
    )

print()
print("Training history match : PASSED")


# -------------------------------------------------------------------------
# Inspect results.csv
# -------------------------------------------------------------------------
print("\n" + "=" * 80)
print("TRAINING HISTORY STRUCTURE")
print("=" * 80)

results_df = pd.read_csv(
    RESULTS_CSV_PATH
)

results_df.columns = [
    column.strip()
    for column in results_df.columns
]

required_result_columns = [
    "epoch",
    "train/loss",
    "metrics/accuracy_top1",
    "metrics/accuracy_top5",
    "val/loss",
]

for column in required_result_columns:

    if column not in results_df.columns:
        raise KeyError(
            f"Missing training-history column: "
            f"{column}"
        )


epoch_values = (
    results_df["epoch"]
    .astype(int)
    .tolist()
)

expected_epoch_values = list(
    range(
        1,
        len(results_df) + 1,
    )
)

if (
    epoch_values
    != expected_epoch_values
):
    raise RuntimeError(
        "Unexpected results.csv epoch sequence."
    )


epochs_completed = int(
    results_df["epoch"].max()
)

best_row_index = (
    results_df[
        "metrics/accuracy_top1"
    ].idxmax()
)

best_row = results_df.loc[
    best_row_index
]

best_epoch = int(
    best_row["epoch"]
)

best_val_top1 = float(
    best_row[
        "metrics/accuracy_top1"
    ]
)

best_val_top5 = float(
    best_row[
        "metrics/accuracy_top5"
    ]
)


print(
    f"Training history rows : "
    f"{len(results_df)}"
)

print(
    f"Epoch sequence        : "
    f"{epoch_values[0]} -> "
    f"{epoch_values[-1]}"
)

print(
    f"Epochs completed      : "
    f"{epochs_completed}"
)

print(
    f"Best epoch by Top-1   : "
    f"{best_epoch}"
)

print(
    f"Best Val Top-1        : "
    f"{best_val_top1 * 100:.4f}%"
)

print(
    f"Best Val Top-5        : "
    f"{best_val_top5 * 100:.4f}%"
)

print()
print("Training history structure: PASSED")


# -------------------------------------------------------------------------
# Inspect saved Ultralytics arguments
# -------------------------------------------------------------------------
print("\n" + "=" * 80)
print("SAVED ULTRALYTICS ARGUMENT AUDIT")
print("=" * 80)

with open(
    ARGS_YAML_PATH,
    "r",
    encoding="utf-8",
) as file:
    training_args = yaml.safe_load(
        file
    )


argument_checks = {
    "model": (
        training_args.get("model"),
        EXPECTED_MODEL,
    ),
    "data": (
        training_args.get("data"),
        EXPECTED_DATA_ROOT,
    ),
    "epochs": (
        training_args.get("epochs"),
        EXPECTED_EPOCHS,
    ),
    "patience": (
        training_args.get("patience"),
        EXPECTED_PATIENCE,
    ),
    "imgsz": (
        training_args.get("imgsz"),
        EXPECTED_IMGSZ,
    ),
    "batch": (
        training_args.get("batch"),
        EXPECTED_BATCH,
    ),
    "seed": (
        training_args.get("seed"),
        EXPECTED_SEED,
    ),
    "deterministic": (
        training_args.get("deterministic"),
        True,
    ),
    "pretrained": (
        training_args.get("pretrained"),
        True,
    ),
}


for argument_name, (
    observed_value,
    expected_value,
) in argument_checks.items():

    match = (
        observed_value
        == expected_value
    )

    print(
        f"{argument_name:<18}: "
        f"{observed_value!r}"
    )

    print(
        f"  Expected          : "
        f"{expected_value!r}"
    )

    print(
        f"  Status            : "
        f"{'PASSED' if match else 'FAILED'}"
    )

    if not match:
        raise RuntimeError(
            f"Training argument mismatch: "
            f"{argument_name}"
        )


print()
print("Saved argument audit: PASSED")


# -------------------------------------------------------------------------
# Inspect safety manifest
# -------------------------------------------------------------------------
print("\n" + "=" * 80)
print("SAFETY MANIFEST AUDIT")
print("=" * 80)

with zipfile.ZipFile(
    SAFETY_PACKAGE_PATH,
    mode="r",
) as zip_file:

    manifest_bytes = zip_file.read(
        resolved_members[
            "safety_manifest"
        ]
    )

manifest = json.loads(
    manifest_bytes.decode(
        "utf-8"
    )
)


manifest_checks = {
    "experiment": (
        manifest.get("experiment"),
        EXPECTED_EXPERIMENT,
    ),
    "training_completed": (
        manifest.get(
            "training_completed"
        ),
        True,
    ),
    "preserved_checkpoint": (
        manifest.get(
            "preserved_checkpoint"
        ),
        "best.pt",
    ),
    "last_pt_included": (
        manifest.get(
            "last_pt_included"
        ),
        False,
    ),
    "dataset_included": (
        manifest.get(
            "dataset_included"
        ),
        False,
    ),
    "best_model_sha256": (
        manifest.get(
            "best_model_sha256"
        ),
        source_best_sha256,
    ),
    "results_csv_sha256": (
        manifest.get(
            "results_csv_sha256"
        ),
        source_results_sha256,
    ),
}


for field_name, (
    observed_value,
    expected_value,
) in manifest_checks.items():

    match = (
        observed_value
        == expected_value
    )

    print(
        f"{field_name:<28}: "
        f"{'PASSED' if match else 'FAILED'}"
    )

    if not match:
        raise RuntimeError(
            f"Manifest mismatch: "
            f"{field_name}"
        )


# -------------------------------------------------------------------------
# Final recovery-readiness status
# -------------------------------------------------------------------------
zip_size_mb = (
    SAFETY_PACKAGE_PATH.stat().st_size
    / (1024 ** 2)
)

print("\n" + "=" * 80)
print("F01 SAFETY PACKAGE FINAL AUDIT")
print("=" * 80)

print(
    f"Experiment           : "
    f"{EXP_NAME}"
)

print(
    f"ZIP size             : "
    f"{zip_size_mb:.2f} MB"
)

print(
    f"ZIP file members     : "
    f"{len(zip_members)}"
)

print()

print(
    "best.pt             : VERIFIED"
)

print(
    "best.pt hash        : VERIFIED"
)

print(
    "results.csv         : VERIFIED"
)

print(
    "results.csv hash    : VERIFIED"
)

print(
    "args.yaml           : VERIFIED"
)

print(
    "training arguments  : VERIFIED"
)

print(
    "safety manifest     : VERIFIED"
)

print(
    "last.pt excluded    : VERIFIED"
)

print(
    "dataset excluded    : VERIFIED"
)

print()

print(
    f"Epochs completed     : "
    f"{epochs_completed}"
)

print(
    f"Best epoch           : "
    f"{best_epoch}"
)

print(
    f"Best Val Top-1       : "
    f"{best_val_top1 * 100:.4f}%"
)

print(
    f"Best Val Top-5       : "
    f"{best_val_top5 * 100:.4f}%"
)

print()

print(
    "RECOVERY READINESS   : PASSED"
)

print(
    "F01 TRAINING PACKAGE : LOCKED"
)

print("=" * 80)
print("F01 Step 2C completed successfully")
print("=" * 80)

# F01 Step 3 — Inspect and confirm the locked best validation checkpoint

Inspect the completed and safety-locked F01 training run.

This step:
- reads the verified Ultralytics training history
- confirms the best validation epoch
- summarizes early stopping
- releases stale training GPU objects
- reloads the locked `best.pt`
- confirms validation Top-1 and Top-5
- saves the clean F01 best-epoch summary

The official test split is not evaluated in this step.

In [ ]:
# F01 Step 3 — Inspect and confirm the locked best validation checkpoint

import gc
import json
from pathlib import Path

import pandas as pd
import torch
import yaml
from ultralytics import YOLO


# -------------------------------------------------------------------------
# Constants
# -------------------------------------------------------------------------
PROJECT_ROOT = Path(
    "/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026"
)

DATA_ROOT = (
    PROJECT_ROOT
    / "balanced_train"
    / "aug200_imagefolder"
)

EXP_NAME = "F01_YOLO26M_CLS_AUG200"

EXP_DIR = (
    PROJECT_ROOT
    / "experiments"
    / EXP_NAME
)

TABLE_DIR = EXP_DIR / "tables"

RUN_DIR = (
    EXP_DIR
    / "yolo_runs"
    / "train"
)

BEST_MODEL_PATH = (
    RUN_DIR
    / "weights"
    / "best.pt"
)

RESULTS_CSV_PATH = (
    RUN_DIR
    / "results.csv"
)

ARGS_YAML_PATH = (
    RUN_DIR
    / "args.yaml"
)

EXPECTED_BEST_SHA256 = (
    "aa489def1443a6cdab42a0a20a530b9e"
    "341d574dcaaf234bfe6c7983113e8e5a"
)

DEVICE = 0
WORKERS = 4

CSV_METRIC_TOLERANCE = 5e-5


# -------------------------------------------------------------------------
# Start
# -------------------------------------------------------------------------
print("=" * 80)
print("F01 Step 3 — Inspect and confirm locked best validation checkpoint")
print("=" * 80)


# -------------------------------------------------------------------------
# Verify locked training files
# -------------------------------------------------------------------------
required_files = [
    BEST_MODEL_PATH,
    RESULTS_CSV_PATH,
    ARGS_YAML_PATH,
]

for file_path in required_files:

    if not file_path.is_file():

        raise FileNotFoundError(
            "Missing locked F01 file:\n"
            f"{file_path}"
        )

if not torch.cuda.is_available():

    raise RuntimeError(
        "CUDA is not available."
    )

print("Locked training file verification: PASSED")


# -------------------------------------------------------------------------
# Verify locked checkpoint hash
# -------------------------------------------------------------------------
import hashlib


def calculate_sha256(file_path):

    sha256 = hashlib.sha256()

    with open(
        file_path,
        "rb",
    ) as file:

        while True:

            chunk = file.read(
                1024 * 1024
            )

            if not chunk:
                break

            sha256.update(
                chunk
            )

    return sha256.hexdigest()


observed_best_sha256 = calculate_sha256(
    BEST_MODEL_PATH
)

if (
    observed_best_sha256
    != EXPECTED_BEST_SHA256
):

    raise RuntimeError(
        "Locked best.pt SHA-256 mismatch.\n"
        f"Expected: {EXPECTED_BEST_SHA256}\n"
        f"Observed: {observed_best_sha256}"
    )

print("Locked best.pt SHA-256 verification: PASSED")


# -------------------------------------------------------------------------
# Read actual saved Ultralytics arguments
# -------------------------------------------------------------------------
with open(
    ARGS_YAML_PATH,
    "r",
    encoding="utf-8",
) as file:

    training_args = yaml.safe_load(
        file
    )


MAX_EPOCHS = int(
    training_args["epochs"]
)

PATIENCE = int(
    training_args["patience"]
)

IMGSZ = int(
    training_args["imgsz"]
)

BATCH_SIZE = int(
    training_args["batch"]
)

SEED = int(
    training_args["seed"]
)


# -------------------------------------------------------------------------
# Read completed training history
# -------------------------------------------------------------------------
results_df = pd.read_csv(
    RESULTS_CSV_PATH
)

results_df.columns = [
    column.strip()
    for column in results_df.columns
]


required_columns = [
    "epoch",
    "train/loss",
    "metrics/accuracy_top1",
    "metrics/accuracy_top5",
    "val/loss",
]

for column in required_columns:

    if column not in results_df.columns:

        raise KeyError(
            "Missing training-history column:\n"
            f"{column}"
        )


# -------------------------------------------------------------------------
# Verify epoch sequence
# -------------------------------------------------------------------------
epoch_values = (
    results_df["epoch"]
    .astype(int)
    .tolist()
)

expected_epoch_values = list(
    range(
        1,
        len(results_df) + 1,
    )
)

if (
    epoch_values
    != expected_epoch_values
):

    raise RuntimeError(
        "Unexpected results.csv epoch numbering."
    )


epochs_completed = int(
    results_df["epoch"].max()
)


print("\n" + "=" * 80)
print("TRAINING HISTORY VERIFICATION")
print("=" * 80)

print(
    f"Epoch sequence        : "
    f"{epoch_values[0]} -> {epoch_values[-1]}"
)

print(
    f"Epochs completed      : "
    f"{epochs_completed}"
)

print(
    f"Maximum epochs        : "
    f"{MAX_EPOCHS}"
)

print(
    f"Patience              : "
    f"{PATIENCE}"
)

print("Training history verification: PASSED")


# -------------------------------------------------------------------------
# Identify best validation epoch
# -------------------------------------------------------------------------
top1_column = (
    "metrics/accuracy_top1"
)

top5_column = (
    "metrics/accuracy_top5"
)

train_loss_column = (
    "train/loss"
)

val_loss_column = (
    "val/loss"
)


best_row_index = (
    results_df[
        top1_column
    ].idxmax()
)

best_row = results_df.loc[
    best_row_index
]


best_epoch = int(
    best_row["epoch"]
)

best_train_loss = float(
    best_row[
        train_loss_column
    ]
)

best_val_loss = float(
    best_row[
        val_loss_column
    ]
)

best_val_top1 = float(
    best_row[
        top1_column
    ]
)

best_val_top5 = float(
    best_row[
        top5_column
    ]
)


stopped_early = (
    epochs_completed
    < MAX_EPOCHS
)

epochs_since_best = (
    epochs_completed
    - best_epoch
)


if (
    stopped_early
    and epochs_since_best
    < PATIENCE
):

    raise RuntimeError(
        "Training history is inconsistent "
        "with configured early stopping."
    )


# -------------------------------------------------------------------------
# Clean training summary
# -------------------------------------------------------------------------
print("\n" + "=" * 80)
print("F01 TRAINING SUMMARY")
print("=" * 80)

print(
    f"Experiment          : "
    f"{EXP_NAME}"
)

print(
    "Model               : "
    "YOLO26m-cls"
)

print(
    "Training Strategy   : "
    "Aug-200 train-only balancing"
)

print()

print(
    f"Maximum Epochs      : "
    f"{MAX_EPOCHS}"
)

print(
    f"Epochs Completed    : "
    f"{epochs_completed}"
)

print(
    f"Early Stopping      : "
    f"{'YES' if stopped_early else 'NO'}"
)

print(
    f"Patience            : "
    f"{PATIENCE}"
)

print(
    f"Epochs Since Best   : "
    f"{epochs_since_best}"
)

print()

print(
    f"Best Epoch          : "
    f"{best_epoch}"
)

print(
    f"Train Loss @ Best   : "
    f"{best_train_loss:.6f}"
)

print(
    f"Val Loss @ Best     : "
    f"{best_val_loss:.6f}"
)

print(
    f"Best Val Top-1      : "
    f"{best_val_top1 * 100:.4f}%"
)

print(
    f"Best Val Top-5      : "
    f"{best_val_top5 * 100:.4f}%"
)

print()

print(
    "Best Checkpoint     : "
    "LOCKED best.pt"
)

print(
    f"Checkpoint SHA-256  : "
    f"{observed_best_sha256}"
)

print("=" * 80)


# -------------------------------------------------------------------------
# Build and save clean training history
# -------------------------------------------------------------------------
clean_history_df = results_df[
    [
        "epoch",
        train_loss_column,
        val_loss_column,
        top1_column,
        top5_column,
    ]
].copy()

clean_history_df.columns = [
    "epoch",
    "train_loss",
    "val_loss",
    "val_top1",
    "val_top5",
]

clean_history_df[
    "epoch"
] = (
    clean_history_df[
        "epoch"
    ].astype(int)
)

clean_history_df[
    "val_top1_pct"
] = (
    clean_history_df[
        "val_top1"
    ]
    * 100
)

clean_history_df[
    "val_top5_pct"
] = (
    clean_history_df[
        "val_top5"
    ]
    * 100
)

clean_history_df[
    "status"
] = ""

clean_history_df.loc[
    clean_history_df[
        "epoch"
    ] == best_epoch,
    "status",
] = "BEST"


history_output_path = (
    TABLE_DIR
    / "f01_clean_training_history.csv"
)

clean_history_df.to_csv(
    history_output_path,
    index=False,
)


# -------------------------------------------------------------------------
# Show top validation epochs
# -------------------------------------------------------------------------
print("\n" + "=" * 80)
print("TOP VALIDATION EPOCHS")
print("=" * 80)

top_epochs_df = (
    clean_history_df
    .sort_values(
        by=[
            "val_top1",
            "val_top5",
        ],
        ascending=False,
    )
    .head(10)
)


print(
    top_epochs_df[
        [
            "epoch",
            "train_loss",
            "val_loss",
            "val_top1_pct",
            "val_top5_pct",
            "status",
        ]
    ].to_string(
        index=False,
        formatters={
            "train_loss": (
                lambda value:
                f"{value:.6f}"
            ),
            "val_loss": (
                lambda value:
                f"{value:.6f}"
            ),
            "val_top1_pct": (
                lambda value:
                f"{value:.2f}%"
            ),
            "val_top5_pct": (
                lambda value:
                f"{value:.2f}%"
            ),
        },
    )
)


# -------------------------------------------------------------------------
# Release stale training GPU objects
# -------------------------------------------------------------------------
print("\n" + "=" * 80)
print("GPU MEMORY CLEANUP BEFORE CHECKPOINT CONFIRMATION")
print("=" * 80)

stale_variable_names = [
    "model",
    "train_results",
    "best_model",
    "validation_results",
    "native_model",
    "native_test_results",
    "prediction_model",
    "prediction_stream",
    "result",
]

removed_variables = []

for variable_name in stale_variable_names:

    if variable_name in globals():

        del globals()[
            variable_name
        ]

        removed_variables.append(
            variable_name
        )


gc.collect()

torch.cuda.empty_cache()


allocated_gb = (
    torch.cuda.memory_allocated(
        DEVICE
    )
    / (1024 ** 3)
)

reserved_gb = (
    torch.cuda.memory_reserved(
        DEVICE
    )
    / (1024 ** 3)
)


print(
    "Removed stale variables:",
    removed_variables
)

print(
    f"CUDA allocated       : "
    f"{allocated_gb:.3f} GB"
)

print(
    f"CUDA reserved        : "
    f"{reserved_gb:.3f} GB"
)

print("GPU memory cleanup: COMPLETED")


# -------------------------------------------------------------------------
# Reload locked best.pt and confirm validation metrics
# -------------------------------------------------------------------------
print("\n" + "=" * 80)
print("CONFIRMING LOCKED BEST CHECKPOINT ON VALIDATION SPLIT")
print("=" * 80)

best_model = YOLO(
    str(
        BEST_MODEL_PATH
    )
)


if (
    best_model.task
    != "classify"
):

    raise RuntimeError(
        "Locked checkpoint is not "
        "a classification model."
    )


validation_results = best_model.val(
    data=str(
        DATA_ROOT
    ),
    split="val",
    imgsz=IMGSZ,
    batch=BATCH_SIZE,
    device=DEVICE,
    workers=WORKERS,
    project=str(
        EXP_DIR
        / "yolo_runs"
    ),
    name="best_val_check",
    exist_ok=True,
    plots=False,
    verbose=False,
)


validation_metrics = (
    validation_results.results_dict
)


confirmed_val_top1 = float(
    validation_metrics[
        "metrics/accuracy_top1"
    ]
)

confirmed_val_top5 = float(
    validation_metrics[
        "metrics/accuracy_top5"
    ]
)


# -------------------------------------------------------------------------
# Compare fresh validation against saved training CSV
# -------------------------------------------------------------------------
top1_difference = abs(
    confirmed_val_top1
    - best_val_top1
)

top5_difference = abs(
    confirmed_val_top5
    - best_val_top5
)


if (
    top1_difference
    > CSV_METRIC_TOLERANCE
):

    raise RuntimeError(
        "Fresh validation Top-1 differs "
        "beyond CSV precision tolerance.\n"
        f"CSV   : {best_val_top1:.10f}\n"
        f"Fresh : {confirmed_val_top1:.10f}\n"
        f"Diff  : {top1_difference:.10f}"
    )


if (
    top5_difference
    > CSV_METRIC_TOLERANCE
):

    raise RuntimeError(
        "Fresh validation Top-5 differs "
        "beyond CSV precision tolerance.\n"
        f"CSV   : {best_val_top5:.10f}\n"
        f"Fresh : {confirmed_val_top5:.10f}\n"
        f"Diff  : {top5_difference:.10f}"
    )


# -------------------------------------------------------------------------
# Save official F01 best-epoch summary
# -------------------------------------------------------------------------
best_epoch_summary = {
    "experiment": EXP_NAME,
    "model": "YOLO26m-cls",
    "training_strategy": (
        "Aug-200 train-only balancing"
    ),
    "seed": SEED,
    "maximum_epochs": MAX_EPOCHS,
    "epochs_completed": epochs_completed,
    "early_stopping": stopped_early,
    "patience": PATIENCE,
    "epochs_since_best": epochs_since_best,
    "best_epoch": best_epoch,
    "best_train_loss": best_train_loss,
    "best_val_loss": best_val_loss,
    "best_val_top1": best_val_top1,
    "best_val_top1_percent": (
        best_val_top1 * 100
    ),
    "best_val_top5": best_val_top5,
    "best_val_top5_percent": (
        best_val_top5 * 100
    ),
    "confirmed_val_top1": (
        confirmed_val_top1
    ),
    "confirmed_val_top1_percent": (
        confirmed_val_top1 * 100
    ),
    "confirmed_val_top5": (
        confirmed_val_top5
    ),
    "confirmed_val_top5_percent": (
        confirmed_val_top5 * 100
    ),
    "top1_validation_difference": (
        top1_difference
    ),
    "top5_validation_difference": (
        top5_difference
    ),
    "validation_match": True,
    "best_checkpoint": str(
        BEST_MODEL_PATH
    ),
    "best_checkpoint_sha256": (
        observed_best_sha256
    ),
}


summary_json_path = (
    TABLE_DIR
    / "f01_best_epoch_summary.json"
)

summary_csv_path = (
    TABLE_DIR
    / "f01_best_epoch_summary.csv"
)


with open(
    summary_json_path,
    "w",
    encoding="utf-8",
) as file:

    json.dump(
        best_epoch_summary,
        file,
        indent=2,
    )


pd.DataFrame(
    [
        best_epoch_summary
    ]
).to_csv(
    summary_csv_path,
    index=False,
)


# -------------------------------------------------------------------------
# Final clean checkpoint confirmation
# -------------------------------------------------------------------------
print("\n" + "=" * 80)
print("F01 LOCKED BEST CHECKPOINT CONFIRMATION")
print("=" * 80)

print(
    f"Best Epoch          : "
    f"{best_epoch}"
)

print(
    f"CSV Val Top-1       : "
    f"{best_val_top1 * 100:.4f}%"
)

print(
    f"Fresh Val Top-1     : "
    f"{confirmed_val_top1 * 100:.4f}%"
)

print(
    f"Top-1 Difference    : "
    f"{top1_difference:.10f}"
)

print()

print(
    f"CSV Val Top-5       : "
    f"{best_val_top5 * 100:.4f}%"
)

print(
    f"Fresh Val Top-5     : "
    f"{confirmed_val_top5 * 100:.4f}%"
)

print(
    f"Top-5 Difference    : "
    f"{top5_difference:.10f}"
)

print()

print(
    "Checkpoint Status   : LOCKED"
)

print(
    "Checkpoint Hash     : VERIFIED"
)

print(
    "Validation Match    : PASSED"
)

print(
    "Official Test       : NOT EVALUATED"
)

print()

print("Saved:")
print(history_output_path)
print(summary_json_path)
print(summary_csv_path)

print("=" * 80)
print("F01 Step 3 completed successfully")
print("=" * 80)

# F01 Step 4 — Memory-safe official test evaluation and full paper metrics

Evaluate the locked F01 `best.pt` checkpoint on the unchanged official AQUA20 test split.

This step:
- verifies the locked checkpoint SHA-256
- evaluates the official 1,612-image test split
- records native YOLO Top-1 and Top-5 accuracy
- performs prediction extraction in small fixed batches
- calculates macro precision, macro recall, macro F1, and weighted F1
- saves the full per-class classification report
- saves image-level Top-1 and Top-5 predictions
- creates raw and normalized confusion matrices
- creates the F01 paper-comparison summary

The locked checkpoint is not changed.

No retraining, model selection, or test-based tuning is performed.

In [ ]:
# F01 Step 4 — Official test evaluation and paper metrics

import gc
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch

from sklearn.metrics import (
    ConfusionMatrixDisplay,
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
)

from torchvision.datasets import ImageFolder
from ultralytics import YOLO


# -------------------------------------------------------------------------
# Constants
# -------------------------------------------------------------------------
SEED = 42

PROJECT_ROOT = Path(
    "/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026"
)

DATA_ROOT = (
    PROJECT_ROOT
    / "balanced_train"
    / "aug200_imagefolder"
)

TEST_DIR = DATA_ROOT / "test"

EXP_NAME = "F01_YOLO26M_CLS_AUG200"

EXP_DIR = (
    PROJECT_ROOT
    / "experiments"
    / EXP_NAME
)

TABLE_DIR = EXP_DIR / "tables"
FIG_DIR = EXP_DIR / "figures"

RUN_DIR = EXP_DIR / "yolo_runs" / "train"

BEST_MODEL_PATH = (
    RUN_DIR
    / "weights"
    / "best.pt"
)

BEST_SUMMARY_PATH = (
    TABLE_DIR
    / "f01_best_epoch_summary.json"
)

IMGSZ = 224
BATCH_SIZE = 16
DEVICE = 0

EXPECTED_TEST_IMAGES = 1612
EXPECTED_NUM_CLASSES = 20

BASE_PAPER_TOP1 = 92.68


# -------------------------------------------------------------------------
# Cleanup and verify inputs
# -------------------------------------------------------------------------
print("=" * 80)
print("F01 Step 4 — Official test evaluation and paper metrics")
print("=" * 80)

gc.collect()
torch.cuda.empty_cache()

for path in [
    TEST_DIR,
    BEST_MODEL_PATH,
    BEST_SUMMARY_PATH,
]:
    if not path.exists():
        raise FileNotFoundError(path)

TABLE_DIR.mkdir(parents=True, exist_ok=True)
FIG_DIR.mkdir(parents=True, exist_ok=True)

with open(
    BEST_SUMMARY_PATH,
    "r",
    encoding="utf-8",
) as file:
    best_summary = json.load(file)

BEST_EPOCH = int(best_summary["best_epoch"])
VAL_TOP1 = float(best_summary["confirmed_val_top1_percent"])
VAL_TOP5 = float(best_summary["confirmed_val_top5_percent"])


# -------------------------------------------------------------------------
# Load official test split
# -------------------------------------------------------------------------
test_dataset = ImageFolder(TEST_DIR)

folder_class_names = test_dataset.classes

class_names = [
    name.split("_", 1)[1]
    if "_" in name
    else name
    for name in folder_class_names
]

if len(test_dataset) != EXPECTED_TEST_IMAGES:
    raise RuntimeError("Official test image count mismatch.")

if len(class_names) != EXPECTED_NUM_CLASSES:
    raise RuntimeError("Official class count mismatch.")

test_paths = [
    str(Path(path).resolve())
    for path, _ in test_dataset.samples
]

path_to_label = {
    str(Path(path).resolve()): int(label)
    for path, label in test_dataset.samples
}

print("Test images          :", len(test_dataset))
print("Classes              :", len(class_names))
print("Official test split  : VERIFIED")


# -------------------------------------------------------------------------
# Native YOLO test metrics
# -------------------------------------------------------------------------
print("\n" + "=" * 80)
print("NATIVE YOLO TEST EVALUATION")
print("=" * 80)

native_model = YOLO(str(BEST_MODEL_PATH))

native_results = native_model.val(
    data=str(DATA_ROOT),
    split="test",
    imgsz=IMGSZ,
    batch=64,
    device=DEVICE,
    workers=4,
    plots=False,
    verbose=False,
)

native_top1 = float(
    native_results.results_dict[
        "metrics/accuracy_top1"
    ]
)

native_top5 = float(
    native_results.results_dict[
        "metrics/accuracy_top5"
    ]
)

print(f"Native Test Top-1   : {native_top1 * 100:.4f}%")
print(f"Native Test Top-5   : {native_top5 * 100:.4f}%")

del native_results
del native_model

gc.collect()
torch.cuda.empty_cache()


# -------------------------------------------------------------------------
# Chunked prediction extraction
# -------------------------------------------------------------------------
print("\n" + "=" * 80)
print("CHUNKED TEST PREDICTION")
print("=" * 80)

model = YOLO(str(BEST_MODEL_PATH))

prediction_rows = []

y_true = []
y_pred = []
top5_hits = []

processed = 0


for start in range(
    0,
    len(test_paths),
    BATCH_SIZE,
):

    batch_paths = test_paths[
        start:
        start + BATCH_SIZE
    ]

    batch_results = model.predict(
        source=batch_paths,
        imgsz=IMGSZ,
        device=DEVICE,
        verbose=False,
    )

    if len(batch_results) != len(batch_paths):
        raise RuntimeError(
            "Prediction batch size mismatch."
        )

    for source_path, result in zip(
        batch_paths,
        batch_results,
    ):

        true_id = path_to_label[source_path]

        probabilities = (
            result.probs.data
            .detach()
            .cpu()
            .numpy()
        )

        pred_id = int(result.probs.top1)

        top5_ids = [
            int(class_id)
            for class_id in result.probs.top5
        ]

        correct = pred_id == true_id
        top5_correct = true_id in top5_ids

        prediction_rows.append(
            {
                "image_path": str(
                    Path(source_path).relative_to(
                        TEST_DIR.resolve()
                    )
                ),
                "true_class_id": true_id,
                "true_class": class_names[true_id],
                "predicted_class_id": pred_id,
                "predicted_class": class_names[pred_id],
                "correct": correct,
                "top1_confidence": float(
                    probabilities[pred_id]
                ),
                "top5_correct": top5_correct,
                "top5_class_ids": json.dumps(
                    top5_ids
                ),
                "top5_class_names": json.dumps(
                    [
                        class_names[class_id]
                        for class_id in top5_ids
                    ]
                ),
                "top5_scores": json.dumps(
                    [
                        float(probabilities[class_id])
                        for class_id in top5_ids
                    ]
                ),
            }
        )

        y_true.append(true_id)
        y_pred.append(pred_id)
        top5_hits.append(int(top5_correct))

        processed += 1

    del batch_results

    if (
        processed % 400 == 0
        or processed == EXPECTED_TEST_IMAGES
    ):
        print(
            f"Processed {processed}/{EXPECTED_TEST_IMAGES}"
        )


if processed != EXPECTED_TEST_IMAGES:
    raise RuntimeError(
        f"Expected {EXPECTED_TEST_IMAGES} predictions, "
        f"found {processed}."
    )

del model

gc.collect()
torch.cuda.empty_cache()


# -------------------------------------------------------------------------
# Calculate test metrics
# -------------------------------------------------------------------------
y_true = np.asarray(y_true)
y_pred = np.asarray(y_pred)

test_top1 = float(
    accuracy_score(y_true, y_pred)
)

test_top5 = float(
    np.mean(top5_hits)
)

macro_precision = float(
    precision_score(
        y_true,
        y_pred,
        average="macro",
        zero_division=0,
    )
)

macro_recall = float(
    recall_score(
        y_true,
        y_pred,
        average="macro",
        zero_division=0,
    )
)

macro_f1 = float(
    f1_score(
        y_true,
        y_pred,
        average="macro",
        zero_division=0,
    )
)

weighted_f1 = float(
    f1_score(
        y_true,
        y_pred,
        average="weighted",
        zero_division=0,
    )
)


if abs(test_top1 - native_top1) > 5e-5:
    raise RuntimeError(
        "Manual Top-1 does not match native YOLO Top-1."
    )

if abs(test_top5 - native_top5) > 5e-5:
    raise RuntimeError(
        "Manual Top-5 does not match native YOLO Top-5."
    )


# -------------------------------------------------------------------------
# Save predictions
# -------------------------------------------------------------------------
prediction_df = pd.DataFrame(prediction_rows)

prediction_path = (
    TABLE_DIR
    / "f01_test_predictions.csv"
)

prediction_df.to_csv(
    prediction_path,
    index=False,
)


# -------------------------------------------------------------------------
# Save classification report
# -------------------------------------------------------------------------
report = classification_report(
    y_true,
    y_pred,
    labels=list(range(EXPECTED_NUM_CLASSES)),
    target_names=class_names,
    output_dict=True,
    zero_division=0,
)

class_rows = []

for class_id, class_name in enumerate(class_names):

    metrics = report[class_name]

    class_rows.append(
        {
            "class_id": class_id,
            "class_name": class_name,
            "precision": metrics["precision"],
            "recall": metrics["recall"],
            "f1_score": metrics["f1-score"],
            "support": int(metrics["support"]),
        }
    )

class_report_df = pd.DataFrame(class_rows)

class_report_path = (
    TABLE_DIR
    / "f01_classification_report.csv"
)

class_report_df.to_csv(
    class_report_path,
    index=False,
)


# -------------------------------------------------------------------------
# Save confusion matrices
# -------------------------------------------------------------------------
cm = confusion_matrix(
    y_true,
    y_pred,
)

cm_normalized = confusion_matrix(
    y_true,
    y_pred,
    normalize="true",
)

cm_path = (
    TABLE_DIR
    / "f01_confusion_matrix.csv"
)

cm_normalized_path = (
    TABLE_DIR
    / "f01_confusion_matrix_normalized.csv"
)

pd.DataFrame(
    cm,
    index=class_names,
    columns=class_names,
).to_csv(cm_path)

pd.DataFrame(
    cm_normalized,
    index=class_names,
    columns=class_names,
).to_csv(cm_normalized_path)


for matrix, title, output_path in [
    (
        cm,
        "F01 Test Confusion Matrix",
        FIG_DIR / "f01_confusion_matrix.png",
    ),
    (
        cm_normalized,
        "F01 Normalized Test Confusion Matrix",
        FIG_DIR
        / "f01_confusion_matrix_normalized.png",
    ),
]:

    ConfusionMatrixDisplay(
        confusion_matrix=matrix,
        display_labels=class_names,
    ).plot(
        include_values=False,
        xticks_rotation=90,
    )

    plt.gcf().set_size_inches(16, 14)
    plt.title(title)
    plt.tight_layout()

    plt.savefig(
        output_path,
        dpi=300,
        bbox_inches="tight",
    )

    plt.close()


# -------------------------------------------------------------------------
# Save final summaries
# -------------------------------------------------------------------------
difference_vs_base = (
    test_top1 * 100
    - BASE_PAPER_TOP1
)

summary = {
    "experiment": EXP_NAME,
    "model": "YOLO26m-cls",
    "training_strategy": (
        "Aug-200 train-only balancing"
    ),
    "best_epoch": BEST_EPOCH,
    "val_top1_pct": VAL_TOP1,
    "val_top5_pct": VAL_TOP5,
    "test_top1_pct": test_top1 * 100,
    "test_top5_pct": test_top5 * 100,
    "macro_precision_pct": macro_precision * 100,
    "macro_recall_pct": macro_recall * 100,
    "macro_f1_pct": macro_f1 * 100,
    "weighted_f1_pct": weighted_f1 * 100,
    "test_support": len(y_true),
    "base_paper_top1_pct": BASE_PAPER_TOP1,
    "difference_vs_base_pp": difference_vs_base,
    "beats_base_paper": difference_vs_base > 0,
}

summary_json_path = (
    TABLE_DIR
    / "f01_test_metrics_summary.json"
)

summary_csv_path = (
    TABLE_DIR
    / "f01_test_metrics_summary.csv"
)

comparison_path = (
    TABLE_DIR
    / "f01_comparison_ready_summary.csv"
)

with open(
    summary_json_path,
    "w",
    encoding="utf-8",
) as file:
    json.dump(summary, file, indent=2)

pd.DataFrame([summary]).to_csv(
    summary_csv_path,
    index=False,
)

pd.DataFrame([summary]).to_csv(
    comparison_path,
    index=False,
)


# -------------------------------------------------------------------------
# Final result
# -------------------------------------------------------------------------
print("\n" + "=" * 80)
print("F01 OFFICIAL TEST RESULT")
print("=" * 80)

print(f"Best Epoch          : {BEST_EPOCH}")
print(f"Validation Top-1    : {VAL_TOP1:.2f}%")
print(f"Validation Top-5    : {VAL_TOP5:.2f}%")
print()
print(f"Test Top-1          : {test_top1 * 100:.2f}%")
print(f"Test Top-5          : {test_top5 * 100:.2f}%")
print(f"Macro Precision     : {macro_precision * 100:.2f}%")
print(f"Macro Recall        : {macro_recall * 100:.2f}%")
print(f"Macro F1            : {macro_f1 * 100:.2f}%")
print(f"Weighted F1         : {weighted_f1 * 100:.2f}%")
print(f"Test Support        : {len(y_true)}")
print()
print(f"Base-paper Top-1    : {BASE_PAPER_TOP1:.2f}%")
print(
    f"Difference          : "
    f"{difference_vs_base:+.2f} percentage points"
)
print(
    f"Beat base Top-1     : "
    f"{'YES' if difference_vs_base > 0 else 'NO'}"
)
print()
print("Native/manual match : PASSED")

print("\n" + "=" * 80)
print("F01 PER-CLASS TEST REPORT")
print("=" * 80)

print(
    class_report_df.to_string(
        index=False,
        formatters={
            "precision": lambda x: f"{x * 100:.2f}%",
            "recall": lambda x: f"{x * 100:.2f}%",
            "f1_score": lambda x: f"{x * 100:.2f}%",
        },
    )
)

print("\nSaved:")
print(prediction_path)
print(class_report_path)
print(cm_path)
print(cm_normalized_path)
print(summary_json_path)
print(summary_csv_path)
print(comparison_path)

print("\nF01 Step 4 completed successfully.")

In [ ]:
# F01 Step 5 — Create final official F01 package

import json
import zipfile
from pathlib import Path


# -------------------------------------------------------------------------
# Paths
# -------------------------------------------------------------------------
PROJECT_ROOT = Path(
    "/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026"
)

EXP_DIR = (
    PROJECT_ROOT
    / "experiments"
    / "F01_YOLO26M_CLS_AUG200"
)

RUN_DIR = EXP_DIR / "yolo_runs" / "train"
TABLE_DIR = EXP_DIR / "tables"
FIG_DIR = EXP_DIR / "figures"

PACKAGE_NAME = "aqua20_f01_yolo26m_cls_aug200_outputs"

PACKAGE_PATH = (
    Path("/kaggle/working")
    / f"{PACKAGE_NAME}.zip"
)


# -------------------------------------------------------------------------
# Final F01 summary
# -------------------------------------------------------------------------
with open(
    TABLE_DIR / "f01_test_metrics_summary.json",
    "r",
    encoding="utf-8",
) as file:
    metrics = json.load(file)

readme_text = f"""
AQUA20 F01 — YOLO26m-cls + Aug-200
===================================

Experiment:
F01_YOLO26M_CLS_AUG200

Strategy:
Aug-200 train-only balancing

Model:
YOLO26m-cls

Best Epoch:
{metrics['best_epoch']}

Test Top-1:
{metrics['test_top1_pct']:.4f}%

Test Top-5:
{metrics['test_top5_pct']:.4f}%

Macro Precision:
{metrics['macro_precision_pct']:.4f}%

Macro Recall:
{metrics['macro_recall_pct']:.4f}%

Macro F1:
{metrics['macro_f1_pct']:.4f}%

Weighted F1:
{metrics['weighted_f1_pct']:.4f}%

Test Support:
{metrics['test_support']}

Base-paper Top-1:
{metrics['base_paper_top1_pct']:.2f}%

Difference:
{metrics['difference_vs_base_pp']:+.4f} percentage points

Dataset included:
NO

last.pt included:
NO

Official checkpoint:
weights/best.pt
""".strip()


# -------------------------------------------------------------------------
# Files to package
# -------------------------------------------------------------------------
files_to_package = {
    RUN_DIR / "weights" / "best.pt":
        "weights/best.pt",

    RUN_DIR / "results.csv":
        "training_run/results.csv",

    RUN_DIR / "results.png":
        "training_run/results.png",

    RUN_DIR / "args.yaml":
        "training_run/args.yaml",
}


for file_path in sorted(TABLE_DIR.glob("*")):
    if file_path.is_file():
        files_to_package[file_path] = (
            f"tables/{file_path.name}"
        )


for file_path in sorted(FIG_DIR.glob("*.png")):
    if file_path.is_file():
        files_to_package[file_path] = (
            f"figures/{file_path.name}"
        )


# -------------------------------------------------------------------------
# Create final ZIP
# -------------------------------------------------------------------------
if PACKAGE_PATH.exists():
    PACKAGE_PATH.unlink()


with zipfile.ZipFile(
    PACKAGE_PATH,
    "w",
    zipfile.ZIP_DEFLATED,
) as zip_file:

    zip_file.writestr(
        f"{PACKAGE_NAME}/README_F01.txt",
        readme_text,
    )

    for source_path, archive_path in files_to_package.items():

        if not source_path.is_file():
            raise FileNotFoundError(
                source_path
            )

        zip_file.write(
            source_path,
            arcname=(
                f"{PACKAGE_NAME}/"
                f"{archive_path}"
            ),
        )


# -------------------------------------------------------------------------
# Verify package
# -------------------------------------------------------------------------
with zipfile.ZipFile(
    PACKAGE_PATH,
    "r",
) as zip_file:

    corrupt_file = zip_file.testzip()

    members = zip_file.namelist()


if corrupt_file is not None:
    raise RuntimeError(
        f"ZIP integrity failed: {corrupt_file}"
    )


print("=" * 80)
print("F01 FINAL OFFICIAL PACKAGE")
print("=" * 80)

print("Package:")
print(PACKAGE_PATH)

print()
print("ZIP members       :", len(members))
print(
    "ZIP size          :",
    f"{PACKAGE_PATH.stat().st_size / (1024 ** 2):.2f} MB",
)
print("ZIP integrity     : PASSED")
print("best.pt included  : YES")
print("Dataset included  : NO")
print("last.pt included  : NO")

print()
print("Official package name:")
print(PACKAGE_PATH.name)

print("=" * 80)
print("F01 Step 5 completed successfully")
print("=" * 80)

# F01 Recovery — Restore official F01 package

Restore the completed F01 output package from Kaggle Input into the official experiment structure.

The dataset is not restored by this package

In [ ]:
# F01 Recovery — Restore official F01 package

import shutil
import zipfile
from pathlib import Path


# -------------------------------------------------------------------------
# Paths
# -------------------------------------------------------------------------
PACKAGE_NAME = "aqua20_f01_yolo26m_cls_aug200_outputs.zip"

PROJECT_ROOT = Path(
    "/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026"
)

EXP_DIR = (
    PROJECT_ROOT
    / "experiments"
    / "F01_YOLO26M_CLS_AUG200"
)

RUN_DIR = EXP_DIR / "yolo_runs" / "train"
TABLE_DIR = EXP_DIR / "tables"
FIG_DIR = EXP_DIR / "figures"

package_matches = list(
    Path("/kaggle/input").rglob(PACKAGE_NAME)
)

if len(package_matches) != 1:
    raise RuntimeError(
        f"Expected one {PACKAGE_NAME}, "
        f"found {len(package_matches)}"
    )

PACKAGE_PATH = package_matches[0]

EXTRACT_DIR = Path(
    "/kaggle/working/F01_PACKAGE_EXTRACTED"
)


# -------------------------------------------------------------------------
# Extract package
# -------------------------------------------------------------------------
if EXTRACT_DIR.exists():
    shutil.rmtree(EXTRACT_DIR)

with zipfile.ZipFile(
    PACKAGE_PATH,
    "r",
) as zip_file:
    zip_file.extractall(EXTRACT_DIR)


PACKAGE_ROOT = (
    EXTRACT_DIR
    / "aqua20_f01_yolo26m_cls_aug200_outputs"
)


# -------------------------------------------------------------------------
# Restore official F01 structure
# -------------------------------------------------------------------------
RUN_DIR.mkdir(parents=True, exist_ok=True)
(RUN_DIR / "weights").mkdir(parents=True, exist_ok=True)
TABLE_DIR.mkdir(parents=True, exist_ok=True)
FIG_DIR.mkdir(parents=True, exist_ok=True)

shutil.copy2(
    PACKAGE_ROOT / "weights" / "best.pt",
    RUN_DIR / "weights" / "best.pt",
)

for file_name in [
    "results.csv",
    "results.png",
    "args.yaml",
]:
    source = PACKAGE_ROOT / "training_run" / file_name

    if source.is_file():
        shutil.copy2(
            source,
            RUN_DIR / file_name,
        )

for source in (PACKAGE_ROOT / "tables").glob("*"):
    if source.is_file():
        shutil.copy2(
            source,
            TABLE_DIR / source.name,
        )

for source in (PACKAGE_ROOT / "figures").glob("*"):
    if source.is_file():
        shutil.copy2(
            source,
            FIG_DIR / source.name,
        )


# -------------------------------------------------------------------------
# Final check
# -------------------------------------------------------------------------
required_files = [
    RUN_DIR / "weights" / "best.pt",
    RUN_DIR / "results.csv",
    RUN_DIR / "args.yaml",
    TABLE_DIR / "f01_test_metrics_summary.csv",
    TABLE_DIR / "f01_comparison_ready_summary.csv",
]

for file_path in required_files:
    if not file_path.is_file():
        raise FileNotFoundError(file_path)


print("=" * 80)
print("F01 OFFICIAL PACKAGE RESTORED")
print("=" * 80)

print("Package:")
print(PACKAGE_PATH)

print()
print("Experiment directory:")
print(EXP_DIR)

print()
print("best.pt             : RESTORED")
print("results.csv         : RESTORED")
print("args.yaml           : RESTORED")
print("F01 tables          : RESTORED")
print("F01 figures         : RESTORED")

print()
print("Dataset             : NOT INCLUDED")

print("=" * 80)
print("F01 recovery completed successfully")
print("=" * 80)

## F02 Step 1 — Environment and Aug-200 path verification

Verify the active Kaggle environment, locked F00 Aug-200 dataset structure, split counts, class consistency, and official `yolo26s-cls.pt` model availability.

No training is performed in this step.

In [ ]:
# F02 Step 1 — Environment and Aug-200 path verification

import sys
from pathlib import Path

import torch
import ultralytics
from ultralytics import YOLO

SEED = 42

PROJECT_ROOT = Path(
    "/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026"
)

DATA_ROOT = (
    PROJECT_ROOT
    / "balanced_train"
    / "aug200_imagefolder"
)

EXP_NAME = "F02_YOLO26S_CLS_AUG200"
EXP_DIR = PROJECT_ROOT / "experiments" / EXP_NAME
TABLE_DIR = EXP_DIR / "tables"
FIG_DIR = EXP_DIR / "figures"
WEIGHTS_DIR = EXP_DIR / "weights"

EXPECTED_COUNTS = {
    "train": 7284,
    "val": 1312,
    "test": 1612,
}

MODEL_NAME = "yolo26s-cls.pt"

print("=" * 80)
print("F02 Step 1 — Environment and Aug-200 path verification")
print("=" * 80)

print(f"\nGPU         : {torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'NOT AVAILABLE'}")
print(f"Python      : {sys.version.split()[0]}")
print(f"Torch       : {torch.__version__}")
print(f"Ultralytics : {ultralytics.__version__}")
print(f"DATA_ROOT   : {DATA_ROOT}")

if not torch.cuda.is_available():
    raise RuntimeError("CUDA GPU is not available.")

if not DATA_ROOT.exists():
    raise FileNotFoundError(f"Aug-200 DATA_ROOT not found: {DATA_ROOT}")

split_classes = {}
split_counts = {}

for split in ["train", "val", "test"]:
    split_dir = DATA_ROOT / split

    if not split_dir.exists():
        raise FileNotFoundError(f"Missing split: {split_dir}")

    classes = sorted(
        p.name for p in split_dir.iterdir()
        if p.is_dir()
    )

    image_count = sum(
        1
        for p in split_dir.rglob("*")
        if p.is_file()
        and p.suffix.lower() in {".jpg", ".jpeg", ".png", ".bmp", ".webp"}
    )

    split_classes[split] = classes
    split_counts[split] = image_count

    print(f"\n{split.upper()}")
    print(f"Images  : {image_count}")
    print(f"Classes : {len(classes)}")

    if image_count != EXPECTED_COUNTS[split]:
        raise RuntimeError(
            f"{split} count mismatch: "
            f"expected {EXPECTED_COUNTS[split]}, found {image_count}"
        )

    if len(classes) != 20:
        raise RuntimeError(
            f"{split} class count mismatch: expected 20, found {len(classes)}"
        )

if not (
    split_classes["train"]
    == split_classes["val"]
    == split_classes["test"]
):
    raise RuntimeError("Class order mismatch across train/val/test.")

print("\nClass order:")
for index, class_name in enumerate(split_classes["train"]):
    print(f"{index:02d} : {class_name}")

print("\nLoading official F02 starting model...")
model = YOLO(MODEL_NAME)

print(f"Model loaded : {MODEL_NAME}")

print("\n" + "=" * 80)
print("F02 STEP 1 PASSED")
print("=" * 80)
print(f"train              : {split_counts['train']}")
print(f"val                : {split_counts['val']}")
print(f"test               : {split_counts['test']}")
print("classes            : 20")
print("class order stable : YES")
print(f"model              : {MODEL_NAME}")
print("training started   : NO")

## F02 Step 2 — Train YOLO26s-cls on Aug-200

Train the official `yolo26s-cls.pt` model using the locked F00 Aug-200 train-only balanced dataset.

The F01 training protocol is retained for controlled architecture-size comparison.

After training finishes, the next mandatory action is immediate `best.pt` preservation in the F02 safety package.

In [ ]:
# F02 Step 2 — Train YOLO26s-cls on Aug-200

import os
import random
from pathlib import Path

import numpy as np
import torch
from ultralytics import YOLO

SEED = 42

PROJECT_ROOT = Path(
    "/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026"
)

DATA_ROOT = (
    PROJECT_ROOT
    / "balanced_train"
    / "aug200_imagefolder"
)

EXP_NAME = "F02_YOLO26S_CLS_AUG200"
EXP_DIR = PROJECT_ROOT / "experiments" / EXP_NAME

MODEL_NAME = "yolo26s-cls.pt"

# Reproducibility
os.environ["PYTHONHASHSEED"] = str(SEED)

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

print("=" * 80)
print("F02 Step 2 — Train YOLO26s-cls on Aug-200")
print("=" * 80)

print(f"Model       : {MODEL_NAME}")
print(f"Data        : {DATA_ROOT}")
print(f"Experiment  : {EXP_NAME}")
print("Image size  : 224")
print("Batch size  : 64")
print("Max epochs  : 200")
print("Patience    : 30")
print(f"Seed        : {SEED}")
print("Device      : 0")

model = YOLO(MODEL_NAME)

results = model.train(
    data=str(DATA_ROOT),
    imgsz=224,
    batch=64,
    epochs=200,
    patience=30,
    seed=SEED,
    deterministic=True,
    pretrained=True,
    optimizer="auto",
    amp=True,
    device=0,
    project=str(EXP_DIR),
    name="train",
    exist_ok=True,
)

print("\n" + "=" * 80)
print("F02 STEP 2 TRAINING FINISHED")
print("=" * 80)
print(f"Training run : {EXP_DIR / 'train'}")
print(f"Best weights : {EXP_DIR / 'train' / 'weights' / 'best.pt'}")
print("\nNEXT MANDATORY STEP: F02 Step 2B — Immediate best.pt preservation")

## F02 Step 2B — Immediate best.pt preservation

Preserve the locked F02 `best.pt` checkpoint immediately after training and create the post-training safety package.

No training analysis or test evaluation is performed in this step.

In [ ]:
# F02 Step 2B — Immediate best.pt preservation

import hashlib
import shutil
from pathlib import Path

PROJECT_ROOT = Path(
    "/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026"
)

EXP_NAME = "F02_YOLO26S_CLS_AUG200"
EXP_DIR = PROJECT_ROOT / "experiments" / EXP_NAME
WEIGHTS_DIR = EXP_DIR / "weights"

TRAIN_DIR = EXP_DIR / "train"
BEST_PT = TRAIN_DIR / "weights" / "best.pt"

SAFETY_DIR = EXP_DIR / "safety_package"
SAFETY_ZIP = (
    PROJECT_ROOT
    / "F02_YOLO26S_CLS_AUG200_SAFETY_PACKAGE.zip"
)

print("=" * 80)
print("F02 Step 2B — Immediate best.pt preservation")
print("=" * 80)

if not BEST_PT.exists():
    raise FileNotFoundError(f"best.pt not found: {BEST_PT}")

WEIGHTS_DIR.mkdir(parents=True, exist_ok=True)
SAFETY_DIR.mkdir(parents=True, exist_ok=True)

locked_best = WEIGHTS_DIR / "best.pt"
shutil.copy2(BEST_PT, locked_best)

safety_weights = SAFETY_DIR / "weights"
safety_weights.mkdir(parents=True, exist_ok=True)
shutil.copy2(locked_best, safety_weights / "best.pt")

for filename in ["results.csv", "results.png", "args.yaml"]:
    src = TRAIN_DIR / filename
    if src.exists():
        shutil.copy2(src, SAFETY_DIR / filename)

sha256 = hashlib.sha256(
    locked_best.read_bytes()
).hexdigest()

(SAFETY_DIR / "BEST_PT_SHA256.txt").write_text(
    sha256 + "\n"
)

if SAFETY_ZIP.exists():
    SAFETY_ZIP.unlink()

shutil.make_archive(
    str(SAFETY_ZIP.with_suffix("")),
    "zip",
    SAFETY_DIR,
)

print(f"Source best.pt : {BEST_PT}")
print(f"Locked best.pt : {locked_best}")
print(f"SHA-256        : {sha256}")
print(f"Safety package : {SAFETY_ZIP}")
print(f"ZIP size       : {SAFETY_ZIP.stat().st_size / (1024**2):.2f} MB")

print("\n" + "=" * 80)
print("F02 STEP 2B PASSED — BEST.PT PRESERVED")
print("=" * 80)
print("NEXT: Download the safety package before Step 2C.")

## F02 Step 2C — Safety package and actual training arguments audit

Verify the preserved F02 checkpoint, confirm the safety package contents, and inspect the actual Ultralytics `args.yaml` generated during training.

No validation or test evaluation is performed in this step.

In [ ]:
# F02 Step 2C — Safety package and actual training arguments audit

import hashlib
import zipfile
from pathlib import Path

import yaml

PROJECT_ROOT = Path(
    "/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026"
)

EXP_NAME = "F02_YOLO26S_CLS_AUG200"
EXP_DIR = PROJECT_ROOT / "experiments" / EXP_NAME

LOCKED_BEST = EXP_DIR / "weights" / "best.pt"
ARGS_YAML = EXP_DIR / "train" / "args.yaml"

SAFETY_ZIP = (
    PROJECT_ROOT
    / "F02_YOLO26S_CLS_AUG200_SAFETY_PACKAGE.zip"
)

EXPECTED_SHA256 = (
    "38a4948f97f8ed3194d4c3ce7d56132180f8a1b3b84a4c575fba45d1380ab302"
)

print("=" * 80)
print("F02 Step 2C — Safety package and actual training arguments audit")
print("=" * 80)

# -------------------------------------------------------------------------
# Locked checkpoint verification
# -------------------------------------------------------------------------

actual_sha256 = hashlib.sha256(
    LOCKED_BEST.read_bytes()
).hexdigest()

print("\nLOCKED CHECKPOINT")
print(f"Path     : {LOCKED_BEST}")
print(f"SHA-256  : {actual_sha256}")
print(f"SHA match: {actual_sha256 == EXPECTED_SHA256}")

if actual_sha256 != EXPECTED_SHA256:
    raise RuntimeError("Locked best.pt SHA-256 mismatch.")

# -------------------------------------------------------------------------
# Safety ZIP audit
# -------------------------------------------------------------------------

print("\nSAFETY PACKAGE CONTENTS")

with zipfile.ZipFile(SAFETY_ZIP, "r") as zf:
    zip_files = sorted(zf.namelist())

for name in zip_files:
    print(name)

required_files = {
    "weights/best.pt",
    "results.csv",
    "results.png",
    "args.yaml",
    "BEST_PT_SHA256.txt",
}

if not required_files.issubset(set(zip_files)):
    missing = required_files - set(zip_files)
    raise RuntimeError(f"Safety package missing files: {sorted(missing)}")

# -------------------------------------------------------------------------
# Actual Ultralytics arguments
# -------------------------------------------------------------------------

with open(ARGS_YAML, "r") as f:
    args = yaml.safe_load(f)

audit_keys = [
    "model",
    "data",
    "epochs",
    "patience",
    "batch",
    "imgsz",
    "optimizer",
    "seed",
    "deterministic",
    "pretrained",
    "amp",
    "device",
    "project",
    "name",
]

print("\nACTUAL ARGS.YAML")

for key in audit_keys:
    print(f"{key:<15}: {args.get(key)}")

print("\n" + "=" * 80)
print("F02 STEP 2C PASSED")
print("=" * 80)
print("Locked best.pt verified : YES")
print("Safety package complete : YES")
print("Actual args.yaml audited : YES")
print("\nNEXT: F02 Step 3 — Inspect training and confirm locked best.pt")

## F02 Step 3 — Inspect training and confirm locked best.pt

Inspect the F02 training history using the native Ultralytics classification fitness criterion, defined from Top-1 and Top-5 accuracy.

Identify the checkpoint-selected best epoch and reproduce the training-time validation protocol using the locked `best.pt`.

The official test split is not evaluated in this step.

In [ ]:
# F02 Step 3 — Inspect training and confirm locked best.pt
# Corrected native Ultralytics fitness-based checkpoint audit

import hashlib
from pathlib import Path

import pandas as pd
from ultralytics import YOLO

PROJECT_ROOT = Path(
    "/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026"
)

DATA_ROOT = (
    PROJECT_ROOT
    / "balanced_train"
    / "aug200_imagefolder"
)

EXP_NAME = "F02_YOLO26S_CLS_AUG200"
EXP_DIR = PROJECT_ROOT / "experiments" / EXP_NAME
TABLE_DIR = EXP_DIR / "tables"
WEIGHTS_DIR = EXP_DIR / "weights"

RESULTS_CSV = EXP_DIR / "train" / "results.csv"
LOCKED_BEST = WEIGHTS_DIR / "best.pt"

EXPECTED_SHA256 = (
    "38a4948f97f8ed3194d4c3ce7d56132180f8a1b3b84a4c575fba45d1380ab302"
)

TABLE_DIR.mkdir(parents=True, exist_ok=True)

print("=" * 80)
print("F02 Step 3 — Inspect training and confirm locked best.pt")
print("=" * 80)

# -------------------------------------------------------------------------
# Training history + native classification fitness
# -------------------------------------------------------------------------

history = pd.read_csv(RESULTS_CSV)
history.columns = history.columns.str.strip()

top1_col = "metrics/accuracy_top1"
top5_col = "metrics/accuracy_top5"
loss_col = "val/loss"

history["fitness"] = (
    history[top1_col] + history[top5_col]
) / 2.0

best_idx = history["fitness"].idxmax()
best_row = history.loc[best_idx]

best_epoch = int(best_row["epoch"]) + 1
epochs_completed = len(history)

best_val_top1 = float(best_row[top1_col])
best_val_top5 = float(best_row[top5_col])
best_val_loss = float(best_row[loss_col])
best_fitness = float(best_row["fitness"])

history.to_csv(
    TABLE_DIR / "F02_clean_training_history.csv",
    index=False,
)

# -------------------------------------------------------------------------
# Locked checkpoint verification
# -------------------------------------------------------------------------

actual_sha256 = hashlib.sha256(
    LOCKED_BEST.read_bytes()
).hexdigest()

if actual_sha256 != EXPECTED_SHA256:
    raise RuntimeError("Locked best.pt SHA-256 mismatch.")

# -------------------------------------------------------------------------
# Fresh validation using training-time validation batch size
# -------------------------------------------------------------------------

model = YOLO(str(LOCKED_BEST))

val_results = model.val(
    data=str(DATA_ROOT),
    split="val",
    imgsz=224,
    batch=128,
    device=0,
    verbose=False,
)

fresh_val_top1 = float(val_results.top1)
fresh_val_top5 = float(val_results.top5)
fresh_fitness = (fresh_val_top1 + fresh_val_top5) / 2.0

top1_match = abs(fresh_val_top1 - best_val_top1) < 1e-4
top5_match = abs(fresh_val_top5 - best_val_top5) < 1e-4

if not (top1_match and top5_match):
    raise RuntimeError(
        "Fresh validation metrics do not match the "
        "fitness-selected training-history epoch."
    )

summary = pd.DataFrame([{
    "experiment": "F02",
    "model": "YOLO26s-cls",
    "epochs_completed": epochs_completed,
    "best_epoch": best_epoch,
    "selection_metric": "Ultralytics classification fitness",
    "best_val_loss": best_val_loss,
    "best_fitness": best_fitness,
    "recorded_val_top1": best_val_top1,
    "recorded_val_top5": best_val_top5,
    "fresh_val_top1": fresh_val_top1,
    "fresh_val_top5": fresh_val_top5,
    "fresh_fitness": fresh_fitness,
    "validation_match": True,
    "best_pt_sha256": actual_sha256,
}])

summary.to_csv(
    TABLE_DIR / "F02_best_epoch_summary.csv",
    index=False,
)

print(f"\nEpochs completed    : {epochs_completed}")
print(f"Best epoch          : {best_epoch}")
print("Selection metric    : Ultralytics classification fitness")
print(f"Best Val Loss       : {best_val_loss:.6f}")
print(f"Best Fitness        : {best_fitness:.6f}")
print(f"Recorded Val Top-1  : {best_val_top1 * 100:.4f}%")
print(f"Recorded Val Top-5  : {best_val_top5 * 100:.4f}%")

print("\nFRESH VALIDATION")
print("Validation batch    : 128")
print(f"Fresh Val Top-1     : {fresh_val_top1 * 100:.4f}%")
print(f"Fresh Val Top-5     : {fresh_val_top5 * 100:.4f}%")
print(f"Fresh Fitness       : {fresh_fitness:.6f}")
print("Validation Match    : PASSED")

print("\nLOCKED CHECKPOINT")
print(f"Path                 : {LOCKED_BEST}")
print(f"SHA-256              : {actual_sha256}")

print("\nSaved:")
print(TABLE_DIR / "F02_clean_training_history.csv")
print(TABLE_DIR / "F02_best_epoch_summary.csv")

print("\n" + "=" * 80)
print("F02 STEP 3 PASSED — LOCKED BEST.PT CONFIRMED")
print("=" * 80)
print("NEXT: F02 Step 4 — Official test evaluation and paper metrics")

## F02 Step 3A — Exact checkpoint and validation discrepancy audit

Inspect the exact fitness-selected training row, checkpoint metadata, and fresh validation values.

No test evaluation is performed and no metric is locked in this diagnostic step.

In [ ]:
# F02 Step 3A — Exact checkpoint and validation discrepancy audit

from pathlib import Path

import pandas as pd
import torch
from ultralytics import YOLO

PROJECT_ROOT = Path(
    "/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026"
)

DATA_ROOT = (
    PROJECT_ROOT
    / "balanced_train"
    / "aug200_imagefolder"
)

EXP_DIR = (
    PROJECT_ROOT
    / "experiments"
    / "F02_YOLO26S_CLS_AUG200"
)

RESULTS_CSV = EXP_DIR / "train" / "results.csv"
LOCKED_BEST = EXP_DIR / "weights" / "best.pt"

print("=" * 80)
print("F02 Step 3A — Exact checkpoint and validation discrepancy audit")
print("=" * 80)

history = pd.read_csv(RESULTS_CSV)
history.columns = history.columns.str.strip()

top1_col = "metrics/accuracy_top1"
top5_col = "metrics/accuracy_top5"

history["fitness"] = (
    history[top1_col] + history[top5_col]
) / 2.0

top_rows = history.nlargest(
    5,
    "fitness",
)[[
    "epoch",
    "val/loss",
    top1_col,
    top5_col,
    "fitness",
]]

print("\nTOP 5 FITNESS ROWS")
print(top_rows.to_string(index=False))

best_row = top_rows.iloc[0]

recorded_top1 = float(best_row[top1_col])
recorded_top5 = float(best_row[top5_col])
recorded_fitness = float(best_row["fitness"])

print("\nFITNESS-SELECTED ROW")
print(f"Epoch value      : {best_row['epoch']}")
print(f"Recorded Top-1   : {recorded_top1:.10f}")
print(f"Recorded Top-5   : {recorded_top5:.10f}")
print(f"Recorded fitness : {recorded_fitness:.10f}")

ckpt = torch.load(
    LOCKED_BEST,
    map_location="cpu",
    weights_only=False,
)

print("\nCHECKPOINT METADATA")
print(f"Checkpoint epoch : {ckpt.get('epoch')}")
print(f"Best fitness     : {ckpt.get('best_fitness')}")
print(f"Train metrics    : {ckpt.get('train_metrics')}")
print(f"Version          : {ckpt.get('version')}")

model = YOLO(str(LOCKED_BEST))

val_results = model.val(
    data=str(DATA_ROOT),
    split="val",
    imgsz=224,
    batch=128,
    device=0,
    verbose=False,
)

fresh_top1 = float(val_results.top1)
fresh_top5 = float(val_results.top5)
fresh_fitness = (fresh_top1 + fresh_top5) / 2.0

print("\nFRESH VALIDATION")
print(f"Fresh Top-1      : {fresh_top1:.10f}")
print(f"Fresh Top-5      : {fresh_top5:.10f}")
print(f"Fresh fitness    : {fresh_fitness:.10f}")

print("\nEXACT DIFFERENCE")
print(f"Top-1 difference : {fresh_top1 - recorded_top1:+.10f}")
print(f"Top-5 difference : {fresh_top5 - recorded_top5:+.10f}")
print(f"Fitness diff     : {fresh_fitness - recorded_fitness:+.10f}")

print("\nSAMPLE-EQUIVALENT DIFFERENCE")
print(
    f"Top-1 images     : "
    f"{(fresh_top1 - recorded_top1) * 1312:+.4f}"
)
print(
    f"Top-5 images     : "
    f"{(fresh_top5 - recorded_top5) * 1312:+.4f}"
)

print("\n" + "=" * 80)
print("F02 STEP 3A DIAGNOSTIC COMPLETE")
print("=" * 80)
print("DO NOT RUN STEP 4 YET.")

## F02 Step 3 — Lock training result and confirm best.pt

Resolve the native Ultralytics equal-fitness checkpoint tie, identify the actual training-history row represented by the locked `best.pt`, and confirm the checkpoint using fresh validation.

The first best-fitness epoch and actual locked checkpoint epoch are recorded separately.

The official test split is not evaluated in this step.

In [ ]:
# F02 Step 3 — Lock training result and confirm best.pt

import hashlib
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from ultralytics import YOLO

PROJECT_ROOT = Path(
    "/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026"
)

DATA_ROOT = (
    PROJECT_ROOT
    / "balanced_train"
    / "aug200_imagefolder"
)

EXP_NAME = "F02_YOLO26S_CLS_AUG200"
EXP_DIR = PROJECT_ROOT / "experiments" / EXP_NAME
TABLE_DIR = EXP_DIR / "tables"
WEIGHTS_DIR = EXP_DIR / "weights"

RESULTS_CSV = EXP_DIR / "train" / "results.csv"
LOCKED_BEST = WEIGHTS_DIR / "best.pt"

EXPECTED_SHA256 = (
    "38a4948f97f8ed3194d4c3ce7d56132180f8a1b3b84a4c575fba45d1380ab302"
)

TABLE_DIR.mkdir(parents=True, exist_ok=True)

print("=" * 80)
print("F02 Step 3 — Lock training result and confirm best.pt")
print("=" * 80)

# -------------------------------------------------------------------------
# Training history
# -------------------------------------------------------------------------

history = pd.read_csv(RESULTS_CSV)
history.columns = history.columns.str.strip()

top1_col = "metrics/accuracy_top1"
top5_col = "metrics/accuracy_top5"
loss_col = "val/loss"

history["fitness"] = (
    history[top1_col] + history[top5_col]
) / 2.0

first_best_idx = history["fitness"].idxmax()
first_best_row = history.loc[first_best_idx]

first_best_epoch = int(first_best_row["epoch"])

# -------------------------------------------------------------------------
# Locked checkpoint
# -------------------------------------------------------------------------

actual_sha256 = hashlib.sha256(
    LOCKED_BEST.read_bytes()
).hexdigest()

if actual_sha256 != EXPECTED_SHA256:
    raise RuntimeError("Locked best.pt SHA-256 mismatch.")

ckpt = torch.load(
    LOCKED_BEST,
    map_location="cpu",
    weights_only=False,
)

checkpoint_metrics = ckpt["train_metrics"]

checkpoint_top1 = float(
    checkpoint_metrics[top1_col]
)
checkpoint_top5 = float(
    checkpoint_metrics[top5_col]
)
checkpoint_loss = float(
    checkpoint_metrics[loss_col]
)
checkpoint_fitness = float(
    checkpoint_metrics["fitness"]
)

checkpoint_rows = history[
    np.isclose(history[top1_col], checkpoint_top1, atol=1e-6)
    & np.isclose(history[top5_col], checkpoint_top5, atol=1e-6)
    & np.isclose(history[loss_col], checkpoint_loss, atol=1e-6)
]

if len(checkpoint_rows) != 1:
    raise RuntimeError(
        "Could not uniquely identify the locked checkpoint epoch."
    )

checkpoint_row = checkpoint_rows.iloc[0]
checkpoint_epoch = int(checkpoint_row["epoch"])

# -------------------------------------------------------------------------
# Fresh validation
# -------------------------------------------------------------------------

model = YOLO(str(LOCKED_BEST))

val_results = model.val(
    data=str(DATA_ROOT),
    split="val",
    imgsz=224,
    batch=128,
    device=0,
    verbose=False,
)

fresh_top1 = float(val_results.top1)
fresh_top5 = float(val_results.top5)
fresh_fitness = (fresh_top1 + fresh_top5) / 2.0

validation_match = (
    abs(fresh_top1 - checkpoint_top1) < 1e-5
    and abs(fresh_top5 - checkpoint_top5) < 1e-5
)

if not validation_match:
    raise RuntimeError(
        "Fresh validation does not match locked checkpoint metrics."
    )

# -------------------------------------------------------------------------
# Save official Step 3 tables
# -------------------------------------------------------------------------

history.to_csv(
    TABLE_DIR / "F02_clean_training_history.csv",
    index=False,
)

summary = pd.DataFrame([{
    "experiment": "F02",
    "model": "YOLO26s-cls",
    "epochs_completed": len(history),
    "selection_metric": "Ultralytics classification fitness",
    "first_best_fitness_epoch": first_best_epoch,
    "locked_checkpoint_epoch": checkpoint_epoch,
    "equal_fitness_tie": first_best_epoch != checkpoint_epoch,
    "first_best_val_top1": float(first_best_row[top1_col]),
    "first_best_val_top5": float(first_best_row[top5_col]),
    "best_fitness": checkpoint_fitness,
    "checkpoint_val_loss": checkpoint_loss,
    "checkpoint_val_top1": checkpoint_top1,
    "checkpoint_val_top5": checkpoint_top5,
    "fresh_val_top1": fresh_top1,
    "fresh_val_top5": fresh_top5,
    "fresh_fitness": fresh_fitness,
    "validation_match": validation_match,
    "best_pt_sha256": actual_sha256,
}])

summary.to_csv(
    TABLE_DIR / "F02_best_epoch_summary.csv",
    index=False,
)

print(f"\nEpochs completed         : {len(history)}")
print(f"First best-fitness epoch : {first_best_epoch}")
print(f"Locked checkpoint epoch  : {checkpoint_epoch}")
print("Equal-fitness tie        : YES")

print("\nFIRST BEST-FITNESS EPOCH")
print(
    f"Val Top-1                : "
    f"{float(first_best_row[top1_col]) * 100:.4f}%"
)
print(
    f"Val Top-5                : "
    f"{float(first_best_row[top5_col]) * 100:.4f}%"
)
print(
    f"Fitness                  : "
    f"{float(first_best_row['fitness']):.6f}"
)

print("\nLOCKED BEST.PT CHECKPOINT")
print(f"Checkpoint Val Loss       : {checkpoint_loss:.6f}")
print(f"Checkpoint Val Top-1      : {checkpoint_top1 * 100:.4f}%")
print(f"Checkpoint Val Top-5      : {checkpoint_top5 * 100:.4f}%")
print(f"Checkpoint Fitness        : {checkpoint_fitness:.6f}")

print("\nFRESH VALIDATION")
print(f"Fresh Val Top-1           : {fresh_top1 * 100:.4f}%")
print(f"Fresh Val Top-5           : {fresh_top5 * 100:.4f}%")
print(f"Fresh Fitness             : {fresh_fitness:.8f}")
print("Validation Match          : PASSED")

print("\nLOCKED CHECKPOINT")
print(f"SHA-256                   : {actual_sha256}")

print("\nSaved:")
print(TABLE_DIR / "F02_clean_training_history.csv")
print(TABLE_DIR / "F02_best_epoch_summary.csv")

print("\n" + "=" * 80)
print("F02 STEP 3 PASSED — LOCKED BEST.PT CONFIRMED")
print("=" * 80)
print("NEXT: F02 Step 4 — Official test evaluation and paper metrics")

## F02 Step 4 — Official test evaluation and paper metrics

Evaluate the locked F02 `best.pt` checkpoint on the unchanged official AQUA20 test split.

Report native YOLO Top-1 and Top-5 accuracy and calculate prediction-level paper metrics, per-class performance, and confusion matrices.

Save all comparison-ready tables and figures immediately.

In [ ]:
# F02 Step 4 — Official test evaluation and paper metrics

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import (
    confusion_matrix,
    precision_recall_fscore_support,
)
from sklearn.metrics import ConfusionMatrixDisplay
from ultralytics import YOLO

PROJECT_ROOT = Path(
    "/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026"
)

DATA_ROOT = (
    PROJECT_ROOT
    / "balanced_train"
    / "aug200_imagefolder"
)

EXP_NAME = "F02_YOLO26S_CLS_AUG200"
EXP_DIR = PROJECT_ROOT / "experiments" / EXP_NAME
TABLE_DIR = EXP_DIR / "tables"
FIG_DIR = EXP_DIR / "figures"
WEIGHTS_DIR = EXP_DIR / "weights"

LOCKED_BEST = WEIGHTS_DIR / "best.pt"
TEST_DIR = DATA_ROOT / "test"

TABLE_DIR.mkdir(parents=True, exist_ok=True)
FIG_DIR.mkdir(parents=True, exist_ok=True)

print("=" * 80)
print("F02 Step 4 — Official test evaluation and paper metrics")
print("=" * 80)

# -------------------------------------------------------------------------
# Classes and official test images
# -------------------------------------------------------------------------

class_dirs = sorted(
    p for p in TEST_DIR.iterdir()
    if p.is_dir()
)

raw_class_names = [p.name for p in class_dirs]

class_names = [
    name.split("_", 1)[1]
    if "_" in name else name
    for name in raw_class_names
]

image_paths = []
y_true = []

for class_idx, class_dir in enumerate(class_dirs):
    paths = sorted(
        p for p in class_dir.rglob("*")
        if p.is_file()
        and p.suffix.lower()
        in {".jpg", ".jpeg", ".png", ".bmp", ".webp"}
    )

    image_paths.extend(paths)
    y_true.extend([class_idx] * len(paths))

y_true = np.asarray(y_true)

print(f"\nTest images          : {len(image_paths)}")
print(f"Classes              : {len(class_names)}")
print("Official test split  : VERIFIED")

# -------------------------------------------------------------------------
# Locked model
# -------------------------------------------------------------------------

model = YOLO(str(LOCKED_BEST))

model_class_names = [
    model.names[i]
    for i in range(len(model.names))
]

if model_class_names != raw_class_names:
    raise RuntimeError("Model and test class order mismatch.")

# -------------------------------------------------------------------------
# Native YOLO test evaluation
# -------------------------------------------------------------------------

print("\n" + "=" * 80)
print("NATIVE YOLO TEST EVALUATION")
print("=" * 80)

native_results = model.val(
    data=str(DATA_ROOT),
    split="test",
    imgsz=224,
    batch=128,
    device=0,
    verbose=False,
)

native_top1 = float(native_results.top1)
native_top5 = float(native_results.top5)

pd.DataFrame([{
    "experiment": "F02",
    "model": "YOLO26s-cls",
    "test_top1": native_top1,
    "test_top5": native_top5,
    "support": len(image_paths),
}]).to_csv(
    TABLE_DIR / "F02_native_test_metrics.csv",
    index=False,
)

# -------------------------------------------------------------------------
# Prediction-level evaluation
# -------------------------------------------------------------------------

print("\n" + "=" * 80)
print("PREDICTION-LEVEL PAPER METRICS")
print("=" * 80)

pred_results = model.predict(
    source=[str(p) for p in image_paths],
    imgsz=224,
    batch=128,
    device=0,
    verbose=False,
)

scores = np.stack([
    result.probs.data.cpu().numpy()
    for result in pred_results
])

y_pred = scores.argmax(axis=1)

top5_indices = np.argsort(
    -scores,
    axis=1,
)[:, :5]

manual_top1 = float(
    np.mean(y_pred == y_true)
)

manual_top5 = float(
    np.mean([
        true_idx in top5
        for true_idx, top5 in zip(
            y_true,
            top5_indices,
        )
    ])
)

native_manual_match = (
    abs(native_top1 - manual_top1) < 1e-4
    and abs(native_top5 - manual_top5) < 1e-4
)

if not native_manual_match:
    raise RuntimeError(
        "Native and prediction-level Top-1/Top-5 metrics do not match."
    )

macro_precision, macro_recall, macro_f1, _ = (
    precision_recall_fscore_support(
        y_true,
        y_pred,
        average="macro",
        zero_division=0,
    )
)

_, _, weighted_f1, _ = (
    precision_recall_fscore_support(
        y_true,
        y_pred,
        average="weighted",
        zero_division=0,
    )
)

class_precision, class_recall, class_f1, class_support = (
    precision_recall_fscore_support(
        y_true,
        y_pred,
        labels=np.arange(len(class_names)),
        zero_division=0,
    )
)

# -------------------------------------------------------------------------
# Predictions table
# -------------------------------------------------------------------------

predictions = pd.DataFrame({
    "image": [
        str(path.relative_to(TEST_DIR))
        for path in image_paths
    ],
    "true_index": y_true,
    "true_class": [
        class_names[i]
        for i in y_true
    ],
    "pred_index": y_pred,
    "pred_class": [
        class_names[i]
        for i in y_pred
    ],
    "top1_confidence": scores.max(axis=1),
})

for class_idx, class_name in enumerate(class_names):
    predictions[f"prob_{class_name}"] = scores[:, class_idx]

predictions.to_csv(
    TABLE_DIR / "F02_test_predictions.csv",
    index=False,
)

# -------------------------------------------------------------------------
# Per-class report
# -------------------------------------------------------------------------

class_report = pd.DataFrame({
    "class": class_names,
    "precision": class_precision,
    "recall": class_recall,
    "f1": class_f1,
    "support": class_support.astype(int),
})

class_report.to_csv(
    TABLE_DIR / "F02_classification_report.csv",
    index=False,
)

# -------------------------------------------------------------------------
# Confusion matrices
# -------------------------------------------------------------------------

cm = confusion_matrix(
    y_true,
    y_pred,
    labels=np.arange(len(class_names)),
)

cm_normalized = cm / cm.sum(
    axis=1,
    keepdims=True,
)

pd.DataFrame(
    cm,
    index=class_names,
    columns=class_names,
).to_csv(
    TABLE_DIR / "F02_confusion_matrix.csv"
)

pd.DataFrame(
    cm_normalized,
    index=class_names,
    columns=class_names,
).to_csv(
    TABLE_DIR / "F02_confusion_matrix_normalized.csv"
)

fig, ax = plt.subplots(figsize=(14, 12))
ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=class_names,
).plot(
    ax=ax,
    xticks_rotation=90,
    include_values=False,
    colorbar=True,
)
plt.tight_layout()
plt.savefig(
    FIG_DIR / "F02_confusion_matrix.png",
    dpi=300,
    bbox_inches="tight",
)
plt.close()

fig, ax = plt.subplots(figsize=(14, 12))
ConfusionMatrixDisplay(
    confusion_matrix=cm_normalized,
    display_labels=class_names,
).plot(
    ax=ax,
    xticks_rotation=90,
    include_values=False,
    colorbar=True,
    values_format=".2f",
)
plt.tight_layout()
plt.savefig(
    FIG_DIR / "F02_confusion_matrix_normalized.png",
    dpi=300,
    bbox_inches="tight",
)
plt.close()

# -------------------------------------------------------------------------
# Official metric summaries
# -------------------------------------------------------------------------

test_summary = pd.DataFrame([{
    "experiment": "F02",
    "model": "YOLO26s-cls",
    "train_strategy": "Aug-200 train-only",
    "test_top1": manual_top1,
    "test_top5": manual_top5,
    "macro_precision": macro_precision,
    "macro_recall": macro_recall,
    "macro_f1": macro_f1,
    "weighted_f1": weighted_f1,
    "support": len(y_true),
    "native_manual_match": native_manual_match,
}])

test_summary.to_csv(
    TABLE_DIR / "F02_test_metrics_summary.csv",
    index=False,
)

comparison = pd.DataFrame([{
    "experiment": "F02",
    "model": "YOLO26s-cls",
    "train strategy": "Aug-200 train-only",
    "val top-1": 86.0518,
    "val top-5": 98.7043,
    "test top-1": manual_top1 * 100,
    "test top-5": manual_top5 * 100,
    "macro precision": macro_precision * 100,
    "macro recall": macro_recall * 100,
    "macro F1": macro_f1 * 100,
    "weighted F1": weighted_f1 * 100,
}])

comparison.to_csv(
    TABLE_DIR / "F02_comparison_ready_summary.csv",
    index=False,
)

# -------------------------------------------------------------------------
# Final output
# -------------------------------------------------------------------------

print(f"\nNative Test Top-1   : {native_top1 * 100:.4f}%")
print(f"Native Test Top-5   : {native_top5 * 100:.4f}%")
print(f"Manual Test Top-1   : {manual_top1 * 100:.4f}%")
print(f"Manual Test Top-5   : {manual_top5 * 100:.4f}%")
print(f"Native/Manual Match : PASSED")

print("\nPAPER METRICS")
print(f"Macro Precision     : {macro_precision * 100:.4f}%")
print(f"Macro Recall        : {macro_recall * 100:.4f}%")
print(f"Macro F1            : {macro_f1 * 100:.4f}%")
print(f"Weighted F1         : {weighted_f1 * 100:.4f}%")
print(f"Test Support        : {len(y_true)}")

print("\nF02 vs F01")
print(f"Top-1 difference    : {(manual_top1 * 100) - 84.68:+.4f} pp")
print(f"Top-5 difference    : {(manual_top5 * 100) - 98.95:+.4f} pp")
print(f"Macro Precision diff: {(macro_precision * 100) - 83.31:+.4f} pp")
print(f"Macro Recall diff   : {(macro_recall * 100) - 73.99:+.4f} pp")
print(f"Macro F1 diff       : {(macro_f1 * 100) - 75.99:+.4f} pp")
print(f"Weighted F1 diff    : {(weighted_f1 * 100) - 84.42:+.4f} pp")

print("\nBASE-PAPER TARGET")
print("Target Top-1        : 92.6800%")
print(f"F02 Top-1           : {manual_top1 * 100:.4f}%")
print(f"Difference          : {(manual_top1 * 100) - 92.68:+.4f} pp")
print(
    f"Beat base           : "
    f"{'YES' if manual_top1 * 100 > 92.68 else 'NO'}"
)

print("\nPER-CLASS REPORT")
print(
    class_report.to_string(
        index=False,
        formatters={
            "precision": lambda x: f"{x * 100:.2f}%",
            "recall": lambda x: f"{x * 100:.2f}%",
            "f1": lambda x: f"{x * 100:.2f}%",
        },
    )
)

print("\n" + "=" * 80)
print("F02 STEP 4 PASSED — OFFICIAL TEST EVALUATION COMPLETE")
print("=" * 80)
print("NEXT: F02 Step 5 — Create official final experiment package")

## F02 Step 5 — Create official final experiment package

Create the final reproducible F02 experiment package containing the locked checkpoint, training artifacts, paper-ready tables, confusion-matrix figures, and experiment README.

The dataset and `last.pt` are excluded.

In [ ]:
# F02 Step 5 — Create official final experiment package

import shutil
import zipfile
from pathlib import Path

PROJECT_ROOT = Path(
    "/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026"
)

EXP_NAME = "F02_YOLO26S_CLS_AUG200"
EXP_DIR = PROJECT_ROOT / "experiments" / EXP_NAME

TRAIN_DIR = EXP_DIR / "train"
TABLE_DIR = EXP_DIR / "tables"
FIG_DIR = EXP_DIR / "figures"
WEIGHTS_DIR = EXP_DIR / "weights"

PACKAGE_DIR = EXP_DIR / "official_package"

FINAL_ZIP = (
    PROJECT_ROOT
    / "aqua20_f02_yolo26s_cls_aug200_outputs.zip"
)

print("=" * 80)
print("F02 Step 5 — Create official final experiment package")
print("=" * 80)

if PACKAGE_DIR.exists():
    shutil.rmtree(PACKAGE_DIR)

PACKAGE_DIR.mkdir(parents=True)

# -------------------------------------------------------------------------
# Package folders
# -------------------------------------------------------------------------

package_weights = PACKAGE_DIR / "weights"
package_training = PACKAGE_DIR / "training_run"
package_tables = PACKAGE_DIR / "tables"
package_figures = PACKAGE_DIR / "figures"

package_weights.mkdir()
package_training.mkdir()
package_tables.mkdir()
package_figures.mkdir()

# -------------------------------------------------------------------------
# Locked checkpoint
# -------------------------------------------------------------------------

shutil.copy2(
    WEIGHTS_DIR / "best.pt",
    package_weights / "best.pt",
)

# -------------------------------------------------------------------------
# Training artifacts
# -------------------------------------------------------------------------

for filename in [
    "results.csv",
    "results.png",
    "args.yaml",
]:
    src = TRAIN_DIR / filename

    if src.exists():
        shutil.copy2(
            src,
            package_training / filename,
        )

# -------------------------------------------------------------------------
# Tables
# -------------------------------------------------------------------------

for src in TABLE_DIR.glob("*.csv"):
    shutil.copy2(
        src,
        package_tables / src.name,
    )

# -------------------------------------------------------------------------
# Figures
# -------------------------------------------------------------------------

for src in FIG_DIR.glob("*.png"):
    shutil.copy2(
        src,
        package_figures / src.name,
    )

# -------------------------------------------------------------------------
# README
# -------------------------------------------------------------------------

readme = """AQUA20 F02 OFFICIAL EXPERIMENT PACKAGE

Official project:
04-07-2026 AQUA20 FINAL BEAT BASE PLAN

Experiment:
F02_YOLO26S_CLS_AUG200

Model:
YOLO26s-cls

Scientific role:
G2 — Data-level balancing experiment

Method:
YOLO26s-cls + Aug-200 train-only balancing

DATASET PROTOCOL
Train : 7,284
Val   : 1,312
Test  : 1,612
Classes: 20

Validation and test were unchanged.

TRAINING CONFIGURATION
Model          : yolo26s-cls.pt
Image size     : 224
Batch size     : 64
Maximum epochs : 200
Patience       : 30
Seed           : 42
Deterministic  : True
Pretrained     : True
Optimizer      : auto
AMP            : True
Custom weights : No
Custom focal   : No

TRAINING RESULT
Epochs completed         : 68
First best-fitness epoch : 38
Locked checkpoint epoch  : 49
Equal-fitness tie        : Yes

The first best-fitness epoch and locked checkpoint epoch differ because
Ultralytics encountered an equal-fitness tie. The preserved best.pt
corresponds to the later tied checkpoint represented by epoch 49 metrics.

LOCKED VALIDATION RESULT
Val Top-1 : 86.0518%
Val Top-5 : 98.7043%

OFFICIAL TEST RESULT
Test Top-1      : 83.4367%
Test Top-5      : 97.9529%
Macro Precision : 80.9103%
Macro Recall    : 65.2565%
Macro F1        : 70.3909%
Weighted F1     : 82.8376%
Support         : 1,612

F01 COMPARISON
F01 YOLO26m-cls + Aug-200 Top-1 : 84.68%
F02 YOLO26s-cls + Aug-200 Top-1 : 83.44%

F02 Top-1 difference vs F01:
-1.24 percentage points

BASE-PAPER TARGET
Reported YOLO26m Top-1 : 92.68%
F02 Top-1              : 83.44%
Difference             : -9.24 percentage points
Beat base              : No

SCIENTIFIC INTERPRETATION
F02 confirms that Aug-200 train-only balancing alone is insufficient to
solve AQUA20 minority-class recognition imbalance.

The smaller YOLO26s-cls model performed worse than YOLO26m-cls under the
same Aug-200 protocol, particularly in macro recall and macro F1.

Important weak minority-class recall included:
marine_dolphin : 30.00%
seaCucumber    : 30.00%
octopus        : 40.00%
eel            : 48.78%
flatworm       : 23.08%

F02 is a valid negative architecture-size/data-balancing ablation result.

Do not tune F02 using the official test result.

LOCKED BEST.PT SHA-256
38a4948f97f8ed3194d4c3ce7d56132180f8a1b3b84a4c575fba45d1380ab302

PACKAGE CONTENTS
weights/
    best.pt

training_run/
    results.csv
    results.png
    args.yaml

tables/
    training history
    best epoch summary
    native test metrics
    test predictions
    classification report
    confusion matrices
    test metrics summary
    comparison-ready summary

figures/
    confusion matrix
    normalized confusion matrix

Excluded:
dataset
last.pt
"""

(PACKAGE_DIR / "README_F02.txt").write_text(
    readme,
    encoding="utf-8",
)

# -------------------------------------------------------------------------
# Create final ZIP
# -------------------------------------------------------------------------

if FINAL_ZIP.exists():
    FINAL_ZIP.unlink()

shutil.make_archive(
    str(FINAL_ZIP.with_suffix("")),
    "zip",
    PACKAGE_DIR,
)

# -------------------------------------------------------------------------
# Audit ZIP
# -------------------------------------------------------------------------

with zipfile.ZipFile(FINAL_ZIP, "r") as zf:
    files = sorted(zf.namelist())

print(f"\nFinal package : {FINAL_ZIP}")
print(
    f"ZIP size      : "
    f"{FINAL_ZIP.stat().st_size / (1024 ** 2):.2f} MB"
)

print("\nPACKAGE CONTENTS")
for name in files:
    print(name)

if any(
    "last.pt" in name.lower()
    for name in files
):
    raise RuntimeError("last.pt found in final package.")

print("\n" + "=" * 80)
print("F02 STEP 5 PASSED — OFFICIAL FINAL PACKAGE CREATED")
print("=" * 80)
print("F02 STATUS : COMPLETED")
print(f"DOWNLOAD   : {FINAL_ZIP}")

# F03 Step 1 — Environment and Original Dataset Verification

Verify the Kaggle environment, locked original AQUA20 ImageFolder dataset, stable 20-class order, and pretrained TorchVision ConvNeXt-Small availability.

No class-balanced weights are calculated and no training is performed in this step.

In [ ]:
# F03 Step 1 — Environment and original dataset verification

import sys
from pathlib import Path

import torch
import torchvision
import torch.nn as nn
from torchvision.models import convnext_small, ConvNeXt_Small_Weights

SEED = 42

PROJECT_ROOT = Path("/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026")
DATA_ROOT = PROJECT_ROOT / "official_imagefolder"

EXPECTED_COUNTS = {
    "train": 5247,
    "val": 1312,
    "test": 1612,
}

EXPECTED_CLASSES = [
    "00_coral",
    "01_crab",
    "02_diver",
    "03_eel",
    "04_fish",
    "05_fishInGroups",
    "06_flatworm",
    "07_jellyfish",
    "08_marine_dolphin",
    "09_octopus",
    "10_rayfish",
    "11_seaAnemone",
    "12_seaCucumber",
    "13_seaSlug",
    "14_seaUrchin",
    "15_shark",
    "16_shrimp",
    "17_squid",
    "18_starfish",
    "19_turtle",
]

IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}

print("=" * 80)
print("F03 Step 1 — Environment and original dataset verification")
print("=" * 80)

print(f"Python      : {sys.version.split()[0]}")
print(f"Torch       : {torch.__version__}")
print(f"Torchvision : {torchvision.__version__}")
print(f"CUDA        : {torch.cuda.is_available()}")

if not torch.cuda.is_available():
    raise RuntimeError("CUDA GPU is not available.")

print(f"GPU         : {torch.cuda.get_device_name(0)}")
print(f"DATA_ROOT   : {DATA_ROOT}")

if not DATA_ROOT.exists():
    raise FileNotFoundError(f"Original DATA_ROOT not found: {DATA_ROOT}")

print("\n" + "=" * 80)
print("DATASET VERIFICATION")
print("=" * 80)

for split, expected_count in EXPECTED_COUNTS.items():
    split_dir = DATA_ROOT / split

    class_names = sorted(
        p.name for p in split_dir.iterdir() if p.is_dir()
    )

    image_count = sum(
        1
        for p in split_dir.rglob("*")
        if p.is_file() and p.suffix.lower() in IMAGE_EXTS
    )

    print(
        f"{split:<5} | images: {image_count:<4} | "
        f"classes: {len(class_names)}"
    )

    assert image_count == expected_count, (
        f"{split} count mismatch: {image_count} != {expected_count}"
    )
    assert class_names == EXPECTED_CLASSES, (
        f"{split} class order mismatch."
    )

print("\nStable class order:")
for idx, class_name in enumerate(EXPECTED_CLASSES):
    print(f"{idx:02d} : {class_name}")

print("\n" + "=" * 80)
print("CONVNEXT-SMALL VERIFICATION")
print("=" * 80)

weights = ConvNeXt_Small_Weights.DEFAULT
model = convnext_small(weights=weights)

original_in_features = model.classifier[2].in_features
model.classifier[2] = nn.Linear(original_in_features, 20)

print(f"Model                 : ConvNeXt-Small")
print(f"Pretrained weights    : {weights}")
print(f"Classifier in_features: {original_in_features}")
print(f"Classifier out_features: {model.classifier[2].out_features}")

assert model.classifier[2].out_features == 20

del model

print("\n" + "=" * 80)
print("F03 STEP 1 PASSED")
print("=" * 80)
print("Original dataset verified.")
print("ConvNeXt-Small pretrained model verified.")
print("20-class classifier replacement verified.")
print("NEXT: F03 Step 2 — Class counts + Gentle CB Focal configuration")

# F03 Step 2 — Class Counts and Gentle CB Focal Configuration

Calculate the original training-set class counts and lock the Gentle Class-Balanced Focal Loss configuration before training.

Locked loss constants:

- Beta = 0.999
- Gamma = 1.0
- Effective-number class balancing
- Mean-normalized class weights
- No raw inverse-frequency weighting

In [ ]:
# F03 Step 2 — Class counts + lock Gentle CB Focal configuration

import json
import numpy as np
import pandas as pd
from pathlib import Path
from torchvision.datasets import ImageFolder

SEED = 42

PROJECT_ROOT = Path("/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026")
DATA_ROOT = PROJECT_ROOT / "official_imagefolder"

EXP_NAME = "F03_CONVNEXT_SMALL_GENTLE_CB_FOCAL"
EXP_DIR = PROJECT_ROOT / "experiments" / EXP_NAME
TABLE_DIR = EXP_DIR / "tables"
FIG_DIR = EXP_DIR / "figures"
WEIGHTS_DIR = EXP_DIR / "weights"

for path in [EXP_DIR, TABLE_DIR, FIG_DIR, WEIGHTS_DIR]:
    path.mkdir(parents=True, exist_ok=True)

BETA = 0.999
GAMMA = 1.0

print("=" * 80)
print("F03 Step 2 — Class counts + Gentle CB Focal configuration")
print("=" * 80)

train_dataset = ImageFolder(DATA_ROOT / "train")

class_counts = np.bincount(
    train_dataset.targets,
    minlength=len(train_dataset.classes)
)

effective_num = 1.0 - np.power(BETA, class_counts)
class_weights = (1.0 - BETA) / effective_num
class_weights = class_weights / class_weights.mean()

class_table = pd.DataFrame({
    "class_id": range(len(train_dataset.classes)),
    "class_name": train_dataset.classes,
    "train_count": class_counts,
    "cb_weight": class_weights,
})

class_table.to_csv(
    TABLE_DIR / "F03_class_counts_and_cb_weights.csv",
    index=False
)

loss_config = {
    "experiment": EXP_NAME,
    "loss_name": "Gentle Class-Balanced Focal Loss",
    "beta": BETA,
    "gamma": GAMMA,
    "weight_method": "effective_number",
    "weight_normalization": "mean_1",
    "inverse_frequency_weighting": False,
    "training_data": "original_train_5247",
    "seed": SEED,
}

with open(
    TABLE_DIR / "F03_gentle_cb_focal_config.json",
    "w"
) as f:
    json.dump(loss_config, f, indent=4)

print(f"Training images : {len(train_dataset)}")
print(f"Classes         : {len(train_dataset.classes)}")
print(f"Beta            : {BETA}")
print(f"Gamma           : {GAMMA}")
print("\nCLASS COUNTS AND LOCKED WEIGHTS")
print(class_table.to_string(index=False))

print("\nSaved:")
print(TABLE_DIR / "F03_class_counts_and_cb_weights.csv")
print(TABLE_DIR / "F03_gentle_cb_focal_config.json")

print("\n" + "=" * 80)
print("F03 STEP 2 PASSED — LOSS CONFIGURATION LOCKED")
print("=" * 80)
print("NEXT: F03 Step 3 — Train ConvNeXt-Small + Gentle CB Focal")

# F03 Step 3 — P100-Optimized ConvNeXt-Small Training

Train ConvNeXt-Small on the original AQUA20 training split using the locked Gentle Class-Balanced Focal Loss.

The scientific method remains unchanged.

Optimized execution:
- Batch size 32
- AMP enabled
- Pinned-memory DataLoader
- Persistent workers and prefetching
- Compact one-row-per-epoch training table
- Best checkpoint saved only on validation macro-F1 improvement
- Recovery checkpoint saved every 5 epochs

Checkpoint selection remains strictly based on validation macro F1.
The official test set is not used during training.

In [ ]:
# F03 Step 3 — Official ConvNeXt-Small + Gentle CB Focal training

import json
import random
import time
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F

from sklearn.metrics import precision_recall_fscore_support
from torch.utils.data import DataLoader
from torchvision import transforms
from torchvision.datasets import ImageFolder
from torchvision.models import convnext_small, ConvNeXt_Small_Weights


# =============================================================================
# OFFICIAL F03 CONFIGURATION
# =============================================================================

SEED = 42

PROJECT_ROOT = Path("/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026")
DATA_ROOT = PROJECT_ROOT / "official_imagefolder"

EXP_NAME = "F03_CONVNEXT_SMALL_GENTLE_CB_FOCAL"
EXP_DIR = PROJECT_ROOT / "experiments" / EXP_NAME

TABLE_DIR = EXP_DIR / "tables"
FIG_DIR = EXP_DIR / "figures"
WEIGHTS_DIR = EXP_DIR / "weights"

BEST_MODEL_PATH = WEIGHTS_DIR / "best_model.pth"
RECOVERY_PATH = WEIGHTS_DIR / "recovery_checkpoint.pth"

HISTORY_PATH = TABLE_DIR / "F03_training_history.csv"
CONFIG_PATH = TABLE_DIR / "F03_training_config.json"

WEIGHT_TABLE_PATH = (
    TABLE_DIR / "F03_class_counts_and_cb_weights.csv"
)

IMG_SIZE = 224
BATCH_SIZE = 16
NUM_WORKERS = 4
PREFETCH_FACTOR = 2

MAX_EPOCHS = 40
PATIENCE = 8

LR = 1e-5
WEIGHT_DECAY = 1e-4

BETA = 0.999
GAMMA = 1.0

GRAD_CLIP = 1.0
RECOVERY_EVERY = 5

DEVICE = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

AMP_ENABLED = DEVICE.type == "cuda"

for path in [EXP_DIR, TABLE_DIR, FIG_DIR, WEIGHTS_DIR]:
    path.mkdir(parents=True, exist_ok=True)


# =============================================================================
# CLEAN PREVIOUS SPEED-TRIAL STEP 3 FILES
# =============================================================================

print("=" * 145)
print("F03 STEP 3 — OFFICIAL BATCH-16 CLEAN RESTART")
print("=" * 145)

old_step3_files = [
    BEST_MODEL_PATH,
    RECOVERY_PATH,
    HISTORY_PATH,
    CONFIG_PATH,
    WEIGHTS_DIR / "last_checkpoint.pth",
]

for path in old_step3_files:
    if path.exists():
        path.unlink()
        print(f"Removed: {path.name}")

print("Step 2 class counts and locked CB weights preserved.")


# =============================================================================
# REPRODUCIBILITY
# =============================================================================

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed(SEED)
    torch.cuda.manual_seed_all(SEED)

if DEVICE.type != "cuda":
    raise RuntimeError("CUDA GPU is required for F03 training.")

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False


# =============================================================================
# TRANSFORMS
# =============================================================================

IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD = [0.229, 0.224, 0.225]

train_transform = transforms.Compose([
    transforms.Resize((256, 256)),

    transforms.RandomResizedCrop(
        IMG_SIZE,
        scale=(0.80, 1.00),
    ),

    transforms.RandomHorizontalFlip(p=0.5),

    transforms.RandomRotation(10),

    transforms.ColorJitter(
        brightness=0.12,
        contrast=0.12,
        saturation=0.12,
        hue=0.03,
    ),

    transforms.ToTensor(),

    transforms.Normalize(
        IMAGENET_MEAN,
        IMAGENET_STD,
    ),
])

val_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(
        IMAGENET_MEAN,
        IMAGENET_STD,
    ),
])


# =============================================================================
# DATA
# =============================================================================

train_dataset = ImageFolder(
    DATA_ROOT / "train",
    transform=train_transform,
)

val_dataset = ImageFolder(
    DATA_ROOT / "val",
    transform=val_transform,
)

assert len(train_dataset) == 5247
assert len(val_dataset) == 1312
assert train_dataset.classes == val_dataset.classes
assert len(train_dataset.classes) == 20

loader_generator = torch.Generator()
loader_generator.manual_seed(SEED)

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=NUM_WORKERS,
    pin_memory=True,
    persistent_workers=True,
    prefetch_factor=PREFETCH_FACTOR,
    generator=loader_generator,
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=True,
    persistent_workers=True,
    prefetch_factor=PREFETCH_FACTOR,
)


# =============================================================================
# LOCKED CLASS WEIGHTS
# =============================================================================

weight_table = pd.read_csv(
    WEIGHT_TABLE_PATH
)

class_weights = torch.tensor(
    weight_table["cb_weight"].values,
    dtype=torch.float32,
    device=DEVICE,
)


# =============================================================================
# GENTLE CLASS-BALANCED FOCAL LOSS
# =============================================================================

class GentleCBFocalLoss(nn.Module):

    def __init__(self, class_weights, gamma=1.0):
        super().__init__()

        self.register_buffer(
            "class_weights",
            class_weights.clone().detach(),
        )

        self.gamma = gamma

    def forward(self, logits, targets):

        ce_loss = F.cross_entropy(
            logits,
            targets,
            weight=self.class_weights,
            reduction="none",
        )

        probabilities = torch.softmax(
            logits,
            dim=1,
        )

        pt = probabilities.gather(
            1,
            targets.unsqueeze(1),
        ).squeeze(1)

        focal_factor = (
            1.0 - pt
        ).pow(self.gamma)

        return (
            focal_factor * ce_loss
        ).mean()


# =============================================================================
# MODEL
# =============================================================================

weights = ConvNeXt_Small_Weights.DEFAULT

model = convnext_small(
    weights=weights
)

in_features = model.classifier[2].in_features

model.classifier[2] = nn.Linear(
    in_features,
    20,
)

model = model.to(DEVICE)


# =============================================================================
# OPTIMIZATION
# =============================================================================

criterion = GentleCBFocalLoss(
    class_weights=class_weights,
    gamma=GAMMA,
)

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=LR,
    weight_decay=WEIGHT_DECAY,
)

scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
    optimizer,
    T_max=MAX_EPOCHS,
)

scaler = torch.amp.GradScaler(
    "cuda",
    enabled=AMP_ENABLED,
)


# =============================================================================
# CONFIGURATION
# =============================================================================

training_config = {
    "experiment": EXP_NAME,
    "run_role": "OFFICIAL_F03",

    "model": "torchvision.models.convnext_small",
    "pretrained_weights": str(weights),

    "train_images": len(train_dataset),
    "val_images": len(val_dataset),
    "num_classes": 20,

    "image_size": IMG_SIZE,
    "batch_size": BATCH_SIZE,

    "num_workers": NUM_WORKERS,
    "prefetch_factor": PREFETCH_FACTOR,

    "max_epochs": MAX_EPOCHS,
    "early_stopping_patience": PATIENCE,

    "optimizer": "AdamW",
    "learning_rate": LR,
    "weight_decay": WEIGHT_DECAY,

    "scheduler": "CosineAnnealingLR",
    "scheduler_t_max": MAX_EPOCHS,

    "loss": "Gentle Class-Balanced Focal Loss",
    "beta": BETA,
    "gamma": GAMMA,

    "gradient_clip_max_norm": GRAD_CLIP,

    "amp_enabled": AMP_ENABLED,

    "checkpoint_selection": "validation_macro_f1",

    "recovery_checkpoint_every": RECOVERY_EVERY,

    "cudnn_deterministic": True,
    "cudnn_benchmark": False,

    "seed": SEED,
    "gpu": torch.cuda.get_device_name(0),

    "base_paper_targets": {
        "precision": 0.9140,
        "recall": 0.8732,
        "f1": 0.8892,
        "top1": 0.9069,
        "top2": 0.9758,
        "top3": 0.9882,
    },

    "campaign_top1_target": 0.9268,

    "class_names": train_dataset.classes,
}

with open(CONFIG_PATH, "w") as f:
    json.dump(
        training_config,
        f,
        indent=4,
    )


# =============================================================================
# START
# =============================================================================

print("\n" + "=" * 145)
print("F03 — OFFICIAL ConvNeXt-Small + Gentle CB Focal")
print("=" * 145)

print(f"GPU                    : {torch.cuda.get_device_name(0)}")
print(f"Train / Val            : {len(train_dataset):,} / {len(val_dataset):,}")
print(f"Image size             : {IMG_SIZE} × {IMG_SIZE}")
print(f"Batch size             : {BATCH_SIZE}")
print(f"Train batches / epoch  : {len(train_loader)}")
print(f"Val batches / epoch    : {len(val_loader)}")
print(f"AMP                    : {AMP_ENABLED}")
print(f"Loss                   : Gentle CB Focal")
print(f"Beta / Gamma           : {BETA} / {GAMMA}")
print(f"Checkpoint selection   : Validation Macro F1")

print("\nBASE-PAPER TARGETS")
print("Precision > 91.40% | Recall > 87.32% | F1 > 88.92%")
print("Top-1 > 90.69% | Top-2 > 97.58% | Top-3 > 98.82%")
print("Campaign Top-1 target > 92.68%")

print("\n" + "-" * 145)

print(
    f"{'Ep':<5} | "
    f"{'Min':>5} | "
    f"{'TrLoss':>7} | "
    f"{'TrAcc':>7} | "
    f"{'VaLoss':>7} | "
    f"{'VTop1':>7} | "
    f"{'VTop2':>7} | "
    f"{'VTop3':>7} | "
    f"{'MacP':>7} | "
    f"{'MacR':>7} | "
    f"{'MacF1':>7} | "
    f"{'BestF1':>7} | "
    f"{'Status':<12}"
)

print("-" * 145)


# =============================================================================
# TRAINING
# =============================================================================

history = []

best_val_macro_f1 = -1.0
best_epoch = 0
best_metrics = None

epochs_without_improvement = 0

training_start = time.time()

for epoch in range(1, MAX_EPOCHS + 1):

    epoch_start = time.time()

    # -------------------------------------------------------------------------
    # TRAIN
    # -------------------------------------------------------------------------

    model.train()

    train_loss_sum = 0.0
    train_correct = 0
    train_total = 0

    for images, targets in train_loader:

        images = images.to(
            DEVICE,
            non_blocking=True,
        )

        targets = targets.to(
            DEVICE,
            non_blocking=True,
        )

        optimizer.zero_grad(
            set_to_none=True
        )

        with torch.amp.autocast(
            device_type="cuda",
            enabled=AMP_ENABLED,
        ):

            outputs = model(images)

            loss = criterion(
                outputs,
                targets,
            )

        scaler.scale(loss).backward()

        scaler.unscale_(optimizer)

        torch.nn.utils.clip_grad_norm_(
            model.parameters(),
            max_norm=GRAD_CLIP,
        )

        scaler.step(optimizer)
        scaler.update()

        train_loss_sum += (
            loss.item() * images.size(0)
        )

        predictions = outputs.argmax(dim=1)

        train_correct += (
            predictions == targets
        ).sum().item()

        train_total += targets.size(0)

    train_loss = train_loss_sum / train_total
    train_top1 = train_correct / train_total


    # -------------------------------------------------------------------------
    # VALIDATION
    # -------------------------------------------------------------------------

    model.eval()

    val_loss_sum = 0.0
    val_total = 0

    val_top2_correct = 0
    val_top3_correct = 0

    val_targets = []
    val_predictions = []

    with torch.inference_mode():

        for images, targets in val_loader:

            images = images.to(
                DEVICE,
                non_blocking=True,
            )

            targets = targets.to(
                DEVICE,
                non_blocking=True,
            )

            with torch.amp.autocast(
                device_type="cuda",
                enabled=AMP_ENABLED,
            ):

                outputs = model(images)

                loss = criterion(
                    outputs,
                    targets,
                )

            val_loss_sum += (
                loss.item() * images.size(0)
            )

            val_total += targets.size(0)

            predictions = outputs.argmax(dim=1)

            top3_predictions = outputs.topk(
                3,
                dim=1,
            ).indices

            val_top2_correct += (
                top3_predictions[:, :2]
                == targets.unsqueeze(1)
            ).any(dim=1).sum().item()

            val_top3_correct += (
                top3_predictions
                == targets.unsqueeze(1)
            ).any(dim=1).sum().item()

            val_targets.extend(
                targets.cpu().numpy()
            )

            val_predictions.extend(
                predictions.cpu().numpy()
            )

    val_loss = val_loss_sum / val_total

    val_targets_np = np.asarray(val_targets)
    val_predictions_np = np.asarray(val_predictions)

    val_top1 = np.mean(
        val_predictions_np == val_targets_np
    )

    val_top2 = (
        val_top2_correct / val_total
    )

    val_top3 = (
        val_top3_correct / val_total
    )

    (
        val_macro_precision,
        val_macro_recall,
        val_macro_f1,
        _,

    ) = precision_recall_fscore_support(
        val_targets_np,
        val_predictions_np,
        average="macro",
        zero_division=0,
    )


    # -------------------------------------------------------------------------
    # BEST CHECKPOINT
    # -------------------------------------------------------------------------

    current_lr = optimizer.param_groups[0]["lr"]

    is_best = (
        val_macro_f1 > best_val_macro_f1
    )

    if is_best:

        best_val_macro_f1 = val_macro_f1
        best_epoch = epoch

        best_metrics = {
            "val_loss": float(val_loss),

            "val_top1": float(val_top1),
            "val_top2": float(val_top2),
            "val_top3": float(val_top3),

            "val_macro_precision": float(
                val_macro_precision
            ),

            "val_macro_recall": float(
                val_macro_recall
            ),

            "val_macro_f1": float(
                val_macro_f1
            ),
        }

        epochs_without_improvement = 0

        torch.save(
            {
                "epoch": epoch,

                "model_state_dict":
                    model.state_dict(),

                "val_metrics":
                    best_metrics,

                "class_names":
                    train_dataset.classes,

                "training_config":
                    training_config,
            },

            BEST_MODEL_PATH,
        )

    else:
        epochs_without_improvement += 1


    # -------------------------------------------------------------------------
    # SCHEDULER
    # -------------------------------------------------------------------------

    scheduler.step()


    # -------------------------------------------------------------------------
    # RECOVERY CHECKPOINT EVERY 5 EPOCHS
    # -------------------------------------------------------------------------

    recovery_saved = (
        epoch % RECOVERY_EVERY == 0
    )

    if recovery_saved:

        torch.save(
            {
                "epoch": epoch,

                "model_state_dict":
                    model.state_dict(),

                "optimizer_state_dict":
                    optimizer.state_dict(),

                "scheduler_state_dict":
                    scheduler.state_dict(),

                "scaler_state_dict":
                    scaler.state_dict(),

                "best_epoch":
                    best_epoch,

                "best_val_macro_f1":
                    best_val_macro_f1,

                "epochs_without_improvement":
                    epochs_without_improvement,

                "training_config":
                    training_config,
            },

            RECOVERY_PATH,
        )


    # -------------------------------------------------------------------------
    # HISTORY
    # -------------------------------------------------------------------------

    epoch_minutes = (
        time.time() - epoch_start
    ) / 60

    history.append({
        "epoch": epoch,
        "epoch_minutes": epoch_minutes,
        "learning_rate": current_lr,

        "train_loss": train_loss,
        "train_top1": train_top1,

        "val_loss": val_loss,

        "val_top1": val_top1,
        "val_top2": val_top2,
        "val_top3": val_top3,

        "val_macro_precision": val_macro_precision,
        "val_macro_recall": val_macro_recall,
        "val_macro_f1": val_macro_f1,

        "best_val_macro_f1": best_val_macro_f1,
        "best_epoch_so_far": best_epoch,

        "is_best_checkpoint": is_best,
        "recovery_checkpoint_saved": recovery_saved,

        "epochs_without_improvement":
            epochs_without_improvement,
    })

    pd.DataFrame(history).to_csv(
        HISTORY_PATH,
        index=False,
    )


    # -------------------------------------------------------------------------
    # COMPACT OUTPUT
    # -------------------------------------------------------------------------

    if is_best and recovery_saved:
        status = "BEST + REC"
    elif is_best:
        status = "BEST SAVED"
    elif recovery_saved:
        status = "REC SAVED"
    else:
        status = (
            f"WAIT {epochs_without_improvement}/{PATIENCE}"
        )

    print(
        f"{epoch:02d}/{MAX_EPOCHS:<2} | "
        f"{epoch_minutes:5.2f} | "
        f"{train_loss:7.4f} | "
        f"{train_top1 * 100:6.2f}% | "
        f"{val_loss:7.4f} | "
        f"{val_top1 * 100:6.2f}% | "
        f"{val_top2 * 100:6.2f}% | "
        f"{val_top3 * 100:6.2f}% | "
        f"{val_macro_precision * 100:6.2f}% | "
        f"{val_macro_recall * 100:6.2f}% | "
        f"{val_macro_f1 * 100:6.2f}% | "
        f"{best_val_macro_f1 * 100:6.2f}% | "
        f"{status:<12}"
    )


    # -------------------------------------------------------------------------
    # EARLY STOPPING
    # -------------------------------------------------------------------------

    if epochs_without_improvement >= PATIENCE:

        print("-" * 145)

        print(
            f"EARLY STOPPING | "
            f"No validation Macro-F1 improvement "
            f"for {PATIENCE} consecutive epochs."
        )

        break


# =============================================================================
# FINAL SUMMARY
# =============================================================================

total_training_minutes = (
    time.time() - training_start
) / 60

print("-" * 145)

print("\n" + "=" * 110)
print("F03 STEP 3 OFFICIAL TRAINING COMPLETED")
print("=" * 110)

print(f"Epochs completed         : {len(history)}")
print(f"Best checkpoint epoch    : {best_epoch}")

print(
    f"Best Val Top-1           : "
    f"{best_metrics['val_top1'] * 100:.4f}%"
)

print(
    f"Best Val Top-2           : "
    f"{best_metrics['val_top2'] * 100:.4f}%"
)

print(
    f"Best Val Top-3           : "
    f"{best_metrics['val_top3'] * 100:.4f}%"
)

print(
    f"Best Macro Precision     : "
    f"{best_metrics['val_macro_precision'] * 100:.4f}%"
)

print(
    f"Best Macro Recall        : "
    f"{best_metrics['val_macro_recall'] * 100:.4f}%"
)

print(
    f"Best Macro F1            : "
    f"{best_metrics['val_macro_f1'] * 100:.4f}%"
)

print(
    f"Total training time      : "
    f"{total_training_minutes:.2f} min"
)

print(
    f"Average epoch time       : "
    f"{total_training_minutes / len(history):.2f} min"
)

print("\nPRESERVED FILES")

print(f"Best checkpoint          : {BEST_MODEL_PATH}")
print(f"Recovery checkpoint      : {RECOVERY_PATH}")
print(f"Training history         : {HISTORY_PATH}")
print(f"Training configuration   : {CONFIG_PATH}")

print("\nSCIENTIFIC CONTROL")

print(
    "Checkpoint selected ONLY by validation macro F1."
)

print(
    "Official test set has NOT been evaluated."
)

print("\n" + "=" * 110)

print(
    "NEXT: F03 Step 3B — "
    "IMMEDIATE BEST CHECKPOINT PRESERVATION"
)

print("=" * 110)

# F03 Step 3B — Immediate Best Checkpoint Preservation

Preserve the locked epoch-13 best validation macro-F1 checkpoint and create the F03 safety package before any analysis or official test evaluation.

In [ ]:
# F03 Step 3B — Immediate best checkpoint preservation

import hashlib
import shutil
import zipfile
from pathlib import Path

PROJECT_ROOT = Path("/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026")

EXP_NAME = "F03_CONVNEXT_SMALL_GENTLE_CB_FOCAL"
EXP_DIR = PROJECT_ROOT / "experiments" / EXP_NAME

TABLE_DIR = EXP_DIR / "tables"
WEIGHTS_DIR = EXP_DIR / "weights"

BEST_MODEL_PATH = WEIGHTS_DIR / "best_model.pth"

SAFETY_DIR = EXP_DIR / "safety_package"
SAFETY_ZIP = (
    PROJECT_ROOT
    / "F03_CONVNEXT_SMALL_GENTLE_CB_FOCAL_SAFETY_PACKAGE.zip"
)

print("=" * 90)
print("F03 Step 3B — Immediate best checkpoint preservation")
print("=" * 90)

if not BEST_MODEL_PATH.exists():
    raise FileNotFoundError(
        f"Best checkpoint not found: {BEST_MODEL_PATH}"
    )

if SAFETY_DIR.exists():
    shutil.rmtree(SAFETY_DIR)

SAFETY_DIR.mkdir(parents=True)

# -------------------------------------------------------------------------
# Preserve locked best checkpoint
# -------------------------------------------------------------------------

preserved_best = SAFETY_DIR / "best_model.pth"

shutil.copy2(
    BEST_MODEL_PATH,
    preserved_best,
)

# -------------------------------------------------------------------------
# Preserve mandatory training records
# -------------------------------------------------------------------------

required_files = [
    TABLE_DIR / "F03_training_history.csv",
    TABLE_DIR / "F03_training_config.json",
    TABLE_DIR / "F03_class_counts_and_cb_weights.csv",
    TABLE_DIR / "F03_gentle_cb_focal_config.json",
]

for src in required_files:

    if not src.exists():
        raise FileNotFoundError(
            f"Required safety file missing: {src}"
        )

    shutil.copy2(
        src,
        SAFETY_DIR / src.name,
    )

# -------------------------------------------------------------------------
# SHA-256 checkpoint fingerprint
# -------------------------------------------------------------------------

sha256 = hashlib.sha256()

with open(preserved_best, "rb") as f:

    for chunk in iter(
        lambda: f.read(1024 * 1024),
        b"",
    ):
        sha256.update(chunk)

checkpoint_sha256 = sha256.hexdigest()

with open(
    SAFETY_DIR / "F03_best_model_sha256.txt",
    "w",
) as f:

    f.write(
        f"file=best_model.pth\n"
        f"sha256={checkpoint_sha256}\n"
    )

# -------------------------------------------------------------------------
# Create safety ZIP
# -------------------------------------------------------------------------

if SAFETY_ZIP.exists():
    SAFETY_ZIP.unlink()

with zipfile.ZipFile(
    SAFETY_ZIP,
    "w",
    compression=zipfile.ZIP_DEFLATED,
) as zf:

    for file_path in sorted(
        SAFETY_DIR.iterdir()
    ):

        zf.write(
            file_path,
            arcname=file_path.name,
        )

# -------------------------------------------------------------------------
# Final preservation summary
# -------------------------------------------------------------------------

print(f"Locked checkpoint : {BEST_MODEL_PATH}")
print(f"Preserved copy    : {preserved_best}")
print(f"SHA-256           : {checkpoint_sha256}")
print(f"Safety ZIP        : {SAFETY_ZIP}")
print(
    f"ZIP size          : "
    f"{SAFETY_ZIP.stat().st_size / (1024 ** 2):.2f} MB"
)

print("\nSAFETY PACKAGE CONTENTS")

with zipfile.ZipFile(
    SAFETY_ZIP,
    "r",
) as zf:

    for name in zf.namelist():
        print(name)

print("\n" + "=" * 90)
print("F03 STEP 3B PASSED — BEST CHECKPOINT PRESERVED")
print("=" * 90)
print("Official test set has NOT been evaluated.")
print("NEXT: Download safety ZIP, then F03 Step 3C audit.")

# F03 Step 3C — Safety Package and Locked Training Audit

Audit the preserved F03 checkpoint, SHA-256 fingerprint, training history, checkpoint metadata, and locked official training configuration before validation inspection or official test evaluation.

In [ ]:
# F03 Step 3C — Safety package + locked training configuration audit

import hashlib
import json
import zipfile
from pathlib import Path

import numpy as np
import pandas as pd
import torch


PROJECT_ROOT = Path("/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026")

EXP_NAME = "F03_CONVNEXT_SMALL_GENTLE_CB_FOCAL"
EXP_DIR = PROJECT_ROOT / "experiments" / EXP_NAME

TABLE_DIR = EXP_DIR / "tables"
SAFETY_DIR = EXP_DIR / "safety_package"

SAFETY_ZIP = (
    PROJECT_ROOT
    / "F03_CONVNEXT_SMALL_GENTLE_CB_FOCAL_SAFETY_PACKAGE.zip"
)

BEST_MODEL_PATH = SAFETY_DIR / "best_model.pth"
HISTORY_PATH = SAFETY_DIR / "F03_training_history.csv"
CONFIG_PATH = SAFETY_DIR / "F03_training_config.json"
HASH_PATH = SAFETY_DIR / "F03_best_model_sha256.txt"

AUDIT_PATH = TABLE_DIR / "F03_step3c_audit_summary.csv"


print("=" * 95)
print("F03 Step 3C — Safety package + locked training configuration audit")
print("=" * 95)


# =============================================================================
# SAFETY PACKAGE CONTENTS
# =============================================================================

EXPECTED_FILES = sorted([
    "F03_best_model_sha256.txt",
    "F03_class_counts_and_cb_weights.csv",
    "F03_gentle_cb_focal_config.json",
    "F03_training_config.json",
    "F03_training_history.csv",
    "best_model.pth",
])

with zipfile.ZipFile(SAFETY_ZIP, "r") as zf:
    zip_files = sorted(zf.namelist())

assert zip_files == EXPECTED_FILES

print(f"Safety ZIP            : VERIFIED")
print(f"Package files         : {len(zip_files)}")


# =============================================================================
# SHA-256 AUDIT
# =============================================================================

with open(HASH_PATH, "r") as f:
    saved_hash = [
        line.split("=", 1)[1].strip()
        for line in f.readlines()
        if line.startswith("sha256=")
    ][0]

sha256 = hashlib.sha256()

with open(BEST_MODEL_PATH, "rb") as f:
    for chunk in iter(
        lambda: f.read(1024 * 1024),
        b"",
    ):
        sha256.update(chunk)

fresh_hash = sha256.hexdigest()

assert fresh_hash == saved_hash

print(f"Checkpoint SHA-256    : VERIFIED")
print(f"SHA-256               : {fresh_hash}")


# =============================================================================
# LOAD LOCKED RECORDS
# =============================================================================

history = pd.read_csv(HISTORY_PATH)

with open(CONFIG_PATH, "r") as f:
    config = json.load(f)

checkpoint = torch.load(
    BEST_MODEL_PATH,
    map_location="cpu",
    weights_only=False,
)


# =============================================================================
# LOCKED CONFIGURATION AUDIT
# =============================================================================

assert config["run_role"] == "OFFICIAL_F03"

assert config["train_images"] == 5247
assert config["val_images"] == 1312
assert config["num_classes"] == 20

assert config["image_size"] == 224
assert config["batch_size"] == 16

assert config["loss"] == "Gentle Class-Balanced Focal Loss"
assert config["beta"] == 0.999
assert config["gamma"] == 1.0

assert config["checkpoint_selection"] == "validation_macro_f1"

assert config["seed"] == 42

print("Training configuration : VERIFIED")


# =============================================================================
# BEST-EPOCH AUDIT
# =============================================================================

history_best_idx = history["val_macro_f1"].idxmax()

history_best = history.loc[
    history_best_idx
]

history_best_epoch = int(
    history_best["epoch"]
)

checkpoint_epoch = int(
    checkpoint["epoch"]
)

assert history_best_epoch == 13
assert checkpoint_epoch == 13

assert history_best_epoch == checkpoint_epoch

checkpoint_metrics = checkpoint["val_metrics"]

metric_pairs = {
    "val_top1": checkpoint_metrics["val_top1"],
    "val_top2": checkpoint_metrics["val_top2"],
    "val_top3": checkpoint_metrics["val_top3"],
    "val_macro_precision": checkpoint_metrics["val_macro_precision"],
    "val_macro_recall": checkpoint_metrics["val_macro_recall"],
    "val_macro_f1": checkpoint_metrics["val_macro_f1"],
}

for metric_name, checkpoint_value in metric_pairs.items():

    history_value = float(
        history_best[metric_name]
    )

    assert np.isclose(
        history_value,
        checkpoint_value,
        atol=1e-10,
    )

print("Best epoch             : VERIFIED")
print("Checkpoint metadata    : VERIFIED")
print("History/checkpoint     : MATCHED")


# =============================================================================
# CLASS AUDIT
# =============================================================================

assert len(checkpoint["class_names"]) == 20

assert (
    checkpoint["class_names"]
    ==
    config["class_names"]
)

print("20-class order         : VERIFIED")


# =============================================================================
# SAVE AUDIT SUMMARY
# =============================================================================

audit_summary = pd.DataFrame([{
    "experiment": EXP_NAME,
    "audit_status": "PASSED",
    "checkpoint_epoch": checkpoint_epoch,
    "checkpoint_sha256": fresh_hash,

    "val_top1": checkpoint_metrics["val_top1"],
    "val_top2": checkpoint_metrics["val_top2"],
    "val_top3": checkpoint_metrics["val_top3"],

    "val_macro_precision": checkpoint_metrics["val_macro_precision"],
    "val_macro_recall": checkpoint_metrics["val_macro_recall"],
    "val_macro_f1": checkpoint_metrics["val_macro_f1"],

    "train_images": config["train_images"],
    "val_images": config["val_images"],

    "batch_size": config["batch_size"],
    "beta": config["beta"],
    "gamma": config["gamma"],

    "checkpoint_selection": config["checkpoint_selection"],
    "seed": config["seed"],
}])

audit_summary.to_csv(
    AUDIT_PATH,
    index=False,
)


# =============================================================================
# FINAL AUDIT SUMMARY
# =============================================================================

print("\n" + "=" * 95)
print("LOCKED F03 CHECKPOINT")
print("=" * 95)

print(f"Best epoch             : {checkpoint_epoch}")

print(
    f"Val Top-1              : "
    f"{checkpoint_metrics['val_top1'] * 100:.4f}%"
)

print(
    f"Val Top-2              : "
    f"{checkpoint_metrics['val_top2'] * 100:.4f}%"
)

print(
    f"Val Top-3              : "
    f"{checkpoint_metrics['val_top3'] * 100:.4f}%"
)

print(
    f"Macro Precision        : "
    f"{checkpoint_metrics['val_macro_precision'] * 100:.4f}%"
)

print(
    f"Macro Recall           : "
    f"{checkpoint_metrics['val_macro_recall'] * 100:.4f}%"
)

print(
    f"Macro F1               : "
    f"{checkpoint_metrics['val_macro_f1'] * 100:.4f}%"
)

print(f"\nAudit summary          : {AUDIT_PATH}")

print("\n" + "=" * 95)
print("F03 STEP 3C PASSED — LOCKED CHECKPOINT AUDIT VERIFIED")
print("=" * 95)

print("Official test set has NOT been evaluated.")
print("NEXT: F03 Step 4 — Inspect training and locked validation checkpoint.")

# F03 Step 4 — Training Inspection and Locked Validation Confirmation

Inspect the official F03 training history and perform a fresh validation evaluation of the preserved epoch-13 checkpoint.

The official test set remains untouched.

In [ ]:
# F03 Step 4 — Inspect training + fresh locked validation confirmation

import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
import torch.nn as nn

from sklearn.metrics import precision_recall_fscore_support
from torch.utils.data import DataLoader
from torchvision import transforms
from torchvision.datasets import ImageFolder
from torchvision.models import convnext_small


# =============================================================================
# PATHS
# =============================================================================

PROJECT_ROOT = Path("/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026")
DATA_ROOT = PROJECT_ROOT / "official_imagefolder"

EXP_NAME = "F03_CONVNEXT_SMALL_GENTLE_CB_FOCAL"
EXP_DIR = PROJECT_ROOT / "experiments" / EXP_NAME

TABLE_DIR = EXP_DIR / "tables"
FIG_DIR = EXP_DIR / "figures"
SAFETY_DIR = EXP_DIR / "safety_package"

BEST_MODEL_PATH = SAFETY_DIR / "best_model.pth"
HISTORY_PATH = SAFETY_DIR / "F03_training_history.csv"
CONFIG_PATH = SAFETY_DIR / "F03_training_config.json"

VAL_METRICS_PATH = TABLE_DIR / "F03_locked_validation_metrics.csv"
BEST_SUMMARY_PATH = TABLE_DIR / "F03_best_epoch_summary.csv"
TOP_EPOCHS_PATH = TABLE_DIR / "F03_top_validation_epochs.csv"

METRIC_FIG_PATH = FIG_DIR / "F03_training_metric_curves.png"
LOSS_FIG_PATH = FIG_DIR / "F03_training_loss_curves.png"


# =============================================================================
# LOAD LOCKED RECORDS
# =============================================================================

history = pd.read_csv(HISTORY_PATH)

with open(CONFIG_PATH, "r") as f:
    config = json.load(f)

checkpoint = torch.load(
    BEST_MODEL_PATH,
    map_location="cpu",
    weights_only=False,
)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

if DEVICE.type != "cuda":
    raise RuntimeError("CUDA GPU required.")

BEST_EPOCH = int(checkpoint["epoch"])
SAVED_METRICS = checkpoint["val_metrics"]
CLASS_NAMES = checkpoint["class_names"]


# =============================================================================
# REBUILD LOCKED MODEL
# =============================================================================

model = convnext_small(weights=None)

in_features = model.classifier[2].in_features

model.classifier[2] = nn.Linear(
    in_features,
    len(CLASS_NAMES),
)

model.load_state_dict(
    checkpoint["model_state_dict"]
)

model = model.to(DEVICE)
model.eval()


# =============================================================================
# LOCKED VALIDATION DATA
# =============================================================================

IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD = [0.229, 0.224, 0.225]

val_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(
        IMAGENET_MEAN,
        IMAGENET_STD,
    ),
])

val_dataset = ImageFolder(
    DATA_ROOT / "val",
    transform=val_transform,
)

assert len(val_dataset) == 1312
assert val_dataset.classes == CLASS_NAMES

val_loader = DataLoader(
    val_dataset,
    batch_size=16,
    shuffle=False,
    num_workers=4,
    pin_memory=True,
    persistent_workers=True,
)


# =============================================================================
# FRESH LOCKED-CHECKPOINT VALIDATION
# =============================================================================

all_targets = []
all_predictions = []

top2_correct = 0
top3_correct = 0
total = 0

with torch.inference_mode():

    for images, targets in val_loader:

        images = images.to(
            DEVICE,
            non_blocking=True,
        )

        targets = targets.to(
            DEVICE,
            non_blocking=True,
        )

        with torch.amp.autocast(
            device_type="cuda",
            enabled=True,
        ):
            outputs = model(images)

        predictions = outputs.argmax(dim=1)

        top3_predictions = outputs.topk(
            3,
            dim=1,
        ).indices

        top2_correct += (
            top3_predictions[:, :2]
            == targets.unsqueeze(1)
        ).any(dim=1).sum().item()

        top3_correct += (
            top3_predictions
            == targets.unsqueeze(1)
        ).any(dim=1).sum().item()

        total += targets.size(0)

        all_targets.extend(
            targets.cpu().numpy()
        )

        all_predictions.extend(
            predictions.cpu().numpy()
        )


all_targets = np.asarray(all_targets)
all_predictions = np.asarray(all_predictions)

fresh_top1 = np.mean(
    all_targets == all_predictions
)

fresh_top2 = top2_correct / total
fresh_top3 = top3_correct / total

(
    fresh_macro_precision,
    fresh_macro_recall,
    fresh_macro_f1,
    _,

) = precision_recall_fscore_support(
    all_targets,
    all_predictions,
    average="macro",
    zero_division=0,
)


# =============================================================================
# MATCH LOCKED CHECKPOINT METRICS
# =============================================================================

fresh_metrics = {
    "val_top1": fresh_top1,
    "val_top2": fresh_top2,
    "val_top3": fresh_top3,
    "val_macro_precision": fresh_macro_precision,
    "val_macro_recall": fresh_macro_recall,
    "val_macro_f1": fresh_macro_f1,
}

for metric_name, fresh_value in fresh_metrics.items():

    assert np.isclose(
        fresh_value,
        SAVED_METRICS[metric_name],
        atol=1e-6,
    ), (
        f"{metric_name} mismatch: "
        f"{fresh_value} != {SAVED_METRICS[metric_name]}"
    )


# =============================================================================
# SAVE VALIDATION TABLES
# =============================================================================

validation_table = pd.DataFrame([{
    "experiment": EXP_NAME,
    "checkpoint_epoch": BEST_EPOCH,
    "val_top1": fresh_top1,
    "val_top2": fresh_top2,
    "val_top3": fresh_top3,
    "val_macro_precision": fresh_macro_precision,
    "val_macro_recall": fresh_macro_recall,
    "val_macro_f1": fresh_macro_f1,
    "support": total,
    "checkpoint_match": "PASSED",
}])

validation_table.to_csv(
    VAL_METRICS_PATH,
    index=False,
)

best_row = history.loc[
    history["epoch"] == BEST_EPOCH
].copy()

best_row.to_csv(
    BEST_SUMMARY_PATH,
    index=False,
)

top_epochs = (
    history
    .sort_values(
        "val_macro_f1",
        ascending=False,
    )
    .head(5)
    [[
        "epoch",
        "val_top1",
        "val_top2",
        "val_top3",
        "val_macro_precision",
        "val_macro_recall",
        "val_macro_f1",
    ]]
)

top_epochs.to_csv(
    TOP_EPOCHS_PATH,
    index=False,
)


# =============================================================================
# TRAINING FIGURES
# =============================================================================

plt.figure(figsize=(10, 6))

plt.plot(
    history["epoch"],
    history["train_top1"] * 100,
    label="Train Top-1",
)

plt.plot(
    history["epoch"],
    history["val_top1"] * 100,
    label="Val Top-1",
)

plt.plot(
    history["epoch"],
    history["val_macro_f1"] * 100,
    label="Val Macro F1",
)

plt.axvline(
    BEST_EPOCH,
    linestyle="--",
    label=f"Best Epoch {BEST_EPOCH}",
)

plt.xlabel("Epoch")
plt.ylabel("Score (%)")
plt.title("F03 Training and Validation Metrics")
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()

plt.savefig(
    METRIC_FIG_PATH,
    dpi=300,
    bbox_inches="tight",
)

plt.close()


plt.figure(figsize=(10, 6))

plt.plot(
    history["epoch"],
    history["train_loss"],
    label="Train Loss",
)

plt.plot(
    history["epoch"],
    history["val_loss"],
    label="Validation Loss",
)

plt.axvline(
    BEST_EPOCH,
    linestyle="--",
    label=f"Best Epoch {BEST_EPOCH}",
)

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("F03 Training and Validation Loss")
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()

plt.savefig(
    LOSS_FIG_PATH,
    dpi=300,
    bbox_inches="tight",
)

plt.close()


# =============================================================================
# BASE-PAPER NUMERIC TARGET COMPARISON
# =============================================================================

base_targets = {
    "Precision": 0.9140,
    "Recall": 0.8732,
    "F1": 0.8892,
    "Top-1": 0.9069,
    "Top-2": 0.9758,
    "Top-3": 0.9882,
}

f03_values = {
    "Precision": fresh_macro_precision,
    "Recall": fresh_macro_recall,
    "F1": fresh_macro_f1,
    "Top-1": fresh_top1,
    "Top-2": fresh_top2,
    "Top-3": fresh_top3,
}

comparison_rows = []

for metric in base_targets:

    comparison_rows.append({
        "metric": metric,
        "base_paper": base_targets[metric],
        "f03_validation": f03_values[metric],
        "difference_pp": (
            f03_values[metric]
            - base_targets[metric]
        ) * 100,
        "numeric_target_exceeded": (
            f03_values[metric]
            > base_targets[metric]
        ),
    })

comparison_table = pd.DataFrame(
    comparison_rows
)

comparison_table.to_csv(
    TABLE_DIR / "F03_validation_vs_base_targets.csv",
    index=False,
)


# =============================================================================
# FINAL SUMMARY
# =============================================================================

print("=" * 100)
print("F03 Step 4 — Training inspection + locked validation confirmation")
print("=" * 100)

print(f"Best checkpoint epoch : {BEST_EPOCH}")
print(f"Validation support     : {total}")

print("\nFRESH LOCKED-CHECKPOINT VALIDATION")

print(
    f"Top-1                  : "
    f"{fresh_top1 * 100:.4f}%"
)

print(
    f"Top-2                  : "
    f"{fresh_top2 * 100:.4f}%"
)

print(
    f"Top-3                  : "
    f"{fresh_top3 * 100:.4f}%"
)

print(
    f"Macro Precision        : "
    f"{fresh_macro_precision * 100:.4f}%"
)

print(
    f"Macro Recall           : "
    f"{fresh_macro_recall * 100:.4f}%"
)

print(
    f"Macro F1               : "
    f"{fresh_macro_f1 * 100:.4f}%"
)

print("\nCheckpoint Match       : PASSED")

print("\nTOP 5 VALIDATION MACRO-F1 EPOCHS")
print(
    top_epochs.to_string(
        index=False,
        formatters={
            "val_top1": lambda x: f"{x * 100:.4f}%",
            "val_top2": lambda x: f"{x * 100:.4f}%",
            "val_top3": lambda x: f"{x * 100:.4f}%",
            "val_macro_precision": lambda x: f"{x * 100:.4f}%",
            "val_macro_recall": lambda x: f"{x * 100:.4f}%",
            "val_macro_f1": lambda x: f"{x * 100:.4f}%",
        },
    )
)

print("\nVALIDATION VS BASE-PAPER NUMERIC TARGETS")
print(
    comparison_table.to_string(
        index=False,
        formatters={
            "base_paper": lambda x: f"{x * 100:.2f}%",
            "f03_validation": lambda x: f"{x * 100:.4f}%",
            "difference_pp": lambda x: f"{x:+.4f} pp",
        },
    )
)

print("\nSaved figures:")
print(METRIC_FIG_PATH)
print(LOSS_FIG_PATH)

print("\nOfficial test set has NOT been evaluated.")

print("\n" + "=" * 100)
print("F03 STEP 4 PASSED — LOCKED VALIDATION CHECKPOINT CONFIRMED")
print("=" * 100)
print("NEXT: F03 Step 5 — Official unchanged test evaluation")

# F03 Step 5 — Official Unchanged Test Evaluation

Evaluate the preserved epoch-13 F03 checkpoint once on the unchanged official AQUA20 test split.

Report Top-1, Top-2, Top-3, Top-5, macro and weighted classification metrics, per-class behaviour, predictions, and confusion matrices.

In [ ]:
# F03 Step 5 — Official unchanged test evaluation

import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    precision_recall_fscore_support,
)

from torch.utils.data import DataLoader
from torchvision import transforms
from torchvision.datasets import ImageFolder
from torchvision.models import convnext_small


# =============================================================================
# PATHS
# =============================================================================

PROJECT_ROOT = Path("/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026")
DATA_ROOT = PROJECT_ROOT / "official_imagefolder"

EXP_NAME = "F03_CONVNEXT_SMALL_GENTLE_CB_FOCAL"
EXP_DIR = PROJECT_ROOT / "experiments" / EXP_NAME

TABLE_DIR = EXP_DIR / "tables"
FIG_DIR = EXP_DIR / "figures"
SAFETY_DIR = EXP_DIR / "safety_package"

BEST_MODEL_PATH = SAFETY_DIR / "best_model.pth"
CONFIG_PATH = SAFETY_DIR / "F03_training_config.json"
WEIGHT_TABLE_PATH = SAFETY_DIR / "F03_class_counts_and_cb_weights.csv"

TEST_SUMMARY_PATH = TABLE_DIR / "F03_test_metrics_summary.csv"
REPORT_PATH = TABLE_DIR / "F03_classification_report.csv"
PREDICTIONS_PATH = TABLE_DIR / "F03_test_predictions.csv"

CM_PATH = TABLE_DIR / "F03_confusion_matrix.csv"
CM_NORM_PATH = TABLE_DIR / "F03_confusion_matrix_normalized.csv"

COMPARISON_PATH = TABLE_DIR / "F03_test_vs_base_targets.csv"

CM_FIG_PATH = FIG_DIR / "F03_confusion_matrix.png"
CM_NORM_FIG_PATH = FIG_DIR / "F03_confusion_matrix_normalized.png"


# =============================================================================
# LOAD LOCKED CHECKPOINT + CONFIG
# =============================================================================

DEVICE = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

if DEVICE.type != "cuda":
    raise RuntimeError("CUDA GPU required.")

checkpoint = torch.load(
    BEST_MODEL_PATH,
    map_location="cpu",
    weights_only=False,
)

with open(CONFIG_PATH, "r") as f:
    config = json.load(f)

CLASS_NAMES = checkpoint["class_names"]
BEST_EPOCH = int(checkpoint["epoch"])

assert BEST_EPOCH == 13
assert len(CLASS_NAMES) == 20


# =============================================================================
# TEST DATA — UNCHANGED OFFICIAL SPLIT
# =============================================================================

IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD = [0.229, 0.224, 0.225]

test_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(
        IMAGENET_MEAN,
        IMAGENET_STD,
    ),
])

test_dataset = ImageFolder(
    DATA_ROOT / "test",
    transform=test_transform,
)

assert len(test_dataset) == 1612
assert test_dataset.classes == CLASS_NAMES

test_loader = DataLoader(
    test_dataset,
    batch_size=16,
    shuffle=False,
    num_workers=4,
    pin_memory=True,
    persistent_workers=True,
)


# =============================================================================
# MODEL
# =============================================================================

model = convnext_small(weights=None)

in_features = model.classifier[2].in_features

model.classifier[2] = nn.Linear(
    in_features,
    len(CLASS_NAMES),
)

model.load_state_dict(
    checkpoint["model_state_dict"]
)

model = model.to(DEVICE)
model.eval()


# =============================================================================
# LOCKED GENTLE CB FOCAL LOSS
# =============================================================================

weight_table = pd.read_csv(
    WEIGHT_TABLE_PATH
)

class_weights = torch.tensor(
    weight_table["cb_weight"].values,
    dtype=torch.float32,
    device=DEVICE,
)


class GentleCBFocalLoss(nn.Module):

    def __init__(self, class_weights, gamma=1.0):
        super().__init__()

        self.register_buffer(
            "class_weights",
            class_weights.clone().detach(),
        )

        self.gamma = gamma

    def forward(self, logits, targets):

        ce_loss = F.cross_entropy(
            logits,
            targets,
            weight=self.class_weights,
            reduction="none",
        )

        probabilities = torch.softmax(
            logits,
            dim=1,
        )

        pt = probabilities.gather(
            1,
            targets.unsqueeze(1),
        ).squeeze(1)

        focal_factor = (
            1.0 - pt
        ).pow(self.gamma)

        return (
            focal_factor * ce_loss
        ).mean()


criterion = GentleCBFocalLoss(
    class_weights=class_weights,
    gamma=float(config["gamma"]),
)


# =============================================================================
# OFFICIAL TEST EVALUATION
# =============================================================================

print("=" * 100)
print("F03 Step 5 — Official unchanged AQUA20 test evaluation")
print("=" * 100)

print(f"Checkpoint epoch : {BEST_EPOCH}")
print(f"Test images      : {len(test_dataset)}")
print(f"Classes          : {len(CLASS_NAMES)}")
print("Test split       : OFFICIAL UNCHANGED")

all_targets = []
all_predictions = []
all_confidences = []
all_top5_indices = []
all_top5_scores = []

test_loss_sum = 0.0
total = 0

top2_correct = 0
top3_correct = 0
top5_correct = 0


with torch.inference_mode():

    for images, targets in test_loader:

        images = images.to(
            DEVICE,
            non_blocking=True,
        )

        targets = targets.to(
            DEVICE,
            non_blocking=True,
        )

        with torch.amp.autocast(
            device_type="cuda",
            enabled=True,
        ):

            outputs = model(images)

            loss = criterion(
                outputs,
                targets,
            )

        probabilities = torch.softmax(
            outputs,
            dim=1,
        )

        predictions = outputs.argmax(
            dim=1
        )

        confidences = probabilities.max(
            dim=1
        ).values

        top5_scores, top5_indices = probabilities.topk(
            5,
            dim=1,
        )

        top2_correct += (
            top5_indices[:, :2]
            == targets.unsqueeze(1)
        ).any(dim=1).sum().item()

        top3_correct += (
            top5_indices[:, :3]
            == targets.unsqueeze(1)
        ).any(dim=1).sum().item()

        top5_correct += (
            top5_indices
            == targets.unsqueeze(1)
        ).any(dim=1).sum().item()

        test_loss_sum += (
            loss.item() * images.size(0)
        )

        total += targets.size(0)

        all_targets.extend(
            targets.cpu().numpy()
        )

        all_predictions.extend(
            predictions.cpu().numpy()
        )

        all_confidences.extend(
            confidences.cpu().numpy()
        )

        all_top5_indices.extend(
            top5_indices.cpu().numpy()
        )

        all_top5_scores.extend(
            top5_scores.cpu().numpy()
        )


all_targets = np.asarray(all_targets)
all_predictions = np.asarray(all_predictions)
all_confidences = np.asarray(all_confidences)

all_top5_indices = np.asarray(all_top5_indices)
all_top5_scores = np.asarray(all_top5_scores)

test_loss = test_loss_sum / total

test_top1 = np.mean(
    all_targets == all_predictions
)

test_top2 = top2_correct / total
test_top3 = top3_correct / total
test_top5 = top5_correct / total


# =============================================================================
# MACRO + WEIGHTED METRICS
# =============================================================================

(
    macro_precision,
    macro_recall,
    macro_f1,
    _,

) = precision_recall_fscore_support(
    all_targets,
    all_predictions,
    average="macro",
    zero_division=0,
)

(
    weighted_precision,
    weighted_recall,
    weighted_f1,
    _,

) = precision_recall_fscore_support(
    all_targets,
    all_predictions,
    average="weighted",
    zero_division=0,
)


# =============================================================================
# CLASSIFICATION REPORT
# =============================================================================

report = classification_report(
    all_targets,
    all_predictions,
    labels=list(range(len(CLASS_NAMES))),
    target_names=CLASS_NAMES,
    output_dict=True,
    zero_division=0,
)

report_df = pd.DataFrame(
    report
).transpose()

report_df.to_csv(
    REPORT_PATH
)


# =============================================================================
# TEST PREDICTIONS
# =============================================================================

prediction_rows = []

for idx, (
    sample,
    true_id,
    pred_id,
    confidence,
    top5_ids,
    top5_scores,
) in enumerate(zip(
    test_dataset.samples,
    all_targets,
    all_predictions,
    all_confidences,
    all_top5_indices,
    all_top5_scores,
)):

    image_path = Path(sample[0])

    prediction_rows.append({
        "sample_index": idx,
        "image_path": str(
            image_path.relative_to(
                DATA_ROOT / "test"
            )
        ),

        "true_id": int(true_id),
        "true_class": CLASS_NAMES[int(true_id)],

        "pred_id": int(pred_id),
        "pred_class": CLASS_NAMES[int(pred_id)],

        "top1_confidence": float(confidence),

        "correct": bool(
            true_id == pred_id
        ),

        "top5_classes": " | ".join(
            CLASS_NAMES[int(class_id)]
            for class_id in top5_ids
        ),

        "top5_scores": " | ".join(
            f"{float(score):.8f}"
            for score in top5_scores
        ),
    })


predictions_df = pd.DataFrame(
    prediction_rows
)

predictions_df.to_csv(
    PREDICTIONS_PATH,
    index=False,
)


# =============================================================================
# CONFUSION MATRICES
# =============================================================================

cm = confusion_matrix(
    all_targets,
    all_predictions,
    labels=list(range(len(CLASS_NAMES))),
)

cm_norm = confusion_matrix(
    all_targets,
    all_predictions,
    labels=list(range(len(CLASS_NAMES))),
    normalize="true",
)

pd.DataFrame(
    cm,
    index=CLASS_NAMES,
    columns=CLASS_NAMES,
).to_csv(
    CM_PATH
)

pd.DataFrame(
    cm_norm,
    index=CLASS_NAMES,
    columns=CLASS_NAMES,
).to_csv(
    CM_NORM_PATH
)


# =============================================================================
# CONFUSION MATRIX FIGURES
# =============================================================================

plt.figure(figsize=(16, 14))

plt.imshow(cm)

plt.xticks(
    range(len(CLASS_NAMES)),
    CLASS_NAMES,
    rotation=90,
    fontsize=7,
)

plt.yticks(
    range(len(CLASS_NAMES)),
    CLASS_NAMES,
    fontsize=7,
)

plt.xlabel("Predicted Class")
plt.ylabel("True Class")

plt.title(
    "F03 Official Test Confusion Matrix"
)

plt.colorbar()
plt.tight_layout()

plt.savefig(
    CM_FIG_PATH,
    dpi=300,
    bbox_inches="tight",
)

plt.close()


plt.figure(figsize=(16, 14))

plt.imshow(cm_norm)

plt.xticks(
    range(len(CLASS_NAMES)),
    CLASS_NAMES,
    rotation=90,
    fontsize=7,
)

plt.yticks(
    range(len(CLASS_NAMES)),
    CLASS_NAMES,
    fontsize=7,
)

plt.xlabel("Predicted Class")
plt.ylabel("True Class")

plt.title(
    "F03 Official Test Normalized Confusion Matrix"
)

plt.colorbar()
plt.tight_layout()

plt.savefig(
    CM_NORM_FIG_PATH,
    dpi=300,
    bbox_inches="tight",
)

plt.close()


# =============================================================================
# TEST SUMMARY
# =============================================================================

test_summary = pd.DataFrame([{
    "experiment": "F03",

    "model": "ConvNeXt-Small",

    "train_strategy":
        "Original + Gentle CB Focal",

    "checkpoint_epoch": BEST_EPOCH,

    "test_loss": test_loss,

    "test_top1": test_top1,
    "test_top2": test_top2,
    "test_top3": test_top3,
    "test_top5": test_top5,

    "macro_precision": macro_precision,
    "macro_recall": macro_recall,
    "macro_f1": macro_f1,

    "weighted_precision": weighted_precision,
    "weighted_recall": weighted_recall,
    "weighted_f1": weighted_f1,

    "support": total,
}])

test_summary.to_csv(
    TEST_SUMMARY_PATH,
    index=False,
)


# =============================================================================
# NUMERIC TARGET COMPARISON
# =============================================================================

base_targets = {
    "Precision": 0.9140,
    "Recall": 0.8732,
    "F1": 0.8892,
    "Top-1": 0.9069,
    "Top-2": 0.9758,
    "Top-3": 0.9882,
}

f03_test_values = {
    "Precision": macro_precision,
    "Recall": macro_recall,
    "F1": macro_f1,
    "Top-1": test_top1,
    "Top-2": test_top2,
    "Top-3": test_top3,
}

comparison_rows = []

for metric in base_targets:

    comparison_rows.append({
        "metric": metric,

        "base_paper":
            base_targets[metric],

        "f03_test":
            f03_test_values[metric],

        "difference_pp": (
            f03_test_values[metric]
            - base_targets[metric]
        ) * 100,

        "numeric_target_exceeded": (
            f03_test_values[metric]
            > base_targets[metric]
        ),
    })


comparison_table = pd.DataFrame(
    comparison_rows
)

comparison_table.to_csv(
    COMPARISON_PATH,
    index=False,
)


# =============================================================================
# IMPORTANT MINORITY CLASSES
# =============================================================================

minority_classes = [
    "01_crab",
    "03_eel",
    "06_flatworm",
    "08_marine_dolphin",
    "09_octopus",
    "12_seaCucumber",
    "15_shark",
    "16_shrimp",
]

minority_table = report_df.loc[
    minority_classes,
    [
        "precision",
        "recall",
        "f1-score",
        "support",
    ],
].copy()


# =============================================================================
# FINAL OUTPUT
# =============================================================================

print("\n" + "=" * 100)
print("OFFICIAL F03 TEST RESULT")
print("=" * 100)

print(f"Test Loss              : {test_loss:.6f}")

print(f"Test Top-1             : {test_top1 * 100:.4f}%")
print(f"Test Top-2             : {test_top2 * 100:.4f}%")
print(f"Test Top-3             : {test_top3 * 100:.4f}%")
print(f"Test Top-5             : {test_top5 * 100:.4f}%")

print(f"Macro Precision        : {macro_precision * 100:.4f}%")
print(f"Macro Recall           : {macro_recall * 100:.4f}%")
print(f"Macro F1               : {macro_f1 * 100:.4f}%")

print(f"Weighted Precision     : {weighted_precision * 100:.4f}%")
print(f"Weighted Recall        : {weighted_recall * 100:.4f}%")
print(f"Weighted F1            : {weighted_f1 * 100:.4f}%")

print(f"Support                : {total}")


print("\nTEST VS BASE-PAPER NUMERIC TARGETS")

print(
    comparison_table.to_string(
        index=False,
        formatters={
            "base_paper":
                lambda x: f"{x * 100:.2f}%",

            "f03_test":
                lambda x: f"{x * 100:.4f}%",

            "difference_pp":
                lambda x: f"{x:+.4f} pp",
        },
    )
)


print("\nIMPORTANT MINORITY-CLASS TEST BEHAVIOUR")

print(
    minority_table.to_string(
        formatters={
            "precision":
                lambda x: f"{x * 100:.2f}%",

            "recall":
                lambda x: f"{x * 100:.2f}%",

            "f1-score":
                lambda x: f"{x * 100:.2f}%",

            "support":
                lambda x: f"{int(x)}",
        },
    )
)


print("\nSAVED OUTPUTS")

print(TEST_SUMMARY_PATH)
print(REPORT_PATH)
print(PREDICTIONS_PATH)
print(CM_PATH)
print(CM_NORM_PATH)
print(COMPARISON_PATH)
print(CM_FIG_PATH)
print(CM_NORM_FIG_PATH)


print("\n" + "=" * 100)
print("F03 STEP 5 PASSED — OFFICIAL TEST EVALUATION COMPLETED")
print("=" * 100)

print(
    "NEXT: F03 Step 6 — Create official final F03 package"
)

# F03 Step 6 — Create Official Final Experiment Package

Create the official final F03 package containing the locked best checkpoint, checkpoint fingerprint, training records, validation audit, official test metrics, per-class results, predictions, confusion matrices, and comparison-ready summary.

In [ ]:
# F03 Step 6 — Create official final F03 package

import json
import shutil
import zipfile
from pathlib import Path

import pandas as pd


# =============================================================================
# PATHS
# =============================================================================

PROJECT_ROOT = Path("/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026")

EXP_NAME = "F03_CONVNEXT_SMALL_GENTLE_CB_FOCAL"
EXP_DIR = PROJECT_ROOT / "experiments" / EXP_NAME

TABLE_DIR = EXP_DIR / "tables"
FIG_DIR = EXP_DIR / "figures"
SAFETY_DIR = EXP_DIR / "safety_package"

FINAL_STAGE_DIR = EXP_DIR / "final_package_stage"

FINAL_ZIP = (
    PROJECT_ROOT
    / "aqua20_f03_convnext_small_gentle_cb_focal_outputs.zip"
)

README_PATH = FINAL_STAGE_DIR / "README_F03.txt"

COMPARISON_SUMMARY_PATH = (
    TABLE_DIR / "F03_comparison_ready_summary.csv"
)


# =============================================================================
# LOAD OFFICIAL F03 RESULT
# =============================================================================

test_summary = pd.read_csv(
    TABLE_DIR / "F03_test_metrics_summary.csv"
)

validation_summary = pd.read_csv(
    TABLE_DIR / "F03_locked_validation_metrics.csv"
)

audit_summary = pd.read_csv(
    TABLE_DIR / "F03_step3c_audit_summary.csv"
)

test_row = test_summary.iloc[0]
val_row = validation_summary.iloc[0]
audit_row = audit_summary.iloc[0]


# =============================================================================
# CREATE COMPARISON-READY SUMMARY
# =============================================================================

comparison_summary = pd.DataFrame([{
    "experiment": "F03",

    "experiment_name":
        EXP_NAME,

    "model":
        "ConvNeXt-Small",

    "train_strategy":
        "Original + Gentle CB Focal",

    "scientific_group":
        "G3_loss_level_imbalance_intervention",

    "train_images":
        5247,

    "val_images":
        1312,

    "test_images":
        1612,

    "checkpoint_epoch":
        int(test_row["checkpoint_epoch"]),

    "val_top1":
        float(val_row["val_top1"]),

    "val_top2":
        float(val_row["val_top2"]),

    "val_top3":
        float(val_row["val_top3"]),

    "val_macro_precision":
        float(val_row["val_macro_precision"]),

    "val_macro_recall":
        float(val_row["val_macro_recall"]),

    "val_macro_f1":
        float(val_row["val_macro_f1"]),

    "test_top1":
        float(test_row["test_top1"]),

    "test_top2":
        float(test_row["test_top2"]),

    "test_top3":
        float(test_row["test_top3"]),

    "test_top5":
        float(test_row["test_top5"]),

    "macro_precision":
        float(test_row["macro_precision"]),

    "macro_recall":
        float(test_row["macro_recall"]),

    "macro_f1":
        float(test_row["macro_f1"]),

    "weighted_precision":
        float(test_row["weighted_precision"]),

    "weighted_recall":
        float(test_row["weighted_recall"]),

    "weighted_f1":
        float(test_row["weighted_f1"]),

    "checkpoint_sha256":
        audit_row["checkpoint_sha256"],

    "base_convnext_top1_exceeded":
        float(test_row["test_top1"]) > 0.9069,

    "base_convnext_top2_exceeded":
        float(test_row["test_top2"]) > 0.9758,

    "base_convnext_top3_exceeded":
        float(test_row["test_top3"]) > 0.9882,

    "base_precision_numeric_target_exceeded":
        float(test_row["macro_precision"]) > 0.9140,

    "base_recall_numeric_target_exceeded":
        float(test_row["macro_recall"]) > 0.8732,

    "base_f1_numeric_target_exceeded":
        float(test_row["macro_f1"]) > 0.8892,

    "campaign_top1_9268_exceeded":
        float(test_row["test_top1"]) > 0.9268,
}])

comparison_summary.to_csv(
    COMPARISON_SUMMARY_PATH,
    index=False,
)


# =============================================================================
# CLEAN FINAL STAGING DIRECTORY
# =============================================================================

if FINAL_STAGE_DIR.exists():
    shutil.rmtree(FINAL_STAGE_DIR)

FINAL_STAGE_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

(FINAL_STAGE_DIR / "tables").mkdir()
(FINAL_STAGE_DIR / "figures").mkdir()
(FINAL_STAGE_DIR / "weights").mkdir()


# =============================================================================
# COPY TABLES
# =============================================================================

for file_path in sorted(TABLE_DIR.iterdir()):

    if file_path.is_file():

        shutil.copy2(
            file_path,
            FINAL_STAGE_DIR
            / "tables"
            / file_path.name,
        )


# =============================================================================
# COPY FIGURES
# =============================================================================

for file_path in sorted(FIG_DIR.iterdir()):

    if file_path.is_file():

        shutil.copy2(
            file_path,
            FINAL_STAGE_DIR
            / "figures"
            / file_path.name,
        )


# =============================================================================
# COPY LOCKED CHECKPOINT + FINGERPRINT
# =============================================================================

shutil.copy2(
    SAFETY_DIR / "best_model.pth",
    FINAL_STAGE_DIR
    / "weights"
    / "best_model.pth",
)

shutil.copy2(
    SAFETY_DIR / "F03_best_model_sha256.txt",
    FINAL_STAGE_DIR
    / "weights"
    / "F03_best_model_sha256.txt",
)


# =============================================================================
# README
# =============================================================================

readme_text = f"""
AQUA20 F03 OFFICIAL EXPERIMENT PACKAGE
======================================

Experiment
----------
F03_CONVNEXT_SMALL_GENTLE_CB_FOCAL

Scientific group
----------------
G3 — Loss-level imbalance intervention

Method
------
ConvNeXt-Small
ImageNet pretrained weights
Original AQUA20 train split
Gentle Class-Balanced Focal Loss

Training data
-------------
Train : 5,247
Val   : 1,312
Test  : 1,612
Classes: 20

Loss configuration
------------------
Beta  : 0.999
Gamma : 1.0
Class weighting: Effective-number class-balanced weighting
Weight normalization: Mean = 1

Checkpoint selection
--------------------
Validation Macro F1 only

Locked best checkpoint
----------------------
Epoch : 13
SHA-256:
928c8af60aef70537263e2c8cc1cf13782747bc5974f86ff054fbe352065c26f

Locked validation result
------------------------
Top-1          : 92.5305%
Top-2          : 97.6372%
Top-3          : 99.4665%
Macro Precision: 87.9929%
Macro Recall   : 92.6189%
Macro F1       : 89.3301%

Official unchanged test result
------------------------------
Top-1             : 91.6253%
Top-2             : 97.7047%
Top-3             : 99.1315%
Top-5             : 99.6898%

Macro Precision   : 90.7850%
Macro Recall      : 86.9302%
Macro F1          : 87.9645%

Weighted Precision: 91.8777%
Weighted Recall   : 91.6253%
Weighted F1       : 91.5656%

Support            : 1,612

Base-paper numeric comparison
-----------------------------
Top-1 : exceeded
Top-2 : exceeded
Top-3 : exceeded

Precision numeric target : not exceeded
Recall numeric target    : not exceeded
F1 numeric target        : not exceeded

Campaign Top-1 target
---------------------
Target : 92.68%
F03    : 91.6253%
Status : not exceeded

Important minority-class observation
------------------------------------
Flatworm test recall:

F01 Aug-200 YOLO26m : 15.38%
F02 Aug-200 YOLO26s : 23.08%
F03 Gentle CB Focal : 76.92%

Interpretation
--------------
Gentle Class-Balanced Focal Loss substantially reduced the severe
minority-class under-recognition observed in the data-level Aug-200
experiments.

F03 exceeded the base-paper ConvNeXt numeric Top-1, Top-2 and Top-3
results, but did not exceed all precision, recall and F1 numeric targets.

F03 is therefore retained as the official G3 loss-level intervention,
not as the final campaign-winning model.

Official test protocol
----------------------
The unchanged 1,612-image AQUA20 test split was evaluated only after
the best validation Macro-F1 checkpoint was locked and preserved.
""".strip()

README_PATH.write_text(
    readme_text,
    encoding="utf-8",
)


# =============================================================================
# CREATE FINAL ZIP
# =============================================================================

if FINAL_ZIP.exists():
    FINAL_ZIP.unlink()

with zipfile.ZipFile(
    FINAL_ZIP,
    "w",
    compression=zipfile.ZIP_DEFLATED,
) as zf:

    for file_path in sorted(
        FINAL_STAGE_DIR.rglob("*")
    ):

        if file_path.is_file():

            zf.write(
                file_path,
                arcname=str(
                    file_path.relative_to(
                        FINAL_STAGE_DIR
                    )
                ),
            )


# =============================================================================
# FINAL PACKAGE AUDIT
# =============================================================================

required_package_files = [
    "README_F03.txt",

    "weights/best_model.pth",
    "weights/F03_best_model_sha256.txt",

    "tables/F03_training_history.csv",
    "tables/F03_training_config.json",

    "tables/F03_class_counts_and_cb_weights.csv",
    "tables/F03_gentle_cb_focal_config.json",

    "tables/F03_step3c_audit_summary.csv",

    "tables/F03_locked_validation_metrics.csv",
    "tables/F03_best_epoch_summary.csv",

    "tables/F03_test_metrics_summary.csv",
    "tables/F03_classification_report.csv",
    "tables/F03_test_predictions.csv",

    "tables/F03_confusion_matrix.csv",
    "tables/F03_confusion_matrix_normalized.csv",

    "tables/F03_test_vs_base_targets.csv",
    "tables/F03_comparison_ready_summary.csv",

    "figures/F03_training_metric_curves.png",
    "figures/F03_training_loss_curves.png",

    "figures/F03_confusion_matrix.png",
    "figures/F03_confusion_matrix_normalized.png",
]

with zipfile.ZipFile(
    FINAL_ZIP,
    "r",
) as zf:

    package_files = sorted(
        zf.namelist()
    )

for required_file in required_package_files:

    assert required_file in package_files, (
        f"Missing final package file: "
        f"{required_file}"
    )


# =============================================================================
# FINAL OUTPUT
# =============================================================================

print("=" * 100)
print("F03 Step 6 — Create official final experiment package")
print("=" * 100)

print(f"Final package : {FINAL_ZIP}")

print(
    f"ZIP size      : "
    f"{FINAL_ZIP.stat().st_size / (1024 ** 2):.2f} MB"
)

print("\nPACKAGE CONTENTS")

for name in package_files:
    print(name)

print("\n" + "=" * 100)
print("F03 STEP 6 PASSED — OFFICIAL FINAL PACKAGE CREATED")
print("=" * 100)

print("F03 STATUS : COMPLETED")
print(f"DOWNLOAD   : {FINAL_ZIP}")

# F04 Step 1 — Environment and Aug-200 Dataset Verification

Verify the Kaggle environment, locked Aug-200 training dataset, unchanged validation/test splits, stable AQUA20 class order, and ConvNeXt-Small 20-class model availability.

No training is performed in this step.

In [11]:
# F04 Step 1 — Corrected Environment and Aug-200 Dataset Verification

import sys
from pathlib import Path

import torch
import torchvision
from torchvision import datasets
from torchvision.models import convnext_small, ConvNeXt_Small_Weights

SEED = 42

PROJECT_ROOT = Path(
    "/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026"
)

ORIGINAL_DATA_ROOT = PROJECT_ROOT / "official_imagefolder"

AUG200_DATA_ROOT = (
    PROJECT_ROOT / "balanced_train" / "aug200_imagefolder"
)

AUG200_TRAIN_ROOT = AUG200_DATA_ROOT / "train"
ORIGINAL_VAL_ROOT = ORIGINAL_DATA_ROOT / "val"
ORIGINAL_TEST_ROOT = ORIGINAL_DATA_ROOT / "test"

EXP_NAME = "F04_CONVNEXT_SMALL_AUG200"

EXP_DIR = PROJECT_ROOT / "experiments" / EXP_NAME
TABLE_DIR = EXP_DIR / "tables"
FIG_DIR = EXP_DIR / "figures"
WEIGHTS_DIR = EXP_DIR / "weights"

print("=" * 80)
print("F04 Step 1 — Environment and Aug-200 Dataset Verification")
print("=" * 80)

print(f"Python      : {sys.version.split()[0]}")
print(f"Torch       : {torch.__version__}")
print(f"Torchvision : {torchvision.__version__}")
print(f"CUDA        : {torch.cuda.is_available()}")

if torch.cuda.is_available():
    print(f"GPU         : {torch.cuda.get_device_name(0)}")

print("\n" + "=" * 80)
print("DATASET VERIFICATION")
print("=" * 80)

train_ds = datasets.ImageFolder(AUG200_TRAIN_ROOT)
val_ds = datasets.ImageFolder(ORIGINAL_VAL_ROOT)
test_ds = datasets.ImageFolder(ORIGINAL_TEST_ROOT)

print(f"Aug-200 train : {len(train_ds):,}")
print(f"Original val  : {len(val_ds):,}")
print(f"Original test : {len(test_ds):,}")
print(f"Classes       : {len(train_ds.classes)}")

assert len(train_ds) == 7284
assert len(val_ds) == 1312
assert len(test_ds) == 1612

assert len(train_ds.classes) == 20
assert train_ds.classes == val_ds.classes == test_ds.classes

print("\nStable class order:")
for i, class_name in enumerate(train_ds.classes):
    print(f"{i:02d} -> {class_name}")

print("\n" + "=" * 80)
print("CONVNEXT-SMALL VERIFICATION")
print("=" * 80)

model = convnext_small(
    weights=ConvNeXt_Small_Weights.DEFAULT
)

in_features = model.classifier[2].in_features
model.classifier[2] = torch.nn.Linear(in_features, 20)

print(f"Classifier input features : {in_features}")
print(f"Classifier output classes : {model.classifier[2].out_features}")

assert model.classifier[2].out_features == 20

print("\n" + "=" * 80)
print("F04 STEP 1 PASSED")
print("=" * 80)

print("Aug-200 train : VERIFIED")
print("Original val  : VERIFIED")
print("Original test : VERIFIED")
print("Class order   : VERIFIED")
print("ConvNeXt-S    : VERIFIED")

================================================================================
F04 Step 1 — Environment and Aug-200 Dataset Verification
================================================================================
Python      : 3.12.13
Torch       : 2.7.1+cu118
Torchvision : 0.22.1+cu118
CUDA        : True
GPU         : Tesla P100-PCIE-16GB

================================================================================
DATASET VERIFICATION
================================================================================
Aug-200 train : 7,284
Original val  : 1,312
Original test : 1,612
Classes       : 20

Stable class order:
00 -> 00_coral
01 -> 01_crab
02 -> 02_diver
03 -> 03_eel
04 -> 04_fish
05 -> 05_fishInGroups
06 -> 06_flatworm
07 -> 07_jellyfish
08 -> 08_marine_dolphin
09 -> 09_octopus
10 -> 10_rayfish
11 -> 11_seaAnemone
12 -> 12_seaCucumber
13 -> 13_seaSlug
14 -> 14_seaUrchin
15 -> 15_shark
16 -> 16_shrimp
17 -> 17_squid
18 -> 18_starfish
19 -> 19_turtle

================================================================================
CONVNEXT-SMALL VERIFICATION
================================================================================
Downloading: "https://download.pytorch.org/models/convnext_small-0c510722.pth" to /root/.cache/torch/hub/checkpoints/convnext_small-0c510722.pth

100%|██████████| 192M/192M [00:00<00:00, 217MB/s]

Classifier input features : 768
Classifier output classes : 20

================================================================================
F04 STEP 1 PASSED
================================================================================
Aug-200 train : VERIFIED
Original val  : VERIFIED
Original test : VERIFIED
Class order   : VERIFIED
ConvNeXt-S    : VERIFIED

# F04 Step 2 — Lock Standard-Loss Training Configuration

Lock the ConvNeXt-Small Aug-200 training configuration.

F04 uses standard Cross-Entropy loss with no class weighting or focal-loss terms.

The best checkpoint is selected using validation Macro F1 only.

In [12]:
# F04 Step 2 — Lock standard-loss training configuration

import json

IMG_SIZE = 224
BATCH_SIZE = 16
MAX_EPOCHS = 40
PATIENCE = 8

LEARNING_RATE = 1e-5
WEIGHT_DECAY = 1e-4
ETA_MIN = LEARNING_RATE * 0.05

NUM_WORKERS = 4
USE_AMP = True

LOSS_NAME = "CrossEntropyLoss"
OPTIMIZER_NAME = "AdamW"
SCHEDULER_NAME = "CosineAnnealingLR"
CHECKPOINT_METRIC = "validation_macro_f1"

for path in [EXP_DIR, TABLE_DIR, FIG_DIR, WEIGHTS_DIR]:
    path.mkdir(parents=True, exist_ok=True)

training_config = {
    "experiment": EXP_NAME,
    "seed": SEED,
    "model": "torchvision_convnext_small",
    "pretrained_weights": "ConvNeXt_Small_Weights.DEFAULT",
    "num_classes": 20,
    "image_size": IMG_SIZE,
    "batch_size": BATCH_SIZE,
    "max_epochs": MAX_EPOCHS,
    "early_stopping_patience": PATIENCE,
    "optimizer": OPTIMIZER_NAME,
    "learning_rate": LEARNING_RATE,
    "weight_decay": WEIGHT_DECAY,
    "scheduler": SCHEDULER_NAME,
    "scheduler_t_max": MAX_EPOCHS,
    "scheduler_eta_min": ETA_MIN,
    "loss": LOSS_NAME,
    "class_weights": False,
    "focal_loss": False,
    "amp": USE_AMP,
    "num_workers": NUM_WORKERS,
    "checkpoint_metric": CHECKPOINT_METRIC,
    "train_root": str(AUG200_TRAIN_ROOT),
    "val_root": str(ORIGINAL_VAL_ROOT),
    "test_root": str(ORIGINAL_TEST_ROOT),
}

config_path = EXP_DIR / "F04_training_config.json"

with open(config_path, "w") as f:
    json.dump(training_config, f, indent=2)

print("=" * 80)
print("F04 Step 2 — Locked Standard-Loss Training Configuration")
print("=" * 80)

for key, value in training_config.items():
    print(f"{key:<28}: {value}")

print("\nConfig saved:")
print(config_path)

print("\n" + "=" * 80)
print("F04 STEP 2 PASSED — TRAINING CONFIGURATION LOCKED")
print("=" * 80)

================================================================================
F04 Step 2 — Locked Standard-Loss Training Configuration
================================================================================
experiment                  : F04_CONVNEXT_SMALL_AUG200
seed                        : 42
model                       : torchvision_convnext_small
pretrained_weights          : ConvNeXt_Small_Weights.DEFAULT
num_classes                 : 20
image_size                  : 224
batch_size                  : 16
max_epochs                  : 40
early_stopping_patience     : 8
optimizer                   : AdamW
learning_rate               : 1e-05
weight_decay                : 0.0001
scheduler                   : CosineAnnealingLR
scheduler_t_max             : 40
scheduler_eta_min           : 5.000000000000001e-07
loss                        : CrossEntropyLoss
class_weights               : False
focal_loss                  : False
amp                         : True
num_workers                 : 4
checkpoint_metric           : validation_macro_f1
train_root                  : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/balanced_train/aug200_imagefolder/train
val_root                    : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/official_imagefolder/val
test_root                   : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/official_imagefolder/test

Config saved:
/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/experiments/F04_CONVNEXT_SMALL_AUG200/F04_training_config.json

================================================================================
F04 STEP 2 PASSED — TRAINING CONFIGURATION LOCKED
================================================================================

# F04 Step 3 — ConvNeXt-Small Aug-200 Training

Train ImageNet-pretrained ConvNeXt-Small using the locked 7,284-image Aug-200 training set and standard Cross-Entropy loss.

Validation uses the unchanged 1,312-image original validation split.

The best checkpoint is selected by validation Macro F1 only. Training history is saved after every epoch.

In [13]:
# F04 Step 3 — ConvNeXt-Small Aug-200 training

import random
import time

import numpy as np
import pandas as pd
from sklearn.metrics import precision_recall_fscore_support

import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
from torchvision.models import convnext_small, ConvNeXt_Small_Weights

# -------------------------------------------------------------------------
# Reproducibility
# -------------------------------------------------------------------------

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

torch.backends.cudnn.benchmark = True

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# -------------------------------------------------------------------------
# Transforms
# -------------------------------------------------------------------------

IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD = [0.229, 0.224, 0.225]

train_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomRotation(10),
    transforms.ToTensor(),
    transforms.Normalize(IMAGENET_MEAN, IMAGENET_STD),
])

val_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(IMAGENET_MEAN, IMAGENET_STD),
])

# -------------------------------------------------------------------------
# Datasets and loaders
# -------------------------------------------------------------------------

train_dataset = datasets.ImageFolder(
    AUG200_TRAIN_ROOT,
    transform=train_transform,
)

val_dataset = datasets.ImageFolder(
    ORIGINAL_VAL_ROOT,
    transform=val_transform,
)

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=NUM_WORKERS,
    pin_memory=True,
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=True,
)

# -------------------------------------------------------------------------
# Model
# -------------------------------------------------------------------------

model = convnext_small(
    weights=ConvNeXt_Small_Weights.DEFAULT
)

in_features = model.classifier[2].in_features
model.classifier[2] = nn.Linear(in_features, 20)

model = model.to(device)

# -------------------------------------------------------------------------
# Locked F04 loss and optimization
# -------------------------------------------------------------------------

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=LEARNING_RATE,
    weight_decay=WEIGHT_DECAY,
)

scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
    optimizer,
    T_max=MAX_EPOCHS,
    eta_min=ETA_MIN,
)

scaler = torch.amp.GradScaler(
    "cuda",
    enabled=USE_AMP,
)

# -------------------------------------------------------------------------
# Paths
# -------------------------------------------------------------------------

BEST_MODEL_PATH = WEIGHTS_DIR / "best_model.pth"
LAST_CHECKPOINT_PATH = WEIGHTS_DIR / "last_checkpoint.pth"
HISTORY_PATH = TABLE_DIR / "F04_training_history.csv"

# -------------------------------------------------------------------------
# Training
# -------------------------------------------------------------------------

history = []

best_val_macro_f1 = -1.0
best_epoch = 0
epochs_without_improvement = 0

print("=" * 110)
print("F04 Step 3 — ConvNeXt-Small Aug-200 Training")
print("=" * 110)
print(f"Device       : {device}")
print(f"Train images : {len(train_dataset):,}")
print(f"Val images   : {len(val_dataset):,}")
print(f"Batch size   : {BATCH_SIZE}")
print(f"Loss         : CrossEntropyLoss")
print(f"Selection    : Validation Macro F1")
print("=" * 110)

print(
    f"{'Epoch':>5} "
    f"{'Train Loss':>12} "
    f"{'Train Acc':>10} "
    f"{'Val Loss':>10} "
    f"{'Val Acc':>9} "
    f"{'Val P':>9} "
    f"{'Val R':>9} "
    f"{'Val F1':>9} "
    f"{'LR':>11} "
    f"{'Time':>8}"
)

print("-" * 110)

for epoch in range(1, MAX_EPOCHS + 1):

    epoch_start = time.time()

    # ---------------------------------------------------------------------
    # Train
    # ---------------------------------------------------------------------

    model.train()

    train_loss_sum = 0.0
    train_correct = 0
    train_total = 0

    for images, targets in train_loader:

        images = images.to(device, non_blocking=True)
        targets = targets.to(device, non_blocking=True)

        optimizer.zero_grad(set_to_none=True)

        with torch.amp.autocast(
            "cuda",
            enabled=USE_AMP,
        ):
            logits = model(images)
            loss = criterion(logits, targets)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        train_loss_sum += loss.item() * images.size(0)

        predictions = logits.argmax(dim=1)

        train_correct += (
            predictions == targets
        ).sum().item()

        train_total += targets.size(0)

    train_loss = train_loss_sum / train_total
    train_acc = train_correct / train_total

    # ---------------------------------------------------------------------
    # Validation
    # ---------------------------------------------------------------------

    model.eval()

    val_loss_sum = 0.0
    val_correct = 0
    val_total = 0

    val_targets = []
    val_predictions = []

    with torch.no_grad():

        for images, targets in val_loader:

            images = images.to(device, non_blocking=True)
            targets = targets.to(device, non_blocking=True)

            with torch.amp.autocast(
                "cuda",
                enabled=USE_AMP,
            ):
                logits = model(images)
                loss = criterion(logits, targets)

            predictions = logits.argmax(dim=1)

            val_loss_sum += loss.item() * images.size(0)

            val_correct += (
                predictions == targets
            ).sum().item()

            val_total += targets.size(0)

            val_targets.extend(
                targets.cpu().numpy()
            )

            val_predictions.extend(
                predictions.cpu().numpy()
            )

    val_loss = val_loss_sum / val_total
    val_acc = val_correct / val_total

    val_precision, val_recall, val_macro_f1, _ = (
        precision_recall_fscore_support(
            val_targets,
            val_predictions,
            average="macro",
            zero_division=0,
        )
    )

    current_lr = optimizer.param_groups[0]["lr"]

    epoch_time = time.time() - epoch_start

    # ---------------------------------------------------------------------
    # History
    # ---------------------------------------------------------------------

    epoch_record = {
        "epoch": epoch,
        "train_loss": train_loss,
        "train_accuracy": train_acc,
        "val_loss": val_loss,
        "val_accuracy": val_acc,
        "val_macro_precision": val_precision,
        "val_macro_recall": val_recall,
        "val_macro_f1": val_macro_f1,
        "learning_rate": current_lr,
        "epoch_seconds": epoch_time,
    }

    history.append(epoch_record)

    pd.DataFrame(history).to_csv(
        HISTORY_PATH,
        index=False,
    )

    # ---------------------------------------------------------------------
    # Best checkpoint — validation Macro F1 only
    # ---------------------------------------------------------------------

    if val_macro_f1 > best_val_macro_f1:

        best_val_macro_f1 = val_macro_f1
        best_epoch = epoch
        epochs_without_improvement = 0

        torch.save(
            {
                "experiment": EXP_NAME,
                "epoch": epoch,
                "model_state_dict": model.state_dict(),
                "optimizer_state_dict": optimizer.state_dict(),
                "scheduler_state_dict": scheduler.state_dict(),
                "val_accuracy": val_acc,
                "val_macro_precision": val_precision,
                "val_macro_recall": val_recall,
                "val_macro_f1": val_macro_f1,
                "class_names": train_dataset.classes,
                "training_config": training_config,
            },
            BEST_MODEL_PATH,
        )

        status = "BEST"

    else:

        epochs_without_improvement += 1
        status = ""

    # ---------------------------------------------------------------------
    # Lightweight recovery checkpoint
    # ---------------------------------------------------------------------

    torch.save(
        {
            "experiment": EXP_NAME,
            "epoch": epoch,
            "model_state_dict": model.state_dict(),
            "optimizer_state_dict": optimizer.state_dict(),
            "scheduler_state_dict": scheduler.state_dict(),
            "best_epoch": best_epoch,
            "best_val_macro_f1": best_val_macro_f1,
            "epochs_without_improvement": epochs_without_improvement,
            "history": history,
        },
        LAST_CHECKPOINT_PATH,
    )

    print(
        f"{epoch:>5} "
        f"{train_loss:>12.4f} "
        f"{train_acc * 100:>9.2f}% "
        f"{val_loss:>10.4f} "
        f"{val_acc * 100:>8.2f}% "
        f"{val_precision * 100:>8.2f}% "
        f"{val_recall * 100:>8.2f}% "
        f"{val_macro_f1 * 100:>8.2f}% "
        f"{current_lr:>11.2e} "
        f"{epoch_time:>7.1f}s "
        f"{status}"
    )

    scheduler.step()

    # ---------------------------------------------------------------------
    # Early stopping
    # ---------------------------------------------------------------------

    if epochs_without_improvement >= PATIENCE:

        print("\nEarly stopping triggered.")
        break

print("\n" + "=" * 110)
print("F04 STEP 3 TRAINING COMPLETED")
print("=" * 110)

print(f"Best epoch        : {best_epoch}")
print(
    f"Best Val Macro F1 : "
    f"{best_val_macro_f1 * 100:.4f}%"
)

print(f"Best checkpoint   : {BEST_MODEL_PATH}")
print(f"Last checkpoint   : {LAST_CHECKPOINT_PATH}")
print(f"Training history  : {HISTORY_PATH}")

print("\nNEXT REQUIRED STEP:")
print("F04 Step 3B — IMMEDIATELY preserve best_model.pth")

==============================================================================================================
F04 Step 3 — ConvNeXt-Small Aug-200 Training
==============================================================================================================
Device       : cuda
Train images : 7,284
Val images   : 1,312
Batch size   : 16
Loss         : CrossEntropyLoss
Selection    : Validation Macro F1
==============================================================================================================
Epoch   Train Loss  Train Acc   Val Loss   Val Acc     Val P     Val R    Val F1          LR     Time
--------------------------------------------------------------------------------------------------------------
    1       1.6498     58.02%     0.5779    87.88%    87.25%    75.61%    77.58%    1.00e-05   143.7s BEST
    2       0.5910     88.78%     0.3012    91.54%    87.88%    87.05%    86.27%    9.99e-06   138.2s BEST
    3       0.3144     93.31%     0.2509    92.53%    88.46%    88.66%    87.87%    9.94e-06   138.3s BEST
    4       0.2223     94.96%     0.2689    92.45%    89.15%    87.62%    87.48%    9.87e-06   138.2s
    5       0.1553     96.27%     0.2559    92.45%    89.66%    88.77%    88.49%    9.77e-06   138.2s BEST
    6       0.1285     96.73%     0.2548    92.76%    88.39%    87.38%    86.52%    9.64e-06   138.2s
    7       0.1040     97.36%     0.2519    92.53%    87.90%    89.18%    87.58%    9.48e-06   138.2s
    8       0.0785     98.08%     0.2778    92.30%    86.87%    85.71%    84.55%    9.30e-06   138.2s
    9       0.0669     98.33%     0.2828    92.38%    86.30%    87.07%    85.84%    9.09e-06   138.2s
   10       0.0542     98.82%     0.2807    92.91%    89.20%    90.36%    89.03%    8.86e-06   138.6s BEST
   11       0.0433     98.92%     0.3176    92.68%    88.68%    90.16%    88.53%    8.61e-06   138.2s
   12       0.0354     99.20%     0.3326    92.61%    89.10%    89.46%    88.33%    8.33e-06   138.2s
   13       0.0329     99.23%     0.3081    92.84%    90.03%    89.78%    88.95%    8.04e-06   138.3s
   14       0.0254     99.49%     0.3446    92.61%    89.15%    88.61%    87.67%    7.73e-06   138.5s
   15       0.0265     99.40%     0.3504    92.91%    89.21%    89.63%    88.30%    7.41e-06   138.2s
   16       0.0198     99.56%     0.3613    92.45%    88.09%    89.49%    88.15%    7.07e-06   138.3s
   17       0.0202     99.55%     0.3684    92.76%    89.78%    89.35%    88.32%    6.72e-06   138.4s
   18       0.0168     99.63%     0.3544    93.37%    89.27%    90.67%    89.17%    6.36e-06   138.5s BEST
   19       0.0146     99.74%     0.3775    92.68%    89.05%    90.76%    89.13%    5.99e-06   138.2s
   20       0.0155     99.62%     0.3665    92.84%    90.75%    90.51%    89.81%    5.62e-06   138.2s BEST
   21       0.0127     99.78%     0.3908    92.76%    89.09%    88.77%    88.01%    5.25e-06   138.3s
   22       0.0145     99.63%     0.3818    92.76%    88.73%    88.74%    87.74%    4.88e-06   138.5s
   23       0.0093     99.84%     0.3735    92.91%    88.96%    87.42%    86.70%    4.51e-06   138.3s
   24       0.0105     99.78%     0.3862    92.76%    90.63%    88.74%    88.46%    4.14e-06   138.3s
   25       0.0093     99.81%     0.3968    92.99%    90.31%    89.29%    88.50%    3.78e-06   138.3s
   26       0.0093     99.84%     0.4016    92.61%    90.14%    89.24%    88.40%    3.43e-06   138.6s
   27       0.0072     99.85%     0.4179    92.68%    90.21%    88.17%    87.95%    3.09e-06   138.3s
   28       0.0074     99.86%     0.3981    92.91%    89.42%    89.46%    88.37%    2.77e-06   138.2s

Early stopping triggered.

==============================================================================================================
F04 STEP 3 TRAINING COMPLETED
==============================================================================================================
Best epoch        : 20
Best Val Macro F1 : 89.8088%
Best checkpoint   : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/experiments/F04_CONVNEXT_SMALL_AUG200/weights/best_model.pth
Last checkpoint   : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/experiments/F04_CONVNEXT_SMALL_AUG200/weights/last_checkpoint.pth
Training history  : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/experiments/F04_CONVNEXT_SMALL_AUG200/tables/F04_training_history.csv

NEXT REQUIRED STEP:
F04 Step 3B — IMMEDIATELY preserve best_model.pth

# F04 Step 3B — Preserve Best Checkpoint

Immediately preserve the validation-selected best F04 checkpoint.

Create a SHA-256 fingerprint and a compact safety package containing the locked best checkpoint, training configuration, and training history.

No validation re-evaluation or official test evaluation is performed in this step.

In [14]:
# F04 Step 3B — Preserve locked best checkpoint and create safety package

import hashlib
import shutil
import zipfile
from pathlib import Path

LOCKED_BEST_PATH = WEIGHTS_DIR / "F04_best_model_locked.pth"

SAFETY_ZIP_PATH = (
    PROJECT_ROOT /
    "F04_CONVNEXT_SMALL_AUG200_SAFETY_PACKAGE.zip"
)

CHECKSUM_PATH = EXP_DIR / "F04_best_model_sha256.txt"

# -------------------------------------------------------------------------
# Preserve best checkpoint
# -------------------------------------------------------------------------

shutil.copy2(
    BEST_MODEL_PATH,
    LOCKED_BEST_PATH,
)

# -------------------------------------------------------------------------
# SHA-256
# -------------------------------------------------------------------------

sha256 = hashlib.sha256()

with open(LOCKED_BEST_PATH, "rb") as f:
    for chunk in iter(lambda: f.read(1024 * 1024), b""):
        sha256.update(chunk)

checkpoint_sha256 = sha256.hexdigest()

CHECKSUM_PATH.write_text(
    checkpoint_sha256 + "\n"
)

# -------------------------------------------------------------------------
# Safety package
# -------------------------------------------------------------------------

with zipfile.ZipFile(
    SAFETY_ZIP_PATH,
    "w",
    compression=zipfile.ZIP_DEFLATED,
) as zipf:

    zipf.write(
        LOCKED_BEST_PATH,
        arcname="weights/F04_best_model_locked.pth",
    )

    zipf.write(
        config_path,
        arcname="F04_training_config.json",
    )

    zipf.write(
        HISTORY_PATH,
        arcname="tables/F04_training_history.csv",
    )

    zipf.write(
        CHECKSUM_PATH,
        arcname="F04_best_model_sha256.txt",
    )

# -------------------------------------------------------------------------
# Verification
# -------------------------------------------------------------------------

assert LOCKED_BEST_PATH.exists()
assert SAFETY_ZIP_PATH.exists()

print("=" * 80)
print("F04 Step 3B — Best Checkpoint Preservation")
print("=" * 80)

print(f"Best epoch         : {best_epoch}")
print(f"Best Val Macro F1  : {best_val_macro_f1 * 100:.4f}%")
print(f"Locked checkpoint  : {LOCKED_BEST_PATH}")
print(f"SHA-256            : {checkpoint_sha256}")

print("\nSafety package:")
print(SAFETY_ZIP_PATH)

print(
    f"ZIP size            : "
    f"{SAFETY_ZIP_PATH.stat().st_size / (1024 ** 2):.2f} MB"
)

print("\nPACKAGE CONTENTS")

with zipfile.ZipFile(SAFETY_ZIP_PATH, "r") as zipf:
    for name in zipf.namelist():
        print(name)

print("\n" + "=" * 80)
print("F04 STEP 3B PASSED — BEST CHECKPOINT PRESERVED")
print("=" * 80)

print("\nDOWNLOAD NOW:")
print(SAFETY_ZIP_PATH)

print("\nNEXT:")
print("F04 Step 3C — Audit locked checkpoint and safety package")

================================================================================
F04 Step 3B — Best Checkpoint Preservation
================================================================================
Best epoch         : 20
Best Val Macro F1  : 89.8088%
Locked checkpoint  : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/experiments/F04_CONVNEXT_SMALL_AUG200/weights/F04_best_model_locked.pth
SHA-256            : 4e2c4abddb528e52d9721c6e1f85ea389788495f315d2891989e4ff2e403a1a7

Safety package:
/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/F04_CONVNEXT_SMALL_AUG200_SAFETY_PACKAGE.zip
ZIP size            : 524.38 MB

PACKAGE CONTENTS
weights/F04_best_model_locked.pth
F04_training_config.json
tables/F04_training_history.csv
F04_best_model_sha256.txt

================================================================================
F04 STEP 3B PASSED — BEST CHECKPOINT PRESERVED
================================================================================

DOWNLOAD NOW:
/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/F04_CONVNEXT_SMALL_AUG200_SAFETY_PACKAGE.zip

NEXT:
F04 Step 3C — Audit locked checkpoint and safety package

# F04 Step 3C — Locked Checkpoint and Safety Package Audit

Audit the preserved F04 checkpoint, SHA-256 fingerprint, safety package contents, locked training configuration, and validation-selected checkpoint metadata.

No model evaluation is performed in this step.

In [15]:
# F04 Step 3C — Audit locked checkpoint and safety package

import hashlib
import json
import zipfile

# -------------------------------------------------------------------------
# Recalculate checkpoint SHA-256
# -------------------------------------------------------------------------

sha256 = hashlib.sha256()

with open(LOCKED_BEST_PATH, "rb") as f:
    for chunk in iter(lambda: f.read(1024 * 1024), b""):
        sha256.update(chunk)

audit_sha256 = sha256.hexdigest()

saved_sha256 = CHECKSUM_PATH.read_text().strip()

assert audit_sha256 == saved_sha256
assert audit_sha256 == checkpoint_sha256

# -------------------------------------------------------------------------
# Load locked checkpoint metadata
# -------------------------------------------------------------------------

checkpoint = torch.load(
    LOCKED_BEST_PATH,
    map_location="cpu",
    weights_only=False,
)

assert checkpoint["experiment"] == EXP_NAME
assert checkpoint["epoch"] == best_epoch
assert checkpoint["class_names"] == train_dataset.classes

# -------------------------------------------------------------------------
# Load locked config
# -------------------------------------------------------------------------

with open(config_path, "r") as f:
    audit_config = json.load(f)

assert audit_config["loss"] == "CrossEntropyLoss"
assert audit_config["class_weights"] is False
assert audit_config["focal_loss"] is False
assert audit_config["checkpoint_metric"] == "validation_macro_f1"

# -------------------------------------------------------------------------
# Audit safety package
# -------------------------------------------------------------------------

expected_package_files = {
    "weights/F04_best_model_locked.pth",
    "F04_training_config.json",
    "tables/F04_training_history.csv",
    "F04_best_model_sha256.txt",
}

with zipfile.ZipFile(SAFETY_ZIP_PATH, "r") as zipf:
    package_files = set(zipf.namelist())

assert package_files == expected_package_files

# -------------------------------------------------------------------------
# Report
# -------------------------------------------------------------------------

print("=" * 80)
print("F04 Step 3C — Locked Checkpoint and Safety Package Audit")
print("=" * 80)

print(f"Experiment           : {checkpoint['experiment']}")
print(f"Locked best epoch    : {checkpoint['epoch']}")
print(
    f"Locked Val Accuracy  : "
    f"{checkpoint['val_accuracy'] * 100:.4f}%"
)
print(
    f"Locked Val Precision : "
    f"{checkpoint['val_macro_precision'] * 100:.4f}%"
)
print(
    f"Locked Val Recall    : "
    f"{checkpoint['val_macro_recall'] * 100:.4f}%"
)
print(
    f"Locked Val Macro F1  : "
    f"{checkpoint['val_macro_f1'] * 100:.4f}%"
)

print(f"\nLoss                 : {audit_config['loss']}")
print(f"Class weights        : {audit_config['class_weights']}")
print(f"Focal loss           : {audit_config['focal_loss']}")
print(f"Checkpoint metric    : {audit_config['checkpoint_metric']}")

print(f"\nCheckpoint SHA-256   : {audit_sha256}")
print("SHA-256 audit        : PASSED")

print("\nSafety package files:")

for name in sorted(package_files):
    print(name)

print("\nPackage audit        : PASSED")

print("\n" + "=" * 80)
print("F04 STEP 3C PASSED — LOCKED ARTIFACTS AUDITED")
print("=" * 80)

print("\nNEXT:")
print("F04 Step 4 — Inspect training and fresh locked validation confirmation")

================================================================================
F04 Step 3C — Locked Checkpoint and Safety Package Audit
================================================================================
Experiment           : F04_CONVNEXT_SMALL_AUG200
Locked best epoch    : 20
Locked Val Accuracy  : 92.8354%
Locked Val Precision : 90.7527%
Locked Val Recall    : 90.5123%
Locked Val Macro F1  : 89.8088%

Loss                 : CrossEntropyLoss
Class weights        : False
Focal loss           : False
Checkpoint metric    : validation_macro_f1

Checkpoint SHA-256   : 4e2c4abddb528e52d9721c6e1f85ea389788495f315d2891989e4ff2e403a1a7
SHA-256 audit        : PASSED

Safety package files:
F04_best_model_sha256.txt
F04_training_config.json
tables/F04_training_history.csv
weights/F04_best_model_locked.pth

Package audit        : PASSED

================================================================================
F04 STEP 3C PASSED — LOCKED ARTIFACTS AUDITED
================================================================================

NEXT:
F04 Step 4 — Inspect training and fresh locked validation confirmation

# F04 Step 4 — Training Inspection and Locked Validation Confirmation

Inspect the saved F04 training history and independently reload the preserved epoch-20 checkpoint.

Re-evaluate the unchanged 1,312-image validation split and confirm that the fresh metrics reproduce the validation-selected checkpoint metadata.

The official test split is not evaluated in this step.

In [16]:
# F04 Step 4 — Inspect training and fresh locked validation confirmation

import numpy as np
import pandas as pd
from sklearn.metrics import precision_recall_fscore_support

import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
from torchvision.models import convnext_small

# -------------------------------------------------------------------------
# Training history inspection
# -------------------------------------------------------------------------

history_df = pd.read_csv(HISTORY_PATH)

history_best_idx = history_df["val_macro_f1"].idxmax()
history_best = history_df.loc[history_best_idx]

assert int(history_best["epoch"]) == checkpoint["epoch"]

print("=" * 90)
print("F04 Step 4 — Training Inspection")
print("=" * 90)

print(f"Epochs completed        : {len(history_df)}")
print(f"History best epoch      : {int(history_best['epoch'])}")
print(
    f"History best Val Acc    : "
    f"{history_best['val_accuracy'] * 100:.4f}%"
)
print(
    f"History best Val P      : "
    f"{history_best['val_macro_precision'] * 100:.4f}%"
)
print(
    f"History best Val R      : "
    f"{history_best['val_macro_recall'] * 100:.4f}%"
)
print(
    f"History best Val F1     : "
    f"{history_best['val_macro_f1'] * 100:.4f}%"
)

# -------------------------------------------------------------------------
# Fresh validation dataset and loader
# -------------------------------------------------------------------------

val_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(
        [0.485, 0.456, 0.406],
        [0.229, 0.224, 0.225],
    ),
])

fresh_val_dataset = datasets.ImageFolder(
    ORIGINAL_VAL_ROOT,
    transform=val_transform,
)

fresh_val_loader = DataLoader(
    fresh_val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=True,
)

assert len(fresh_val_dataset) == 1312
assert fresh_val_dataset.classes == checkpoint["class_names"]

# -------------------------------------------------------------------------
# Fresh model reload from locked checkpoint
# -------------------------------------------------------------------------

fresh_model = convnext_small(weights=None)

in_features = fresh_model.classifier[2].in_features
fresh_model.classifier[2] = nn.Linear(in_features, 20)

fresh_model.load_state_dict(
    checkpoint["model_state_dict"]
)

fresh_model = fresh_model.to(device)
fresh_model.eval()

criterion = nn.CrossEntropyLoss()

# -------------------------------------------------------------------------
# Fresh locked validation evaluation
# -------------------------------------------------------------------------

val_loss_sum = 0.0
val_total = 0

all_targets = []
all_predictions = []
all_probabilities = []

with torch.no_grad():

    for images, targets in fresh_val_loader:

        images = images.to(device, non_blocking=True)
        targets = targets.to(device, non_blocking=True)

        with torch.amp.autocast(
            "cuda",
            enabled=USE_AMP,
        ):
            logits = fresh_model(images)
            loss = criterion(logits, targets)

        probabilities = torch.softmax(logits, dim=1)
        predictions = logits.argmax(dim=1)

        val_loss_sum += loss.item() * targets.size(0)
        val_total += targets.size(0)

        all_targets.extend(targets.cpu().numpy())
        all_predictions.extend(predictions.cpu().numpy())
        all_probabilities.append(
            probabilities.cpu().numpy()
        )

all_targets = np.asarray(all_targets)
all_predictions = np.asarray(all_predictions)
all_probabilities = np.concatenate(
    all_probabilities,
    axis=0,
)

fresh_val_loss = val_loss_sum / val_total
fresh_val_top1 = np.mean(
    all_predictions == all_targets
)

fresh_val_precision, fresh_val_recall, fresh_val_macro_f1, _ = (
    precision_recall_fscore_support(
        all_targets,
        all_predictions,
        average="macro",
        zero_division=0,
    )
)

# -------------------------------------------------------------------------
# Top-k validation metrics
# -------------------------------------------------------------------------

sorted_indices = np.argsort(
    -all_probabilities,
    axis=1,
)

fresh_val_top2 = np.mean([
    target in row[:2]
    for target, row in zip(all_targets, sorted_indices)
])

fresh_val_top3 = np.mean([
    target in row[:3]
    for target, row in zip(all_targets, sorted_indices)
])

fresh_val_top5 = np.mean([
    target in row[:5]
    for target, row in zip(all_targets, sorted_indices)
])

# -------------------------------------------------------------------------
# Independent reproduction checks
# -------------------------------------------------------------------------

assert np.isclose(
    fresh_val_top1,
    checkpoint["val_accuracy"],
    atol=1e-8,
)

assert np.isclose(
    fresh_val_precision,
    checkpoint["val_macro_precision"],
    atol=1e-8,
)

assert np.isclose(
    fresh_val_recall,
    checkpoint["val_macro_recall"],
    atol=1e-8,
)

assert np.isclose(
    fresh_val_macro_f1,
    checkpoint["val_macro_f1"],
    atol=1e-8,
)

# -------------------------------------------------------------------------
# Save locked validation summary
# -------------------------------------------------------------------------

validation_summary = pd.DataFrame([{
    "experiment": EXP_NAME,
    "checkpoint_epoch": checkpoint["epoch"],
    "val_loss": fresh_val_loss,
    "val_top1": fresh_val_top1,
    "val_top2": fresh_val_top2,
    "val_top3": fresh_val_top3,
    "val_top5": fresh_val_top5,
    "val_macro_precision": fresh_val_precision,
    "val_macro_recall": fresh_val_recall,
    "val_macro_f1": fresh_val_macro_f1,
    "checkpoint_sha256": audit_sha256,
}])

VALIDATION_SUMMARY_PATH = (
    TABLE_DIR / "F04_locked_validation_summary.csv"
)

validation_summary.to_csv(
    VALIDATION_SUMMARY_PATH,
    index=False,
)

# -------------------------------------------------------------------------
# Report
# -------------------------------------------------------------------------

print("\n" + "=" * 90)
print("FRESH LOCKED VALIDATION CONFIRMATION")
print("=" * 90)

print(f"Checkpoint epoch : {checkpoint['epoch']}")
print(f"Validation images: {len(fresh_val_dataset):,}")
print(f"Val Loss         : {fresh_val_loss:.6f}")
print(f"Top-1            : {fresh_val_top1 * 100:.4f}%")
print(f"Top-2            : {fresh_val_top2 * 100:.4f}%")
print(f"Top-3            : {fresh_val_top3 * 100:.4f}%")
print(f"Top-5            : {fresh_val_top5 * 100:.4f}%")
print(f"Macro Precision  : {fresh_val_precision * 100:.4f}%")
print(f"Macro Recall     : {fresh_val_recall * 100:.4f}%")
print(f"Macro F1         : {fresh_val_macro_f1 * 100:.4f}%")

print("\nCheckpoint reproduction : PASSED")
print(f"Summary saved           : {VALIDATION_SUMMARY_PATH}")

print("\n" + "=" * 90)
print("F04 STEP 4 PASSED — LOCKED VALIDATION INDEPENDENTLY CONFIRMED")
print("=" * 90)

print("\nNEXT:")
print("F04 Step 5 — Official unchanged test evaluation")

==========================================================================================
F04 Step 4 — Training Inspection
==========================================================================================
Epochs completed        : 28
History best epoch      : 20
History best Val Acc    : 92.8354%
History best Val P      : 90.7527%
History best Val R      : 90.5123%
History best Val F1     : 89.8088%

==========================================================================================
FRESH LOCKED VALIDATION CONFIRMATION
==========================================================================================
Checkpoint epoch : 20
Validation images: 1,312
Val Loss         : 0.366462
Top-1            : 92.8354%
Top-2            : 97.7896%
Top-3            : 99.3140%
Top-5            : 99.8476%
Macro Precision  : 90.7527%
Macro Recall     : 90.5123%
Macro F1         : 89.8088%

Checkpoint reproduction : PASSED
Summary saved           : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/experiments/F04_CONVNEXT_SMALL_AUG200/tables/F04_locked_validation_summary.csv

==========================================================================================
F04 STEP 4 PASSED — LOCKED VALIDATION INDEPENDENTLY CONFIRMED
==========================================================================================

NEXT:
F04 Step 5 — Official unchanged test evaluation

# F04 Step 5 — Official Unchanged Test Evaluation

Evaluate the locked epoch-20 F04 checkpoint on the unchanged 1,612-image official AQUA20 test split.

Report Top-1, Top-2, Top-3, Top-5, macro and weighted precision/recall/F1, per-class metrics, predictions, and confusion matrices.

The training configuration and locked checkpoint remain unchanged.

In [17]:
# F04 Step 5 — Official unchanged test evaluation

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    precision_recall_fscore_support,
)

import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
from torchvision.models import convnext_small

# -------------------------------------------------------------------------
# Official unchanged test dataset
# -------------------------------------------------------------------------

test_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(
        [0.485, 0.456, 0.406],
        [0.229, 0.224, 0.225],
    ),
])

test_dataset = datasets.ImageFolder(
    ORIGINAL_TEST_ROOT,
    transform=test_transform,
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=True,
)

assert len(test_dataset) == 1612
assert test_dataset.classes == checkpoint["class_names"]

# -------------------------------------------------------------------------
# Fresh locked model reload
# -------------------------------------------------------------------------

test_model = convnext_small(weights=None)

in_features = test_model.classifier[2].in_features
test_model.classifier[2] = nn.Linear(in_features, 20)

test_model.load_state_dict(
    checkpoint["model_state_dict"]
)

test_model = test_model.to(device)
test_model.eval()

criterion = nn.CrossEntropyLoss()

# -------------------------------------------------------------------------
# Official test inference
# -------------------------------------------------------------------------

test_loss_sum = 0.0
test_total = 0

test_targets = []
test_predictions = []
test_probabilities = []

with torch.no_grad():

    for images, targets in test_loader:

        images = images.to(device, non_blocking=True)
        targets = targets.to(device, non_blocking=True)

        with torch.amp.autocast(
            "cuda",
            enabled=USE_AMP,
        ):
            logits = test_model(images)
            loss = criterion(logits, targets)

        probabilities = torch.softmax(logits, dim=1)
        predictions = logits.argmax(dim=1)

        test_loss_sum += loss.item() * targets.size(0)
        test_total += targets.size(0)

        test_targets.extend(
            targets.cpu().numpy()
        )

        test_predictions.extend(
            predictions.cpu().numpy()
        )

        test_probabilities.append(
            probabilities.cpu().numpy()
        )

test_targets = np.asarray(test_targets)
test_predictions = np.asarray(test_predictions)

test_probabilities = np.concatenate(
    test_probabilities,
    axis=0,
)

test_loss = test_loss_sum / test_total

# -------------------------------------------------------------------------
# Top-k metrics
# -------------------------------------------------------------------------

sorted_indices = np.argsort(
    -test_probabilities,
    axis=1,
)

test_top1 = np.mean(
    test_predictions == test_targets
)

test_top2 = np.mean([
    target in row[:2]
    for target, row in zip(
        test_targets,
        sorted_indices,
    )
])

test_top3 = np.mean([
    target in row[:3]
    for target, row in zip(
        test_targets,
        sorted_indices,
    )
])

test_top5 = np.mean([
    target in row[:5]
    for target, row in zip(
        test_targets,
        sorted_indices,
    )
])

# -------------------------------------------------------------------------
# Macro metrics
# -------------------------------------------------------------------------

(
    macro_precision,
    macro_recall,
    macro_f1,
    _,
) = precision_recall_fscore_support(
    test_targets,
    test_predictions,
    average="macro",
    zero_division=0,
)

# -------------------------------------------------------------------------
# Weighted metrics
# -------------------------------------------------------------------------

(
    weighted_precision,
    weighted_recall,
    weighted_f1,
    _,
) = precision_recall_fscore_support(
    test_targets,
    test_predictions,
    average="weighted",
    zero_division=0,
)

# -------------------------------------------------------------------------
# Classification report
# -------------------------------------------------------------------------

report_dict = classification_report(
    test_targets,
    test_predictions,
    target_names=test_dataset.classes,
    output_dict=True,
    zero_division=0,
)

report_df = pd.DataFrame(
    report_dict
).transpose()

CLASS_REPORT_PATH = (
    TABLE_DIR / "F04_classification_report.csv"
)

report_df.to_csv(CLASS_REPORT_PATH)

# -------------------------------------------------------------------------
# Confusion matrices
# -------------------------------------------------------------------------

cm = confusion_matrix(
    test_targets,
    test_predictions,
)

cm_normalized = cm.astype(float) / np.maximum(
    cm.sum(axis=1, keepdims=True),
    1,
)

CM_CSV_PATH = (
    TABLE_DIR / "F04_confusion_matrix.csv"
)

CM_NORM_CSV_PATH = (
    TABLE_DIR / "F04_confusion_matrix_normalized.csv"
)

pd.DataFrame(
    cm,
    index=test_dataset.classes,
    columns=test_dataset.classes,
).to_csv(CM_CSV_PATH)

pd.DataFrame(
    cm_normalized,
    index=test_dataset.classes,
    columns=test_dataset.classes,
).to_csv(CM_NORM_CSV_PATH)

# -------------------------------------------------------------------------
# Confusion matrix figure
# -------------------------------------------------------------------------

plt.figure(figsize=(14, 12))

plt.imshow(cm)
plt.colorbar()

plt.xticks(
    range(len(test_dataset.classes)),
    test_dataset.classes,
    rotation=90,
)

plt.yticks(
    range(len(test_dataset.classes)),
    test_dataset.classes,
)

plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("F04 Official Test Confusion Matrix")

plt.tight_layout()

CM_FIG_PATH = (
    FIG_DIR / "F04_confusion_matrix.png"
)

plt.savefig(
    CM_FIG_PATH,
    dpi=300,
    bbox_inches="tight",
)

plt.close()

# -------------------------------------------------------------------------
# Normalized confusion matrix figure
# -------------------------------------------------------------------------

plt.figure(figsize=(14, 12))

plt.imshow(cm_normalized)
plt.colorbar()

plt.xticks(
    range(len(test_dataset.classes)),
    test_dataset.classes,
    rotation=90,
)

plt.yticks(
    range(len(test_dataset.classes)),
    test_dataset.classes,
)

plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("F04 Official Test Normalized Confusion Matrix")

plt.tight_layout()

CM_NORM_FIG_PATH = (
    FIG_DIR / "F04_confusion_matrix_normalized.png"
)

plt.savefig(
    CM_NORM_FIG_PATH,
    dpi=300,
    bbox_inches="tight",
)

plt.close()

# -------------------------------------------------------------------------
# Test predictions
# -------------------------------------------------------------------------

test_image_paths = [
    path
    for path, _ in test_dataset.samples
]

prediction_df = pd.DataFrame({
    "image_path": test_image_paths,
    "true_index": test_targets,
    "true_class": [
        test_dataset.classes[i]
        for i in test_targets
    ],
    "predicted_index": test_predictions,
    "predicted_class": [
        test_dataset.classes[i]
        for i in test_predictions
    ],
    "top1_confidence": test_probabilities.max(axis=1),
    "correct": (
        test_targets == test_predictions
    ),
})

PREDICTIONS_PATH = (
    TABLE_DIR / "F04_test_predictions.csv"
)

prediction_df.to_csv(
    PREDICTIONS_PATH,
    index=False,
)

# -------------------------------------------------------------------------
# Official test metric summary
# -------------------------------------------------------------------------

test_summary = pd.DataFrame([{
    "experiment": EXP_NAME,
    "checkpoint_epoch": checkpoint["epoch"],
    "test_images": len(test_dataset),
    "test_loss": test_loss,
    "top1": test_top1,
    "top2": test_top2,
    "top3": test_top3,
    "top5": test_top5,
    "macro_precision": macro_precision,
    "macro_recall": macro_recall,
    "macro_f1": macro_f1,
    "weighted_precision": weighted_precision,
    "weighted_recall": weighted_recall,
    "weighted_f1": weighted_f1,
    "checkpoint_sha256": audit_sha256,
}])

TEST_SUMMARY_PATH = (
    TABLE_DIR / "F04_test_metrics_summary.csv"
)

test_summary.to_csv(
    TEST_SUMMARY_PATH,
    index=False,
)

# -------------------------------------------------------------------------
# Comparison-ready summary
# -------------------------------------------------------------------------

comparison_df = pd.DataFrame([
    {
        "experiment": "F03_CONVNEXT_SMALL_GENTLE_CB_FOCAL",
        "top1": 0.916253,
        "top2": 0.977047,
        "top3": 0.991315,
        "top5": 0.996898,
        "macro_precision": 0.907850,
        "macro_recall": 0.869302,
        "macro_f1": 0.879645,
        "weighted_f1": 0.915656,
    },
    {
        "experiment": EXP_NAME,
        "top1": test_top1,
        "top2": test_top2,
        "top3": test_top3,
        "top5": test_top5,
        "macro_precision": macro_precision,
        "macro_recall": macro_recall,
        "macro_f1": macro_f1,
        "weighted_f1": weighted_f1,
    },
])

COMPARISON_PATH = (
    TABLE_DIR / "F04_comparison_ready_summary.csv"
)

comparison_df.to_csv(
    COMPARISON_PATH,
    index=False,
)

# -------------------------------------------------------------------------
# Campaign threshold checks
# -------------------------------------------------------------------------

campaign_checks = {
    "Top-1 > 92.68%": test_top1 > 0.9268,
    "Macro Precision > 91.40%": macro_precision > 0.9140,
    "Macro Recall > 87.32%": macro_recall > 0.8732,
    "Macro F1 > 88.92%": macro_f1 > 0.8892,
    "Top-2 > 97.58%": test_top2 > 0.9758,
    "Top-3 > 98.82%": test_top3 > 0.9882,
}

# -------------------------------------------------------------------------
# Official report
# -------------------------------------------------------------------------

print("=" * 90)
print("F04 Step 5 — OFFICIAL UNCHANGED TEST EVALUATION")
print("=" * 90)

print(f"Experiment         : {EXP_NAME}")
print(f"Checkpoint epoch   : {checkpoint['epoch']}")
print(f"Checkpoint SHA-256 : {audit_sha256}")
print(f"Official test      : {len(test_dataset):,} images")

print("\n" + "=" * 90)
print("OFFICIAL TEST METRICS")
print("=" * 90)

print(f"Test Loss          : {test_loss:.6f}")
print(f"Top-1              : {test_top1 * 100:.4f}%")
print(f"Top-2              : {test_top2 * 100:.4f}%")
print(f"Top-3              : {test_top3 * 100:.4f}%")
print(f"Top-5              : {test_top5 * 100:.4f}%")
print(f"Macro Precision    : {macro_precision * 100:.4f}%")
print(f"Macro Recall       : {macro_recall * 100:.4f}%")
print(f"Macro F1           : {macro_f1 * 100:.4f}%")
print(f"Weighted Precision : {weighted_precision * 100:.4f}%")
print(f"Weighted Recall    : {weighted_recall * 100:.4f}%")
print(f"Weighted F1        : {weighted_f1 * 100:.4f}%")

print("\n" + "=" * 90)
print("CAMPAIGN TARGET CHECK")
print("=" * 90)

for target, passed in campaign_checks.items():
    print(
        f"{target:<30}: "
        f"{'PASSED' if passed else 'NOT PASSED'}"
    )

print("\n" + "=" * 90)
print("F03 vs F04 TEST COMPARISON")
print("=" * 90)

print(comparison_df.to_string(index=False))

print("\n" + "=" * 90)
print("IMPORTANT PER-CLASS RESULT — FLATWORM")
print("=" * 90)

flatworm_metrics = report_df.loc["06_flatworm"]

print(
    f"Precision : "
    f"{flatworm_metrics['precision'] * 100:.4f}%"
)

print(
    f"Recall    : "
    f"{flatworm_metrics['recall'] * 100:.4f}%"
)

print(
    f"F1        : "
    f"{flatworm_metrics['f1-score'] * 100:.4f}%"
)

print(
    f"Support   : "
    f"{int(flatworm_metrics['support'])}"
)

print("\nSaved outputs:")
print(TEST_SUMMARY_PATH)
print(CLASS_REPORT_PATH)
print(PREDICTIONS_PATH)
print(CM_CSV_PATH)
print(CM_NORM_CSV_PATH)
print(CM_FIG_PATH)
print(CM_NORM_FIG_PATH)
print(COMPARISON_PATH)

print("\n" + "=" * 90)
print("F04 STEP 5 PASSED — OFFICIAL TEST EVALUATION COMPLETED")
print("=" * 90)

print("\nNEXT:")
print("F04 Step 6 — Create official final F04 package")

==========================================================================================
F04 Step 5 — OFFICIAL UNCHANGED TEST EVALUATION
==========================================================================================
Experiment         : F04_CONVNEXT_SMALL_AUG200
Checkpoint epoch   : 20
Checkpoint SHA-256 : 4e2c4abddb528e52d9721c6e1f85ea389788495f315d2891989e4ff2e403a1a7
Official test      : 1,612 images

==========================================================================================
OFFICIAL TEST METRICS
==========================================================================================
Test Loss          : 0.424807
Top-1              : 91.3772%
Top-2              : 97.2705%
Top-3              : 99.0074%
Top-5              : 99.6278%
Macro Precision    : 89.3241%
Macro Recall       : 84.3236%
Macro F1           : 86.0035%
Weighted Precision : 91.4067%
Weighted Recall    : 91.3772%
Weighted F1        : 91.2641%

==========================================================================================
CAMPAIGN TARGET CHECK
==========================================================================================
Top-1 > 92.68%                : NOT PASSED
Macro Precision > 91.40%      : NOT PASSED
Macro Recall > 87.32%         : NOT PASSED
Macro F1 > 88.92%             : NOT PASSED
Top-2 > 97.58%                : NOT PASSED
Top-3 > 98.82%                : PASSED

==========================================================================================
F03 vs F04 TEST COMPARISON
==========================================================================================
                        experiment     top1     top2     top3     top5  macro_precision  macro_recall  macro_f1  weighted_f1
F03_CONVNEXT_SMALL_GENTLE_CB_FOCAL 0.916253 0.977047 0.991315 0.996898         0.907850      0.869302  0.879645     0.915656
         F04_CONVNEXT_SMALL_AUG200 0.913772 0.972705 0.990074 0.996278         0.893241      0.843236  0.860035     0.912641

==========================================================================================
IMPORTANT PER-CLASS RESULT — FLATWORM
==========================================================================================
Precision : 81.8182%
Recall    : 69.2308%
F1        : 75.0000%
Support   : 13

Saved outputs:
/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/experiments/F04_CONVNEXT_SMALL_AUG200/tables/F04_test_metrics_summary.csv
/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/experiments/F04_CONVNEXT_SMALL_AUG200/tables/F04_classification_report.csv
/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/experiments/F04_CONVNEXT_SMALL_AUG200/tables/F04_test_predictions.csv
/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/experiments/F04_CONVNEXT_SMALL_AUG200/tables/F04_confusion_matrix.csv
/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/experiments/F04_CONVNEXT_SMALL_AUG200/tables/F04_confusion_matrix_normalized.csv
/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/experiments/F04_CONVNEXT_SMALL_AUG200/figures/F04_confusion_matrix.png
/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/experiments/F04_CONVNEXT_SMALL_AUG200/figures/F04_confusion_matrix_normalized.png
/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/experiments/F04_CONVNEXT_SMALL_AUG200/tables/F04_comparison_ready_summary.csv

==========================================================================================
F04 STEP 5 PASSED — OFFICIAL TEST EVALUATION COMPLETED
==========================================================================================

NEXT:
F04 Step 6 — Create official final F04 package

# F04 Step 6 — Create Official Final F04 Package

Create the official reproducibility package for F04.

The package contains the locked validation-selected checkpoint, training configuration, training history, fresh validation summary, official test metrics, per-class results, predictions, confusion matrices, comparison summary, checkpoint fingerprint, and final experiment summary.

In [18]:
# F04 Step 6 — Create official final F04 package

import json
import zipfile
from pathlib import Path

FINAL_PACKAGE_PATH = (
    PROJECT_ROOT /
    "aqua20_f04_convnext_small_aug200_outputs.zip"
)

FINAL_SUMMARY_PATH = (
    EXP_DIR / "F04_official_final_summary.json"
)

# -------------------------------------------------------------------------
# Official F04 final summary
# -------------------------------------------------------------------------

f04_final_summary = {
    "experiment": EXP_NAME,
    "status": "COMPLETED",
    "scientific_group": "G2_data_level_balancing_control",
    "method": (
        "ConvNeXt-Small + Aug-200 train-only balancing "
        "+ standard CrossEntropyLoss"
    ),
    "checkpoint_selection": "validation_macro_f1",
    "best_epoch": int(checkpoint["epoch"]),
    "checkpoint_sha256": audit_sha256,
    "dataset": {
        "train": 7284,
        "validation": 1312,
        "test": 1612,
        "classes": 20,
        "seed": SEED,
    },
    "validation": {
        "top1": float(fresh_val_top1),
        "top2": float(fresh_val_top2),
        "top3": float(fresh_val_top3),
        "top5": float(fresh_val_top5),
        "macro_precision": float(fresh_val_precision),
        "macro_recall": float(fresh_val_recall),
        "macro_f1": float(fresh_val_macro_f1),
    },
    "official_test": {
        "top1": float(test_top1),
        "top2": float(test_top2),
        "top3": float(test_top3),
        "top5": float(test_top5),
        "macro_precision": float(macro_precision),
        "macro_recall": float(macro_recall),
        "macro_f1": float(macro_f1),
        "weighted_precision": float(weighted_precision),
        "weighted_recall": float(weighted_recall),
        "weighted_f1": float(weighted_f1),
    },
    "flatworm_test": {
        "precision": float(flatworm_metrics["precision"]),
        "recall": float(flatworm_metrics["recall"]),
        "f1": float(flatworm_metrics["f1-score"]),
        "support": int(flatworm_metrics["support"]),
    },
    "campaign_targets": {
        target: bool(passed)
        for target, passed in campaign_checks.items()
    },
    "comparison_with_f03": {
        "f04_top1_minus_f03_pp": -0.2481,
        "f04_top2_minus_f03_pp": -0.4342,
        "f04_top3_minus_f03_pp": -0.1241,
        "f04_top5_minus_f03_pp": -0.0620,
        "f04_macro_precision_minus_f03_pp": -1.4609,
        "f04_macro_recall_minus_f03_pp": -2.6066,
        "f04_macro_f1_minus_f03_pp": -1.9610,
        "f04_weighted_f1_minus_f03_pp": -0.3015,
    },
    "scientific_conclusion": (
        "Aug-200 became substantially more effective with ConvNeXt-Small "
        "than in the earlier YOLO experiments, but data-level balancing "
        "alone remained inferior to F03 Gentle Class-Balanced Focal Loss "
        "on the unchanged official AQUA20 test set, especially for macro "
        "recall and macro F1."
    ),
    "next_experiment": (
        "F05_AUG200_GENTLE_CB_FOCAL_COMBINED_INTERVENTION"
    ),
}

with open(FINAL_SUMMARY_PATH, "w") as f:
    json.dump(
        f04_final_summary,
        f,
        indent=2,
    )

# -------------------------------------------------------------------------
# Curated official package files
# -------------------------------------------------------------------------

package_files = {
    LOCKED_BEST_PATH:
        "weights/F04_best_model_locked.pth",

    config_path:
        "F04_training_config.json",

    HISTORY_PATH:
        "tables/F04_training_history.csv",

    VALIDATION_SUMMARY_PATH:
        "tables/F04_locked_validation_summary.csv",

    TEST_SUMMARY_PATH:
        "tables/F04_test_metrics_summary.csv",

    CLASS_REPORT_PATH:
        "tables/F04_classification_report.csv",

    PREDICTIONS_PATH:
        "tables/F04_test_predictions.csv",

    CM_CSV_PATH:
        "tables/F04_confusion_matrix.csv",

    CM_NORM_CSV_PATH:
        "tables/F04_confusion_matrix_normalized.csv",

    COMPARISON_PATH:
        "tables/F04_comparison_ready_summary.csv",

    CM_FIG_PATH:
        "figures/F04_confusion_matrix.png",

    CM_NORM_FIG_PATH:
        "figures/F04_confusion_matrix_normalized.png",

    CHECKSUM_PATH:
        "F04_best_model_sha256.txt",

    FINAL_SUMMARY_PATH:
        "F04_official_final_summary.json",
}

# -------------------------------------------------------------------------
# Verify every required artifact
# -------------------------------------------------------------------------

for source_path in package_files:
    assert source_path.exists(), (
        f"Missing required artifact: {source_path}"
    )

# -------------------------------------------------------------------------
# Create official ZIP
# -------------------------------------------------------------------------

with zipfile.ZipFile(
    FINAL_PACKAGE_PATH,
    "w",
    compression=zipfile.ZIP_DEFLATED,
) as zipf:

    for source_path, archive_name in package_files.items():
        zipf.write(
            source_path,
            arcname=archive_name,
        )

# -------------------------------------------------------------------------
# Package audit
# -------------------------------------------------------------------------

with zipfile.ZipFile(
    FINAL_PACKAGE_PATH,
    "r",
) as zipf:

    final_package_contents = zipf.namelist()

expected_contents = set(package_files.values())

assert set(final_package_contents) == expected_contents

# -------------------------------------------------------------------------
# Report
# -------------------------------------------------------------------------

print("=" * 90)
print("F04 Step 6 — OFFICIAL FINAL PACKAGE")
print("=" * 90)

print(f"Experiment       : {EXP_NAME}")
print(f"Status           : COMPLETED")
print(f"Best epoch       : {checkpoint['epoch']}")
print(f"Checkpoint SHA   : {audit_sha256}")

print("\nOFFICIAL TEST")
print(f"Top-1            : {test_top1 * 100:.4f}%")
print(f"Top-2            : {test_top2 * 100:.4f}%")
print(f"Top-3            : {test_top3 * 100:.4f}%")
print(f"Top-5            : {test_top5 * 100:.4f}%")
print(f"Macro Precision  : {macro_precision * 100:.4f}%")
print(f"Macro Recall     : {macro_recall * 100:.4f}%")
print(f"Macro F1         : {macro_f1 * 100:.4f}%")
print(f"Weighted F1      : {weighted_f1 * 100:.4f}%")

print("\nFINAL PACKAGE")
print(FINAL_PACKAGE_PATH)

print(
    f"ZIP size          : "
    f"{FINAL_PACKAGE_PATH.stat().st_size / (1024 ** 2):.2f} MB"
)

print("\nPACKAGE CONTENTS")

for name in final_package_contents:
    print(name)

print("\nPackage audit     : PASSED")

print("\n" + "=" * 90)
print("F04 OFFICIALLY CLOSED")
print("=" * 90)

print("\nDOWNLOAD NOW:")
print(FINAL_PACKAGE_PATH)

print("\nNEXT OFFICIAL EXPERIMENT:")
print("F05 — Aug-200 + Gentle Class-Balanced Focal Loss")

==========================================================================================
F04 Step 6 — OFFICIAL FINAL PACKAGE
==========================================================================================
Experiment       : F04_CONVNEXT_SMALL_AUG200
Status           : COMPLETED
Best epoch       : 20
Checkpoint SHA   : 4e2c4abddb528e52d9721c6e1f85ea389788495f315d2891989e4ff2e403a1a7

OFFICIAL TEST
Top-1            : 91.3772%
Top-2            : 97.2705%
Top-3            : 99.0074%
Top-5            : 99.6278%
Macro Precision  : 89.3241%
Macro Recall     : 84.3236%
Macro F1         : 86.0035%
Weighted F1      : 91.2641%

FINAL PACKAGE
/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/aqua20_f04_convnext_small_aug200_outputs.zip
ZIP size          : 524.86 MB

PACKAGE CONTENTS
weights/F04_best_model_locked.pth
F04_training_config.json
tables/F04_training_history.csv
tables/F04_locked_validation_summary.csv
tables/F04_test_metrics_summary.csv
tables/F04_classification_report.csv
tables/F04_test_predictions.csv
tables/F04_confusion_matrix.csv
tables/F04_confusion_matrix_normalized.csv
tables/F04_comparison_ready_summary.csv
figures/F04_confusion_matrix.png
figures/F04_confusion_matrix_normalized.png
F04_best_model_sha256.txt
F04_official_final_summary.json

Package audit     : PASSED

==========================================================================================
F04 OFFICIALLY CLOSED
==========================================================================================

DOWNLOAD NOW:
/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/aqua20_f04_convnext_small_aug200_outputs.zip

NEXT OFFICIAL EXPERIMENT:
F05 — Aug-200 + Gentle Class-Balanced Focal Loss

# F05 — ConvNeXt-Small + Aug-200 + Gentle Class-Balanced Focal Loss

## Step 1 — Environment, dataset, and model verification

This step verifies the locked AQUA20 F05 environment before training.

F05 uses:

- ConvNeXt-Small
- Aug-200 train-only balancing
- Gentle Class-Balanced Focal Loss
- Original unchanged validation split
- Original unchanged official test split
- Seed 42
- Best checkpoint selected by validation Macro F1

Expected split sizes:

- Aug-200 train: 7,284 images
- Original validation: 1,312 images
- Official test: 1,612 images
- Classes: 20

No training or official test evaluation is performed in this step.

In [13]:
# ============================================================
# F05 Step 1 — Environment, dataset, and model verification
# ============================================================

import os

os.environ["CUBLAS_WORKSPACE_CONFIG"] = ":4096:8"
os.environ["PYTHONHASHSEED"] = "42"

import sys
from pathlib import Path

import torch
import torchvision
from torchvision.datasets import ImageFolder
from torchvision.models import convnext_small, ConvNeXt_Small_Weights

print("=" * 80)
print("F05 Step 1 — Environment, dataset, and model verification")
print("=" * 80)

# -------------------------------------------------------------------------
# Official paths
# -------------------------------------------------------------------------

PROJECT_ROOT = Path(
    "/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026"
)

AUG200_TRAIN_ROOT = (
    PROJECT_ROOT
    / "balanced_train"
    / "aug200_imagefolder"
    / "train"
)

ORIGINAL_DATA_ROOT = PROJECT_ROOT / "official_imagefolder"

VAL_ROOT = ORIGINAL_DATA_ROOT / "val"
TEST_ROOT = ORIGINAL_DATA_ROOT / "test"

# -------------------------------------------------------------------------
# Environment
# -------------------------------------------------------------------------

print("\nENVIRONMENT")
print("-" * 80)
print("Python      :", sys.version.split()[0])
print("Torch       :", torch.__version__)
print("Torchvision :", torchvision.__version__)
print("CUDA        :", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU         :", torch.cuda.get_device_name(0))

# -------------------------------------------------------------------------
# Dataset verification
# -------------------------------------------------------------------------

assert AUG200_TRAIN_ROOT.exists(), (
    f"Missing Aug-200 train root: {AUG200_TRAIN_ROOT}"
)

assert VAL_ROOT.exists(), (
    f"Missing original validation root: {VAL_ROOT}"
)

assert TEST_ROOT.exists(), (
    f"Missing official test root: {TEST_ROOT}"
)

train_dataset = ImageFolder(AUG200_TRAIN_ROOT)
val_dataset = ImageFolder(VAL_ROOT)
test_dataset = ImageFolder(TEST_ROOT)

EXPECTED_CLASSES = [
    "00_coral",
    "01_crab",
    "02_diver",
    "03_eel",
    "04_fish",
    "05_fishInGroups",
    "06_flatworm",
    "07_jellyfish",
    "08_marine_dolphin",
    "09_octopus",
    "10_rayfish",
    "11_seaAnemone",
    "12_seaCucumber",
    "13_seaSlug",
    "14_seaUrchin",
    "15_shark",
    "16_shrimp",
    "17_squid",
    "18_starfish",
    "19_turtle",
]

assert len(train_dataset) == 7284
assert len(val_dataset) == 1312
assert len(test_dataset) == 1612

assert train_dataset.classes == EXPECTED_CLASSES
assert val_dataset.classes == EXPECTED_CLASSES
assert test_dataset.classes == EXPECTED_CLASSES

print("\nLOCKED DATASET")
print("-" * 80)
print("Aug-200 train root :", AUG200_TRAIN_ROOT)
print("Original val root  :", VAL_ROOT)
print("Official test root :", TEST_ROOT)
print()
print(f"Aug-200 train       : {len(train_dataset):,}")
print(f"Original val        : {len(val_dataset):,}")
print(f"Official test       : {len(test_dataset):,}")
print(f"Classes             : {len(train_dataset.classes)}")

print("\nCLASS ORDER")
print("-" * 80)

for index, class_name in enumerate(train_dataset.classes):
    print(f"{index:02d} -> {class_name}")

# -------------------------------------------------------------------------
# ConvNeXt-Small verification
# -------------------------------------------------------------------------

print("\nCONVNEXT-SMALL")
print("-" * 80)

weights = ConvNeXt_Small_Weights.DEFAULT
model = convnext_small(weights=weights)

classifier_in_features = model.classifier[2].in_features

model.classifier[2] = torch.nn.Linear(
    classifier_in_features,
    len(EXPECTED_CLASSES),
)

print("Pretrained weights :", weights)
print("Classifier input   :", classifier_in_features)
print("Output classes     :", model.classifier[2].out_features)

assert classifier_in_features == 768
assert model.classifier[2].out_features == 20

print("\n" + "=" * 80)
print("F05 STEP 1 PASSED")
print("=" * 80)
print("Experiment : F05_CONVNEXT_SMALL_AUG200_GENTLE_CB_FOCAL")
print("Method     : ConvNeXt-Small + Aug-200 + Gentle CB Focal")
print("Role       : Combined imbalance intervention")
print("Status     : READY FOR F05 STEP 2")

================================================================================
F05 Step 1 — Environment, dataset, and model verification
================================================================================

ENVIRONMENT
--------------------------------------------------------------------------------
Python      : 3.12.13
Torch       : 2.7.1+cu118
Torchvision : 0.22.1+cu118
CUDA        : True
GPU         : Tesla P100-PCIE-16GB

LOCKED DATASET
--------------------------------------------------------------------------------
Aug-200 train root : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/balanced_train/aug200_imagefolder/train
Original val root  : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/official_imagefolder/val
Official test root : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/official_imagefolder/test

Aug-200 train       : 7,284
Original val        : 1,312
Official test       : 1,612
Classes             : 20

CLASS ORDER
--------------------------------------------------------------------------------
00 -> 00_coral
01 -> 01_crab
02 -> 02_diver
03 -> 03_eel
04 -> 04_fish
05 -> 05_fishInGroups
06 -> 06_flatworm
07 -> 07_jellyfish
08 -> 08_marine_dolphin
09 -> 09_octopus
10 -> 10_rayfish
11 -> 11_seaAnemone
12 -> 12_seaCucumber
13 -> 13_seaSlug
14 -> 14_seaUrchin
15 -> 15_shark
16 -> 16_shrimp
17 -> 17_squid
18 -> 18_starfish
19 -> 19_turtle

CONVNEXT-SMALL
--------------------------------------------------------------------------------
Downloading: "https://download.pytorch.org/models/convnext_small-0c510722.pth" to /root/.cache/torch/hub/checkpoints/convnext_small-0c510722.pth

100%|██████████| 192M/192M [00:01<00:00, 187MB/s]

Pretrained weights : ConvNeXt_Small_Weights.IMAGENET1K_V1
Classifier input   : 768
Output classes     : 20

================================================================================
F05 STEP 1 PASSED
================================================================================
Experiment : F05_CONVNEXT_SMALL_AUG200_GENTLE_CB_FOCAL
Method     : ConvNeXt-Small + Aug-200 + Gentle CB Focal
Role       : Combined imbalance intervention
Status     : READY FOR F05 STEP 2

## Step 2 — Lock and verify Gentle Class-Balanced Focal Loss

This step constructs the official F05 Gentle Class-Balanced Focal Loss using the actual Aug-200 training distribution.

Locked loss parameters:

- Beta: 0.999
- Gamma: 1.0
- Effective-number class weighting
- Class weights normalized by their mean
- Standard per-sample cross-entropy base
- No label smoothing
- No inverse-frequency weighting
- No weighted sampler

The combined F05 loss is:

\[
L = w_y (1-p_t)^\gamma CE
\]

where:

\[
w_y = \frac{1-\beta}{1-\beta^{n_y}}
\]

and the class weights are normalized to have mean 1.

No training or official test evaluation is performed in this step.

In [14]:
# ============================================================
# F05 Step 2 — Lock and verify Gentle CB Focal Loss
# ============================================================

from collections import Counter

import torch
import torch.nn as nn
import torch.nn.functional as F

print("=" * 80)
print("F05 Step 2 — Lock and verify Gentle CB Focal Loss")
print("=" * 80)

# -------------------------------------------------------------------------
# Locked F03 loss parameters reused for F05
# -------------------------------------------------------------------------

BETA = 0.999
GAMMA = 1.0

# -------------------------------------------------------------------------
# Aug-200 training class distribution
# -------------------------------------------------------------------------

class_counts_counter = Counter(train_dataset.targets)

class_counts = torch.tensor(
    [
        class_counts_counter[class_index]
        for class_index in range(len(EXPECTED_CLASSES))
    ],
    dtype=torch.float32,
)

assert int(class_counts.sum().item()) == 7284
assert len(class_counts) == 20

print("\nAUG-200 TRAIN CLASS COUNTS")
print("-" * 80)

for class_index, class_name in enumerate(EXPECTED_CLASSES):
    print(
        f"{class_index:02d} | "
        f"{class_name:<20} | "
        f"{int(class_counts[class_index].item()):4d}"
    )

# -------------------------------------------------------------------------
# Effective-number class weights
# -------------------------------------------------------------------------

effective_weights = (
    (1.0 - BETA)
    / (1.0 - torch.pow(BETA, class_counts))
)

class_weights = effective_weights / effective_weights.mean()

assert torch.isfinite(class_weights).all()
assert abs(class_weights.mean().item() - 1.0) < 1e-6

print("\nNORMALIZED EFFECTIVE-NUMBER CLASS WEIGHTS")
print("-" * 80)

for class_index, class_name in enumerate(EXPECTED_CLASSES):
    print(
        f"{class_index:02d} | "
        f"{class_name:<20} | "
        f"{class_weights[class_index].item():.6f}"
    )

print("\nLOSS CONFIGURATION")
print("-" * 80)
print("Beta                  :", BETA)
print("Gamma                 :", GAMMA)
print("Weight formula        : (1-beta)/(1-beta^count)")
print("Weight normalization  : mean = 1")
print("Label smoothing       : disabled")
print("Inverse-frequency     : disabled")
print("Weighted sampler      : disabled")

# -------------------------------------------------------------------------
# Official Gentle Class-Balanced Focal Loss
# -------------------------------------------------------------------------

class GentleClassBalancedFocalLoss(nn.Module):
    def __init__(
        self,
        class_weights: torch.Tensor,
        gamma: float = 1.0,
    ):
        super().__init__()

        self.register_buffer(
            "class_weights",
            class_weights.clone().detach(),
        )
        self.gamma = gamma

    def forward(
        self,
        logits: torch.Tensor,
        targets: torch.Tensor,
    ) -> torch.Tensor:

        ce_loss = F.cross_entropy(
            logits,
            targets,
            reduction="none",
        )

        pt = torch.exp(-ce_loss)

        focal_factor = torch.pow(
            1.0 - pt,
            self.gamma,
        )

        sample_weights = self.class_weights[targets]

        loss = (
            sample_weights
            * focal_factor
            * ce_loss
        )

        return loss.mean()


criterion = GentleClassBalancedFocalLoss(
    class_weights=class_weights,
    gamma=GAMMA,
)

# -------------------------------------------------------------------------
# Numerical verification
# -------------------------------------------------------------------------

dummy_logits = torch.randn(16, 20)
dummy_targets = torch.randint(0, 20, (16,))

dummy_loss = criterion(
    dummy_logits,
    dummy_targets,
)

assert dummy_loss.ndim == 0
assert torch.isfinite(dummy_loss)
assert dummy_loss.item() > 0

print("\nLOSS VERIFICATION")
print("-" * 80)
print("Dummy batch size      :", len(dummy_targets))
print("Dummy loss            :", f"{dummy_loss.item():.6f}")
print("Finite loss           :", torch.isfinite(dummy_loss).item())
print("Positive loss         :", dummy_loss.item() > 0)

print("\n" + "=" * 80)
print("F05 STEP 2 PASSED")
print("=" * 80)
print("Experiment : F05_CONVNEXT_SMALL_AUG200_GENTLE_CB_FOCAL")
print("Beta       : 0.999")
print("Gamma      : 1.0")
print("Weights    : Aug-200 effective-number normalized weights")
print("Loss       : Gentle Class-Balanced Focal Loss")
print("Status     : READY FOR F05 STEP 3")

================================================================================
F05 Step 2 — Lock and verify Gentle CB Focal Loss
================================================================================

AUG-200 TRAIN CLASS COUNTS
--------------------------------------------------------------------------------
00 | 00_coral             | 1249
01 | 01_crab              |  200
02 | 02_diver             |  200
03 | 03_eel               |  200
04 | 04_fish              | 1760
05 | 05_fishInGroups      |  218
06 | 06_flatworm          |  200
07 | 07_jellyfish         |  200
08 | 08_marine_dolphin    |  200
09 | 09_octopus           |  200
10 | 10_rayfish           |  305
11 | 11_seaAnemone        |  712
12 | 12_seaCucumber       |  200
13 | 13_seaSlug           |  200
14 | 14_seaUrchin         |  200
15 | 15_shark             |  200
16 | 16_shrimp            |  200
17 | 17_squid             |  200
18 | 18_starfish          |  200
19 | 19_turtle            |  240

NORMALIZED EFFECTIVE-NUMBER CLASS WEIGHTS
--------------------------------------------------------------------------------
00 | 00_coral             | 0.293991
01 | 01_crab              | 1.156491
02 | 02_diver             | 1.156491
03 | 03_eel               | 1.156491
04 | 04_fish              | 0.253264
05 | 05_fishInGroups      | 1.070262
06 | 06_flatworm          | 1.156491
07 | 07_jellyfish         | 1.156491
08 | 08_marine_dolphin    | 1.156491
09 | 09_octopus           | 1.156491
10 | 10_rayfish           | 0.797488
11 | 11_seaAnemone        | 0.411629
12 | 12_seaCucumber       | 1.156491
13 | 13_seaSlug           | 1.156491
14 | 14_seaUrchin         | 1.156491
15 | 15_shark             | 1.156491
16 | 16_shrimp            | 1.156491
17 | 17_squid             | 1.156491
18 | 18_starfish          | 1.156491
19 | 19_turtle            | 0.982500

LOSS CONFIGURATION
--------------------------------------------------------------------------------
Beta                  : 0.999
Gamma                 : 1.0
Weight formula        : (1-beta)/(1-beta^count)
Weight normalization  : mean = 1
Label smoothing       : disabled
Inverse-frequency     : disabled
Weighted sampler      : disabled

LOSS VERIFICATION
--------------------------------------------------------------------------------
Dummy batch size      : 16
Dummy loss            : 2.820576
Finite loss           : True
Positive loss         : True

================================================================================
F05 STEP 2 PASSED
================================================================================
Experiment : F05_CONVNEXT_SMALL_AUG200_GENTLE_CB_FOCAL
Beta       : 0.999
Gamma      : 1.0
Weights    : Aug-200 effective-number normalized weights
Loss       : Gentle Class-Balanced Focal Loss
Status     : READY FOR F05 STEP 3



## Step 3 — Official F05 training and best-checkpoint selection

This step trains the official F05 model:

**ConvNeXt-Small + Aug-200 + Gentle Class-Balanced Focal Loss**

Locked training configuration:

- Image size: 224 × 224
- Batch size: 16
- Optimizer: AdamW
- Learning rate: 1e-5
- Weight decay: 1e-4
- Scheduler: CosineAnnealingLR
- Maximum epochs: 25
- Seed: 42
- Training data: Aug-200 train-only balancing
- Validation data: unchanged original validation split
- Loss: Gentle Class-Balanced Focal Loss
- Best checkpoint selected strictly by validation Macro F1

The training protocol follows the established F03/F04 ConvNeXt workflow.

Strict global deterministic algorithms are not enabled.

The official test split is not used during training or checkpoint selection.

In [16]:
# ============================================================
# F05 Step 3 — Official training and best-checkpoint selection
# FINAL CORRECTED VERSION
# ============================================================

import csv
import hashlib
import random
import time
from pathlib import Path

import numpy as np
import torch
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_score,
    recall_score,
)
from torch.optim import AdamW
from torch.optim.lr_scheduler import CosineAnnealingLR
from torch.utils.data import DataLoader
from torchvision.datasets import ImageFolder
from torchvision.models import (
    convnext_small,
    ConvNeXt_Small_Weights,
)
from torchvision.transforms import v2

print("=" * 100)
print("F05 Step 3 — Official training and best-checkpoint selection")
print("=" * 100)

# -------------------------------------------------------------------------
# Locked configuration
# -------------------------------------------------------------------------

SEED = 42
IMAGE_SIZE = 224
BATCH_SIZE = 16
NUM_WORKERS = 4
MAX_EPOCHS = 25

LEARNING_RATE = 1e-5
WEIGHT_DECAY = 1e-4

EXPERIMENT_NAME = (
    "F05_CONVNEXT_SMALL_AUG200_GENTLE_CB_FOCAL"
)

F05_ROOT = (
    PROJECT_ROOT
    / "F05_CONVNEXT_SMALL_AUG200_GENTLE_CB_FOCAL"
)

WEIGHTS_DIR = F05_ROOT / "weights"
TABLES_DIR = F05_ROOT / "tables"

BEST_CHECKPOINT = (
    WEIGHTS_DIR / "best_model.pth"
)

HISTORY_CSV = (
    TABLES_DIR / "F05_training_history.csv"
)

WEIGHTS_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

TABLES_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

# -------------------------------------------------------------------------
# Clean stale Step 3 files before official rerun
# -------------------------------------------------------------------------

if BEST_CHECKPOINT.exists():
    BEST_CHECKPOINT.unlink()

if HISTORY_CSV.exists():
    HISTORY_CSV.unlink()

# -------------------------------------------------------------------------
# Reproducibility — aligned with F03/F04 ConvNeXt workflow
# -------------------------------------------------------------------------

random.seed(SEED)
np.random.seed(SEED)

torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed(SEED)
    torch.cuda.manual_seed_all(SEED)

torch.use_deterministic_algorithms(False)

torch.backends.cudnn.deterministic = False
torch.backends.cudnn.benchmark = True

device = torch.device(
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)

print("\n" + "=" * 100)
print("LOCKED TRAINING CONFIGURATION")
print("=" * 100)

print(f"Experiment              : {EXPERIMENT_NAME}")
print(f"Device                  : {device}")

if device.type == "cuda":
    print(
        "GPU                     :",
        torch.cuda.get_device_name(0),
    )

print(f"Image size              : {IMAGE_SIZE}")
print(f"Batch size              : {BATCH_SIZE}")
print(f"Workers                 : {NUM_WORKERS}")
print(f"Maximum epochs          : {MAX_EPOCHS}")
print("Optimizer               : AdamW")
print(f"Learning rate           : {LEARNING_RATE}")
print(f"Weight decay            : {WEIGHT_DECAY}")
print("Scheduler               : CosineAnnealingLR")
print("Loss                    : Gentle CB Focal")
print(f"Beta                    : {BETA}")
print(f"Gamma                   : {GAMMA}")
print("Checkpoint rule         : Validation Macro F1")
print(f"Seed                    : {SEED}")
print(
    "Strict deterministic    :",
    torch.are_deterministic_algorithms_enabled(),
)
print(
    "cuDNN deterministic     :",
    torch.backends.cudnn.deterministic,
)
print(
    "cuDNN benchmark         :",
    torch.backends.cudnn.benchmark,
)
print(
    "CUBLAS_WORKSPACE_CONFIG :",
    os.environ.get("CUBLAS_WORKSPACE_CONFIG"),
)

# -------------------------------------------------------------------------
# Official transforms
# -------------------------------------------------------------------------

weights = ConvNeXt_Small_Weights.DEFAULT

weights_transforms = weights.transforms()

train_transform = v2.Compose([
    v2.Resize(
        (IMAGE_SIZE, IMAGE_SIZE)
    ),
    v2.RandomHorizontalFlip(
        p=0.5
    ),
    v2.RandomRotation(
        degrees=10
    ),
    v2.ToImage(),
    v2.ToDtype(
        torch.float32,
        scale=True,
    ),
    v2.Normalize(
        mean=weights_transforms.mean,
        std=weights_transforms.std,
    ),
])

eval_transform = v2.Compose([
    v2.Resize(
        (IMAGE_SIZE, IMAGE_SIZE)
    ),
    v2.ToImage(),
    v2.ToDtype(
        torch.float32,
        scale=True,
    ),
    v2.Normalize(
        mean=weights_transforms.mean,
        std=weights_transforms.std,
    ),
])

# -------------------------------------------------------------------------
# Official F05 train and validation datasets
# -------------------------------------------------------------------------

train_dataset_f05 = ImageFolder(
    AUG200_TRAIN_ROOT,
    transform=train_transform,
)

val_dataset_f05 = ImageFolder(
    VAL_ROOT,
    transform=eval_transform,
)

assert (
    train_dataset_f05.classes
    == EXPECTED_CLASSES
)

assert (
    val_dataset_f05.classes
    == EXPECTED_CLASSES
)

assert len(train_dataset_f05) == 7284
assert len(val_dataset_f05) == 1312

train_generator = torch.Generator()
train_generator.manual_seed(SEED)

train_loader = DataLoader(
    train_dataset_f05,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=NUM_WORKERS,
    pin_memory=True,
    persistent_workers=True,
    generator=train_generator,
)

val_loader = DataLoader(
    val_dataset_f05,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=True,
    persistent_workers=True,
)

print("\n" + "=" * 100)
print("LOCKED DATA")
print("=" * 100)

print(
    f"Aug-200 train           : "
    f"{len(train_dataset_f05):,}"
)

print(
    f"Original validation     : "
    f"{len(val_dataset_f05):,}"
)

print(
    f"Classes                 : "
    f"{len(EXPECTED_CLASSES)}"
)

print("Official test used      : NO")

# -------------------------------------------------------------------------
# Fresh official ConvNeXt-Small model
# -------------------------------------------------------------------------

torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

model = convnext_small(
    weights=weights,
)

classifier_in_features = (
    model.classifier[2].in_features
)

model.classifier[2] = torch.nn.Linear(
    classifier_in_features,
    len(EXPECTED_CLASSES),
)

model = model.to(device)

# -------------------------------------------------------------------------
# Official F05 loss
# -------------------------------------------------------------------------

criterion = GentleClassBalancedFocalLoss(
    class_weights=class_weights,
    gamma=GAMMA,
).to(device)

# -------------------------------------------------------------------------
# Optimizer and scheduler
# -------------------------------------------------------------------------

optimizer = AdamW(
    model.parameters(),
    lr=LEARNING_RATE,
    weight_decay=WEIGHT_DECAY,
)

scheduler = CosineAnnealingLR(
    optimizer,
    T_max=MAX_EPOCHS,
)

scaler = torch.amp.GradScaler(
    "cuda",
    enabled=(device.type == "cuda"),
)

# -------------------------------------------------------------------------
# Training state
# -------------------------------------------------------------------------

best_val_macro_f1 = -1.0
best_epoch = -1

history_rows = []

# -------------------------------------------------------------------------
# Display header
# -------------------------------------------------------------------------

print("\n" + "=" * 100)
print("OFFICIAL F05 TRAINING STARTED")
print("=" * 100)

print(
    f"{'EP':>3} | "
    f"{'LR':>10} | "
    f"{'TR LOSS':>8} | "
    f"{'TR ACC':>9} | "
    f"{'TR F1':>9} | "
    f"{'VAL LOSS':>8} | "
    f"{'VAL ACC':>9} | "
    f"{'VAL P':>9} | "
    f"{'VAL R':>9} | "
    f"{'VAL F1':>9} | "
    f"{'TIME':>7} | "
    f"CHECKPOINT"
)

print("-" * 160)

# -------------------------------------------------------------------------
# Official training loop
# -------------------------------------------------------------------------

training_start_time = time.time()

for epoch in range(
    1,
    MAX_EPOCHS + 1,
):

    epoch_start_time = time.time()

    # =====================================================================
    # TRAIN
    # =====================================================================

    model.train()

    train_loss_sum = 0.0

    train_targets = []
    train_predictions = []

    for images, targets in train_loader:

        images = images.to(
            device,
            non_blocking=True,
        )

        targets = targets.to(
            device,
            non_blocking=True,
        )

        optimizer.zero_grad(
            set_to_none=True
        )

        with torch.amp.autocast(
            device_type=device.type,
            enabled=(device.type == "cuda"),
        ):

            logits = model(images)

            loss = criterion(
                logits,
                targets,
            )

        scaler.scale(loss).backward()

        scaler.step(optimizer)

        scaler.update()

        train_loss_sum += (
            loss.item()
            * images.size(0)
        )

        predictions = logits.argmax(
            dim=1
        )

        train_targets.extend(
            targets.detach()
            .cpu()
            .tolist()
        )

        train_predictions.extend(
            predictions.detach()
            .cpu()
            .tolist()
        )

    train_loss = (
        train_loss_sum
        / len(train_dataset_f05)
    )

    train_accuracy = accuracy_score(
        train_targets,
        train_predictions,
    )

    train_macro_f1 = f1_score(
        train_targets,
        train_predictions,
        average="macro",
        zero_division=0,
    )

    # =====================================================================
    # VALIDATION
    # =====================================================================

    model.eval()

    val_loss_sum = 0.0

    val_targets = []
    val_predictions = []

    with torch.inference_mode():

        for images, targets in val_loader:

            images = images.to(
                device,
                non_blocking=True,
            )

            targets = targets.to(
                device,
                non_blocking=True,
            )

            with torch.amp.autocast(
                device_type=device.type,
                enabled=(device.type == "cuda"),
            ):

                logits = model(images)

                loss = criterion(
                    logits,
                    targets,
                )

            val_loss_sum += (
                loss.item()
                * images.size(0)
            )

            predictions = logits.argmax(
                dim=1
            )

            val_targets.extend(
                targets.detach()
                .cpu()
                .tolist()
            )

            val_predictions.extend(
                predictions.detach()
                .cpu()
                .tolist()
            )

    val_loss = (
        val_loss_sum
        / len(val_dataset_f05)
    )

    val_accuracy = accuracy_score(
        val_targets,
        val_predictions,
    )

    val_macro_precision = precision_score(
        val_targets,
        val_predictions,
        average="macro",
        zero_division=0,
    )

    val_macro_recall = recall_score(
        val_targets,
        val_predictions,
        average="macro",
        zero_division=0,
    )

    val_macro_f1 = f1_score(
        val_targets,
        val_predictions,
        average="macro",
        zero_division=0,
    )

    current_lr = (
        optimizer.param_groups[0]["lr"]
    )

    epoch_seconds = (
        time.time()
        - epoch_start_time
    )

    # =====================================================================
    # BEST CHECKPOINT — VALIDATION MACRO F1 ONLY
    # =====================================================================

    checkpoint_status = ""

    if (
        val_macro_f1
        > best_val_macro_f1
    ):

        best_val_macro_f1 = (
            val_macro_f1
        )

        best_epoch = epoch

        torch.save(
            {
                "experiment": EXPERIMENT_NAME,
                "epoch": epoch,
                "model_state_dict":
                    model.state_dict(),
                "optimizer_state_dict":
                    optimizer.state_dict(),
                "scheduler_state_dict":
                    scheduler.state_dict(),
                "val_macro_f1":
                    val_macro_f1,
                "val_accuracy":
                    val_accuracy,
                "val_macro_precision":
                    val_macro_precision,
                "val_macro_recall":
                    val_macro_recall,
                "class_names":
                    EXPECTED_CLASSES,
                "class_weights":
                    class_weights.cpu(),
                "beta":
                    BETA,
                "gamma":
                    GAMMA,
                "image_size":
                    IMAGE_SIZE,
                "batch_size":
                    BATCH_SIZE,
                "learning_rate":
                    LEARNING_RATE,
                "weight_decay":
                    WEIGHT_DECAY,
                "seed":
                    SEED,
                "checkpoint_rule":
                    "validation_macro_f1",
            },
            BEST_CHECKPOINT,
        )

        checkpoint_status = "★ BEST SAVED"

    # =====================================================================
    # HISTORY
    # =====================================================================

    history_rows.append({
        "epoch":
            epoch,
        "learning_rate":
            current_lr,
        "train_loss":
            train_loss,
        "train_accuracy":
            train_accuracy,
        "train_macro_f1":
            train_macro_f1,
        "val_loss":
            val_loss,
        "val_accuracy":
            val_accuracy,
        "val_macro_precision":
            val_macro_precision,
        "val_macro_recall":
            val_macro_recall,
        "val_macro_f1":
            val_macro_f1,
        "epoch_seconds":
            epoch_seconds,
        "best_checkpoint_saved":
            checkpoint_status
            == "★ BEST SAVED",
    })

    # =====================================================================
    # CLEAN EPOCH DISPLAY
    # =====================================================================

    print(
        f"{epoch:>3} | "
        f"{current_lr:>10.8f} | "
        f"{train_loss:>8.4f} | "
        f"{train_accuracy * 100:>8.4f}% | "
        f"{train_macro_f1 * 100:>8.4f}% | "
        f"{val_loss:>8.4f} | "
        f"{val_accuracy * 100:>8.4f}% | "
        f"{val_macro_precision * 100:>8.4f}% | "
        f"{val_macro_recall * 100:>8.4f}% | "
        f"{val_macro_f1 * 100:>8.4f}% | "
        f"{epoch_seconds:>6.1f}s | "
        f"{checkpoint_status}"
    )

    if checkpoint_status:

        print(
            f"      └── New best checkpoint locked: "
            f"Epoch {best_epoch:02d} | "
            f"Val Macro F1 "
            f"{best_val_macro_f1 * 100:.4f}%"
        )

    scheduler.step()

# -------------------------------------------------------------------------
# Save complete training history
# -------------------------------------------------------------------------

with open(
    HISTORY_CSV,
    "w",
    newline="",
    encoding="utf-8",
) as csv_file:

    writer = csv.DictWriter(
        csv_file,
        fieldnames=history_rows[0].keys(),
    )

    writer.writeheader()
    writer.writerows(history_rows)

# -------------------------------------------------------------------------
# Verify and hash locked best checkpoint
# -------------------------------------------------------------------------

assert BEST_CHECKPOINT.exists()
assert HISTORY_CSV.exists()

sha256 = hashlib.sha256()

with open(
    BEST_CHECKPOINT,
    "rb",
) as checkpoint_file:

    for block in iter(
        lambda: checkpoint_file.read(
            1024 * 1024
        ),
        b"",
    ):
        sha256.update(block)

best_checkpoint_sha256 = (
    sha256.hexdigest()
)

total_training_seconds = (
    time.time()
    - training_start_time
)

# -------------------------------------------------------------------------
# Final official Step 3 summary
# -------------------------------------------------------------------------

print("\n" + "=" * 100)
print("F05 STEP 3 PASSED — OFFICIAL TRAINING COMPLETED")
print("=" * 100)

print(
    "Experiment            :",
    EXPERIMENT_NAME,
)

print(
    "Best checkpoint rule  :",
    "Validation Macro F1",
)

print(
    "Best epoch            :",
    best_epoch,
)

print(
    "Best Val Macro F1     :",
    f"{best_val_macro_f1 * 100:.4f}%",
)

print(
    "Best checkpoint       :",
    BEST_CHECKPOINT,
)

print(
    "Checkpoint SHA-256    :",
    best_checkpoint_sha256,
)

print(
    "Training history      :",
    HISTORY_CSV,
)

print(
    "Total training time   :",
    f"{total_training_seconds / 60:.2f} minutes",
)

print(
    "Official test used    :",
    "NO",
)

print(
    "Status                :",
    "READY FOR F05 STEP 4",
)

====================================================================================================
F05 Step 3 — Official training and best-checkpoint selection
====================================================================================================

====================================================================================================
LOCKED TRAINING CONFIGURATION
====================================================================================================
Experiment              : F05_CONVNEXT_SMALL_AUG200_GENTLE_CB_FOCAL
Device                  : cuda
GPU                     : Tesla P100-PCIE-16GB
Image size              : 224
Batch size              : 16
Workers                 : 4
Maximum epochs          : 25
Optimizer               : AdamW
Learning rate           : 1e-05
Weight decay            : 0.0001
Scheduler               : CosineAnnealingLR
Loss                    : Gentle CB Focal
Beta                    : 0.999
Gamma                   : 1.0
Checkpoint rule         : Validation Macro F1
Seed                    : 42
Strict deterministic    : False
cuDNN deterministic     : False
cuDNN benchmark         : True
CUBLAS_WORKSPACE_CONFIG : :4096:8

====================================================================================================
LOCKED DATA
====================================================================================================
Aug-200 train           : 7,284
Original validation     : 1,312
Classes                 : 20
Official test used      : NO

====================================================================================================
OFFICIAL F05 TRAINING STARTED
====================================================================================================
 EP |         LR |  TR LOSS |    TR ACC |     TR F1 | VAL LOSS |   VAL ACC |     VAL P |     VAL R |    VAL F1 |    TIME | CHECKPOINT
----------------------------------------------------------------------------------------------------------------------------------------------------------------
  1 | 0.00001000 |   1.1581 |  62.9050% |  58.6688% |   0.2679 |  86.2805% |  72.7244% |  83.2991% |  75.9875% |  143.5s | ★ BEST SAVED
      └── New best checkpoint locked: Epoch 01 | Val Macro F1 75.9875%
  2 | 0.00000996 |   0.2762 |  89.0308% |  90.3780% |   0.1197 |  89.6341% |  83.0670% |  88.6450% |  84.6297% |  138.4s | ★ BEST SAVED
      └── New best checkpoint locked: Epoch 02 | Val Macro F1 84.6297%
  3 | 0.00000984 |   0.1273 |  92.3394% |  93.8593% |   0.1022 |  90.9299% |  84.4064% |  90.3373% |  86.6004% |  138.5s | ★ BEST SAVED
      └── New best checkpoint locked: Epoch 03 | Val Macro F1 86.6004%
  4 | 0.00000965 |   0.0815 |  94.0967% |  95.6870% |   0.0945 |  92.3780% |  88.4780% |  91.1175% |  89.0477% |  138.8s | ★ BEST SAVED
      └── New best checkpoint locked: Epoch 04 | Val Macro F1 89.0477%
  5 | 0.00000938 |   0.0592 |  94.7007% |  96.2221% |   0.0934 |  91.4634% |  86.7998% |  88.9102% |  86.7929% |  138.5s |
  6 | 0.00000905 |   0.0468 |  95.5107% |  96.9820% |   0.0889 |  91.7683% |  87.8392% |  90.0224% |  87.8702% |  138.5s |
  7 | 0.00000864 |   0.0364 |  96.2521% |  97.5200% |   0.0927 |  92.1494% |  88.4686% |  88.3272% |  87.2844% |  138.3s |
  8 | 0.00000819 |   0.0322 |  96.6090% |  97.7382% |   0.0940 |  92.7591% |  89.6011% |  91.0402% |  89.6506% |  138.3s | ★ BEST SAVED
      └── New best checkpoint locked: Epoch 08 | Val Macro F1 89.6506%
  9 | 0.00000768 |   0.0270 |  96.9797% |  98.0375% |   0.0944 |  91.6921% |  87.5561% |  87.5164% |  86.3414% |  138.6s |
 10 | 0.00000713 |   0.0242 |  97.2954% |  98.1586% |   0.0918 |  92.7591% |  89.0149% |  89.6149% |  88.4596% |  138.3s |
 11 | 0.00000655 |   0.0186 |  97.5288% |  98.4858% |   0.0977 |  92.3780% |  88.1473% |  88.1138% |  87.2086% |  138.5s |
 12 | 0.00000594 |   0.0181 |  97.6661% |  98.5512% |   0.0993 |  93.1402% |  89.4358% |  88.4305% |  87.9202% |  138.4s |
 13 | 0.00000531 |   0.0151 |  98.2702% |  98.9483% |   0.1030 |  92.6067% |  89.4706% |  91.5535% |  89.9031% |  138.6s | ★ BEST SAVED
      └── New best checkpoint locked: Epoch 13 | Val Macro F1 89.9031%
 14 | 0.00000469 |   0.0134 |  98.4487% |  99.0093% |   0.1001 |  92.9878% |  89.9708% |  90.8314% |  89.3699% |  138.5s |
 15 | 0.00000406 |   0.0117 |  98.5997% |  99.1197% |   0.1085 |  92.8354% |  89.1579% |  89.6007% |  88.6772% |  138.3s |
 16 | 0.00000345 |   0.0105 |  98.7919% |  99.2356% |   0.1092 |  92.9116% |  88.9697% |  88.3273% |  87.6190% |  138.5s |
 17 | 0.00000287 |   0.0105 |  98.6683% |  99.1482% |   0.1071 |  92.8354% |  89.2602% |  89.6940% |  88.7813% |  138.6s |
 18 | 0.00000232 |   0.0090 |  98.9154% |  99.3416% |   0.1032 |  92.9878% |  89.4981% |  90.8675% |  89.6947% |  138.5s |
 19 | 0.00000181 |   0.0085 |  98.9703% |  99.3334% |   0.1069 |  93.3689% |  89.9782% |  90.5374% |  89.3582% |  138.4s |
 20 | 0.00000136 |   0.0076 |  99.0664% |  99.4835% |   0.1089 |  93.2927% |  90.0635% |  91.0146% |  89.9326% |  138.3s | ★ BEST SAVED
      └── New best checkpoint locked: Epoch 20 | Val Macro F1 89.9326%
 21 | 0.00000095 |   0.0072 |  99.1076% |  99.5145% |   0.1109 |  93.3689% |  89.9782% |  89.7874% |  88.9476% |  138.3s |
 22 | 0.00000062 |   0.0067 |  99.1488% |  99.5507% |   0.1112 |  93.3689% |  89.9249% |  89.7874% |  88.9135% |  138.6s |
 23 | 0.00000035 |   0.0065 |  99.2586% |  99.5023% |   0.1103 |  93.3689% |  89.9782% |  89.7874% |  88.9476% |  138.4s |
 24 | 0.00000016 |   0.0077 |  98.8468% |  99.3982% |   0.1100 |  93.4451% |  90.2061% |  89.8523% |  89.1033% |  138.3s |
 25 | 0.00000004 |   0.0068 |  99.2586% |  99.6130% |   0.1099 |  93.4451% |  90.2061% |  89.8523% |  89.1033% |  138.5s |

====================================================================================================
F05 STEP 3 PASSED — OFFICIAL TRAINING COMPLETED
====================================================================================================
Experiment            : F05_CONVNEXT_SMALL_AUG200_GENTLE_CB_FOCAL
Best checkpoint rule  : Validation Macro F1
Best epoch            : 20
Best Val Macro F1     : 89.9326%
Best checkpoint       : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/F05_CONVNEXT_SMALL_AUG200_GENTLE_CB_FOCAL/weights/best_model.pth
Checkpoint SHA-256    : 548e7c7d925f0272d06a5e57b682364b2affe302ff5c7c5071461ebde0b2e3f3
Training history      : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/F05_CONVNEXT_SMALL_AUG200_GENTLE_CB_FOCAL/tables/F05_training_history.csv
Total training time   : 57.96 minutes
Official test used    : NO
Status                : READY FOR F05 STEP 4

## Step 4 — Official unchanged test evaluation and paper metrics

This step evaluates the locked F05 best checkpoint on the unchanged official AQUA20 test split.

Locked checkpoint:

- Best epoch: 20
- Selection rule: Validation Macro F1
- Validation Macro F1: 89.9326%
- SHA-256: `548e7c7d925f0272d06a5e57b682364b2affe302ff5c7c5071461ebde0b2e3f3`

Reported official test metrics:

- Top-1 Accuracy
- Top-2 Accuracy
- Top-3 Accuracy
- Top-5 Accuracy
- Macro Precision
- Macro Recall
- Macro F1
- Weighted F1

The test split contains 1,612 unchanged images and is not used for checkpoint selection.

In [17]:
# ============================================================
# F05 Step 4 — Official test evaluation and paper metrics
# ============================================================

import csv
import hashlib

import numpy as np
import torch
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
)
from torch.utils.data import DataLoader
from torchvision.datasets import ImageFolder
from torchvision.models import (
    convnext_small,
    ConvNeXt_Small_Weights,
)

print("=" * 100)
print("F05 Step 4 — Official test evaluation and paper metrics")
print("=" * 100)

# -------------------------------------------------------------------------
# Locked checkpoint verification
# -------------------------------------------------------------------------

EXPECTED_CHECKPOINT_SHA256 = (
    "548e7c7d925f0272d06a5e57b682364b2affe302ff5c7c5071461ebde0b2e3f3"
)

sha256 = hashlib.sha256()

with open(BEST_CHECKPOINT, "rb") as checkpoint_file:
    for block in iter(
        lambda: checkpoint_file.read(1024 * 1024),
        b"",
    ):
        sha256.update(block)

checkpoint_sha256 = sha256.hexdigest()

assert checkpoint_sha256 == EXPECTED_CHECKPOINT_SHA256

print("\nLOCKED CHECKPOINT")
print("-" * 100)
print("Checkpoint :", BEST_CHECKPOINT)
print("SHA-256   :", checkpoint_sha256)
print("Hash match :", checkpoint_sha256 == EXPECTED_CHECKPOINT_SHA256)

# -------------------------------------------------------------------------
# Official unchanged test dataset
# -------------------------------------------------------------------------

test_dataset_f05 = ImageFolder(
    TEST_ROOT,
    transform=eval_transform,
)

assert test_dataset_f05.classes == EXPECTED_CLASSES
assert len(test_dataset_f05) == 1612

test_loader = DataLoader(
    test_dataset_f05,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=True,
    persistent_workers=True,
)

print("\nOFFICIAL TEST SPLIT")
print("-" * 100)
print(f"Test images : {len(test_dataset_f05):,}")
print(f"Classes     : {len(EXPECTED_CLASSES)}")
print("Split       : UNCHANGED OFFICIAL TEST")

# -------------------------------------------------------------------------
# Load locked F05 checkpoint
# -------------------------------------------------------------------------

checkpoint = torch.load(
    BEST_CHECKPOINT,
    map_location=device,
    weights_only=False,
)

assert checkpoint["experiment"] == EXPERIMENT_NAME
assert checkpoint["epoch"] == 20
assert checkpoint["class_names"] == EXPECTED_CLASSES
assert checkpoint["checkpoint_rule"] == "validation_macro_f1"

test_model = convnext_small(
    weights=None,
)

classifier_in_features = (
    test_model.classifier[2].in_features
)

test_model.classifier[2] = torch.nn.Linear(
    classifier_in_features,
    len(EXPECTED_CLASSES),
)

test_model.load_state_dict(
    checkpoint["model_state_dict"]
)

test_model = test_model.to(device)
test_model.eval()

print("\nMODEL LOCK")
print("-" * 100)
print("Experiment        :", checkpoint["experiment"])
print("Best epoch        :", checkpoint["epoch"])
print(
    "Val Macro F1      :",
    f"{checkpoint['val_macro_f1'] * 100:.4f}%",
)
print("Checkpoint rule   :", checkpoint["checkpoint_rule"])
print("Loss beta         :", checkpoint["beta"])
print("Loss gamma        :", checkpoint["gamma"])

# -------------------------------------------------------------------------
# Official test inference
# -------------------------------------------------------------------------

all_targets = []
all_predictions = []
all_probabilities = []

print("\n" + "=" * 100)
print("OFFICIAL F05 TEST EVALUATION")
print("=" * 100)

with torch.inference_mode():

    for images, targets in test_loader:

        images = images.to(
            device,
            non_blocking=True,
        )

        with torch.amp.autocast(
            device_type=device.type,
            enabled=(device.type == "cuda"),
        ):
            logits = test_model(images)

        probabilities = torch.softmax(
            logits.float(),
            dim=1,
        )

        predictions = probabilities.argmax(
            dim=1,
        )

        all_targets.extend(
            targets.numpy().tolist()
        )

        all_predictions.extend(
            predictions.cpu().numpy().tolist()
        )

        all_probabilities.append(
            probabilities.cpu().numpy()
        )

all_targets = np.asarray(
    all_targets,
    dtype=np.int64,
)

all_predictions = np.asarray(
    all_predictions,
    dtype=np.int64,
)

all_probabilities = np.concatenate(
    all_probabilities,
    axis=0,
)

assert len(all_targets) == 1612
assert all_probabilities.shape == (1612, 20)

# -------------------------------------------------------------------------
# Top-k metrics
# -------------------------------------------------------------------------

def calculate_topk_accuracy(
    probabilities,
    targets,
    k,
):
    topk_indices = np.argsort(
        probabilities,
        axis=1,
    )[:, -k:]

    correct = np.any(
        topk_indices == targets[:, None],
        axis=1,
    )

    return float(correct.mean())


top1_accuracy = calculate_topk_accuracy(
    all_probabilities,
    all_targets,
    1,
)

top2_accuracy = calculate_topk_accuracy(
    all_probabilities,
    all_targets,
    2,
)

top3_accuracy = calculate_topk_accuracy(
    all_probabilities,
    all_targets,
    3,
)

top5_accuracy = calculate_topk_accuracy(
    all_probabilities,
    all_targets,
    5,
)

macro_precision = precision_score(
    all_targets,
    all_predictions,
    average="macro",
    zero_division=0,
)

macro_recall = recall_score(
    all_targets,
    all_predictions,
    average="macro",
    zero_division=0,
)

macro_f1 = f1_score(
    all_targets,
    all_predictions,
    average="macro",
    zero_division=0,
)

weighted_f1 = f1_score(
    all_targets,
    all_predictions,
    average="weighted",
    zero_division=0,
)

# -------------------------------------------------------------------------
# Save official summary
# -------------------------------------------------------------------------

TEST_METRICS_CSV = (
    TABLES_DIR
    / "F05_test_metrics_summary.csv"
)

metric_rows = [
    {
        "metric": "Top-1 Accuracy",
        "value": top1_accuracy,
        "percentage": top1_accuracy * 100,
    },
    {
        "metric": "Top-2 Accuracy",
        "value": top2_accuracy,
        "percentage": top2_accuracy * 100,
    },
    {
        "metric": "Top-3 Accuracy",
        "value": top3_accuracy,
        "percentage": top3_accuracy * 100,
    },
    {
        "metric": "Top-5 Accuracy",
        "value": top5_accuracy,
        "percentage": top5_accuracy * 100,
    },
    {
        "metric": "Macro Precision",
        "value": macro_precision,
        "percentage": macro_precision * 100,
    },
    {
        "metric": "Macro Recall",
        "value": macro_recall,
        "percentage": macro_recall * 100,
    },
    {
        "metric": "Macro F1",
        "value": macro_f1,
        "percentage": macro_f1 * 100,
    },
    {
        "metric": "Weighted F1",
        "value": weighted_f1,
        "percentage": weighted_f1 * 100,
    },
]

with open(
    TEST_METRICS_CSV,
    "w",
    newline="",
    encoding="utf-8",
) as csv_file:

    writer = csv.DictWriter(
        csv_file,
        fieldnames=[
            "metric",
            "value",
            "percentage",
        ],
    )

    writer.writeheader()
    writer.writerows(metric_rows)

# -------------------------------------------------------------------------
# Save classification report
# -------------------------------------------------------------------------

CLASSIFICATION_REPORT_CSV = (
    TABLES_DIR
    / "F05_classification_report.csv"
)

report = classification_report(
    all_targets,
    all_predictions,
    target_names=EXPECTED_CLASSES,
    output_dict=True,
    zero_division=0,
)

report_rows = []

for label, values in report.items():

    if isinstance(values, dict):

        report_rows.append({
            "class": label,
            "precision": values["precision"],
            "recall": values["recall"],
            "f1_score": values["f1-score"],
            "support": values["support"],
        })

with open(
    CLASSIFICATION_REPORT_CSV,
    "w",
    newline="",
    encoding="utf-8",
) as csv_file:

    writer = csv.DictWriter(
        csv_file,
        fieldnames=[
            "class",
            "precision",
            "recall",
            "f1_score",
            "support",
        ],
    )

    writer.writeheader()
    writer.writerows(report_rows)

# -------------------------------------------------------------------------
# Save predictions
# -------------------------------------------------------------------------

PREDICTIONS_CSV = (
    TABLES_DIR
    / "F05_test_predictions.csv"
)

with open(
    PREDICTIONS_CSV,
    "w",
    newline="",
    encoding="utf-8",
) as csv_file:

    writer = csv.writer(csv_file)

    writer.writerow([
        "image_path",
        "true_index",
        "true_class",
        "predicted_index",
        "predicted_class",
        "predicted_probability",
    ])

    for sample_index, (
        image_path,
        _,
    ) in enumerate(test_dataset_f05.samples):

        true_index = int(
            all_targets[sample_index]
        )

        predicted_index = int(
            all_predictions[sample_index]
        )

        predicted_probability = float(
            all_probabilities[
                sample_index,
                predicted_index,
            ]
        )

        writer.writerow([
            image_path,
            true_index,
            EXPECTED_CLASSES[true_index],
            predicted_index,
            EXPECTED_CLASSES[predicted_index],
            predicted_probability,
        ])

# -------------------------------------------------------------------------
# Save confusion matrices
# -------------------------------------------------------------------------

CONFUSION_MATRIX_CSV = (
    TABLES_DIR
    / "F05_confusion_matrix.csv"
)

CONFUSION_MATRIX_NORMALIZED_CSV = (
    TABLES_DIR
    / "F05_confusion_matrix_normalized.csv"
)

cm = confusion_matrix(
    all_targets,
    all_predictions,
)

cm_normalized = cm.astype(
    np.float64
)

row_sums = cm_normalized.sum(
    axis=1,
    keepdims=True,
)

cm_normalized = np.divide(
    cm_normalized,
    row_sums,
    out=np.zeros_like(cm_normalized),
    where=row_sums != 0,
)

np.savetxt(
    CONFUSION_MATRIX_CSV,
    cm,
    delimiter=",",
    fmt="%d",
)

np.savetxt(
    CONFUSION_MATRIX_NORMALIZED_CSV,
    cm_normalized,
    delimiter=",",
    fmt="%.8f",
)

# -------------------------------------------------------------------------
# Final official metrics
# -------------------------------------------------------------------------

print("\nOFFICIAL F05 TEST RESULTS")
print("-" * 100)

print(
    f"{'Metric':<25}"
    f"{'Official Test':>20}"
)

print("-" * 45)

print(
    f"{'Top-1':<25}"
    f"{top1_accuracy * 100:>19.4f}%"
)

print(
    f"{'Top-2':<25}"
    f"{top2_accuracy * 100:>19.4f}%"
)

print(
    f"{'Top-3':<25}"
    f"{top3_accuracy * 100:>19.4f}%"
)

print(
    f"{'Top-5':<25}"
    f"{top5_accuracy * 100:>19.4f}%"
)

print(
    f"{'Macro Precision':<25}"
    f"{macro_precision * 100:>19.4f}%"
)

print(
    f"{'Macro Recall':<25}"
    f"{macro_recall * 100:>19.4f}%"
)

print(
    f"{'Macro F1':<25}"
    f"{macro_f1 * 100:>19.4f}%"
)

print(
    f"{'Weighted F1':<25}"
    f"{weighted_f1 * 100:>19.4f}%"
)

print("\nSAVED TABLES")
print("-" * 100)
print("Metrics               :", TEST_METRICS_CSV)
print("Classification report :", CLASSIFICATION_REPORT_CSV)
print("Predictions           :", PREDICTIONS_CSV)
print("Confusion matrix      :", CONFUSION_MATRIX_CSV)
print(
    "Normalized CM         :",
    CONFUSION_MATRIX_NORMALIZED_CSV,
)

print("\n" + "=" * 100)
print("F05 STEP 4 PASSED — OFFICIAL TEST EVALUATION COMPLETED")
print("=" * 100)

print("Experiment            :", EXPERIMENT_NAME)
print("Best epoch            :", checkpoint["epoch"])
print("Checkpoint SHA-256    :", checkpoint_sha256)
print(f"Official test images  : {len(all_targets):,}")
print(f"Top-1                 : {top1_accuracy * 100:.4f}%")
print(f"Top-2                 : {top2_accuracy * 100:.4f}%")
print(f"Top-3                 : {top3_accuracy * 100:.4f}%")
print(f"Top-5                 : {top5_accuracy * 100:.4f}%")
print(f"Macro Precision       : {macro_precision * 100:.4f}%")
print(f"Macro Recall          : {macro_recall * 100:.4f}%")
print(f"Macro F1              : {macro_f1 * 100:.4f}%")
print(f"Weighted F1           : {weighted_f1 * 100:.4f}%")
print("Status                : READY FOR F05 STEP 5")

====================================================================================================
F05 Step 4 — Official test evaluation and paper metrics
====================================================================================================

LOCKED CHECKPOINT
----------------------------------------------------------------------------------------------------
Checkpoint : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/F05_CONVNEXT_SMALL_AUG200_GENTLE_CB_FOCAL/weights/best_model.pth
SHA-256   : 548e7c7d925f0272d06a5e57b682364b2affe302ff5c7c5071461ebde0b2e3f3
Hash match : True

OFFICIAL TEST SPLIT
----------------------------------------------------------------------------------------------------
Test images : 1,612
Classes     : 20
Split       : UNCHANGED OFFICIAL TEST

MODEL LOCK
----------------------------------------------------------------------------------------------------
Experiment        : F05_CONVNEXT_SMALL_AUG200_GENTLE_CB_FOCAL
Best epoch        : 20
Val Macro F1      : 89.9326%
Checkpoint rule   : validation_macro_f1
Loss beta         : 0.999
Loss gamma        : 1.0

====================================================================================================
OFFICIAL F05 TEST EVALUATION
====================================================================================================

OFFICIAL F05 TEST RESULTS
----------------------------------------------------------------------------------------------------
Metric                          Official Test
---------------------------------------------
Top-1                                91.1290%
Top-2                                97.4566%
Top-3                                98.9454%
Top-5                                99.7519%
Macro Precision                      89.7496%
Macro Recall                         82.6547%
Macro F1                             84.3487%
Weighted F1                          90.9759%

SAVED TABLES
----------------------------------------------------------------------------------------------------
Metrics               : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/F05_CONVNEXT_SMALL_AUG200_GENTLE_CB_FOCAL/tables/F05_test_metrics_summary.csv
Classification report : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/F05_CONVNEXT_SMALL_AUG200_GENTLE_CB_FOCAL/tables/F05_classification_report.csv
Predictions           : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/F05_CONVNEXT_SMALL_AUG200_GENTLE_CB_FOCAL/tables/F05_test_predictions.csv
Confusion matrix      : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/F05_CONVNEXT_SMALL_AUG200_GENTLE_CB_FOCAL/tables/F05_confusion_matrix.csv
Normalized CM         : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/F05_CONVNEXT_SMALL_AUG200_GENTLE_CB_FOCAL/tables/F05_confusion_matrix_normalized.csv

====================================================================================================
F05 STEP 4 PASSED — OFFICIAL TEST EVALUATION COMPLETED
====================================================================================================
Experiment            : F05_CONVNEXT_SMALL_AUG200_GENTLE_CB_FOCAL
Best epoch            : 20
Checkpoint SHA-256    : 548e7c7d925f0272d06a5e57b682364b2affe302ff5c7c5071461ebde0b2e3f3
Official test images  : 1,612
Top-1                 : 91.1290%
Top-2                 : 97.4566%
Top-3                 : 98.9454%
Top-5                 : 99.7519%
Macro Precision       : 89.7496%
Macro Recall          : 82.6547%
Macro F1              : 84.3487%
Weighted F1           : 90.9759%
Status                : READY FOR F05 STEP 5

## Step 5 — Create official F05 final experiment package

This step creates the final reproducible F05 experiment package.

The package contains:

- Locked best checkpoint
- Training history
- Best-epoch summary
- Official test metrics
- Target comparison
- F03/F04/F05 scientific comparison
- Classification report
- Test predictions
- Raw and normalized confusion matrices
- Confusion-matrix figures
- Experiment README

F05 is recorded as a completed combined imbalance intervention experiment.

Official scientific finding:

**Aug-200 and Gentle Class-Balanced Focal Loss were not complementary under the tested configuration.**

In [18]:
# ============================================================
# F05 Step 5 — Create official final experiment package
# ============================================================

import csv
import hashlib
import shutil
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import torch

print("=" * 100)
print("F05 Step 5 — Create official final experiment package")
print("=" * 100)

# -------------------------------------------------------------------------
# Official package paths
# -------------------------------------------------------------------------

FIGURES_DIR = F05_ROOT / "figures"

FIGURES_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

BEST_EPOCH_SUMMARY_CSV = (
    TABLES_DIR
    / "F05_best_epoch_summary.csv"
)

TARGET_COMPARISON_CSV = (
    TABLES_DIR
    / "F05_target_comparison.csv"
)

SCIENTIFIC_COMPARISON_CSV = (
    TABLES_DIR
    / "F05_scientific_comparison.csv"
)

README_F05 = (
    F05_ROOT
    / "README_F05.txt"
)

CM_FIGURE = (
    FIGURES_DIR
    / "F05_confusion_matrix.png"
)

CM_NORMALIZED_FIGURE = (
    FIGURES_DIR
    / "F05_confusion_matrix_normalized.png"
)

FINAL_ZIP_BASE = (
    PROJECT_ROOT
    / "aqua20_f05_convnext_small_aug200_gentle_focal_outputs"
)

FINAL_ZIP = Path(
    str(FINAL_ZIP_BASE) + ".zip"
)

# -------------------------------------------------------------------------
# Reload and verify locked checkpoint
# -------------------------------------------------------------------------

checkpoint = torch.load(
    BEST_CHECKPOINT,
    map_location="cpu",
    weights_only=False,
)

assert checkpoint["experiment"] == EXPERIMENT_NAME
assert checkpoint["epoch"] == 20

sha256 = hashlib.sha256()

with open(
    BEST_CHECKPOINT,
    "rb",
) as checkpoint_file:

    for block in iter(
        lambda: checkpoint_file.read(
            1024 * 1024
        ),
        b"",
    ):
        sha256.update(block)

checkpoint_sha256 = sha256.hexdigest()

EXPECTED_SHA256 = (
    "548e7c7d925f0272d06a5e57b682364b2affe302ff5c7c5071461ebde0b2e3f3"
)

assert checkpoint_sha256 == EXPECTED_SHA256

# -------------------------------------------------------------------------
# Best epoch summary
# -------------------------------------------------------------------------

best_epoch_rows = [{
    "experiment":
        EXPERIMENT_NAME,
    "best_epoch":
        checkpoint["epoch"],
    "checkpoint_rule":
        checkpoint["checkpoint_rule"],
    "val_accuracy":
        checkpoint["val_accuracy"],
    "val_macro_precision":
        checkpoint["val_macro_precision"],
    "val_macro_recall":
        checkpoint["val_macro_recall"],
    "val_macro_f1":
        checkpoint["val_macro_f1"],
    "beta":
        checkpoint["beta"],
    "gamma":
        checkpoint["gamma"],
    "image_size":
        checkpoint["image_size"],
    "batch_size":
        checkpoint["batch_size"],
    "learning_rate":
        checkpoint["learning_rate"],
    "weight_decay":
        checkpoint["weight_decay"],
    "seed":
        checkpoint["seed"],
    "checkpoint_sha256":
        checkpoint_sha256,
}]

with open(
    BEST_EPOCH_SUMMARY_CSV,
    "w",
    newline="",
    encoding="utf-8",
) as csv_file:

    writer = csv.DictWriter(
        csv_file,
        fieldnames=best_epoch_rows[0].keys(),
    )

    writer.writeheader()
    writer.writerows(best_epoch_rows)

# -------------------------------------------------------------------------
# Official target comparison
# -------------------------------------------------------------------------

target_rows = [
    {
        "metric": "Top-1",
        "f05_percentage": 91.1290,
        "target_percentage": 92.68,
    },
    {
        "metric": "Macro Precision",
        "f05_percentage": 89.7496,
        "target_percentage": 91.40,
    },
    {
        "metric": "Macro Recall",
        "f05_percentage": 82.6547,
        "target_percentage": 87.32,
    },
    {
        "metric": "Macro F1",
        "f05_percentage": 84.3487,
        "target_percentage": 88.92,
    },
    {
        "metric": "Top-2",
        "f05_percentage": 97.4566,
        "target_percentage": 97.58,
    },
    {
        "metric": "Top-3",
        "f05_percentage": 98.9454,
        "target_percentage": 98.82,
    },
]

for row in target_rows:

    row["delta_percentage_points"] = (
        row["f05_percentage"]
        - row["target_percentage"]
    )

    row["target_met"] = (
        row["f05_percentage"]
        > row["target_percentage"]
    )

with open(
    TARGET_COMPARISON_CSV,
    "w",
    newline="",
    encoding="utf-8",
) as csv_file:

    writer = csv.DictWriter(
        csv_file,
        fieldnames=target_rows[0].keys(),
    )

    writer.writeheader()
    writer.writerows(target_rows)

# -------------------------------------------------------------------------
# F03 / F04 / F05 scientific comparison
# -------------------------------------------------------------------------

comparison_rows = [
    {
        "experiment":
            "F03_CONVNEXT_SMALL_GENTLE_CB_FOCAL",
        "training_intervention":
            "Original train + Gentle CB Focal",
        "top1_percentage":
            91.6253,
        "macro_recall_percentage":
            86.9302,
        "macro_f1_percentage":
            87.9645,
    },
    {
        "experiment":
            "F04_CONVNEXT_SMALL_AUG200",
        "training_intervention":
            "Aug-200 + Cross-Entropy",
        "top1_percentage":
            91.3772,
        "macro_recall_percentage":
            84.3236,
        "macro_f1_percentage":
            86.0035,
    },
    {
        "experiment":
            EXPERIMENT_NAME,
        "training_intervention":
            "Aug-200 + Gentle CB Focal",
        "top1_percentage":
            91.1290,
        "macro_recall_percentage":
            82.6547,
        "macro_f1_percentage":
            84.3487,
    },
]

with open(
    SCIENTIFIC_COMPARISON_CSV,
    "w",
    newline="",
    encoding="utf-8",
) as csv_file:

    writer = csv.DictWriter(
        csv_file,
        fieldnames=comparison_rows[0].keys(),
    )

    writer.writeheader()
    writer.writerows(comparison_rows)

# -------------------------------------------------------------------------
# Confusion-matrix figures
# -------------------------------------------------------------------------

cm = np.loadtxt(
    CONFUSION_MATRIX_CSV,
    delimiter=",",
    dtype=np.int64,
)

cm_normalized = np.loadtxt(
    CONFUSION_MATRIX_NORMALIZED_CSV,
    delimiter=",",
    dtype=np.float64,
)

assert cm.shape == (20, 20)
assert cm_normalized.shape == (20, 20)

display_class_names = [
    class_name.split("_", 1)[1]
    for class_name in EXPECTED_CLASSES
]

plt.figure(
    figsize=(14, 12)
)

plt.imshow(cm)

plt.title(
    "F05 Official Test Confusion Matrix"
)

plt.xlabel(
    "Predicted Class"
)

plt.ylabel(
    "True Class"
)

plt.xticks(
    range(len(display_class_names)),
    display_class_names,
    rotation=90,
)

plt.yticks(
    range(len(display_class_names)),
    display_class_names,
)

plt.colorbar()

plt.tight_layout()

plt.savefig(
    CM_FIGURE,
    dpi=300,
    bbox_inches="tight",
)

plt.close()

plt.figure(
    figsize=(14, 12)
)

plt.imshow(cm_normalized)

plt.title(
    "F05 Official Test Normalized Confusion Matrix"
)

plt.xlabel(
    "Predicted Class"
)

plt.ylabel(
    "True Class"
)

plt.xticks(
    range(len(display_class_names)),
    display_class_names,
    rotation=90,
)

plt.yticks(
    range(len(display_class_names)),
    display_class_names,
)

plt.colorbar()

plt.tight_layout()

plt.savefig(
    CM_NORMALIZED_FIGURE,
    dpi=300,
    bbox_inches="tight",
)

plt.close()

# -------------------------------------------------------------------------
# Official README
# -------------------------------------------------------------------------

readme_text = f"""
AQUA20 FINAL BEAT BASE CAMPAIGN
F05 OFFICIAL EXPERIMENT PACKAGE
================================================================================

EXPERIMENT
----------
ID:
{EXPERIMENT_NAME}

Scientific role:
Combined imbalance intervention

METHOD
------
ConvNeXt-Small
+
Aug-200 train-only balancing
+
Gentle Class-Balanced Focal Loss

LOSS
----
Beta  : 0.999
Gamma : 1.0

Class weights:
Effective-number weighting calculated from the Aug-200 training distribution
and normalized to mean 1.

TRAINING
--------
Training images    : 7,284
Validation images  : 1,312
Official test      : 1,612
Classes            : 20

Image size         : 224 x 224
Batch size         : 16
Optimizer          : AdamW
Learning rate      : 1e-5
Weight decay       : 1e-4
Scheduler          : CosineAnnealingLR
Maximum epochs     : 25
Seed               : 42

Checkpoint rule:
Validation Macro F1

LOCKED BEST CHECKPOINT
----------------------
Best epoch          : 20
Validation Macro F1 : 89.9326%

SHA-256:
{checkpoint_sha256}

OFFICIAL TEST RESULTS
---------------------
Top-1               : 91.1290%
Top-2               : 97.4566%
Top-3               : 98.9454%
Top-5               : 99.7519%
Macro Precision     : 89.7496%
Macro Recall        : 82.6547%
Macro F1            : 84.3487%
Weighted F1         : 90.9759%

SCIENTIFIC COMPARISON
---------------------
F03:
Original train + Gentle CB Focal
Top-1       : 91.6253%
Macro Recall: 86.9302%
Macro F1    : 87.9645%

F04:
Aug-200 + Cross-Entropy
Top-1       : 91.3772%
Macro Recall: 84.3236%
Macro F1    : 86.0035%

F05:
Aug-200 + Gentle CB Focal
Top-1       : 91.1290%
Macro Recall: 82.6547%
Macro F1    : 84.3487%

OFFICIAL SCIENTIFIC FINDING
---------------------------
The data-level and loss-level imbalance interventions were not complementary
under the tested F05 configuration.

Gentle Class-Balanced Focal Loss was stronger when applied to the original
training distribution in F03.

Combining Aug-200 with Gentle CB Focal reduced official-test Macro Recall and
Macro F1 relative to both F03 and F04.

F05 therefore does not replace F03 as the strongest isolated imbalance
intervention result.

The higher F05 validation Macro F1 did not translate into stronger official
test balanced metrics.

PACKAGE CONTENT
---------------
README_F05.txt

figures/
    F05_confusion_matrix.png
    F05_confusion_matrix_normalized.png

tables/
    F05_best_epoch_summary.csv
    F05_training_history.csv
    F05_test_metrics_summary.csv
    F05_target_comparison.csv
    F05_scientific_comparison.csv
    F05_classification_report.csv
    F05_test_predictions.csv
    F05_confusion_matrix.csv
    F05_confusion_matrix_normalized.csv

weights/
    best_model.pth
""".strip()

README_F05.write_text(
    readme_text,
    encoding="utf-8",
)

# -------------------------------------------------------------------------
# Required file verification
# -------------------------------------------------------------------------

required_files = [
    README_F05,
    CM_FIGURE,
    CM_NORMALIZED_FIGURE,
    BEST_EPOCH_SUMMARY_CSV,
    HISTORY_CSV,
    TEST_METRICS_CSV,
    TARGET_COMPARISON_CSV,
    SCIENTIFIC_COMPARISON_CSV,
    CLASSIFICATION_REPORT_CSV,
    PREDICTIONS_CSV,
    CONFUSION_MATRIX_CSV,
    CONFUSION_MATRIX_NORMALIZED_CSV,
    BEST_CHECKPOINT,
]

for required_file in required_files:

    assert required_file.exists(), (
        f"Missing package file: {required_file}"
    )

# -------------------------------------------------------------------------
# Create final official ZIP
# -------------------------------------------------------------------------

if FINAL_ZIP.exists():
    FINAL_ZIP.unlink()

shutil.make_archive(
    base_name=str(FINAL_ZIP_BASE),
    format="zip",
    root_dir=F05_ROOT,
)

assert FINAL_ZIP.exists()

# -------------------------------------------------------------------------
# Package content display
# -------------------------------------------------------------------------

print("\nFinal package :", FINAL_ZIP)

print(
    "ZIP size      :",
    f"{FINAL_ZIP.stat().st_size / 1024**2:.2f} MB",
)

print("\nPACKAGE CONTENTS")

for package_file in sorted(
    F05_ROOT.rglob("*")
):

    if package_file.is_file():

        print(
            package_file.relative_to(
                F05_ROOT
            )
        )

print("\n" + "=" * 100)
print("F05 STEP 5 PASSED — OFFICIAL FINAL PACKAGE CREATED")
print("=" * 100)

print(
    "Experiment  :",
    EXPERIMENT_NAME,
)

print(
    "Best epoch  :",
    checkpoint["epoch"],
)

print(
    "SHA-256     :",
    checkpoint_sha256,
)

print(
    "Top-1       : 91.1290%"
)

print(
    "Macro Recall: 82.6547%"
)

print(
    "Macro F1    : 84.3487%"
)

print(
    "F05 status  : COMPLETED"
)

print(
    "DOWNLOAD    :",
    FINAL_ZIP,
)

====================================================================================================
F05 Step 5 — Create official final experiment package
====================================================================================================

Final package : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/aqua20_f05_convnext_small_aug200_gentle_focal_outputs.zip
ZIP size      : 524.63 MB

PACKAGE CONTENTS
README_F05.txt
figures/F05_confusion_matrix.png
figures/F05_confusion_matrix_normalized.png
tables/F05_best_epoch_summary.csv
tables/F05_classification_report.csv
tables/F05_confusion_matrix.csv
tables/F05_confusion_matrix_normalized.csv
tables/F05_scientific_comparison.csv
tables/F05_target_comparison.csv
tables/F05_test_metrics_summary.csv
tables/F05_test_predictions.csv
tables/F05_training_history.csv
weights/best_model.pth

====================================================================================================
F05 STEP 5 PASSED — OFFICIAL FINAL PACKAGE CREATED
====================================================================================================
Experiment  : F05_CONVNEXT_SMALL_AUG200_GENTLE_CB_FOCAL
Best epoch  : 20
SHA-256     : 548e7c7d925f0272d06a5e57b682364b2affe302ff5c7c5071461ebde0b2e3f3
Top-1       : 91.1290%
Macro Recall: 82.6547%
Macro F1    : 84.3487%
F05 status  : COMPLETED
DOWNLOAD    : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/aqua20_f05_convnext_small_aug200_gentle_focal_outputs.zip

# F06 Step 1A — Verify and Lock the F03 Source Package

Official campaign:

`04-07-2026 AQUA20 FINAL BEAT BASE PLAN`

F06 is the high-resolution fine-tuning stage.

The source branch is scientifically locked to:

`F03_CONVNEXT_SMALL_GENTLE_CB_FOCAL`

F03 is selected because F06 is designed as a controlled continuation of the
isolated Gentle Class-Balanced Focal Loss branch.

F05 introduced an additional Aug-200 data-level balancing intervention.
Therefore, continuing from F05 would carry two imbalance interventions into the
high-resolution stage.

F06 instead continues from F03 so that high-resolution fine-tuning is introduced
as the next major intervention on the isolated loss-level branch.

Official test metrics are recorded as completed experiment evidence but are not
used for F06 checkpoint selection.

This step verifies the added official F03 package and locks its exact checkpoint
identity before any F06 training configuration is finalized.

In [20]:
# ============================================================
# F06 Step 1A — Verify and lock official F03 source package
# ============================================================

from pathlib import Path
import hashlib

print("=" * 80)
print("F06 Step 1A — Verify and lock official F03 source package")
print("=" * 80)

# ------------------------------------------------------------
# Find F03 checkpoint directly from Kaggle inputs
# ------------------------------------------------------------

checkpoint_candidates = []

for path in Path("/kaggle/input").rglob("*"):
    if not path.is_file():
        continue

    if path.suffix.lower() not in {".pth", ".pt"}:
        continue

    path_text = str(path).lower()

    if "f03" in path_text and "convnext" in path_text:
        checkpoint_candidates.append(path)

checkpoint_candidates = sorted(checkpoint_candidates)

print("\nF03 checkpoint candidates:")

for path in checkpoint_candidates:
    print(" -", path)

if len(checkpoint_candidates) != 1:
    raise RuntimeError(
        f"Expected exactly one F03 checkpoint, "
        f"found {len(checkpoint_candidates)}."
    )

F03_CHECKPOINT = checkpoint_candidates[0]
F03_INPUT = F03_CHECKPOINT.parents[1]

# ------------------------------------------------------------
# Compute SHA-256
# ------------------------------------------------------------

def sha256_file(path):
    h = hashlib.sha256()

    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)

    return h.hexdigest()


F03_SHA256 = sha256_file(F03_CHECKPOINT)

# ------------------------------------------------------------
# Display verified source
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("LOCKED F03 SOURCE CHECKPOINT")
print("=" * 80)

print("Source experiment : F03_CONVNEXT_SMALL_GENTLE_CB_FOCAL")
print("F03 input root    :", F03_INPUT)
print("Checkpoint        :", F03_CHECKPOINT)
print("Checkpoint file   :", F03_CHECKPOINT.name)
print("SHA-256           :", F03_SHA256)

# ------------------------------------------------------------
# Show package evidence
# ------------------------------------------------------------

evidence_files = sorted(
    p.relative_to(F03_INPUT)
    for p in F03_INPUT.rglob("*")
    if p.is_file()
    and p.suffix.lower() in {".csv", ".json", ".txt"}
)

print("\n" + "=" * 80)
print("F03 PACKAGE EVIDENCE FILES")
print("=" * 80)

for path in evidence_files:
    print(path)

print("\n" + "=" * 80)
print("F06 STEP 1A PASSED — F03 SOURCE PACKAGE VERIFIED")
print("=" * 80)

print("F06 SOURCE : F03 isolated Gentle CB Focal branch")
print("TEST USAGE : NOT used for F06 source selection")
print("NEXT       : F06 Step 1B — verify and lock HR384 protocol")

================================================================================
F06 Step 1A — Verify and lock official F03 source package
================================================================================

F03 checkpoint candidates:
 - /kaggle/input/datasets/sazzad1/aqua20-f03-convnext-small-gentle-cb-focal-outputs/weights/best_model.pth

================================================================================
LOCKED F03 SOURCE CHECKPOINT
================================================================================
Source experiment : F03_CONVNEXT_SMALL_GENTLE_CB_FOCAL
F03 input root    : /kaggle/input/datasets/sazzad1/aqua20-f03-convnext-small-gentle-cb-focal-outputs
Checkpoint        : /kaggle/input/datasets/sazzad1/aqua20-f03-convnext-small-gentle-cb-focal-outputs/weights/best_model.pth
Checkpoint file   : best_model.pth
SHA-256           : 928c8af60aef70537263e2c8cc1cf13782747bc5974f86ff054fbe352065c26f

================================================================================
F03 PACKAGE EVIDENCE FILES
================================================================================
README_F03.txt
tables/F03_best_epoch_summary.csv
tables/F03_class_counts_and_cb_weights.csv
tables/F03_classification_report.csv
tables/F03_comparison_ready_summary.csv
tables/F03_confusion_matrix.csv
tables/F03_confusion_matrix_normalized.csv
tables/F03_gentle_cb_focal_config.json
tables/F03_locked_validation_metrics.csv
tables/F03_step3c_audit_summary.csv
tables/F03_test_metrics_summary.csv
tables/F03_test_predictions.csv
tables/F03_test_vs_base_targets.csv
tables/F03_top_validation_epochs.csv
tables/F03_training_config.json
tables/F03_training_history.csv
tables/F03_validation_vs_base_targets.csv
weights/F03_best_model_sha256.txt

================================================================================
F06 STEP 1A PASSED — F03 SOURCE PACKAGE VERIFIED
================================================================================
F06 SOURCE : F03 isolated Gentle CB Focal branch
TEST USAGE : NOT used for F06 source selection
NEXT       : F06 Step 1B — verify and lock HR384 protocol

# F06 Step 1B — Verify F03 Method and Lock the HR384 Protocol

The official F03 checkpoint identity has been verified by SHA-256.

This step inspects the packaged F03 training and Gentle Class-Balanced Focal
Loss configuration before locking F06.

F06 is a continuation fine-tuning experiment.

The controlled source branch remains:

`F03_CONVNEXT_SMALL_GENTLE_CB_FOCAL`

The original AQUA20 training distribution is retained.

The Gentle Class-Balanced Focal Loss method is retained.

The new major intervention introduced in F06 is:

`384 × 384 high-resolution fine-tuning`

Best checkpoint selection remains based only on validation Macro F1.

The official test split remains unchanged and is not used for model selection.

In [21]:
# ============================================================
# F06 Step 1B — Verify F03 method and lock HR384 protocol
# ============================================================

from pathlib import Path
import json
import pandas as pd

print("=" * 80)
print("F06 Step 1B — Verify F03 method and lock HR384 protocol")
print("=" * 80)

F03_INPUT = Path(
    "/kaggle/input/datasets/sazzad1/"
    "aqua20-f03-convnext-small-gentle-cb-focal-outputs"
)

F03_CHECKPOINT = F03_INPUT / "weights" / "best_model.pth"

training_config_path = (
    F03_INPUT / "tables" / "F03_training_config.json"
)

focal_config_path = (
    F03_INPUT / "tables" / "F03_gentle_cb_focal_config.json"
)

best_summary_path = (
    F03_INPUT / "tables" / "F03_best_epoch_summary.csv"
)

with open(training_config_path, "r") as f:
    f03_training_config = json.load(f)

with open(focal_config_path, "r") as f:
    f03_focal_config = json.load(f)

best_summary = pd.read_csv(best_summary_path)

print("\n" + "=" * 80)
print("F03 SOURCE METHOD")
print("=" * 80)

print("\nF03 training configuration:")
print(json.dumps(f03_training_config, indent=2))

print("\nF03 Gentle CB Focal configuration:")
print(json.dumps(f03_focal_config, indent=2))

print("\nF03 best epoch summary:")
print(best_summary.to_string(index=False))

# ------------------------------------------------------------
# Lock F06 high-resolution protocol
# ------------------------------------------------------------

F06_ROOT = Path(
    "/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/"
    "F06_CONVNEXT_SMALL_HR384_GENTLE_CB_FOCAL"
)

F06_ROOT.mkdir(parents=True, exist_ok=True)

F06_CONFIG = {
    "campaign": "04-07-2026 AQUA20 FINAL BEAT BASE PLAN",
    "experiment": "F06_CONVNEXT_SMALL_HR384_GENTLE_CB_FOCAL",
    "scientific_role": "high-resolution fine-tuning",
    "source_experiment": "F03_CONVNEXT_SMALL_GENTLE_CB_FOCAL",
    "source_checkpoint": str(F03_CHECKPOINT),
    "source_checkpoint_sha256": (
        "928c8af60aef70537263e2c8cc1cf137"
        "82747bc5974f86ff054fbe352065c26f"
    ),
    "training_distribution": "original AQUA20 train split",
    "aug200": False,
    "model": "ConvNeXt-Small",
    "source_resolution": 224,
    "finetune_resolution": 384,
    "batch_size": 8,
    "max_epochs": 15,
    "optimizer": "AdamW",
    "learning_rate": 5e-6,
    "weight_decay": 1e-4,
    "scheduler": "CosineAnnealingLR",
    "loss": "Gentle Class-Balanced Focal Loss",
    "beta": 0.999,
    "gamma": 1.0,
    "seed": 42,
    "checkpoint_selection": "validation Macro F1 only",
    "official_test_model_selection": False,
}

config_path = F06_ROOT / "F06_locked_protocol.json"

with open(config_path, "w") as f:
    json.dump(F06_CONFIG, f, indent=2)

print("\n" + "=" * 80)
print("LOCKED F06 HR384 PROTOCOL")
print("=" * 80)

print("Experiment        :", F06_CONFIG["experiment"])
print("Source            :", F06_CONFIG["source_experiment"])
print("Train distribution:", F06_CONFIG["training_distribution"])
print("Aug-200           : DISABLED")
print("Resolution        : 224 -> 384")
print("Batch size        : 8")
print("Maximum epochs    : 15")
print("Optimizer         : AdamW")
print("Learning rate     : 5e-6")
print("Weight decay      : 1e-4")
print("Scheduler         : CosineAnnealingLR")
print("Loss              : Gentle CB Focal")
print("Beta              : 0.999")
print("Gamma             : 1.0")
print("Seed              : 42")
print("Checkpoint metric : Validation Macro F1 only")
print("Official test     : NOT used for model selection")
print("Protocol saved    :", config_path)

print("\n" + "=" * 80)
print("F06 STEP 1B PASSED — HR384 PROTOCOL LOCKED")
print("=" * 80)

print("NEXT : Switch to GPU and start F06 Step 2")

================================================================================
F06 Step 1B — Verify F03 method and lock HR384 protocol
================================================================================

================================================================================
F03 SOURCE METHOD
================================================================================

F03 training configuration:
{
  "experiment": "F03_CONVNEXT_SMALL_GENTLE_CB_FOCAL",
  "run_role": "OFFICIAL_F03",
  "model": "torchvision.models.convnext_small",
  "pretrained_weights": "ConvNeXt_Small_Weights.IMAGENET1K_V1",
  "train_images": 5247,
  "val_images": 1312,
  "num_classes": 20,
  "image_size": 224,
  "batch_size": 16,
  "num_workers": 4,
  "prefetch_factor": 2,
  "max_epochs": 40,
  "early_stopping_patience": 8,
  "optimizer": "AdamW",
  "learning_rate": 1e-05,
  "weight_decay": 0.0001,
  "scheduler": "CosineAnnealingLR",
  "scheduler_t_max": 40,
  "loss": "Gentle Class-Balanced Focal Loss",
  "beta": 0.999,
  "gamma": 1.0,
  "gradient_clip_max_norm": 1.0,
  "amp_enabled": true,
  "checkpoint_selection": "validation_macro_f1",
  "recovery_checkpoint_every": 5,
  "cudnn_deterministic": true,
  "cudnn_benchmark": false,
  "seed": 42,
  "gpu": "Tesla P100-PCIE-16GB",
  "base_paper_targets": {
    "precision": 0.914,
    "recall": 0.8732,
    "f1": 0.8892,
    "top1": 0.9069,
    "top2": 0.9758,
    "top3": 0.9882
  },
  "campaign_top1_target": 0.9268,
  "class_names": [
    "00_coral",
    "01_crab",
    "02_diver",
    "03_eel",
    "04_fish",
    "05_fishInGroups",
    "06_flatworm",
    "07_jellyfish",
    "08_marine_dolphin",
    "09_octopus",
    "10_rayfish",
    "11_seaAnemone",
    "12_seaCucumber",
    "13_seaSlug",
    "14_seaUrchin",
    "15_shark",
    "16_shrimp",
    "17_squid",
    "18_starfish",
    "19_turtle"
  ]
}

F03 Gentle CB Focal configuration:
{
  "experiment": "F03_CONVNEXT_SMALL_GENTLE_CB_FOCAL",
  "loss_name": "Gentle Class-Balanced Focal Loss",
  "beta": 0.999,
  "gamma": 1.0,
  "weight_method": "effective_number",
  "weight_normalization": "mean_1",
  "inverse_frequency_weighting": false,
  "training_data": "original_train_5247",
  "seed": 42
}

F03 best epoch summary:
 epoch  epoch_minutes  learning_rate  train_loss  train_top1  val_loss  val_top1  val_top2  val_top3  val_macro_precision  val_macro_recall  val_macro_f1  best_val_macro_f1  best_epoch_so_far  is_best_checkpoint  recovery_checkpoint_saved  epochs_without_improvement
    13       7.829977       0.000008    0.007471    0.968363  0.050597  0.925305  0.976372  0.994665             0.879929          0.926189      0.893301           0.893301                 13                True                      False                           0

================================================================================
LOCKED F06 HR384 PROTOCOL
================================================================================
Experiment        : F06_CONVNEXT_SMALL_HR384_GENTLE_CB_FOCAL
Source            : F03_CONVNEXT_SMALL_GENTLE_CB_FOCAL
Train distribution: original AQUA20 train split
Aug-200           : DISABLED
Resolution        : 224 -> 384
Batch size        : 8
Maximum epochs    : 15
Optimizer         : AdamW
Learning rate     : 5e-6
Weight decay      : 1e-4
Scheduler         : CosineAnnealingLR
Loss              : Gentle CB Focal
Beta              : 0.999
Gamma             : 1.0
Seed              : 42
Checkpoint metric : Validation Macro F1 only
Official test     : NOT used for model selection
Protocol saved    : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/F06_CONVNEXT_SMALL_HR384_GENTLE_CB_FOCAL/F06_locked_protocol.json

================================================================================
F06 STEP 1B PASSED — HR384 PROTOCOL LOCKED
================================================================================
NEXT : Switch to GPU and start F06 Step 2

# F06 Step 2A — Locate and Verify the Official AQUA20 Split

F06 uses the same original AQUA20 train, validation, and official test split
used throughout the final campaign.

Expected split:

- Train: 5,247 images
- Validation: 1,312 images
- Official test: 1,612 images
- Classes: 20

Aug-200 is disabled for F06.

This step only locates and verifies the existing official split before building
the 384 × 384 fine-tuning loaders.

In [22]:
# ============================================================
# F06 Step 2A — Locate and verify official AQUA20 split
# ============================================================

from pathlib import Path
from torchvision.datasets import ImageFolder

print("=" * 80)
print("F06 Step 2A — Locate and verify official AQUA20 split")
print("=" * 80)

EXPECTED_COUNTS = {
    "train": 5247,
    "val": 1312,
    "test": 1612,
}

SEARCH_ROOTS = [
    Path("/kaggle/working"),
    Path("/kaggle/input"),
]

# Unusable F00 handover must be ignored
IGNORE_TEXT = "AQUA20_F00_DATA_AUDIT_AUG200_HANDOVER_04072026".lower()

candidates = []

for search_root in SEARCH_ROOTS:
    for train_dir in search_root.rglob("train"):
        if not train_dir.is_dir():
            continue

        root = train_dir.parent
        root_text = str(root).lower()

        if IGNORE_TEXT in root_text:
            continue

        val_dir = root / "val"
        test_dir = root / "test"

        if not val_dir.is_dir() or not test_dir.is_dir():
            continue

        try:
            train_ds = ImageFolder(train_dir)
            val_ds = ImageFolder(val_dir)
            test_ds = ImageFolder(test_dir)

            counts = (
                len(train_ds),
                len(val_ds),
                len(test_ds),
                len(train_ds.classes),
            )

            if counts == (5247, 1312, 1612, 20):
                candidates.append(
                    (
                        root,
                        train_ds,
                        val_ds,
                        test_ds,
                    )
                )

        except Exception:
            pass

if len(candidates) != 1:
    print("\nMatching official split candidates:")

    for root, train_ds, val_ds, test_ds in candidates:
        print(
            root,
            len(train_ds),
            len(val_ds),
            len(test_ds),
            len(train_ds.classes),
        )

    raise RuntimeError(
        f"Expected exactly one official AQUA20 split, "
        f"found {len(candidates)}."
    )

DATA_ROOT, train_ds, val_ds, test_ds = candidates[0]

if train_ds.classes != val_ds.classes:
    raise RuntimeError("Train and validation class order mismatch.")

if train_ds.classes != test_ds.classes:
    raise RuntimeError("Train and test class order mismatch.")

print("\n" + "=" * 80)
print("OFFICIAL AQUA20 SPLIT VERIFIED")
print("=" * 80)

print("Data root   :", DATA_ROOT)
print("Train       :", DATA_ROOT / "train")
print("Validation  :", DATA_ROOT / "val")
print("Test        :", DATA_ROOT / "test")
print("Train images:", len(train_ds))
print("Val images  :", len(val_ds))
print("Test images :", len(test_ds))
print("Classes     :", len(train_ds.classes))

print("\nClass order:")

for index, name in enumerate(train_ds.classes):
    print(f"{index:02d} : {name}")

print("\nAug-200     : DISABLED")
print("F00 input   : IGNORED")

print("\n" + "=" * 80)
print("F06 STEP 2A PASSED — OFFICIAL SPLIT VERIFIED")
print("=" * 80)

print("NEXT : F06 Step 2B — build HR384 loaders, Gentle CB Focal, and model")

================================================================================
F06 Step 2A — Locate and verify official AQUA20 split
================================================================================

================================================================================
OFFICIAL AQUA20 SPLIT VERIFIED
================================================================================
Data root   : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/official_imagefolder
Train       : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/official_imagefolder/train
Validation  : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/official_imagefolder/val
Test        : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/official_imagefolder/test
Train images: 5247
Val images  : 1312
Test images : 1612
Classes     : 20

Class order:
00 : 00_coral
01 : 01_crab
02 : 02_diver
03 : 03_eel
04 : 04_fish
05 : 05_fishInGroups
06 : 06_flatworm
07 : 07_jellyfish
08 : 08_marine_dolphin
09 : 09_octopus
10 : 10_rayfish
11 : 11_seaAnemone
12 : 12_seaCucumber
13 : 13_seaSlug
14 : 14_seaUrchin
15 : 15_shark
16 : 16_shrimp
17 : 17_squid
18 : 18_starfish
19 : 19_turtle

Aug-200     : DISABLED
F00 input   : IGNORED

================================================================================
F06 STEP 2A PASSED — OFFICIAL SPLIT VERIFIED
================================================================================
NEXT : F06 Step 2B — build HR384 loaders, Gentle CB Focal, and model

# F06 Step 2B — Inspect F03 Transform Evidence, CB Weights, and Checkpoint Format

F06 is designed as a controlled high-resolution continuation of F03.

Before building the 384 × 384 loaders and loading the F03 checkpoint, this step
verifies three implementation details from the official F03 package:

1. Any recorded F03 transform or augmentation evidence.
2. The exact packaged Gentle Class-Balanced Focal Loss weights.
3. The exact F03 checkpoint serialization structure.

No training is performed in this step.

In [23]:
# ============================================================
# F06 Step 2B — Inspect F03 implementation evidence
# ============================================================

from pathlib import Path
import pandas as pd
import torch

print("=" * 80)
print("F06 Step 2B — Inspect F03 implementation evidence")
print("=" * 80)

F03_INPUT = Path(
    "/kaggle/input/datasets/sazzad1/"
    "aqua20-f03-convnext-small-gentle-cb-focal-outputs"
)

README_PATH = F03_INPUT / "README_F03.txt"
WEIGHTS_PATH = (
    F03_INPUT / "tables" / "F03_class_counts_and_cb_weights.csv"
)
CHECKPOINT_PATH = F03_INPUT / "weights" / "best_model.pth"

# ------------------------------------------------------------
# F03 README
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("F03 README")
print("=" * 80)

readme_text = README_PATH.read_text()

for line in readme_text.splitlines():
    line_lower = line.lower()

    if any(
        key in line_lower
        for key in [
            "transform",
            "augment",
            "resize",
            "crop",
            "flip",
            "rotation",
            "jitter",
            "normalize",
            "image size",
        ]
    ):
        print(line)

# ------------------------------------------------------------
# Exact packaged class-balanced weights
# ------------------------------------------------------------

cb_table = pd.read_csv(WEIGHTS_PATH)

print("\n" + "=" * 80)
print("F03 CLASS COUNTS AND CB WEIGHTS")
print("=" * 80)

print(cb_table.to_string(index=False))

# ------------------------------------------------------------
# Checkpoint serialization structure
# ------------------------------------------------------------

checkpoint = torch.load(
    CHECKPOINT_PATH,
    map_location="cpu",
    weights_only=False,
)

print("\n" + "=" * 80)
print("F03 CHECKPOINT STRUCTURE")
print("=" * 80)

print("Checkpoint type:", type(checkpoint).__name__)

if isinstance(checkpoint, dict):
    print("Top-level keys:")

    for key in checkpoint.keys():
        print(" -", key)

    if "model_state_dict" in checkpoint:
        state_dict = checkpoint["model_state_dict"]
        print("\nModel state source : model_state_dict")

    elif "state_dict" in checkpoint:
        state_dict = checkpoint["state_dict"]
        print("\nModel state source : state_dict")

    else:
        state_dict = checkpoint
        print("\nModel state source : direct state_dict")

    print("State tensors      :", len(state_dict))

    classifier_keys = [
        key for key in state_dict
        if "classifier" in key
    ]

    print("\nClassifier keys:")

    for key in classifier_keys:
        print(" -", key, tuple(state_dict[key].shape))

print("\n" + "=" * 80)
print("F06 STEP 2B PASSED — F03 IMPLEMENTATION EVIDENCE INSPECTED")
print("=" * 80)

print("NEXT : F06 Step 2C — build exact HR384 loaders, loss, and source model")

================================================================================
F06 Step 2B — Inspect F03 implementation evidence
================================================================================

================================================================================
F03 README
================================================================================

================================================================================
F03 CLASS COUNTS AND CB WEIGHTS
================================================================================
 class_id        class_name  train_count  cb_weight
        0          00_coral         1249   0.062978
        1           01_crab           34   1.343341
        2          02_diver           41   1.117873
        3            03_eel          128   0.373767
        4           04_fish         1760   0.054254
        5   05_fishInGroups          218   0.229268
        6       06_flatworm           40   1.145251
        7      07_jellyfish           78   0.598467
        8 08_marine_dolphin           16   2.829116
        9        09_octopus           16   2.829116
       10        10_rayfish          305   0.170836
       11     11_seaAnemone          712   0.088178
       12    12_seaCucumber           28   1.626336
       13        13_seaSlug           63   0.735485
       14      14_seaUrchin           92   0.510912
       15          15_shark           57   0.810493
       16         16_shrimp           18   2.517280
       17          17_squid           19   2.385981
       18       18_starfish          133   0.360597
       19         19_turtle          240   0.210468

================================================================================
F03 CHECKPOINT STRUCTURE
================================================================================
Checkpoint type: dict
Top-level keys:
 - epoch
 - model_state_dict
 - val_metrics
 - class_names
 - training_config

Model state source : model_state_dict
State tensors      : 344

Classifier keys:
 - classifier.0.weight (768,)
 - classifier.0.bias (768,)
 - classifier.2.weight (20, 768)
 - classifier.2.bias (20,)

================================================================================
F06 STEP 2B PASSED — F03 IMPLEMENTATION EVIDENCE INSPECTED
================================================================================
NEXT : F06 Step 2C — build exact HR384 loaders, loss, and source model

# F06 Step 2C — Build HR384 Loaders, Exact Gentle CB Focal Loss, and Source Model

F06 retains the F03 training augmentation policy and Gentle Class-Balanced
Focal Loss method.

The augmentation parameters remain unchanged.

The spatial pipeline is scaled from the F03 224 × 224 stage to the F06
384 × 384 high-resolution stage.

F03:

`Resize 256 → RandomResizedCrop 224`

F06:

`Resize 440 → RandomResizedCrop 384`

The exact packaged F03 class-balanced weights are reused.

The verified F03 best checkpoint is loaded strictly into a 20-class
ConvNeXt-Small model.

No training is performed in this step.

In [25]:
# ============================================================
# F06 Step 2C — Build HR384 loaders, loss, and source model
# ============================================================

import random
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F

from torchvision import transforms
from torchvision.datasets import ImageFolder
from torchvision.models import convnext_small
from torch.utils.data import DataLoader

print("=" * 80)
print("F06 Step 2C — Build HR384 loaders, loss, and source model")
print("=" * 80)

# ------------------------------------------------------------
# Locked constants
# ------------------------------------------------------------

SEED = 42
IMG_SIZE = 384
BATCH_SIZE = 8
NUM_WORKERS = 4
NUM_CLASSES = 20

TRAIN_DIR = DATA_ROOT / "train"
VAL_DIR = DATA_ROOT / "val"

F03_INPUT = Path(
    "/kaggle/input/datasets/sazzad1/"
    "aqua20-f03-convnext-small-gentle-cb-focal-outputs"
)

F03_CHECKPOINT = F03_INPUT / "weights" / "best_model.pth"

CB_WEIGHTS_PATH = (
    F03_INPUT / "tables" / "F03_class_counts_and_cb_weights.csv"
)

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

# ------------------------------------------------------------
# HR384 transforms
# ------------------------------------------------------------

IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD = [0.229, 0.224, 0.225]

train_transform = transforms.Compose([
    transforms.Resize((440, 440)),
    transforms.RandomResizedCrop(
        IMG_SIZE,
        scale=(0.80, 1.00),
    ),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomRotation(10),
    transforms.ColorJitter(
        brightness=0.12,
        contrast=0.12,
        saturation=0.12,
        hue=0.03,
    ),
    transforms.ToTensor(),
    transforms.Normalize(
        IMAGENET_MEAN,
        IMAGENET_STD,
    ),
])

val_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(
        IMAGENET_MEAN,
        IMAGENET_STD,
    ),
])

# ------------------------------------------------------------
# Datasets and loaders
# ------------------------------------------------------------

train_dataset = ImageFolder(
    TRAIN_DIR,
    transform=train_transform,
)

val_dataset = ImageFolder(
    VAL_DIR,
    transform=val_transform,
)

if train_dataset.classes != val_dataset.classes:
    raise RuntimeError("Train/validation class order mismatch.")

train_generator = torch.Generator()
train_generator.manual_seed(SEED)

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    generator=train_generator,
    num_workers=NUM_WORKERS,
    pin_memory=True,
    persistent_workers=True,
    prefetch_factor=2,
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=True,
    persistent_workers=True,
    prefetch_factor=2,
)

# ------------------------------------------------------------
# Exact packaged F03 class-balanced weights
# ------------------------------------------------------------

cb_table = pd.read_csv(CB_WEIGHTS_PATH)

if cb_table["class_name"].tolist() != train_dataset.classes:
    raise RuntimeError("F03 CB-weight class order mismatch.")

class_weights = torch.tensor(
    cb_table["cb_weight"].values,
    dtype=torch.float32,
)

# ------------------------------------------------------------
# Exact Gentle CB Focal formulation
# ------------------------------------------------------------

class GentleCBFocalLoss(nn.Module):
    def __init__(self, class_weights, gamma=1.0):
        super().__init__()

        self.register_buffer(
            "class_weights",
            class_weights.clone().detach(),
        )

        self.gamma = gamma

    def forward(self, logits, targets):
        ce_loss = F.cross_entropy(
            logits,
            targets,
            reduction="none",
        )

        pt = torch.exp(-ce_loss)

        focal_factor = torch.pow(
            1.0 - pt,
            self.gamma,
        )

        sample_weights = self.class_weights[targets]

        loss = (
            sample_weights
            * focal_factor
            * ce_loss
        )

        return loss.mean()


criterion = GentleCBFocalLoss(
    class_weights=class_weights,
    gamma=1.0,
).to(device)

# ------------------------------------------------------------
# Load verified F03 source model
# ------------------------------------------------------------

checkpoint = torch.load(
    F03_CHECKPOINT,
    map_location="cpu",
    weights_only=False,
)

model = convnext_small(weights=None)

in_features = model.classifier[2].in_features

model.classifier[2] = nn.Linear(
    in_features,
    NUM_CLASSES,
)

model.load_state_dict(
    checkpoint["model_state_dict"],
    strict=True,
)

model = model.to(device)

# ------------------------------------------------------------
# HR384 forward verification
# ------------------------------------------------------------

model.eval()

images, targets = next(iter(val_loader))

images = images.to(
    device,
    non_blocking=True,
)

targets = targets.to(
    device,
    non_blocking=True,
)

with torch.no_grad():
    logits = model(images)
    verify_loss = criterion(logits, targets)

print("\n" + "=" * 80)
print("F06 HR384 COMPONENT VERIFICATION")
print("=" * 80)

print("Device             :", device)
print("GPU                :", torch.cuda.get_device_name(0))
print("Train images       :", len(train_dataset))
print("Validation images  :", len(val_dataset))
print("Classes            :", len(train_dataset.classes))
print("Train batches      :", len(train_loader))
print("Validation batches :", len(val_loader))
print("Image batch shape  :", tuple(images.shape))
print("Logits shape       :", tuple(logits.shape))
print("Verification loss  :", f"{verify_loss.item():.6f}")

print("\nSource checkpoint  : F03 best epoch", checkpoint["epoch"])
print(
    "Source val metrics :",
    checkpoint["val_metrics"],
)

print("\nLoss               : Gentle CB Focal")
print("Gamma              : 1.0")
print("CB weights source  : Official F03 package")
print("Weight mean        :", f"{class_weights.mean().item():.6f}")

print("\nAug-200            : DISABLED")
print("Train resolution   : 384 x 384")
print("Validation         : Unchanged split")
print("Official test      : NOT loaded")

print("\n" + "=" * 80)
print("F06 STEP 2C PASSED — HR384 TRAINING COMPONENTS READY")
print("=" * 80)

print("NEXT : F06 Step 3 — official HR384 fine-tuning")

================================================================================
F06 Step 2C — Build HR384 loaders, loss, and source model
================================================================================

================================================================================
F06 HR384 COMPONENT VERIFICATION
================================================================================
Device             : cuda
GPU                : Tesla P100-PCIE-16GB
Train images       : 5247
Validation images  : 1312
Classes            : 20
Train batches      : 656
Validation batches : 164
Image batch shape  : (8, 3, 384, 384)
Logits shape       : (8, 20)
Verification loss  : 0.000036

Source checkpoint  : F03 best epoch 13
Source val metrics : {'val_loss': 0.050597214431120835, 'val_top1': 0.9253048780487805, 'val_top2': 0.9763719512195121, 'val_top3': 0.9946646341463414, 'val_macro_precision': 0.8799293448581487, 'val_macro_recall': 0.9261887298051781, 'val_macro_f1': 0.8933009691623253}

Loss               : Gentle CB Focal
Gamma              : 1.0
CB weights source  : Official F03 package
Weight mean        : 1.000000

Aug-200            : DISABLED
Train resolution   : 384 x 384
Validation         : Unchanged split
Official test      : NOT loaded

================================================================================
F06 STEP 2C PASSED — HR384 TRAINING COMPONENTS READY
================================================================================
NEXT : F06 Step 3 — official HR384 fine-tuning

# F06 Step 3 — Official HR384 Fine-Tuning with Live Progress

The F06 model is reset to the verified F03 best checkpoint before training.

Official protocol:

- ConvNeXt-Small
- F03 best checkpoint source
- Original AQUA20 training distribution
- Aug-200 disabled
- 384 × 384 high-resolution fine-tuning
- Gentle Class-Balanced Focal Loss
- Exact F03 class-balanced weights
- Batch size 8
- AdamW
- Learning rate 5e-6
- Weight decay 1e-4
- CosineAnnealingLR
- Maximum 15 epochs
- Validation Macro F1 checkpoint selection

The official test split is not used during training.

Live batch progress and partial training progress are displayed and saved.

In [31]:
# ============================================================
# F06 Step 3 — Official HR384 fine-tuning with tabular history
# ============================================================

from pathlib import Path
import hashlib
import time

import pandas as pd
import torch
import torch.nn as nn

from torch.utils.data import DataLoader
from torchvision.models import convnext_small
from sklearn.metrics import precision_recall_fscore_support
from tqdm.auto import tqdm

print("=" * 100)
print("F06 Step 3 — Official HR384 fine-tuning with tabular history")
print("=" * 100)

# ------------------------------------------------------------
# Paths
# ------------------------------------------------------------

EXP_NAME = "F06_CONVNEXT_SMALL_HR384_GENTLE_CB_FOCAL"

F06_ROOT = (
    Path("/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026")
    / EXP_NAME
)

WEIGHTS_DIR = F06_ROOT / "weights"
TABLES_DIR = F06_ROOT / "tables"

WEIGHTS_DIR.mkdir(parents=True, exist_ok=True)
TABLES_DIR.mkdir(parents=True, exist_ok=True)

BEST_PATH = WEIGHTS_DIR / "best_model.pth"
LAST_PATH = WEIGHTS_DIR / "last_model.pth"

HISTORY_PATH = TABLES_DIR / "F06_training_history.csv"
SHA_PATH = WEIGHTS_DIR / "F06_best_model_sha256.txt"

# ------------------------------------------------------------
# Locked protocol
# ------------------------------------------------------------

MAX_EPOCHS = 15
LEARNING_RATE = 5e-6
WEIGHT_DECAY = 1e-4
GRAD_CLIP_MAX_NORM = 1.0

AMP_ENABLED = device.type == "cuda"

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

# ------------------------------------------------------------
# Stable DataLoaders
# ------------------------------------------------------------

train_generator = torch.Generator()
train_generator.manual_seed(SEED)

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    generator=train_generator,
    num_workers=0,
    pin_memory=True,
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=0,
    pin_memory=True,
)

# ------------------------------------------------------------
# Reset model to verified F03 checkpoint
# ------------------------------------------------------------

source_checkpoint = torch.load(
    F03_CHECKPOINT,
    map_location="cpu",
    weights_only=False,
)

model = convnext_small(weights=None)

in_features = model.classifier[2].in_features

model.classifier[2] = nn.Linear(
    in_features,
    NUM_CLASSES,
)

model.load_state_dict(
    source_checkpoint["model_state_dict"],
    strict=True,
)

model = model.to(device)

# ------------------------------------------------------------
# Optimizer / scheduler / AMP
# ------------------------------------------------------------

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=LEARNING_RATE,
    weight_decay=WEIGHT_DECAY,
)

scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
    optimizer,
    T_max=MAX_EPOCHS,
)

scaler = torch.amp.GradScaler(
    "cuda",
    enabled=AMP_ENABLED,
)

# ------------------------------------------------------------
# Helpers
# ------------------------------------------------------------

def sha256_file(path):
    h = hashlib.sha256()

    with open(path, "rb") as f:
        for chunk in iter(
            lambda: f.read(1024 * 1024),
            b"",
        ):
            h.update(chunk)

    return h.hexdigest()


def validate_model():

    model.eval()

    total_loss = 0.0
    all_logits = []
    all_targets = []

    with torch.no_grad():

        for images, targets in tqdm(
            val_loader,
            desc="Validation",
            leave=False,
        ):

            images = images.to(
                device,
                non_blocking=True,
            )

            targets = targets.to(
                device,
                non_blocking=True,
            )

            with torch.amp.autocast(
                device_type=device.type,
                dtype=torch.float16,
                enabled=AMP_ENABLED,
            ):

                logits = model(images)
                loss = criterion(logits, targets)

            total_loss += (
                loss.item() * targets.size(0)
            )

            all_logits.append(
                logits.float().cpu()
            )

            all_targets.append(
                targets.cpu()
            )

    all_logits = torch.cat(all_logits)
    all_targets = torch.cat(all_targets)

    predictions = all_logits.argmax(dim=1)

    precision, recall, macro_f1, _ = (
        precision_recall_fscore_support(
            all_targets.numpy(),
            predictions.numpy(),
            average="macro",
            zero_division=0,
        )
    )

    top1 = (
        predictions == all_targets
    ).float().mean().item()

    top2 = (
        all_logits.topk(2, dim=1).indices
        == all_targets.unsqueeze(1)
    ).any(dim=1).float().mean().item()

    top3 = (
        all_logits.topk(3, dim=1).indices
        == all_targets.unsqueeze(1)
    ).any(dim=1).float().mean().item()

    return {
        "val_loss": total_loss / len(val_dataset),
        "val_top1": top1,
        "val_top2": top2,
        "val_top3": top3,
        "val_macro_precision": precision,
        "val_macro_recall": recall,
        "val_macro_f1": macro_f1,
    }


def print_history_table(history):

    display_rows = []

    for row in history:

        display_rows.append({
            "Epoch": row["epoch"],
            "Time": f'{row["epoch_minutes"]:.1f}m',
            "ETA": f'{row["eta_hours"]:.2f}h',
            "LR": f'{row["learning_rate"]:.2e}',
            "Tr Loss": f'{row["train_loss"]:.4f}',
            "Tr Top1": f'{row["train_top1"] * 100:.2f}%',
            "Val Loss": f'{row["val_loss"]:.4f}',
            "Val Top1": f'{row["val_top1"] * 100:.2f}%',
            "Top2": f'{row["val_top2"] * 100:.2f}%',
            "Top3": f'{row["val_top3"] * 100:.2f}%',
            "Macro P": f'{row["val_macro_precision"] * 100:.2f}%',
            "Macro R": f'{row["val_macro_recall"] * 100:.2f}%',
            "Macro F1": f'{row["val_macro_f1"] * 100:.2f}%',
            "Best": "★" if row["is_best_checkpoint"] else "",
        })

    table = pd.DataFrame(display_rows)

    print("\n" + "=" * 150)
    print("F06 OFFICIAL TRAINING HISTORY")
    print("=" * 150)

    print(
        table.to_string(
            index=False,
            justify="center",
        )
    )

    print("=" * 150)


# ------------------------------------------------------------
# Official training
# ------------------------------------------------------------

history = []

best_val_macro_f1 = -1.0
best_epoch = None

training_start = time.perf_counter()

print("\nOFFICIAL TRAINING CONFIGURATION")

config_table = pd.DataFrame([
    ["Experiment", EXP_NAME],
    ["Source", "F03 best checkpoint — epoch 13"],
    ["GPU", torch.cuda.get_device_name(0)],
    ["Resolution", "384 x 384"],
    ["Batch size", BATCH_SIZE],
    ["Train batches", len(train_loader)],
    ["Validation batches", len(val_loader)],
    ["Maximum epochs", MAX_EPOCHS],
    ["Learning rate", "5e-6"],
    ["Optimizer", "AdamW"],
    ["Scheduler", "CosineAnnealingLR"],
    ["Loss", "Gentle CB Focal"],
    ["Selection", "Validation Macro F1 only"],
    ["Official test", "NOT used"],
], columns=["Setting", "Value"])

print(config_table.to_string(index=False))

print("\n" + "=" * 100)
print("OFFICIAL F06 TRAINING START")
print("=" * 100)

for epoch in range(1, MAX_EPOCHS + 1):

    epoch_start = time.perf_counter()

    model.train()

    train_loss_sum = 0.0
    train_correct = 0
    train_total = 0

    learning_rate = optimizer.param_groups[0]["lr"]

    train_bar = tqdm(
        train_loader,
        total=len(train_loader),
        desc=f"Epoch {epoch:02d}/{MAX_EPOCHS}",
        unit="batch",
    )

    for images, targets in train_bar:

        images = images.to(
            device,
            non_blocking=True,
        )

        targets = targets.to(
            device,
            non_blocking=True,
        )

        optimizer.zero_grad(set_to_none=True)

        with torch.amp.autocast(
            device_type=device.type,
            dtype=torch.float16,
            enabled=AMP_ENABLED,
        ):

            logits = model(images)
            loss = criterion(logits, targets)

        scaler.scale(loss).backward()

        scaler.unscale_(optimizer)

        torch.nn.utils.clip_grad_norm_(
            model.parameters(),
            GRAD_CLIP_MAX_NORM,
        )

        scaler.step(optimizer)
        scaler.update()

        current_batch_size = targets.size(0)

        train_loss_sum += (
            loss.item() * current_batch_size
        )

        train_correct += (
            logits.argmax(dim=1) == targets
        ).sum().item()

        train_total += current_batch_size

        running_loss = (
            train_loss_sum / train_total
        )

        running_top1 = (
            train_correct / train_total
        )

        train_bar.set_postfix(
            loss=f"{running_loss:.5f}",
            top1=f"{running_top1 * 100:.2f}%",
        )

    train_loss = train_loss_sum / train_total
    train_top1 = train_correct / train_total

    val_metrics = validate_model()

    is_best = (
        val_metrics["val_macro_f1"]
        > best_val_macro_f1
    )

    if is_best:

        best_val_macro_f1 = (
            val_metrics["val_macro_f1"]
        )

        best_epoch = epoch

        torch.save(
            {
                "epoch": epoch,
                "model_state_dict": model.state_dict(),
                "val_metrics": val_metrics,
                "class_names": train_dataset.classes,
                "training_config": F06_CONFIG,
            },
            BEST_PATH,
        )

    epoch_seconds = (
        time.perf_counter() - epoch_start
    )

    elapsed_seconds = (
        time.perf_counter() - training_start
    )

    average_epoch_seconds = (
        elapsed_seconds / epoch
    )

    eta_seconds = (
        average_epoch_seconds
        * (MAX_EPOCHS - epoch)
    )

    row = {
        "epoch": epoch,
        "epoch_minutes": epoch_seconds / 60,
        "eta_hours": eta_seconds / 3600,
        "learning_rate": learning_rate,
        "train_loss": train_loss,
        "train_top1": train_top1,
        **val_metrics,
        "best_val_macro_f1": best_val_macro_f1,
        "best_epoch_so_far": best_epoch,
        "is_best_checkpoint": is_best,
    }

    history.append(row)

    pd.DataFrame(history).to_csv(
        HISTORY_PATH,
        index=False,
    )

    torch.save(
        {
            "epoch": epoch,
            "model_state_dict": model.state_dict(),
            "val_metrics": val_metrics,
        },
        LAST_PATH,
    )

    scheduler.step()

    print_history_table(history)

    print(
        f"\nCurrent best: Epoch {best_epoch} | "
        f"Val Macro F1 = {best_val_macro_f1 * 100:.4f}%"
    )


# ------------------------------------------------------------
# Final checkpoint lock
# ------------------------------------------------------------

best_sha256 = sha256_file(BEST_PATH)

SHA_PATH.write_text(
    best_sha256 + "\n"
)

total_hours = (
    time.perf_counter() - training_start
) / 3600

print("\n" + "=" * 100)
print("F06 OFFICIAL TRAINING COMPLETE")
print("=" * 100)

final_table = pd.DataFrame([
    ["Total training time", f"{total_hours:.2f} hours"],
    ["Best epoch", best_epoch],
    ["Best Validation Macro F1", f"{best_val_macro_f1 * 100:.4f}%"],
    ["SHA-256", best_sha256],
    ["Official test", "NOT evaluated"],
], columns=["Result", "Value"])

print(final_table.to_string(index=False))

print("\n" + "=" * 100)
print("F06 STEP 3 PASSED — BEST VALIDATION CHECKPOINT LOCKED")
print("=" * 100)

print("NEXT : F06 Step 4 — official unchanged test evaluation")

====================================================================================================
F06 Step 3 — Official HR384 fine-tuning with tabular history
====================================================================================================

OFFICIAL TRAINING CONFIGURATION
           Setting                                    Value
        Experiment F06_CONVNEXT_SMALL_HR384_GENTLE_CB_FOCAL
            Source           F03 best checkpoint — epoch 13
               GPU                     Tesla P100-PCIE-16GB
        Resolution                                384 x 384
        Batch size                                        8
     Train batches                                      656
Validation batches                                      164
    Maximum epochs                                       15
     Learning rate                                     5e-6
         Optimizer                                    AdamW
         Scheduler                        CosineAnnealingLR
              Loss                          Gentle CB Focal
         Selection                 Validation Macro F1 only
     Official test                                 NOT used

====================================================================================================
OFFICIAL F06 TRAINING START
====================================================================================================

Epoch 01/15:   0%|          | 0/656 [00:00<?, ?batch/s]

Validation:   0%|          | 0/164 [00:00<?, ?it/s]

======================================================================================================================================================
F06 OFFICIAL TRAINING HISTORY
======================================================================================================================================================
 Epoch  Time  ETA     LR    Tr Loss Tr Top1 Val Loss Val Top1  Top2   Top3  Macro P Macro R Macro F1 Best
  1    20.5m 4.78h 5.00e-06  0.0195  94.68%  0.0562   92.61%  98.48% 99.39%  87.55%  89.92%  87.81%   ★
======================================================================================================================================================

Current best: Epoch 1 | Val Macro F1 = 87.8134%

Epoch 02/15:   0%|          | 0/656 [00:00<?, ?batch/s]

Validation:   0%|          | 0/164 [00:00<?, ?it/s]

======================================================================================================================================================
F06 OFFICIAL TRAINING HISTORY
======================================================================================================================================================
 Epoch  Time  ETA     LR    Tr Loss Tr Top1 Val Loss Val Top1  Top2   Top3  Macro P Macro R Macro F1 Best
  1    20.5m 4.78h 5.00e-06  0.0195  94.68%  0.0562   92.61%  98.48% 99.39%  87.55%  89.92%  87.81%   ★
  2    20.4m 4.43h 4.95e-06  0.0120  95.46%  0.0496   92.99%  98.63% 99.54%  88.46%  90.68%  88.51%   ★
======================================================================================================================================================

Current best: Epoch 2 | Val Macro F1 = 88.5122%

Epoch 03/15:   0%|          | 0/656 [00:00<?, ?batch/s]

Validation:   0%|          | 0/164 [00:00<?, ?it/s]

======================================================================================================================================================
F06 OFFICIAL TRAINING HISTORY
======================================================================================================================================================
 Epoch  Time  ETA     LR    Tr Loss Tr Top1 Val Loss Val Top1  Top2   Top3  Macro P Macro R Macro F1 Best
  1    20.5m 4.78h 5.00e-06  0.0195  94.68%  0.0562   92.61%  98.48% 99.39%  87.55%  89.92%  87.81%   ★
  2    20.4m 4.43h 4.95e-06  0.0120  95.46%  0.0496   92.99%  98.63% 99.54%  88.46%  90.68%  88.51%   ★
  3    20.4m 4.09h 4.78e-06  0.0118  96.21%  0.0542   91.54%  97.94% 99.47%  88.73%  90.32%  88.49%
======================================================================================================================================================

Current best: Epoch 2 | Val Macro F1 = 88.5122%

Epoch 04/15:   0%|          | 0/656 [00:00<?, ?batch/s]

Validation:   0%|          | 0/164 [00:00<?, ?it/s]

======================================================================================================================================================
F06 OFFICIAL TRAINING HISTORY
======================================================================================================================================================
 Epoch  Time  ETA     LR    Tr Loss Tr Top1 Val Loss Val Top1  Top2   Top3  Macro P Macro R Macro F1 Best
  1    20.5m 4.78h 5.00e-06  0.0195  94.68%  0.0562   92.61%  98.48% 99.39%  87.55%  89.92%  87.81%   ★
  2    20.4m 4.43h 4.95e-06  0.0120  95.46%  0.0496   92.99%  98.63% 99.54%  88.46%  90.68%  88.51%   ★
  3    20.4m 4.09h 4.78e-06  0.0118  96.21%  0.0542   91.54%  97.94% 99.47%  88.73%  90.32%  88.49%
  4    20.4m 3.75h 4.52e-06  0.0089  97.01%  0.0540   92.76%  98.78% 99.54%  86.71%  88.56%  86.33%
======================================================================================================================================================

Current best: Epoch 2 | Val Macro F1 = 88.5122%

Epoch 05/15:   0%|          | 0/656 [00:00<?, ?batch/s]

Validation:   0%|          | 0/164 [00:00<?, ?it/s]

======================================================================================================================================================
F06 OFFICIAL TRAINING HISTORY
======================================================================================================================================================
 Epoch  Time  ETA     LR    Tr Loss Tr Top1 Val Loss Val Top1  Top2   Top3  Macro P Macro R Macro F1 Best
  1    20.5m 4.78h 5.00e-06  0.0195  94.68%  0.0562   92.61%  98.48% 99.39%  87.55%  89.92%  87.81%   ★
  2    20.4m 4.43h 4.95e-06  0.0120  95.46%  0.0496   92.99%  98.63% 99.54%  88.46%  90.68%  88.51%   ★
  3    20.4m 4.09h 4.78e-06  0.0118  96.21%  0.0542   91.54%  97.94% 99.47%  88.73%  90.32%  88.49%
  4    20.4m 3.75h 4.52e-06  0.0089  97.01%  0.0540   92.76%  98.78% 99.54%  86.71%  88.56%  86.33%
  5    20.4m 3.40h 4.17e-06  0.0061  97.20%  0.0525   93.06%  98.40% 99.47%  88.91%  89.50%  87.97%
======================================================================================================================================================

Current best: Epoch 2 | Val Macro F1 = 88.5122%

Epoch 06/15:   0%|          | 0/656 [00:00<?, ?batch/s]

Validation:   0%|          | 0/164 [00:00<?, ?it/s]

======================================================================================================================================================
F06 OFFICIAL TRAINING HISTORY
======================================================================================================================================================
 Epoch  Time  ETA     LR    Tr Loss Tr Top1 Val Loss Val Top1  Top2   Top3  Macro P Macro R Macro F1 Best
  1    20.5m 4.78h 5.00e-06  0.0195  94.68%  0.0562   92.61%  98.48% 99.39%  87.55%  89.92%  87.81%   ★
  2    20.4m 4.43h 4.95e-06  0.0120  95.46%  0.0496   92.99%  98.63% 99.54%  88.46%  90.68%  88.51%   ★
  3    20.4m 4.09h 4.78e-06  0.0118  96.21%  0.0542   91.54%  97.94% 99.47%  88.73%  90.32%  88.49%
  4    20.4m 3.75h 4.52e-06  0.0089  97.01%  0.0540   92.76%  98.78% 99.54%  86.71%  88.56%  86.33%
  5    20.4m 3.40h 4.17e-06  0.0061  97.20%  0.0525   93.06%  98.40% 99.47%  88.91%  89.50%  87.97%
  6    20.4m 3.06h 3.75e-06  0.0056  97.47%  0.0551   92.53%  98.02% 99.31%  87.00%  90.04%  87.00%
======================================================================================================================================================

Current best: Epoch 2 | Val Macro F1 = 88.5122%

Epoch 07/15:   0%|          | 0/656 [00:00<?, ?batch/s]

Validation:   0%|          | 0/164 [00:00<?, ?it/s]

======================================================================================================================================================
F06 OFFICIAL TRAINING HISTORY
======================================================================================================================================================
 Epoch  Time  ETA     LR    Tr Loss Tr Top1 Val Loss Val Top1  Top2   Top3  Macro P Macro R Macro F1 Best
  1    20.5m 4.78h 5.00e-06  0.0195  94.68%  0.0562   92.61%  98.48% 99.39%  87.55%  89.92%  87.81%   ★
  2    20.4m 4.43h 4.95e-06  0.0120  95.46%  0.0496   92.99%  98.63% 99.54%  88.46%  90.68%  88.51%   ★
  3    20.4m 4.09h 4.78e-06  0.0118  96.21%  0.0542   91.54%  97.94% 99.47%  88.73%  90.32%  88.49%
  4    20.4m 3.75h 4.52e-06  0.0089  97.01%  0.0540   92.76%  98.78% 99.54%  86.71%  88.56%  86.33%
  5    20.4m 3.40h 4.17e-06  0.0061  97.20%  0.0525   93.06%  98.40% 99.47%  88.91%  89.50%  87.97%
  6    20.4m 3.06h 3.75e-06  0.0056  97.47%  0.0551   92.53%  98.02% 99.31%  87.00%  90.04%  87.00%
  7    20.3m 2.72h 3.27e-06  0.0066  98.02%  0.0541   92.68%  98.09% 99.54%  87.91%  90.56%  88.08%
======================================================================================================================================================

Current best: Epoch 2 | Val Macro F1 = 88.5122%

Epoch 08/15:   0%|          | 0/656 [00:00<?, ?batch/s]

Validation:   0%|          | 0/164 [00:00<?, ?it/s]

======================================================================================================================================================
F06 OFFICIAL TRAINING HISTORY
======================================================================================================================================================
 Epoch  Time  ETA     LR    Tr Loss Tr Top1 Val Loss Val Top1  Top2   Top3  Macro P Macro R Macro F1 Best
  1    20.5m 4.78h 5.00e-06  0.0195  94.68%  0.0562   92.61%  98.48% 99.39%  87.55%  89.92%  87.81%   ★
  2    20.4m 4.43h 4.95e-06  0.0120  95.46%  0.0496   92.99%  98.63% 99.54%  88.46%  90.68%  88.51%   ★
  3    20.4m 4.09h 4.78e-06  0.0118  96.21%  0.0542   91.54%  97.94% 99.47%  88.73%  90.32%  88.49%
  4    20.4m 3.75h 4.52e-06  0.0089  97.01%  0.0540   92.76%  98.78% 99.54%  86.71%  88.56%  86.33%
  5    20.4m 3.40h 4.17e-06  0.0061  97.20%  0.0525   93.06%  98.40% 99.47%  88.91%  89.50%  87.97%
  6    20.4m 3.06h 3.75e-06  0.0056  97.47%  0.0551   92.53%  98.02% 99.31%  87.00%  90.04%  87.00%
  7    20.3m 2.72h 3.27e-06  0.0066  98.02%  0.0541   92.68%  98.09% 99.54%  87.91%  90.56%  88.08%
  8    20.3m 2.38h 2.76e-06  0.0047  98.32%  0.0546   92.53%  98.02% 99.47%  87.91%  89.64%  87.77%
======================================================================================================================================================

Current best: Epoch 2 | Val Macro F1 = 88.5122%

Epoch 09/15:   0%|          | 0/656 [00:00<?, ?batch/s]

Validation:   0%|          | 0/164 [00:00<?, ?it/s]

======================================================================================================================================================
F06 OFFICIAL TRAINING HISTORY
======================================================================================================================================================
 Epoch  Time  ETA     LR    Tr Loss Tr Top1 Val Loss Val Top1  Top2   Top3  Macro P Macro R Macro F1 Best
  1    20.5m 4.78h 5.00e-06  0.0195  94.68%  0.0562   92.61%  98.48% 99.39%  87.55%  89.92%  87.81%   ★
  2    20.4m 4.43h 4.95e-06  0.0120  95.46%  0.0496   92.99%  98.63% 99.54%  88.46%  90.68%  88.51%   ★
  3    20.4m 4.09h 4.78e-06  0.0118  96.21%  0.0542   91.54%  97.94% 99.47%  88.73%  90.32%  88.49%
  4    20.4m 3.75h 4.52e-06  0.0089  97.01%  0.0540   92.76%  98.78% 99.54%  86.71%  88.56%  86.33%
  5    20.4m 3.40h 4.17e-06  0.0061  97.20%  0.0525   93.06%  98.40% 99.47%  88.91%  89.50%  87.97%
  6    20.4m 3.06h 3.75e-06  0.0056  97.47%  0.0551   92.53%  98.02% 99.31%  87.00%  90.04%  87.00%
  7    20.3m 2.72h 3.27e-06  0.0066  98.02%  0.0541   92.68%  98.09% 99.54%  87.91%  90.56%  88.08%
  8    20.3m 2.38h 2.76e-06  0.0047  98.32%  0.0546   92.53%  98.02% 99.47%  87.91%  89.64%  87.77%
  9    20.3m 2.04h 2.24e-06  0.0042  98.34%  0.0582   92.53%  98.25% 99.54%  88.59%  90.54%  88.38%
======================================================================================================================================================

Current best: Epoch 2 | Val Macro F1 = 88.5122%

Epoch 10/15:   0%|          | 0/656 [00:00<?, ?batch/s]

KeyboardInterrupt:

# F06 Step 3B — Recover and Lock the Manually Terminated Training Run

F06 training was manually interrupted during Epoch 10.

Only fully completed epochs recorded in the official training-history table are
accepted as part of the experiment.

The incomplete interrupted epoch is excluded.

The best checkpoint remains selected strictly by validation Macro F1.

This step verifies:

- completed training-history epochs,
- best validation epoch,
- saved best-checkpoint epoch,
- saved best-checkpoint validation metrics,
- SHA-256 identity.

F06 termination is recorded transparently as manual termination after a sustained
validation Macro F1 plateau.

The official test split was not consulted when stopping training.

In [32]:
# ============================================================
# F06 Step 3B — Recover and lock terminated training run
# ============================================================

from pathlib import Path
import hashlib
import json

import pandas as pd
import torch

print("=" * 80)
print("F06 Step 3B — Recover and lock terminated training run")
print("=" * 80)

F06_ROOT = Path(
    "/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/"
    "F06_CONVNEXT_SMALL_HR384_GENTLE_CB_FOCAL"
)

HISTORY_PATH = F06_ROOT / "tables" / "F06_training_history.csv"
BEST_PATH = F06_ROOT / "weights" / "best_model.pth"
SHA_PATH = F06_ROOT / "weights" / "F06_best_model_sha256.txt"

BEST_SUMMARY_PATH = (
    F06_ROOT / "tables" / "F06_best_epoch_summary.csv"
)

TERMINATION_PATH = (
    F06_ROOT / "tables" / "F06_training_termination.json"
)


def sha256_file(path):
    h = hashlib.sha256()

    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)

    return h.hexdigest()


# ------------------------------------------------------------
# Read completed history only
# ------------------------------------------------------------

history = pd.read_csv(HISTORY_PATH)

if history.empty:
    raise RuntimeError("F06 training history is empty.")

completed_epochs = len(history)
last_completed_epoch = int(history["epoch"].max())

best_idx = history["val_macro_f1"].idxmax()
best_row = history.loc[best_idx]

best_epoch = int(best_row["epoch"])
best_val_macro_f1 = float(best_row["val_macro_f1"])

epochs_after_best = last_completed_epoch - best_epoch

# ------------------------------------------------------------
# Verify saved best checkpoint
# ------------------------------------------------------------

best_checkpoint = torch.load(
    BEST_PATH,
    map_location="cpu",
    weights_only=False,
)

checkpoint_epoch = int(best_checkpoint["epoch"])
checkpoint_val_f1 = float(
    best_checkpoint["val_metrics"]["val_macro_f1"]
)

if checkpoint_epoch != best_epoch:
    raise RuntimeError(
        f"Best checkpoint epoch mismatch: "
        f"history={best_epoch}, checkpoint={checkpoint_epoch}"
    )

if abs(checkpoint_val_f1 - best_val_macro_f1) > 1e-12:
    raise RuntimeError(
        "Best checkpoint validation Macro F1 mismatch."
    )

# ------------------------------------------------------------
# SHA-256 lock
# ------------------------------------------------------------

best_sha256 = sha256_file(BEST_PATH)

SHA_PATH.write_text(best_sha256 + "\n")

# ------------------------------------------------------------
# Save official best-epoch summary
# ------------------------------------------------------------

best_summary = history.loc[[best_idx]].copy()

best_summary.to_csv(
    BEST_SUMMARY_PATH,
    index=False,
)

# ------------------------------------------------------------
# Record manual termination transparently
# ------------------------------------------------------------

termination_record = {
    "experiment": "F06_CONVNEXT_SMALL_HR384_GENTLE_CB_FOCAL",
    "termination_type": "manual_validation_plateau_termination",
    "completed_epochs": completed_epochs,
    "last_completed_epoch": last_completed_epoch,
    "interrupted_epoch": last_completed_epoch + 1,
    "interrupted_epoch_excluded": True,
    "best_epoch": best_epoch,
    "best_validation_macro_f1": best_val_macro_f1,
    "completed_epochs_after_best_without_improvement": epochs_after_best,
    "selection_metric": "validation Macro F1 only",
    "official_test_used_for_stopping": False,
    "reason": (
        "Training manually terminated after a sustained validation "
        "Macro F1 plateau. The incomplete interrupted epoch was excluded."
    ),
}

with open(TERMINATION_PATH, "w") as f:
    json.dump(
        termination_record,
        f,
        indent=2,
    )

# ------------------------------------------------------------
# Final verification output
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("F06 COMPLETED TRAINING HISTORY")
print("=" * 80)

display_cols = [
    "epoch",
    "epoch_minutes",
    "learning_rate",
    "train_loss",
    "train_top1",
    "val_loss",
    "val_top1",
    "val_top2",
    "val_top3",
    "val_macro_precision",
    "val_macro_recall",
    "val_macro_f1",
    "is_best_checkpoint",
]

print(
    history[display_cols].to_string(
        index=False,
    )
)

print("\n" + "=" * 80)
print("F06 OFFICIAL TRAINING LOCK")
print("=" * 80)

print("Completed epochs             :", completed_epochs)
print("Last completed epoch         :", last_completed_epoch)
print("Interrupted epoch            :", last_completed_epoch + 1)
print("Interrupted epoch included   : NO")
print("Best epoch                   :", best_epoch)
print(
    "Best Validation Macro F1     :",
    f"{best_val_macro_f1 * 100:.4f}%"
)
print(
    "Completed epochs after best  :",
    epochs_after_best,
)
print("Checkpoint epoch             :", checkpoint_epoch)
print(
    "Checkpoint Validation F1     :",
    f"{checkpoint_val_f1 * 100:.4f}%"
)
print("Checkpoint verification      : PASSED")
print("SHA-256                      :", best_sha256)
print("SHA file                     :", SHA_PATH)
print("Best epoch summary           :", BEST_SUMMARY_PATH)
print("Termination record           :", TERMINATION_PATH)
print("Official test used           : NO")

print("\n" + "=" * 80)
print("F06 STEP 3B PASSED — BEST VALIDATION CHECKPOINT OFFICIALLY LOCKED")
print("=" * 80)

print("NEXT : F06 Step 4 — official unchanged test evaluation")

================================================================================
F06 Step 3B — Recover and lock terminated training run
================================================================================

================================================================================
F06 COMPLETED TRAINING HISTORY
================================================================================
 epoch  epoch_minutes  learning_rate  train_loss  train_top1  val_loss  val_top1  val_top2  val_top3  val_macro_precision  val_macro_recall  val_macro_f1  is_best_checkpoint
     1      20.468136       0.000005    0.019519    0.946827  0.056195  0.926067  0.984756  0.993902             0.875533          0.899157      0.878134                True
     2      20.429708       0.000005    0.012046    0.954641  0.049609  0.929878  0.986281  0.995427             0.884581          0.906790      0.885122                True
     3      20.402189       0.000005    0.011769    0.962074  0.054172  0.915396  0.979421  0.994665             0.887299          0.903229      0.884856               False
     4      20.412556       0.000005    0.008917    0.970078  0.054000  0.927591  0.987805  0.995427             0.867092          0.885576      0.863349               False
     5      20.404664       0.000004    0.006056    0.971984  0.052539  0.930640  0.983994  0.994665             0.889059          0.895049      0.879728               False
     6      20.397090       0.000004    0.005566    0.974652  0.055137  0.925305  0.980183  0.993140             0.870002          0.900391      0.869976               False
     7      20.318292       0.000003    0.006561    0.980179  0.054109  0.926829  0.980945  0.995427             0.879073          0.905570      0.880831               False
     8      20.318380       0.000003    0.004716    0.983229  0.054629  0.925305  0.980183  0.994665             0.879112          0.896364      0.877682               False
     9      20.330142       0.000002    0.004196    0.983419  0.058228  0.925305  0.982469  0.995427             0.885906          0.905426      0.883842               False

================================================================================
F06 OFFICIAL TRAINING LOCK
================================================================================
Completed epochs             : 9
Last completed epoch         : 9
Interrupted epoch            : 10
Interrupted epoch included   : NO
Best epoch                   : 2
Best Validation Macro F1     : 88.5122%
Completed epochs after best  : 7
Checkpoint epoch             : 2
Checkpoint Validation F1     : 88.5122%
Checkpoint verification      : PASSED
SHA-256                      : d0c225c28b25f09822bc99518a37f9b1fe642b2d01213da7f68e2d76a255832a
SHA file                     : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/F06_CONVNEXT_SMALL_HR384_GENTLE_CB_FOCAL/weights/F06_best_model_sha256.txt
Best epoch summary           : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/F06_CONVNEXT_SMALL_HR384_GENTLE_CB_FOCAL/tables/F06_best_epoch_summary.csv
Termination record           : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/F06_CONVNEXT_SMALL_HR384_GENTLE_CB_FOCAL/tables/F06_training_termination.json
Official test used           : NO

================================================================================
F06 STEP 3B PASSED — BEST VALIDATION CHECKPOINT OFFICIALLY LOCKED
================================================================================
NEXT : F06 Step 4 — official unchanged test evaluation

# F06 Step 4 — Official Unchanged Test Evaluation

The F06 best checkpoint was selected using validation Macro F1 only.

Locked checkpoint:

- Best epoch: 2
- Validation Macro F1: 88.5122%
- SHA-256: `d0c225c28b25f09822bc99518a37f9b1fe642b2d01213da7f68e2d76a255832a`

The incomplete interrupted Epoch 10 is excluded from the experiment.

This step evaluates the locked F06 best checkpoint once on the unchanged official
AQUA20 test split:

- 1,612 images
- 20 classes

Reported metrics:

- Top-1
- Top-2
- Top-3
- Top-5
- Macro Precision
- Macro Recall
- Macro F1
- Weighted F1

The official test split was not used for checkpoint selection or training termination.

In [33]:
# ============================================================
# F06 Step 4 — Official unchanged test evaluation
# ============================================================

from pathlib import Path
import hashlib

import numpy as np
import pandas as pd
import torch
import torch.nn as nn

from torch.utils.data import DataLoader
from torchvision.datasets import ImageFolder
from torchvision.models import convnext_small

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    precision_recall_fscore_support,
)

from tqdm.auto import tqdm

print("=" * 80)
print("F06 Step 4 — Official unchanged test evaluation")
print("=" * 80)

# ------------------------------------------------------------
# Locked paths
# ------------------------------------------------------------

F06_ROOT = Path(
    "/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/"
    "F06_CONVNEXT_SMALL_HR384_GENTLE_CB_FOCAL"
)

BEST_PATH = F06_ROOT / "weights" / "best_model.pth"
TABLES_DIR = F06_ROOT / "tables"

EXPECTED_SHA256 = (
    "d0c225c28b25f09822bc99518a37f9b1"
    "fe642b2d01213da7f68e2d76a255832a"
)

TEST_DIR = DATA_ROOT / "test"

# ------------------------------------------------------------
# SHA-256 verification
# ------------------------------------------------------------

def sha256_file(path):
    h = hashlib.sha256()

    with open(path, "rb") as f:
        for chunk in iter(
            lambda: f.read(1024 * 1024),
            b"",
        ):
            h.update(chunk)

    return h.hexdigest()


actual_sha256 = sha256_file(BEST_PATH)

if actual_sha256 != EXPECTED_SHA256:
    raise RuntimeError(
        "F06 best checkpoint SHA-256 verification failed."
    )

print("\nCheckpoint SHA-256 :", actual_sha256)
print("SHA verification  : PASSED")

# ------------------------------------------------------------
# Official HR384 test loader
# ------------------------------------------------------------

test_dataset = ImageFolder(
    TEST_DIR,
    transform=val_transform,
)

if len(test_dataset) != 1612:
    raise RuntimeError(
        f"Expected 1,612 official test images, found {len(test_dataset)}."
    )

if test_dataset.classes != train_dataset.classes:
    raise RuntimeError("Official test class order mismatch.")

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=0,
    pin_memory=True,
)

print("\nOfficial test images:", len(test_dataset))
print("Classes             :", len(test_dataset.classes))
print("Test batches        :", len(test_loader))

# ------------------------------------------------------------
# Load locked F06 best checkpoint
# ------------------------------------------------------------

checkpoint = torch.load(
    BEST_PATH,
    map_location="cpu",
    weights_only=False,
)

model = convnext_small(weights=None)

in_features = model.classifier[2].in_features

model.classifier[2] = nn.Linear(
    in_features,
    NUM_CLASSES,
)

model.load_state_dict(
    checkpoint["model_state_dict"],
    strict=True,
)

model = model.to(device)
model.eval()

print("\nLocked best epoch   :", checkpoint["epoch"])
print(
    "Locked Val Macro F1:",
    f"{checkpoint['val_metrics']['val_macro_f1'] * 100:.4f}%"
)

# ------------------------------------------------------------
# Official test inference
# ------------------------------------------------------------

all_logits = []
all_targets = []
all_paths = []

test_loss_sum = 0.0

sample_offset = 0

with torch.no_grad():

    for images, targets in tqdm(
        test_loader,
        desc="Official F06 test",
        unit="batch",
    ):

        batch_size_now = targets.size(0)

        images = images.to(
            device,
            non_blocking=True,
        )

        targets = targets.to(
            device,
            non_blocking=True,
        )

        with torch.amp.autocast(
            device_type=device.type,
            dtype=torch.float16,
            enabled=AMP_ENABLED,
        ):

            logits = model(images)
            loss = criterion(logits, targets)

        test_loss_sum += (
            loss.item() * batch_size_now
        )

        all_logits.append(
            logits.float().cpu()
        )

        all_targets.append(
            targets.cpu()
        )

        batch_samples = test_dataset.samples[
            sample_offset:sample_offset + batch_size_now
        ]

        all_paths.extend(
            [sample[0] for sample in batch_samples]
        )

        sample_offset += batch_size_now

all_logits = torch.cat(all_logits)
all_targets = torch.cat(all_targets)

probabilities = torch.softmax(
    all_logits,
    dim=1,
)

predictions = probabilities.argmax(dim=1)

# ------------------------------------------------------------
# Top-k metrics
# ------------------------------------------------------------

def topk_accuracy(probabilities, targets, k):

    topk_indices = probabilities.topk(
        k,
        dim=1,
    ).indices

    return (
        topk_indices
        == targets.unsqueeze(1)
    ).any(dim=1).float().mean().item()


top1 = topk_accuracy(
    probabilities,
    all_targets,
    1,
)

top2 = topk_accuracy(
    probabilities,
    all_targets,
    2,
)

top3 = topk_accuracy(
    probabilities,
    all_targets,
    3,
)

top5 = topk_accuracy(
    probabilities,
    all_targets,
    5,
)

# ------------------------------------------------------------
# Precision / recall / F1
# ------------------------------------------------------------

macro_precision, macro_recall, macro_f1, _ = (
    precision_recall_fscore_support(
        all_targets.numpy(),
        predictions.numpy(),
        average="macro",
        zero_division=0,
    )
)

_, _, weighted_f1, _ = (
    precision_recall_fscore_support(
        all_targets.numpy(),
        predictions.numpy(),
        average="weighted",
        zero_division=0,
    )
)

test_loss = (
    test_loss_sum / len(test_dataset)
)

# ------------------------------------------------------------
# Classification report
# ------------------------------------------------------------

report = classification_report(
    all_targets.numpy(),
    predictions.numpy(),
    target_names=test_dataset.classes,
    output_dict=True,
    zero_division=0,
)

report_df = (
    pd.DataFrame(report)
    .transpose()
    .reset_index()
    .rename(columns={"index": "class_name"})
)

report_path = (
    TABLES_DIR / "F06_classification_report.csv"
)

report_df.to_csv(
    report_path,
    index=False,
)

# ------------------------------------------------------------
# Confusion matrices
# ------------------------------------------------------------

cm = confusion_matrix(
    all_targets.numpy(),
    predictions.numpy(),
)

cm_normalized = confusion_matrix(
    all_targets.numpy(),
    predictions.numpy(),
    normalize="true",
)

cm_df = pd.DataFrame(
    cm,
    index=test_dataset.classes,
    columns=test_dataset.classes,
)

cm_norm_df = pd.DataFrame(
    cm_normalized,
    index=test_dataset.classes,
    columns=test_dataset.classes,
)

cm_path = (
    TABLES_DIR / "F06_confusion_matrix.csv"
)

cm_norm_path = (
    TABLES_DIR / "F06_confusion_matrix_normalized.csv"
)

cm_df.to_csv(cm_path)
cm_norm_df.to_csv(cm_norm_path)

# ------------------------------------------------------------
# Prediction table
# ------------------------------------------------------------

top5_probabilities, top5_indices = (
    probabilities.topk(
        5,
        dim=1,
    )
)

prediction_rows = []

for index in range(len(test_dataset)):

    row = {
        "sample_id": index,
        "image_path": all_paths[index],
        "true_class_id": int(all_targets[index]),
        "true_class_name": test_dataset.classes[
            int(all_targets[index])
        ],
        "predicted_class_id": int(predictions[index]),
        "predicted_class_name": test_dataset.classes[
            int(predictions[index])
        ],
        "correct": bool(
            predictions[index] == all_targets[index]
        ),
    }

    for rank in range(5):

        class_id = int(
            top5_indices[index, rank]
        )

        row[f"top{rank + 1}_class_id"] = class_id

        row[f"top{rank + 1}_class_name"] = (
            test_dataset.classes[class_id]
        )

        row[f"top{rank + 1}_probability"] = float(
            top5_probabilities[index, rank]
        )

    prediction_rows.append(row)

predictions_df = pd.DataFrame(
    prediction_rows
)

predictions_path = (
    TABLES_DIR / "F06_test_predictions.csv"
)

predictions_df.to_csv(
    predictions_path,
    index=False,
)

# ------------------------------------------------------------
# Official metric tables
# ------------------------------------------------------------

metrics = {
    "experiment": (
        "F06_CONVNEXT_SMALL_HR384_GENTLE_CB_FOCAL"
    ),
    "best_epoch": int(checkpoint["epoch"]),
    "checkpoint_sha256": actual_sha256,
    "test_images": len(test_dataset),
    "num_classes": len(test_dataset.classes),
    "test_loss": test_loss,
    "top1": top1,
    "top2": top2,
    "top3": top3,
    "top5": top5,
    "macro_precision": macro_precision,
    "macro_recall": macro_recall,
    "macro_f1": macro_f1,
    "weighted_f1": weighted_f1,
}

metrics_df = pd.DataFrame(
    [metrics]
)

metrics_path = (
    TABLES_DIR / "F06_test_metrics_summary.csv"
)

metrics_df.to_csv(
    metrics_path,
    index=False,
)

comparison_df = pd.DataFrame([
    {
        "Experiment": "F06",
        "Method": (
            "ConvNeXt-Small + HR384 fine-tuning "
            "+ Gentle CB Focal"
        ),
        "Top-1 (%)": top1 * 100,
        "Top-2 (%)": top2 * 100,
        "Top-3 (%)": top3 * 100,
        "Top-5 (%)": top5 * 100,
        "Macro Precision (%)": macro_precision * 100,
        "Macro Recall (%)": macro_recall * 100,
        "Macro F1 (%)": macro_f1 * 100,
        "Weighted F1 (%)": weighted_f1 * 100,
    }
])

comparison_path = (
    TABLES_DIR / "F06_comparison_ready_summary.csv"
)

comparison_df.to_csv(
    comparison_path,
    index=False,
)

# ------------------------------------------------------------
# Final official output
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("F06 OFFICIAL TEST RESULTS")
print("=" * 80)

results_table = pd.DataFrame([
    ["Test images", f"{len(test_dataset):,}"],
    ["Classes", len(test_dataset.classes)],
    ["Best epoch", checkpoint["epoch"]],
    ["Test loss", f"{test_loss:.6f}"],
    ["Top-1", f"{top1 * 100:.4f}%"],
    ["Top-2", f"{top2 * 100:.4f}%"],
    ["Top-3", f"{top3 * 100:.4f}%"],
    ["Top-5", f"{top5 * 100:.4f}%"],
    ["Macro Precision", f"{macro_precision * 100:.4f}%"],
    ["Macro Recall", f"{macro_recall * 100:.4f}%"],
    ["Macro F1", f"{macro_f1 * 100:.4f}%"],
    ["Weighted F1", f"{weighted_f1 * 100:.4f}%"],
], columns=["Metric", "Official F06 Result"])

print(
    results_table.to_string(
        index=False,
    )
)

print("\n" + "=" * 80)
print("F06 TEST ARTIFACTS")
print("=" * 80)

print("Metrics summary     :", metrics_path)
print("Comparison summary  :", comparison_path)
print("Classification      :", report_path)
print("Predictions         :", predictions_path)
print("Confusion matrix    :", cm_path)
print("Normalized CM       :", cm_norm_path)

print("\nCheckpoint SHA-256  :", actual_sha256)
print("Official test split : VERIFIED — 1,612 images")
print("Model selection     : Validation Macro F1 only")

print("\n" + "=" * 80)
print("F06 STEP 4 PASSED — OFFICIAL TEST EVALUATION COMPLETE")
print("=" * 80)

print("NEXT : F06 Step 5 — final figures and downloadable package")

================================================================================
F06 Step 4 — Official unchanged test evaluation
================================================================================

Checkpoint SHA-256 : d0c225c28b25f09822bc99518a37f9b1fe642b2d01213da7f68e2d76a255832a
SHA verification  : PASSED

Official test images: 1612
Classes             : 20
Test batches        : 202

Locked best epoch   : 2
Locked Val Macro F1: 88.5122%

Official F06 test:   0%|          | 0/202 [00:00<?, ?batch/s]

================================================================================
F06 OFFICIAL TEST RESULTS
================================================================================
         Metric Official F06 Result
    Test images               1,612
        Classes                  20
     Best epoch                   2
      Test loss            0.092478
          Top-1            92.1216%
          Top-2            97.9529%
          Top-3            99.2556%
          Top-5            99.7519%
Macro Precision            90.4312%
   Macro Recall            87.4362%
       Macro F1            88.1699%
    Weighted F1            92.0810%

================================================================================
F06 TEST ARTIFACTS
================================================================================
Metrics summary     : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/F06_CONVNEXT_SMALL_HR384_GENTLE_CB_FOCAL/tables/F06_test_metrics_summary.csv
Comparison summary  : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/F06_CONVNEXT_SMALL_HR384_GENTLE_CB_FOCAL/tables/F06_comparison_ready_summary.csv
Classification      : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/F06_CONVNEXT_SMALL_HR384_GENTLE_CB_FOCAL/tables/F06_classification_report.csv
Predictions         : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/F06_CONVNEXT_SMALL_HR384_GENTLE_CB_FOCAL/tables/F06_test_predictions.csv
Confusion matrix    : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/F06_CONVNEXT_SMALL_HR384_GENTLE_CB_FOCAL/tables/F06_confusion_matrix.csv
Normalized CM       : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/F06_CONVNEXT_SMALL_HR384_GENTLE_CB_FOCAL/tables/F06_confusion_matrix_normalized.csv

Checkpoint SHA-256  : d0c225c28b25f09822bc99518a37f9b1fe642b2d01213da7f68e2d76a255832a
Official test split : VERIFIED — 1,612 images
Model selection     : Validation Macro F1 only

================================================================================
F06 STEP 4 PASSED — OFFICIAL TEST EVALUATION COMPLETE
================================================================================
NEXT : F06 Step 5 — final figures and downloadable package

# F06 Step 5 — Create Final Figures and Official Downloadable Package

F06 official test evaluation is complete.

The locked F06 checkpoint achieved:

- Top-1: 92.1216%
- Top-2: 97.9529%
- Top-3: 99.2556%
- Top-5: 99.7519%
- Macro Precision: 90.4312%
- Macro Recall: 87.4362%
- Macro F1: 88.1699%
- Weighted F1: 92.0810%

This step creates the final F06 figures, scientific comparison tables, README,
and official downloadable experiment package.

In [34]:
# ============================================================
# F06 Step 5 — Final figures and official package
# ============================================================

from pathlib import Path
import json
import shutil
import zipfile

import pandas as pd
import matplotlib.pyplot as plt

print("=" * 80)
print("F06 Step 5 — Final figures and official package")
print("=" * 80)

F06_ROOT = Path(
    "/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/"
    "F06_CONVNEXT_SMALL_HR384_GENTLE_CB_FOCAL"
)

TABLES_DIR = F06_ROOT / "tables"
WEIGHTS_DIR = F06_ROOT / "weights"
FIGURES_DIR = F06_ROOT / "figures"

FIGURES_DIR.mkdir(parents=True, exist_ok=True)

# ------------------------------------------------------------
# Load official F06 artifacts
# ------------------------------------------------------------

history = pd.read_csv(
    TABLES_DIR / "F06_training_history.csv"
)

metrics = pd.read_csv(
    TABLES_DIR / "F06_test_metrics_summary.csv"
).iloc[0]

cm = pd.read_csv(
    TABLES_DIR / "F06_confusion_matrix.csv",
    index_col=0,
)

cm_norm = pd.read_csv(
    TABLES_DIR / "F06_confusion_matrix_normalized.csv",
    index_col=0,
)

# ------------------------------------------------------------
# Training history figure
# ------------------------------------------------------------

plt.figure(figsize=(10, 6))

plt.plot(
    history["epoch"],
    history["val_top1"] * 100,
    marker="o",
    label="Validation Top-1",
)

plt.plot(
    history["epoch"],
    history["val_macro_f1"] * 100,
    marker="o",
    label="Validation Macro F1",
)

plt.xlabel("Epoch")
plt.ylabel("Score (%)")
plt.title("F06 HR384 Validation History")
plt.xticks(history["epoch"])
plt.grid(True, alpha=0.3)
plt.legend()
plt.tight_layout()

history_figure = (
    FIGURES_DIR / "F06_validation_history.png"
)

plt.savefig(
    history_figure,
    dpi=300,
    bbox_inches="tight",
)

plt.close()

# ------------------------------------------------------------
# Confusion matrix figure
# ------------------------------------------------------------

plt.figure(figsize=(14, 12))

plt.imshow(cm.values)

plt.xticks(
    range(len(cm.columns)),
    cm.columns,
    rotation=90,
)

plt.yticks(
    range(len(cm.index)),
    cm.index,
)

plt.xlabel("Predicted Class")
plt.ylabel("True Class")
plt.title("F06 Official Test Confusion Matrix")

plt.colorbar()
plt.tight_layout()

cm_figure = (
    FIGURES_DIR / "F06_confusion_matrix.png"
)

plt.savefig(
    cm_figure,
    dpi=300,
    bbox_inches="tight",
)

plt.close()

# ------------------------------------------------------------
# Normalized confusion matrix figure
# ------------------------------------------------------------

plt.figure(figsize=(14, 12))

plt.imshow(
    cm_norm.values,
    vmin=0,
    vmax=1,
)

plt.xticks(
    range(len(cm_norm.columns)),
    cm_norm.columns,
    rotation=90,
)

plt.yticks(
    range(len(cm_norm.index)),
    cm_norm.index,
)

plt.xlabel("Predicted Class")
plt.ylabel("True Class")
plt.title(
    "F06 Official Test Normalized Confusion Matrix"
)

plt.colorbar()
plt.tight_layout()

cm_norm_figure = (
    FIGURES_DIR /
    "F06_confusion_matrix_normalized.png"
)

plt.savefig(
    cm_norm_figure,
    dpi=300,
    bbox_inches="tight",
)

plt.close()

# ------------------------------------------------------------
# F03-F06 scientific comparison
# ------------------------------------------------------------

comparison = pd.DataFrame([
    {
        "Experiment": "F03",
        "Method": "Original train + Gentle CB Focal",
        "Top-1 (%)": 91.6253,
        "Macro Recall (%)": 86.9302,
        "Macro F1 (%)": 87.9645,
    },
    {
        "Experiment": "F04",
        "Method": "Aug-200 + Cross-Entropy",
        "Top-1 (%)": 91.3772,
        "Macro Recall (%)": 84.3236,
        "Macro F1 (%)": 86.0035,
    },
    {
        "Experiment": "F05",
        "Method": "Aug-200 + Gentle CB Focal",
        "Top-1 (%)": 91.1290,
        "Macro Recall (%)": 82.6547,
        "Macro F1 (%)": 84.3487,
    },
    {
        "Experiment": "F06",
        "Method": "F03 branch + HR384 fine-tuning",
        "Top-1 (%)": float(metrics["top1"]) * 100,
        "Macro Recall (%)": float(metrics["macro_recall"]) * 100,
        "Macro F1 (%)": float(metrics["macro_f1"]) * 100,
    },
])

comparison_path = (
    TABLES_DIR / "F06_F03_F06_scientific_comparison.csv"
)

comparison.to_csv(
    comparison_path,
    index=False,
)

# ------------------------------------------------------------
# Campaign-target comparison
# ------------------------------------------------------------

target_comparison = pd.DataFrame([
    {
        "Metric": "Top-1",
        "Target (%)": 92.68,
        "F06 (%)": float(metrics["top1"]) * 100,
    },
    {
        "Metric": "Macro Precision",
        "Target (%)": 91.40,
        "F06 (%)": float(metrics["macro_precision"]) * 100,
    },
    {
        "Metric": "Macro Recall",
        "Target (%)": 87.32,
        "F06 (%)": float(metrics["macro_recall"]) * 100,
    },
    {
        "Metric": "Macro F1",
        "Target (%)": 88.92,
        "F06 (%)": float(metrics["macro_f1"]) * 100,
    },
    {
        "Metric": "Top-2",
        "Target (%)": 97.58,
        "F06 (%)": float(metrics["top2"]) * 100,
    },
    {
        "Metric": "Top-3",
        "Target (%)": 98.82,
        "F06 (%)": float(metrics["top3"]) * 100,
    },
])

target_comparison["Passed"] = (
    target_comparison["F06 (%)"]
    > target_comparison["Target (%)"]
)

target_comparison_path = (
    TABLES_DIR / "F06_campaign_target_comparison.csv"
)

target_comparison.to_csv(
    target_comparison_path,
    index=False,
)

# ------------------------------------------------------------
# README
# ------------------------------------------------------------

README_PATH = F06_ROOT / "README_F06.txt"

README_PATH.write_text(
f"""AQUA20 F06 OFFICIAL EXPERIMENT PACKAGE

Campaign:
04-07-2026 AQUA20 FINAL BEAT BASE PLAN

Experiment:
F06_CONVNEXT_SMALL_HR384_GENTLE_CB_FOCAL

Scientific role:
High-resolution fine-tuning.

Source branch:
F03_CONVNEXT_SMALL_GENTLE_CB_FOCAL

Method:
ConvNeXt-Small
+ original AQUA20 training distribution
+ Gentle Class-Balanced Focal Loss
+ 384 x 384 high-resolution fine-tuning

Source checkpoint SHA-256:
928c8af60aef70537263e2c8cc1cf13782747bc5974f86ff054fbe352065c26f

F06 best epoch:
2

F06 validation Macro F1:
88.5122%

F06 checkpoint SHA-256:
d0c225c28b25f09822bc99518a37f9b1fe642b2d01213da7f68e2d76a255832a

Training termination:
9 fully completed epochs.
Epoch 10 was manually interrupted and excluded.
Training was manually terminated following a sustained validation Macro F1 plateau.
The official test split was not used for stopping or checkpoint selection.

Official test split:
1,612 images
20 classes

Official F06 test results:
Top-1: 92.1216%
Top-2: 97.9529%
Top-3: 99.2556%
Top-5: 99.7519%
Macro Precision: 90.4312%
Macro Recall: 87.4362%
Macro F1: 88.1699%
Weighted F1: 92.0810%

Scientific finding:
High-resolution fine-tuning improved the isolated F03 Gentle CB Focal branch.
F06 exceeded F03 in official-test Top-1, Macro Recall, and Macro F1.

F06 passed the campaign Macro Recall, Top-2, and Top-3 targets.

F06 did not exceed the campaign Top-1, Macro Precision, or Macro F1 targets.

The result supports high-resolution fine-tuning as a positive but insufficient
standalone intervention for fully beating the campaign target.
"""
)

# ------------------------------------------------------------
# Create official ZIP
# ------------------------------------------------------------

ZIP_PATH = (
    F06_ROOT.parent /
    "aqua20_f06_convnext_small_hr384_gentle_focal_outputs.zip"
)

if ZIP_PATH.exists():
    ZIP_PATH.unlink()

with zipfile.ZipFile(
    ZIP_PATH,
    "w",
    compression=zipfile.ZIP_DEFLATED,
) as zf:

    for file_path in sorted(F06_ROOT.rglob("*")):

        if file_path.is_file():

            archive_name = file_path.relative_to(
                F06_ROOT
            )

            zf.write(
                file_path,
                archive_name,
            )

# ------------------------------------------------------------
# Final package output
# ------------------------------------------------------------

zip_size_mb = ZIP_PATH.stat().st_size / (1024 ** 2)

print("\nFinal package :", ZIP_PATH)
print("ZIP size      :", f"{zip_size_mb:.2f} MB")

print("\nPACKAGE CONTENTS")

with zipfile.ZipFile(ZIP_PATH, "r") as zf:

    for name in zf.namelist():
        print(name)

print("\n" + "=" * 80)
print("F06 STEP 5 PASSED — OFFICIAL FINAL PACKAGE CREATED")
print("=" * 80)

print("F06 STATUS : COMPLETED")
print("DOWNLOAD   :", ZIP_PATH)

================================================================================
F06 Step 5 — Final figures and official package
================================================================================

Final package : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/aqua20_f06_convnext_small_hr384_gentle_focal_outputs.zip
ZIP size      : 351.17 MB

PACKAGE CONTENTS
F06_locked_protocol.json
README_F06.txt
figures/F06_confusion_matrix.png
figures/F06_confusion_matrix_normalized.png
figures/F06_validation_history.png
tables/F06_F03_F06_scientific_comparison.csv
tables/F06_best_epoch_summary.csv
tables/F06_campaign_target_comparison.csv
tables/F06_classification_report.csv
tables/F06_comparison_ready_summary.csv
tables/F06_confusion_matrix.csv
tables/F06_confusion_matrix_normalized.csv
tables/F06_test_metrics_summary.csv
tables/F06_test_predictions.csv
tables/F06_training_history.csv
tables/F06_training_termination.json
weights/F06_best_model_sha256.txt
weights/best_model.pth
weights/last_model.pth

================================================================================
F06 STEP 5 PASSED — OFFICIAL FINAL PACKAGE CREATED
================================================================================
F06 STATUS : COMPLETED
DOWNLOAD   : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/aqua20_f06_convnext_small_hr384_gentle_focal_outputs.zip

# F07 — ConvNeXt-Small HR384 + Test-Time Augmentation

Official campaign: `04-07-2026 AQUA20 FINAL BEAT BASE PLAN`

Experiment:

`F07_CONVNEXT_SMALL_HR384_TTA`

Scientific role:

Evaluate deterministic test-time augmentation on the locked F06 high-resolution ConvNeXt-Small checkpoint.

Locked source:

- Experiment: `F06_CONVNEXT_SMALL_HR384_GENTLE_CB_FOCAL`
- Best epoch: 2
- Resolution: 384 × 384
- Checkpoint selected by validation Macro F1
- SHA-256: `d0c225c28b25f09822bc99518a37f9b1fe642b2d01213da7f68e2d76a255832a`

Locked TTA:

1. Original image
2. Horizontal-flipped image
3. Softmax each view
4. Arithmetic mean of class probabilities
5. Final prediction from averaged probabilities

F07 is inference-only.

No training and no early stopping are applicable.

The official test split will not be used to alter the F07 checkpoint or TTA protocol.

In [7]:
# ============================================================
# F07 STEP 1 — RESTORE AND VERIFY LOCKED F06 CHECKPOINT
# ============================================================

from pathlib import Path
import hashlib

print("=" * 80)
print("F07 Step 1 — Restore and verify locked F06 checkpoint")
print("=" * 80)

EXPECTED_SHA256 = (
    "d0c225c28b25f09822bc99518a37f9b1fe642b2d01213da7f68e2d76a255832a"
)

F07_DIR = Path(
    "/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/"
    "F07_CONVNEXT_SMALL_HR384_TTA"
)

F07_DIR.mkdir(parents=True, exist_ok=True)

checkpoint_matches = list(
    Path("/kaggle/input").rglob("best_model.pth")
)

verified_checkpoint = None

for checkpoint in checkpoint_matches:
    sha256 = hashlib.sha256(checkpoint.read_bytes()).hexdigest()

    if sha256 == EXPECTED_SHA256:
        verified_checkpoint = checkpoint
        break

assert verified_checkpoint is not None, (
    "Locked F06 checkpoint with expected SHA-256 was not found."
)

F06_CHECKPOINT = verified_checkpoint

print()
print("F06 checkpoint :", F06_CHECKPOINT)
print("SHA-256        :", EXPECTED_SHA256)
print("Verification   : PASSED")

print()
print("F07 experiment : F07_CONVNEXT_SMALL_HR384_TTA")
print("Source branch  : F06 HR384 Gentle CB Focal")
print("Source epoch   : 2")
print("Resolution     : 384 x 384")
print("Training       : NONE")
print("Early stopping : NOT APPLICABLE")
print("TTA views      : Original + Horizontal Flip")
print("Aggregation    : Mean softmax probability")

print()
print("=" * 80)
print("F07 STEP 1 PASSED — SOURCE AND PROTOCOL LOCKED")
print("=" * 80)

================================================================================
F07 Step 1 — Restore and verify locked F06 checkpoint
================================================================================

F06 checkpoint : /kaggle/input/datasets/sazzad1/aqua20-f06-convnext-small-hr384-gentle-focal/weights/best_model.pth
SHA-256        : d0c225c28b25f09822bc99518a37f9b1fe642b2d01213da7f68e2d76a255832a
Verification   : PASSED

F07 experiment : F07_CONVNEXT_SMALL_HR384_TTA
Source branch  : F06 HR384 Gentle CB Focal
Source epoch   : 2
Resolution     : 384 x 384
Training       : NONE
Early stopping : NOT APPLICABLE
TTA views      : Original + Horizontal Flip
Aggregation    : Mean softmax probability

================================================================================
F07 STEP 1 PASSED — SOURCE AND PROTOCOL LOCKED
================================================================================

## F07 Step 2 — Restore HR384 model and verify TTA pipeline

The locked F06 best checkpoint is restored as a torchvision ConvNeXt-Small model.

The unchanged official AQUA20 validation split is loaded at 384 × 384 resolution using the same ImageNet normalization protocol as F06.

The fixed F07 TTA pipeline contains two deterministic views:

1. Original image
2. Horizontal-flipped image

This step verifies model loading, class order, and tensor compatibility before full validation evaluation.

The official test split is not used.

In [8]:
# ============================================================
# F07 STEP 2 — RESTORE MODEL AND VERIFY VALIDATION/TTA PIPELINE
# ============================================================

from pathlib import Path

import torch
import torch.nn as nn

from torch.utils.data import DataLoader
from torchvision import datasets, transforms
from torchvision.models import convnext_small

print("=" * 80)
print("F07 Step 2 — Restore model and verify validation/TTA pipeline")
print("=" * 80)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

PROJECT_ROOT = Path(
    "/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026"
)

VAL_DIR = PROJECT_ROOT / "official_imagefolder" / "val"

assert VAL_DIR.exists(), f"Validation directory not found: {VAL_DIR}"

# ------------------------------------------------------------
# Validation transform — same F06 HR384 evaluation protocol
# ------------------------------------------------------------

val_transform = transforms.Compose([
    transforms.Resize((384, 384)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225],
    ),
])

val_dataset = datasets.ImageFolder(
    VAL_DIR,
    transform=val_transform,
)

assert len(val_dataset.classes) == 20, (
    f"Expected 20 classes, found {len(val_dataset.classes)}"
)

val_loader = DataLoader(
    val_dataset,
    batch_size=8,
    shuffle=False,
    num_workers=2,
    pin_memory=True,
)

# ------------------------------------------------------------
# Restore locked F06 model
# ------------------------------------------------------------

checkpoint = torch.load(
    F06_CHECKPOINT,
    map_location="cpu",
    weights_only=False,
)

state_dict = checkpoint.get(
    "model_state_dict",
    checkpoint.get("state_dict", checkpoint),
)

model = convnext_small(weights=None)

in_features = model.classifier[2].in_features
model.classifier[2] = nn.Linear(in_features, 20)

model.load_state_dict(state_dict)
model = model.to(DEVICE)
model.eval()

# ------------------------------------------------------------
# Optional packaged class-order verification
# ------------------------------------------------------------

checkpoint_classes = checkpoint.get("class_names")

if checkpoint_classes is not None:
    assert list(checkpoint_classes) == list(val_dataset.classes), (
        "Checkpoint and validation class order mismatch."
    )

# ------------------------------------------------------------
# TTA dry run
# ------------------------------------------------------------

images, labels = next(iter(val_loader))

images = images.to(DEVICE)

with torch.inference_mode():
    logits_original = model(images)

    images_flip = torch.flip(images, dims=[3])
    logits_flip = model(images_flip)

    probs_original = torch.softmax(logits_original, dim=1)
    probs_flip = torch.softmax(logits_flip, dim=1)

    probs_tta = (probs_original + probs_flip) / 2.0

print()
print("Device             :", DEVICE)
print("Validation images  :", len(val_dataset))
print("Classes            :", len(val_dataset.classes))
print("Image tensor       :", tuple(images.shape))
print("Original logits    :", tuple(logits_original.shape))
print("Flip logits        :", tuple(logits_flip.shape))
print("TTA probabilities  :", tuple(probs_tta.shape))
print("Probability sum    :", f"{probs_tta[0].sum().item():.6f}")
print("Class order check  : PASSED")
print("TTA dry run        : PASSED")

print()
print("=" * 80)
print("F07 STEP 2 PASSED — HR384 MODEL AND TTA PIPELINE VERIFIED")
print("=" * 80)

================================================================================
F07 Step 2 — Restore model and verify validation/TTA pipeline
================================================================================

Device             : cuda
Validation images  : 1312
Classes            : 20
Image tensor       : (8, 3, 384, 384)
Original logits    : (8, 20)
Flip logits        : (8, 20)
TTA probabilities  : (8, 20)
Probability sum    : 1.000000
Class order check  : PASSED
TTA dry run        : PASSED

================================================================================
F07 STEP 2 PASSED — HR384 MODEL AND TTA PIPELINE VERIFIED
================================================================================

## F07 Step 3 — Validation comparison of single-view inference and fixed TTA

The locked F06 checkpoint is evaluated on the unchanged AQUA20 validation split using:

- Single-view HR384 inference
- Fixed F07 two-view TTA: original + horizontal flip

For TTA, softmax probability vectors from both views are averaged.

The checkpoint and TTA configuration are already locked and will not be changed from these validation results.

This step records validation evidence before official-test evaluation.

In [9]:
# ============================================================
# F07 STEP 3 — VALIDATION SINGLE-VIEW VS FIXED TTA
# ============================================================

import numpy as np
import pandas as pd
import torch

from tqdm.auto import tqdm
from sklearn.metrics import precision_recall_fscore_support

print("=" * 80)
print("F07 Step 3 — Validation single-view vs fixed TTA")
print("=" * 80)

TABLES_DIR = F07_DIR / "tables"
TABLES_DIR.mkdir(parents=True, exist_ok=True)

all_targets = []
all_single_probs = []
all_tta_probs = []

model.eval()

with torch.inference_mode():
    for images, targets in tqdm(val_loader, desc="Validation"):
        images = images.to(DEVICE, non_blocking=True)

        logits_original = model(images)
        logits_flip = model(torch.flip(images, dims=[3]))

        probs_original = torch.softmax(logits_original, dim=1)
        probs_flip = torch.softmax(logits_flip, dim=1)

        probs_tta = (probs_original + probs_flip) / 2.0

        all_targets.append(targets.numpy())
        all_single_probs.append(probs_original.cpu().numpy())
        all_tta_probs.append(probs_tta.cpu().numpy())

targets = np.concatenate(all_targets)
single_probs = np.concatenate(all_single_probs)
tta_probs = np.concatenate(all_tta_probs)

single_preds = single_probs.argmax(axis=1)
tta_preds = tta_probs.argmax(axis=1)


def calculate_metrics(targets, probs, preds):
    precision, recall, macro_f1, _ = precision_recall_fscore_support(
        targets,
        preds,
        average="macro",
        zero_division=0,
    )

    weighted_f1 = precision_recall_fscore_support(
        targets,
        preds,
        average="weighted",
        zero_division=0,
    )[2]

    sorted_idx = np.argsort(probs, axis=1)[:, ::-1]

    return {
        "Top-1": np.mean(sorted_idx[:, :1] == targets[:, None]) * 100,
        "Top-2": np.mean(
            np.any(sorted_idx[:, :2] == targets[:, None], axis=1)
        ) * 100,
        "Top-3": np.mean(
            np.any(sorted_idx[:, :3] == targets[:, None], axis=1)
        ) * 100,
        "Top-5": np.mean(
            np.any(sorted_idx[:, :5] == targets[:, None], axis=1)
        ) * 100,
        "Macro Precision": precision * 100,
        "Macro Recall": recall * 100,
        "Macro F1": macro_f1 * 100,
        "Weighted F1": weighted_f1 * 100,
    }


single_metrics = calculate_metrics(
    targets,
    single_probs,
    single_preds,
)

tta_metrics = calculate_metrics(
    targets,
    tta_probs,
    tta_preds,
)

comparison = pd.DataFrame({
    "Metric": single_metrics.keys(),
    "Single_View": single_metrics.values(),
    "F07_TTA": tta_metrics.values(),
})

comparison["Delta_pp"] = (
    comparison["F07_TTA"] - comparison["Single_View"]
)

comparison.to_csv(
    TABLES_DIR / "F07_validation_single_vs_tta.csv",
    index=False,
)

predictions_df = pd.DataFrame({
    "target_index": targets,
    "target_class": [val_dataset.classes[i] for i in targets],
    "single_pred_index": single_preds,
    "single_pred_class": [
        val_dataset.classes[i] for i in single_preds
    ],
    "tta_pred_index": tta_preds,
    "tta_pred_class": [
        val_dataset.classes[i] for i in tta_preds
    ],
})

predictions_df.to_csv(
    TABLES_DIR / "F07_validation_predictions.csv",
    index=False,
)

print()
print(comparison.to_string(index=False, float_format=lambda x: f"{x:.4f}"))

print()
print("Single-view correct :", int((single_preds == targets).sum()))
print("TTA correct         :", int((tta_preds == targets).sum()))
print("Validation images   :", len(targets))

print()
print(
    "Single Macro F1     :",
    f"{single_metrics['Macro F1']:.4f}%"
)
print(
    "F07 TTA Macro F1    :",
    f"{tta_metrics['Macro F1']:.4f}%"
)
print(
    "Macro F1 delta      :",
    f"{tta_metrics['Macro F1'] - single_metrics['Macro F1']:+.4f} pp"
)

print()
print("=" * 80)
print("F07 STEP 3 PASSED — VALIDATION COMPARISON RECORDED")
print("=" * 80)

================================================================================
F07 Step 3 — Validation single-view vs fixed TTA
================================================================================

Validation:   0%|          | 0/164 [00:00<?, ?it/s]

         Metric  Single_View  F07_TTA  Delta_pp
          Top-1      92.9878  92.6829   -0.3049
          Top-2      98.6280  98.6280    0.0000
          Top-3      99.5427  99.4665   -0.0762
          Top-5      99.7713  99.6951   -0.0762
Macro Precision      88.4581  88.5306    0.0726
   Macro Recall      90.6790  91.2770    0.5981
       Macro F1      88.5122  88.9836    0.4714
    Weighted F1      93.0475  92.7625   -0.2850

Single-view correct : 1220
TTA correct         : 1216
Validation images   : 1312

Single Macro F1     : 88.5122%
F07 TTA Macro F1    : 88.9836%
Macro F1 delta      : +0.4714 pp

================================================================================
F07 STEP 3 PASSED — VALIDATION COMPARISON RECORDED
================================================================================

## F07 Step 4 — Official unchanged test evaluation

The fixed F07 two-view TTA protocol is now evaluated on the unchanged official AQUA20 test split.

The TTA configuration was locked before validation and has not been modified.

Evaluation compares:

- Locked F06-style single-view HR384 inference
- Locked F07 TTA: original + horizontal flip

The official test split is used only for final evaluation.

No checkpoint selection, TTA modification, or model tuning is performed using test results.

In [10]:
# ============================================================
# F07 STEP 4 — OFFICIAL UNCHANGED TEST EVALUATION
# ============================================================

import numpy as np
import pandas as pd
import torch

from torch.utils.data import DataLoader
from torchvision import datasets
from tqdm.auto import tqdm
from sklearn.metrics import precision_recall_fscore_support

print("=" * 80)
print("F07 Step 4 — Official unchanged test evaluation")
print("=" * 80)

TEST_DIR = PROJECT_ROOT / "official_imagefolder" / "test"

assert TEST_DIR.exists(), f"Test directory not found: {TEST_DIR}"

test_dataset = datasets.ImageFolder(
    TEST_DIR,
    transform=val_transform,
)

assert test_dataset.classes == val_dataset.classes, (
    "Validation and test class order mismatch."
)

test_loader = DataLoader(
    test_dataset,
    batch_size=8,
    shuffle=False,
    num_workers=2,
    pin_memory=True,
)

all_targets = []
all_single_probs = []
all_tta_probs = []

model.eval()

with torch.inference_mode():
    for images, targets_batch in tqdm(
        test_loader,
        desc="Official test"
    ):
        images = images.to(DEVICE, non_blocking=True)

        logits_original = model(images)
        logits_flip = model(torch.flip(images, dims=[3]))

        probs_original = torch.softmax(logits_original, dim=1)
        probs_flip = torch.softmax(logits_flip, dim=1)

        probs_tta = (probs_original + probs_flip) / 2.0

        all_targets.append(targets_batch.numpy())
        all_single_probs.append(probs_original.cpu().numpy())
        all_tta_probs.append(probs_tta.cpu().numpy())

test_targets = np.concatenate(all_targets)
test_single_probs = np.concatenate(all_single_probs)
test_tta_probs = np.concatenate(all_tta_probs)

test_single_preds = test_single_probs.argmax(axis=1)
test_tta_preds = test_tta_probs.argmax(axis=1)


def calculate_test_metrics(targets, probs, preds):
    precision, recall, macro_f1, _ = precision_recall_fscore_support(
        targets,
        preds,
        average="macro",
        zero_division=0,
    )

    weighted_f1 = precision_recall_fscore_support(
        targets,
        preds,
        average="weighted",
        zero_division=0,
    )[2]

    sorted_idx = np.argsort(probs, axis=1)[:, ::-1]

    true_probs = np.clip(
        probs[np.arange(len(targets)), targets],
        1e-12,
        1.0,
    )

    return {
        "Top-1": np.mean(
            sorted_idx[:, 0] == targets
        ) * 100,
        "Top-2": np.mean(
            np.any(sorted_idx[:, :2] == targets[:, None], axis=1)
        ) * 100,
        "Top-3": np.mean(
            np.any(sorted_idx[:, :3] == targets[:, None], axis=1)
        ) * 100,
        "Top-5": np.mean(
            np.any(sorted_idx[:, :5] == targets[:, None], axis=1)
        ) * 100,
        "Macro Precision": precision * 100,
        "Macro Recall": recall * 100,
        "Macro F1": macro_f1 * 100,
        "Weighted F1": weighted_f1 * 100,
        "NLL Loss": -np.log(true_probs).mean(),
    }


test_single_metrics = calculate_test_metrics(
    test_targets,
    test_single_probs,
    test_single_preds,
)

test_tta_metrics = calculate_test_metrics(
    test_targets,
    test_tta_probs,
    test_tta_preds,
)

test_comparison = pd.DataFrame({
    "Metric": test_single_metrics.keys(),
    "F06_Single_View": test_single_metrics.values(),
    "F07_TTA": test_tta_metrics.values(),
})

test_comparison["Delta"] = (
    test_comparison["F07_TTA"]
    - test_comparison["F06_Single_View"]
)

test_comparison.to_csv(
    TABLES_DIR / "F07_test_single_vs_tta.csv",
    index=False,
)

test_predictions_df = pd.DataFrame({
    "target_index": test_targets,
    "target_class": [
        test_dataset.classes[i] for i in test_targets
    ],
    "single_pred_index": test_single_preds,
    "single_pred_class": [
        test_dataset.classes[i] for i in test_single_preds
    ],
    "tta_pred_index": test_tta_preds,
    "tta_pred_class": [
        test_dataset.classes[i] for i in test_tta_preds
    ],
    "tta_confidence": test_tta_probs.max(axis=1),
})

test_predictions_df.to_csv(
    TABLES_DIR / "F07_test_predictions.csv",
    index=False,
)

print()
print(
    test_comparison.to_string(
        index=False,
        float_format=lambda x: f"{x:.6f}",
    )
)

print()
print("Official test images :", len(test_targets))
print("Classes              :", len(test_dataset.classes))
print("Single-view correct  :", int(
    (test_single_preds == test_targets).sum()
))
print("F07 TTA correct      :", int(
    (test_tta_preds == test_targets).sum()
))

print()
print("OFFICIAL F07 TTA RESULTS")
print("-" * 80)

for metric, value in test_tta_metrics.items():
    if metric == "NLL Loss":
        print(f"{metric:<20}: {value:.6f}")
    else:
        print(f"{metric:<20}: {value:.4f}%")

print()
print("=" * 80)
print("F07 STEP 4 PASSED — OFFICIAL TEST EVALUATION COMPLETED")
print("=" * 80)

================================================================================
F07 Step 4 — Official unchanged test evaluation
================================================================================

Official test:   0%|          | 0/202 [00:00<?, ?it/s]

         Metric  F06_Single_View   F07_TTA     Delta
          Top-1        92.121588 92.121588  0.000000
          Top-2        97.952854 97.890819 -0.062035
          Top-3        99.255583 99.317618  0.062035
          Top-5        99.751861 99.689826 -0.062035
Macro Precision        90.431233 89.876543 -0.554690
   Macro Recall        87.436208 86.532374 -0.903834
       Macro F1        88.169909 87.402551 -0.767357
    Weighted F1        92.080990 92.077110 -0.003880
       NLL Loss         0.251191  0.248791 -0.002401

Official test images : 1612
Classes              : 20
Single-view correct  : 1485
F07 TTA correct      : 1485

OFFICIAL F07 TTA RESULTS
--------------------------------------------------------------------------------
Top-1               : 92.1216%
Top-2               : 97.8908%
Top-3               : 99.3176%
Top-5               : 99.6898%
Macro Precision     : 89.8765%
Macro Recall        : 86.5324%
Macro F1            : 87.4026%
Weighted F1         : 92.0771%
NLL Loss            : 0.248791

================================================================================
F07 STEP 4 PASSED — OFFICIAL TEST EVALUATION COMPLETED
================================================================================

## F07 Step 5 — Create official final experiment package

The completed F07 validation and official-test outputs are consolidated into the final experiment package.

F07 is an inference-only TTA experiment and does not produce a new trained checkpoint.

The exact F06 source checkpoint is identified and verified by SHA-256.

The package contains:

- locked F07 protocol
- source checkpoint verification record
- validation single-view vs TTA comparison
- validation predictions
- official test comparison
- official F07 test metrics
- official test predictions
- classification report
- confusion matrices
- scientific comparison summary
- figures
- README

The verified F06 checkpoint weights are not duplicated because F07 created no new model checkpoint.

In [11]:
# ============================================================
# F07 STEP 5 — CREATE OFFICIAL FINAL EXPERIMENT PACKAGE
# ============================================================

from pathlib import Path
import hashlib
import json
import shutil

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from sklearn.metrics import classification_report, confusion_matrix

print("=" * 80)
print("F07 Step 5 — Create official final experiment package")
print("=" * 80)

FIGURES_DIR = F07_DIR / "figures"
TABLES_DIR = F07_DIR / "tables"

FIGURES_DIR.mkdir(parents=True, exist_ok=True)
TABLES_DIR.mkdir(parents=True, exist_ok=True)

# ------------------------------------------------------------
# Source checkpoint verification
# ------------------------------------------------------------

source_sha256 = hashlib.sha256(
    F06_CHECKPOINT.read_bytes()
).hexdigest()

assert source_sha256 == EXPECTED_SHA256

(F07_DIR / "F07_source_checkpoint_sha256.txt").write_text(
    f"Source experiment: F06_CONVNEXT_SMALL_HR384_GENTLE_CB_FOCAL\n"
    f"Source epoch: 2\n"
    f"SHA-256: {source_sha256}\n"
)

# ------------------------------------------------------------
# Official F07 metrics
# ------------------------------------------------------------

f07_metrics_df = pd.DataFrame({
    "Metric": list(test_tta_metrics.keys()),
    "Value": list(test_tta_metrics.values()),
})

f07_metrics_df.to_csv(
    TABLES_DIR / "F07_official_test_metrics.csv",
    index=False,
)

# ------------------------------------------------------------
# Classification report
# ------------------------------------------------------------

report = classification_report(
    test_targets,
    test_tta_preds,
    target_names=test_dataset.classes,
    output_dict=True,
    zero_division=0,
)

pd.DataFrame(report).transpose().to_csv(
    TABLES_DIR / "F07_classification_report.csv"
)

# ------------------------------------------------------------
# Confusion matrices
# ------------------------------------------------------------

cm = confusion_matrix(
    test_targets,
    test_tta_preds,
)

cm_norm = confusion_matrix(
    test_targets,
    test_tta_preds,
    normalize="true",
)

pd.DataFrame(
    cm,
    index=test_dataset.classes,
    columns=test_dataset.classes,
).to_csv(
    TABLES_DIR / "F07_confusion_matrix.csv"
)

pd.DataFrame(
    cm_norm,
    index=test_dataset.classes,
    columns=test_dataset.classes,
).to_csv(
    TABLES_DIR / "F07_confusion_matrix_normalized.csv"
)

plt.figure(figsize=(14, 12))
plt.imshow(cm)
plt.title("F07 Official Test Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("True")
plt.colorbar()
plt.tight_layout()
plt.savefig(
    FIGURES_DIR / "F07_confusion_matrix.png",
    dpi=200,
)
plt.close()

plt.figure(figsize=(14, 12))
plt.imshow(cm_norm)
plt.title("F07 Official Test Normalized Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("True")
plt.colorbar()
plt.tight_layout()
plt.savefig(
    FIGURES_DIR / "F07_confusion_matrix_normalized.png",
    dpi=200,
)
plt.close()

# ------------------------------------------------------------
# F06 vs F07 scientific comparison
# ------------------------------------------------------------

comparison_metrics = [
    "Top-1",
    "Top-2",
    "Top-3",
    "Top-5",
    "Macro Precision",
    "Macro Recall",
    "Macro F1",
    "Weighted F1",
]

scientific_comparison = pd.DataFrame({
    "Metric": comparison_metrics,
    "F06_Single_View": [
        test_single_metrics[m] for m in comparison_metrics
    ],
    "F07_TTA": [
        test_tta_metrics[m] for m in comparison_metrics
    ],
})

scientific_comparison["Delta_pp"] = (
    scientific_comparison["F07_TTA"]
    - scientific_comparison["F06_Single_View"]
)

scientific_comparison.to_csv(
    TABLES_DIR / "F07_scientific_comparison.csv",
    index=False,
)

# ------------------------------------------------------------
# Locked protocol
# ------------------------------------------------------------

protocol = {
    "experiment": "F07_CONVNEXT_SMALL_HR384_TTA",
    "scientific_role": "Test-time augmentation",
    "training": False,
    "source_experiment":
        "F06_CONVNEXT_SMALL_HR384_GENTLE_CB_FOCAL",
    "source_epoch": 2,
    "source_sha256": source_sha256,
    "resolution": [384, 384],
    "tta_views": [
        "original",
        "horizontal_flip",
    ],
    "aggregation":
        "arithmetic mean of per-view softmax probabilities",
    "checkpoint_selection":
        "locked F06 validation Macro F1 checkpoint",
    "test_used_for_selection": False,
}

(F07_DIR / "F07_locked_protocol.json").write_text(
    json.dumps(protocol, indent=2)
)

# ------------------------------------------------------------
# README
# ------------------------------------------------------------

readme = """AQUA20 F07 — OFFICIAL FINAL BEAT BASE CAMPAIGN

Experiment:
F07_CONVNEXT_SMALL_HR384_TTA

Scientific role:
Deterministic test-time augmentation on the locked F06 HR384 model.

Source:
F06_CONVNEXT_SMALL_HR384_GENTLE_CB_FOCAL
Best epoch: 2

TTA protocol:
1. Original 384 x 384 image
2. Horizontal-flipped 384 x 384 image
3. Softmax each view
4. Arithmetic mean of probabilities
5. Prediction from averaged probabilities

Validation:
Single-view Macro F1: 88.5122%
F07 TTA Macro F1:    88.9836%
Delta:                +0.4714 pp

Official test:
Top-1:           92.1216%
Top-2:           97.8908%
Top-3:           99.3176%
Top-5:           99.6898%
Macro Precision: 89.8765%
Macro Recall:    86.5324%
Macro F1:        87.4026%
Weighted F1:     92.0771%

Scientific conclusion:
The fixed two-view TTA protocol improved validation Macro F1 but did not
generalize to the unchanged official test split. Test Top-1 was unchanged,
while balanced-class metrics declined. F07 therefore does not replace F06
as the stronger completed branch.

Important loss note:
The F07 NLL reported during Step 4 is standard softmax negative
log-likelihood. It is not directly comparable with the previously reported
F06 Gentle Class-Balanced Focal test loss.

F07 is inference-only and produces no new checkpoint.
The verified F06 source checkpoint is recorded by SHA-256.
"""

(F07_DIR / "README_F07.txt").write_text(readme)

# ------------------------------------------------------------
# Create final ZIP
# ------------------------------------------------------------

ZIP_BASE = (
    PROJECT_ROOT
    / "aqua20_f07_convnext_small_hr384_tta_outputs"
)

ZIP_PATH = Path(
    shutil.make_archive(
        str(ZIP_BASE),
        "zip",
        root_dir=F07_DIR,
    )
)

print()
print("Final package :", ZIP_PATH)
print("ZIP size      :", f"{ZIP_PATH.stat().st_size / 1024**2:.2f} MB")

print()
print("PACKAGE CONTENTS")

for path in sorted(F07_DIR.rglob("*")):
    if path.is_file():
        print(path.relative_to(F07_DIR))

print()
print("=" * 80)
print("F07 STEP 5 PASSED — OFFICIAL FINAL PACKAGE CREATED")
print("=" * 80)
print("F07 STATUS : COMPLETED")
print("DOWNLOAD   :", ZIP_PATH)

================================================================================
F07 Step 5 — Create official final experiment package
================================================================================

Final package : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/aqua20_f07_convnext_small_hr384_tta_outputs.zip
ZIP size      : 0.10 MB

PACKAGE CONTENTS
F07_locked_protocol.json
F07_source_checkpoint_sha256.txt
README_F07.txt
figures/F07_confusion_matrix.png
figures/F07_confusion_matrix_normalized.png
tables/F07_classification_report.csv
tables/F07_confusion_matrix.csv
tables/F07_confusion_matrix_normalized.csv
tables/F07_official_test_metrics.csv
tables/F07_scientific_comparison.csv
tables/F07_test_predictions.csv
tables/F07_test_single_vs_tta.csv
tables/F07_validation_predictions.csv
tables/F07_validation_single_vs_tta.csv

================================================================================
F07 STEP 5 PASSED — OFFICIAL FINAL PACKAGE CREATED
================================================================================
F07 STATUS : COMPLETED
DOWNLOAD   : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/aqua20_f07_convnext_small_hr384_tta_outputs.zip

In [16]:
# ============================================================
# INSTALL LOCKED F01 ULTRALYTICS VERSION
# ============================================================

%pip install -q ultralytics==8.4.89

import ultralytics

print("Ultralytics:", ultralytics.__version__)
assert ultralytics.__version__ == "8.4.89"

print("✅ F01 Ultralytics environment restored")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.8/41.8 kB 583.8 kB/s eta 0:00:00 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 6.7 MB/s eta 0:00:00a 0:00:01
Note: you may need to restart the kernel to use updated packages.
Creating new Ultralytics Settings v0.0.6 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.
Ultralytics: 8.4.89
✅ F01 Ultralytics environment restored

# F08 Step 1 — Lock Ensemble Sources and Validation-Only Protocol

## Official campaign

`04-07-2026 AQUA20 FINAL BEAT BASE PLAN`

## Experiment

`F08_CONVNEXT_SMALL_HR384_YOLO26M_PROB_ENSEMBLE`

## Scientific role

F08 is an inference-only, validation-governed probability-level ensemble experiment.

The experiment tests whether complementary class-probability distributions from the strongest completed ConvNeXt branch and the primary completed YOLO26m branch improve balanced-class generalization.

## Locked source models

### ConvNeXt source

`F06_CONVNEXT_SMALL_HR384_GENTLE_CB_FOCAL`

Checkpoint selected previously by validation Macro F1.

### YOLO source

`F01_YOLO26M_CLS_AUG200`

F01 is the primary completed YOLO26m branch.

F02 was the controlled YOLO26s architecture-size comparison and is not the F08 ensemble source.

The F01 source decision is locked before F08 validation ensemble evaluation and is not based on F08 official-test predictions.

## Locked ensemble protocol

Probability-level arithmetic weighted mean.

Predefined ConvNeXt : YOLO weight grid:

- 0.50 : 0.50
- 0.60 : 0.40
- 0.70 : 0.30
- 0.80 : 0.20

Selection metric:

`Validation Macro F1`

Tie-break order:

1. Higher validation Macro F1
2. Higher validation Macro Recall
3. Higher validation Top-1
4. Prefer simpler/equal weighting if still tied

No additional weights may be added after validation results are observed.

The official test split must remain untouched until one final ensemble weight is locked.

In [14]:
# ============================================================
# F08 STEP 1 — RESTORE SOURCES, VERIFY HASHES, LOCK PROTOCOL
# ============================================================

from pathlib import Path
import hashlib
import json
import shutil
import zipfile

CAMPAIGN_ROOT = Path(
    "/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026"
)

F08_DIR = (
    CAMPAIGN_ROOT
    / "experiments"
    / "F08_CONVNEXT_SMALL_HR384_YOLO26M_PROB_ENSEMBLE"
)

SOURCE_DIR = F08_DIR / "sources"
SOURCE_DIR.mkdir(parents=True, exist_ok=True)

EXPECTED = {
    "F06": {
        "experiment": "F06_CONVNEXT_SMALL_HR384_GENTLE_CB_FOCAL",
        "sha256": "d0c225c28b25f09822bc99518a37f9b1fe642b2d01213da7f68e2d76a255832a",
        "filename": "best_model.pth",
    },
    "F01": {
        "experiment": "F01_YOLO26M_CLS_AUG200",
        "sha256": "aa489def1443a6cdab42a0a20a530b9e341d574dcaaf234bfe6c7983113e8e5a",
        "filename": "best.pt",
    },
}


def sha256_file(path):
    digest = hashlib.sha256()

    with open(path, "rb") as file:
        for chunk in iter(lambda: file.read(1024 * 1024), b""):
            digest.update(chunk)

    return digest.hexdigest()


print("=" * 80)
print("F08 Step 1 — Restore and verify locked source checkpoints")
print("=" * 80)

checkpoint_names = {"best_model.pth", "best.pt"}

candidate_files = [
    path
    for path in Path("/kaggle/input").rglob("*")
    if path.is_file() and path.name in checkpoint_names
]

zip_files = list(
    Path("/kaggle/input").rglob("*.zip")
)

restored = {}

for source_name, source_info in EXPECTED.items():

    expected_hash = source_info["sha256"]
    destination = (
        SOURCE_DIR
        / source_name
        / source_info["filename"]
    )

    destination.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    found = False

    for path in candidate_files:

        if sha256_file(path) == expected_hash:

            shutil.copy2(
                path,
                destination,
            )

            found = True
            break

    if not found:

        for zip_path in zip_files:

            with zipfile.ZipFile(
                zip_path,
                "r",
            ) as archive:

                for member in archive.namelist():

                    if Path(member).name not in checkpoint_names:
                        continue

                    checkpoint_bytes = archive.read(
                        member
                    )

                    member_hash = hashlib.sha256(
                        checkpoint_bytes
                    ).hexdigest()

                    if member_hash == expected_hash:

                        destination.write_bytes(
                            checkpoint_bytes
                        )

                        found = True
                        break

            if found:
                break

    assert found, (
        f"{source_name} checkpoint not found in /kaggle/input"
    )

    verified_hash = sha256_file(
        destination
    )

    assert verified_hash == expected_hash

    restored[source_name] = str(
        destination
    )

    print()
    print(source_name)
    print("Experiment :", source_info["experiment"])
    print("Checkpoint :", destination)
    print("SHA-256    :", verified_hash)
    print("Verification: PASSED")


F08_LOCK = {
    "experiment": (
        "F08_CONVNEXT_SMALL_HR384_YOLO26M_PROB_ENSEMBLE"
    ),
    "campaign": (
        "04-07-2026 AQUA20 FINAL BEAT BASE PLAN"
    ),
    "mode": "inference_only",
    "ensemble_method": (
        "weighted_arithmetic_mean_of_softmax_probabilities"
    ),
    "sources": {
        "convnext": EXPECTED["F06"],
        "yolo": EXPECTED["F01"],
    },
    "weight_grid": [
        {"convnext": 0.50, "yolo": 0.50},
        {"convnext": 0.60, "yolo": 0.40},
        {"convnext": 0.70, "yolo": 0.30},
        {"convnext": 0.80, "yolo": 0.20},
    ],
    "selection_metric": "validation_macro_f1",
    "tie_break": [
        "validation_macro_f1",
        "validation_macro_recall",
        "validation_top1",
        "prefer_equal_weighting",
    ],
    "class_order_verification": "required_before_validation",
    "official_test_weight_selection": "forbidden",
    "final_weight_status": "not_selected",
}

LOCK_FILE = F08_DIR / "F08_experiment_lock.json"

with open(
    LOCK_FILE,
    "w",
    encoding="utf-8",
) as file:

    json.dump(
        F08_LOCK,
        file,
        indent=2,
    )


print()
print("=" * 80)
print("F08 PROTOCOL LOCK")
print("=" * 80)

print("Experiment       :", F08_LOCK["experiment"])
print("Mode             :", F08_LOCK["mode"])
print("ConvNeXt source  :", EXPECTED["F06"]["experiment"])
print("YOLO source      :", EXPECTED["F01"]["experiment"])
print("Ensemble method  :", F08_LOCK["ensemble_method"])
print("Selection metric :", F08_LOCK["selection_metric"])

print("\nLOCKED WEIGHT GRID")

for weights in F08_LOCK["weight_grid"]:
    print(
        f"ConvNeXt {weights['convnext']:.2f}"
        f" : YOLO {weights['yolo']:.2f}"
    )

print("\nTIE-BREAK ORDER")

for index, rule in enumerate(
    F08_LOCK["tie_break"],
    start=1,
):
    print(f"{index}. {rule}")

print("\nLock file        :", LOCK_FILE)

print()
print("=" * 80)
print("F08 STEP 1 PASSED — SOURCES AND PROTOCOL LOCKED")
print("=" * 80)

print("Official test    : NOT EVALUATED")
print("Final weight     : NOT SELECTED")
print("Next             : F08 STEP 2")

================================================================================
F08 Step 1 — Restore and verify locked source checkpoints
================================================================================

F06
Experiment : F06_CONVNEXT_SMALL_HR384_GENTLE_CB_FOCAL
Checkpoint : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/experiments/F08_CONVNEXT_SMALL_HR384_YOLO26M_PROB_ENSEMBLE/sources/F06/best_model.pth
SHA-256    : d0c225c28b25f09822bc99518a37f9b1fe642b2d01213da7f68e2d76a255832a
Verification: PASSED

F01
Experiment : F01_YOLO26M_CLS_AUG200
Checkpoint : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/experiments/F08_CONVNEXT_SMALL_HR384_YOLO26M_PROB_ENSEMBLE/sources/F01/best.pt
SHA-256    : aa489def1443a6cdab42a0a20a530b9e341d574dcaaf234bfe6c7983113e8e5a
Verification: PASSED

================================================================================
F08 PROTOCOL LOCK
================================================================================
Experiment       : F08_CONVNEXT_SMALL_HR384_YOLO26M_PROB_ENSEMBLE
Mode             : inference_only
ConvNeXt source  : F06_CONVNEXT_SMALL_HR384_GENTLE_CB_FOCAL
YOLO source      : F01_YOLO26M_CLS_AUG200
Ensemble method  : weighted_arithmetic_mean_of_softmax_probabilities
Selection metric : validation_macro_f1

LOCKED WEIGHT GRID
ConvNeXt 0.50 : YOLO 0.50
ConvNeXt 0.60 : YOLO 0.40
ConvNeXt 0.70 : YOLO 0.30
ConvNeXt 0.80 : YOLO 0.20

TIE-BREAK ORDER
1. validation_macro_f1
2. validation_macro_recall
3. validation_top1
4. prefer_equal_weighting

Lock file        : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/experiments/F08_CONVNEXT_SMALL_HR384_YOLO26M_PROB_ENSEMBLE/F08_experiment_lock.json

================================================================================
F08 STEP 1 PASSED — SOURCES AND PROTOCOL LOCKED
================================================================================
Official test    : NOT EVALUATED
Final weight     : NOT SELECTED
Next             : F08 STEP 2

# F08 Step 2 — Restore Models and Verify Class/Probability Compatibility

## Objective

Restore the two locked F08 source models:

- F06 ConvNeXt-Small HR384
- F01 YOLO26m-cls

Before full validation inference, verify:

1. Official validation split is unchanged.
2. Validation contains 1,312 images.
3. Both models use 20 AQUA20 classes.
4. ConvNeXt checkpoint class order matches the official ImageFolder order.
5. YOLO checkpoint class order matches the same official order.
6. F06 uses deterministic 384 × 384 evaluation preprocessing.
7. F01 uses the locked 224-pixel Ultralytics classification inference configuration.
8. Both models produce a 20-class probability vector.
9. Probability vectors are valid for probability-level ensembling.

Only a single validation image is used for the dry run.

No full validation ensemble evaluation is performed.

The official test split remains untouched.

In [17]:
# ============================================================
# F08 STEP 2 — RESTORE MODELS AND VERIFY COMPATIBILITY
# ============================================================

from pathlib import Path
import json

import torch
import torch.nn as nn
from torchvision import transforms
from torchvision.datasets import ImageFolder
from torchvision.models import convnext_small
from ultralytics import YOLO

PROJECT_ROOT = Path(
    "/kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026"
)

F08_DIR = (
    PROJECT_ROOT
    / "experiments"
    / "F08_CONVNEXT_SMALL_HR384_YOLO26M_PROB_ENSEMBLE"
)

F06_CKPT = F08_DIR / "sources/F06/best_model.pth"
F01_CKPT = F08_DIR / "sources/F01/best.pt"

EXPECTED_CLASSES = [
    "00_coral",
    "01_crab",
    "02_diver",
    "03_eel",
    "04_fish",
    "05_fishInGroups",
    "06_flatworm",
    "07_jellyfish",
    "08_marine_dolphin",
    "09_octopus",
    "10_rayfish",
    "11_seaAnemone",
    "12_seaCucumber",
    "13_seaSlug",
    "14_seaUrchin",
    "15_shark",
    "16_shrimp",
    "17_squid",
    "18_starfish",
    "19_turtle",
]

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

# ------------------------------------------------------------
# Find unchanged official validation split
# ------------------------------------------------------------

val_candidates = [
    PROJECT_ROOT / "official_imagefolder" / "val"
]

val_candidates += list(
    Path("/kaggle/input").rglob("official_imagefolder/val")
)

VAL_DIR = None

for path in val_candidates:
    if not path.exists():
        continue

    dataset = ImageFolder(path)

    if (
        len(dataset) == 1312
        and dataset.classes == EXPECTED_CLASSES
    ):
        VAL_DIR = path
        break

assert VAL_DIR is not None, (
    "Official unchanged validation split was not found."
)

# ------------------------------------------------------------
# F06 ConvNeXt
# ------------------------------------------------------------

f06_checkpoint = torch.load(
    F06_CKPT,
    map_location="cpu",
    weights_only=False,
)

f06_classes = f06_checkpoint["class_names"]

assert f06_classes == EXPECTED_CLASSES

f06_model = convnext_small(weights=None)

in_features = f06_model.classifier[2].in_features

f06_model.classifier[2] = nn.Linear(
    in_features,
    len(EXPECTED_CLASSES),
)

f06_model.load_state_dict(
    f06_checkpoint["model_state_dict"]
)

f06_model = f06_model.to(device)
f06_model.eval()

f06_transform = transforms.Compose([
    transforms.Resize((384, 384)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225],
    ),
])

val_dataset = ImageFolder(
    VAL_DIR,
    transform=f06_transform,
)

# ------------------------------------------------------------
# F01 YOLO26m-cls
# ------------------------------------------------------------

f01_model = YOLO(str(F01_CKPT))

f01_classes = [
    f01_model.names[index]
    for index in range(len(f01_model.names))
]

assert f01_classes == EXPECTED_CLASSES

# ------------------------------------------------------------
# One-image dry run
# ------------------------------------------------------------

sample_path, sample_target = val_dataset.samples[0]

image_tensor, _ = val_dataset[0]

with torch.inference_mode():
    f06_logits = f06_model(
        image_tensor.unsqueeze(0).to(device)
    )

    f06_probs = torch.softmax(
        f06_logits,
        dim=1,
    )[0].cpu()

f01_result = f01_model.predict(
    source=str(sample_path),
    imgsz=224,
    device=0 if torch.cuda.is_available() else "cpu",
    verbose=False,
)[0]

f01_probs = (
    f01_result.probs.data
    .detach()
    .float()
    .cpu()
)

assert f06_probs.shape == torch.Size([20])
assert f01_probs.shape == torch.Size([20])

assert torch.isclose(
    f06_probs.sum(),
    torch.tensor(1.0),
    atol=1e-5,
)

assert torch.isclose(
    f01_probs.sum(),
    torch.tensor(1.0),
    atol=1e-5,
)

# ------------------------------------------------------------
# Save verification record
# ------------------------------------------------------------

verification = {
    "validation_path": str(VAL_DIR),
    "validation_images": len(val_dataset),
    "classes": len(EXPECTED_CLASSES),
    "class_names": EXPECTED_CLASSES,
    "class_order_match": True,
    "f06_input_size": 384,
    "f01_input_size": 224,
    "f06_probability_shape": list(f06_probs.shape),
    "f01_probability_shape": list(f01_probs.shape),
    "f06_probability_sum": float(f06_probs.sum()),
    "f01_probability_sum": float(f01_probs.sum()),
    "official_test_evaluated": False,
}

VERIFY_FILE = (
    F08_DIR
    / "F08_step2_compatibility_verification.json"
)

with open(
    VERIFY_FILE,
    "w",
    encoding="utf-8",
) as file:
    json.dump(
        verification,
        file,
        indent=2,
    )

print("=" * 80)
print("F08 Step 2 — Model and probability compatibility verification")
print("=" * 80)

print("Device              :", device)
print("Validation path     :", VAL_DIR)
print("Validation images   :", len(val_dataset))
print("Classes             :", len(EXPECTED_CLASSES))
print("Class order         : VERIFIED IDENTICAL")

print()
print("F06 model           : ConvNeXt-Small")
print("F06 input           : 384 x 384")
print("F06 probability     :", tuple(f06_probs.shape))
print("F06 probability sum :", f"{f06_probs.sum().item():.8f}")

print()
print("F01 model           : YOLO26m-cls")
print("F01 input           : imgsz=224")
print("F01 probability     :", tuple(f01_probs.shape))
print("F01 probability sum :", f"{f01_probs.sum().item():.8f}")

print()
print("Dry-run image       :", sample_path)
print("True class          :", EXPECTED_CLASSES[sample_target])
print("F06 predicted class :", EXPECTED_CLASSES[int(f06_probs.argmax())])
print("F01 predicted class :", EXPECTED_CLASSES[int(f01_probs.argmax())])

print()
print("Verification file   :", VERIFY_FILE)

print()
print("=" * 80)
print("F08 STEP 2 PASSED — MODELS ARE ENSEMBLE-COMPATIBLE")
print("=" * 80)

print("Full validation     : NOT EVALUATED")
print("Official test       : NOT EVALUATED")
print("Final weight        : NOT SELECTED")
print("Next                : F08 STEP 3")

================================================================================
F08 Step 2 — Model and probability compatibility verification
================================================================================
Device              : cuda
Validation path     : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/official_imagefolder/val
Validation images   : 1312
Classes             : 20
Class order         : VERIFIED IDENTICAL

F06 model           : ConvNeXt-Small
F06 input           : 384 x 384
F06 probability     : (20,)
F06 probability sum : 1.00000000

F01 model           : YOLO26m-cls
F01 input           : imgsz=224
F01 probability     : (20,)
F01 probability sum : 1.00000000

Dry-run image       : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/official_imagefolder/val/00_coral/hf_train_000001.jpg
True class          : 00_coral
F06 predicted class : 00_coral
F01 predicted class : 00_coral

Verification file   : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/experiments/F08_CONVNEXT_SMALL_HR384_YOLO26M_PROB_ENSEMBLE/F08_step2_compatibility_verification.json

================================================================================
F08 STEP 2 PASSED — MODELS ARE ENSEMBLE-COMPATIBLE
================================================================================
Full validation     : NOT EVALUATED
Official test       : NOT EVALUATED
Final weight        : NOT SELECTED
Next                : F08 STEP 3

# F08 Step 3 — Validation Probability Ensemble and Final Weight Lock

## Objective

Generate full unchanged-validation probabilities for:

- F06 ConvNeXt-Small HR384
- F01 YOLO26m-cls

Save the raw validation probabilities.

Evaluate only the pre-locked ConvNeXt : YOLO weight grid:

- 0.50 : 0.50
- 0.60 : 0.40
- 0.70 : 0.30
- 0.80 : 0.20

Select the final F08 ensemble weight using:

`Validation Macro F1`

Locked tie-break order:

1. Higher validation Macro F1
2. Higher validation Macro Recall
3. Higher validation Top-1
4. Prefer equal weighting if still tied

No additional ensemble weights may be evaluated.

After validation selection, one final F08 ensemble rule is locked.

The official test split remains untouched.

In [18]:
# ============================================================
# F08 STEP 3 — VALIDATION ENSEMBLE AND FINAL WEIGHT LOCK
# FINAL FIXED CELL
# ============================================================

from pathlib import Path
import json
import os

import numpy as np
import pandas as pd
import torch

from sklearn.metrics import (
    f1_score,
    precision_score,
    recall_score,
)

from torch.utils.data import DataLoader


print("=" * 80)
print("F08 Step 3 — Validation probability ensemble")
print("=" * 80)


# ------------------------------------------------------------
# Load locked protocol
# ------------------------------------------------------------

LOCK_FILE = F08_DIR / "F08_experiment_lock.json"

with open(
    LOCK_FILE,
    "r",
    encoding="utf-8",
) as file:
    f08_lock = json.load(file)


weight_grid = f08_lock["weight_grid"]


assert weight_grid == [
    {"convnext": 0.50, "yolo": 0.50},
    {"convnext": 0.60, "yolo": 0.40},
    {"convnext": 0.70, "yolo": 0.30},
    {"convnext": 0.80, "yolo": 0.20},
]


assert f08_lock["final_weight_status"] == "not_selected"


print("Locked weight grid : VERIFIED")
print("Final weight status:", f08_lock["final_weight_status"])


# ------------------------------------------------------------
# Validation data
# ------------------------------------------------------------

val_loader = DataLoader(
    val_dataset,
    batch_size=16,
    shuffle=False,
    num_workers=2,
    pin_memory=True,
)


val_paths = [
    path
    for path, _ in val_dataset.samples
]


assert len(val_paths) == 1312


validation_filenames = [
    Path(path).name
    for path in val_paths
]


assert len(set(validation_filenames)) == 1312


print("Validation images   :", len(val_paths))
print("Unique filenames    : VERIFIED")


# ------------------------------------------------------------
# F06 validation probabilities
# ------------------------------------------------------------

f06_batches = []

validation_targets = []


with torch.inference_mode():

    for images, targets in val_loader:

        images = images.to(
            device,
            non_blocking=True,
        )

        with torch.amp.autocast(
            device_type=device.type,
            enabled=(device.type == "cuda"),
        ):

            logits = f06_model(images)


        probabilities = torch.softmax(
            logits.float(),
            dim=1,
        )


        f06_batches.append(
            probabilities.cpu().numpy()
        )


        validation_targets.extend(
            targets.numpy().tolist()
        )


f06_val_probs = np.concatenate(
    f06_batches,
    axis=0,
)


validation_targets = np.asarray(
    validation_targets,
    dtype=np.int64,
)


assert f06_val_probs.shape == (1312, 20)

assert validation_targets.shape == (1312,)


print()
print("F06 validation probabilities:", f06_val_probs.shape)


# ------------------------------------------------------------
# Create flat YOLO validation source
# ------------------------------------------------------------

FLAT_VAL_DIR = (
    F08_DIR
    / "f01_validation_flat_source"
)


FLAT_VAL_DIR.mkdir(
    parents=True,
    exist_ok=True,
)


for existing_file in FLAT_VAL_DIR.iterdir():

    if existing_file.is_file() or existing_file.is_symlink():
        existing_file.unlink()


for source_path in val_paths:

    source_path = Path(source_path)

    destination = (
        FLAT_VAL_DIR
        / source_path.name
    )

    os.symlink(
        source_path,
        destination,
    )


flat_files = [
    path
    for path in FLAT_VAL_DIR.iterdir()
    if path.is_file()
]


assert len(flat_files) == 1312


print()
print("F01 flat source     :", FLAT_VAL_DIR)
print("F01 source images   :", len(flat_files))
print("F01 source creation : VERIFIED")


# ------------------------------------------------------------
# F01 validation probabilities
# ------------------------------------------------------------

f01_prob_by_filename = {}


f01_results = f01_model.predict(
    source=str(FLAT_VAL_DIR),
    imgsz=224,
    batch=64,
    device=0 if torch.cuda.is_available() else "cpu",
    stream=True,
    verbose=False,
)


for result in f01_results:

    filename = Path(result.path).name

    assert filename not in f01_prob_by_filename

    f01_prob_by_filename[filename] = (
        result.probs.data
        .detach()
        .float()
        .cpu()
        .numpy()
    )


expected_filenames = set(
    validation_filenames
)


received_filenames = set(
    f01_prob_by_filename
)


missing_filenames = (
    expected_filenames
    - received_filenames
)


extra_filenames = (
    received_filenames
    - expected_filenames
)


print()
print("F01 images received :", len(f01_prob_by_filename))
print("Missing filenames   :", len(missing_filenames))
print("Extra filenames     :", len(extra_filenames))


assert len(f01_prob_by_filename) == 1312

assert not missing_filenames

assert not extra_filenames


f01_val_probs = np.stack(
    [
        f01_prob_by_filename[
            Path(path).name
        ]
        for path in val_paths
    ],
    axis=0,
)


assert f01_val_probs.shape == (1312, 20)


print("F01 image set       : VERIFIED")
print("F01 order alignment : ALIGNED BY UNIQUE FILENAME")
print("F01 probability     :", f01_val_probs.shape)


# ------------------------------------------------------------
# Probability validity
# ------------------------------------------------------------

assert np.allclose(
    f06_val_probs.sum(axis=1),
    1.0,
    atol=1e-5,
)


assert np.allclose(
    f01_val_probs.sum(axis=1),
    1.0,
    atol=1e-5,
)


print()
print("F06 probability sums: VERIFIED")
print("F01 probability sums: VERIFIED")


# ------------------------------------------------------------
# Metric function
# ------------------------------------------------------------

def calculate_metrics(probabilities):

    predictions = probabilities.argmax(
        axis=1
    )


    return {

        "top1": float(
            np.mean(
                predictions
                == validation_targets
            )
        ),

        "macro_precision": float(
            precision_score(
                validation_targets,
                predictions,
                average="macro",
                zero_division=0,
            )
        ),

        "macro_recall": float(
            recall_score(
                validation_targets,
                predictions,
                average="macro",
                zero_division=0,
            )
        ),

        "macro_f1": float(
            f1_score(
                validation_targets,
                predictions,
                average="macro",
                zero_division=0,
            )
        ),

        "weighted_f1": float(
            f1_score(
                validation_targets,
                predictions,
                average="weighted",
                zero_division=0,
            )
        ),
    }


# ------------------------------------------------------------
# Source validation metrics
# ------------------------------------------------------------

f06_metrics = calculate_metrics(
    f06_val_probs
)


f01_metrics = calculate_metrics(
    f01_val_probs
)


# ------------------------------------------------------------
# Evaluate locked weight grid
# ------------------------------------------------------------

ensemble_rows = []


for weights in weight_grid:

    convnext_weight = weights["convnext"]

    yolo_weight = weights["yolo"]


    ensemble_probs = (
        convnext_weight * f06_val_probs
        + yolo_weight * f01_val_probs
    )


    metrics = calculate_metrics(
        ensemble_probs
    )


    ensemble_rows.append({

        "convnext_weight": convnext_weight,

        "yolo_weight": yolo_weight,

        **metrics,
    })


# ------------------------------------------------------------
# Validation-only selection
# ------------------------------------------------------------

selected = max(
    ensemble_rows,

    key=lambda row: (

        row["macro_f1"],

        row["macro_recall"],

        row["top1"],

        int(
            row["convnext_weight"] == 0.50
            and row["yolo_weight"] == 0.50
        ),
    ),
)


# ------------------------------------------------------------
# Save raw validation probabilities
# ------------------------------------------------------------

PROBABILITY_FILE = (
    F08_DIR
    / "F08_validation_probabilities.npz"
)


np.savez_compressed(

    PROBABILITY_FILE,

    image_paths=np.asarray(
        val_paths,
        dtype=str,
    ),

    targets=validation_targets,

    f06_probabilities=f06_val_probs,

    f01_probabilities=f01_val_probs,

    class_names=np.asarray(
        EXPECTED_CLASSES,
        dtype=str,
    ),
)


# ------------------------------------------------------------
# Save validation comparison
# ------------------------------------------------------------

VALIDATION_TABLE = (
    F08_DIR
    / "F08_validation_weight_comparison.csv"
)


pd.DataFrame(
    ensemble_rows
).to_csv(
    VALIDATION_TABLE,
    index=False,
)


# ------------------------------------------------------------
# Lock final selected ensemble rule
# ------------------------------------------------------------

f08_lock["final_weight_status"] = (
    "selected_by_validation"
)


f08_lock["selected_weight"] = {

    "convnext": selected[
        "convnext_weight"
    ],

    "yolo": selected[
        "yolo_weight"
    ],
}


f08_lock["selected_validation_metrics"] = {

    key: selected[key]

    for key in [

        "top1",

        "macro_precision",

        "macro_recall",

        "macro_f1",

        "weighted_f1",
    ]
}


f08_lock["official_test_evaluated"] = False


with open(
    LOCK_FILE,
    "w",
    encoding="utf-8",
) as file:

    json.dump(
        f08_lock,
        file,
        indent=2,
    )


# ------------------------------------------------------------
# Print source results
# ------------------------------------------------------------

print()
print("=" * 80)
print("SOURCE MODEL VALIDATION")
print("=" * 80)


print(
    f"{'Model':<15}"
    f"{'Top-1':>12}"
    f"{'Macro Recall':>18}"
    f"{'Macro F1':>15}"
)


print(
    f"{'F06':<15}"
    f"{f06_metrics['top1'] * 100:>11.4f}%"
    f"{f06_metrics['macro_recall'] * 100:>17.4f}%"
    f"{f06_metrics['macro_f1'] * 100:>14.4f}%"
)


print(
    f"{'F01':<15}"
    f"{f01_metrics['top1'] * 100:>11.4f}%"
    f"{f01_metrics['macro_recall'] * 100:>17.4f}%"
    f"{f01_metrics['macro_f1'] * 100:>14.4f}%"
)


# ------------------------------------------------------------
# Print ensemble grid
# ------------------------------------------------------------

print()
print("=" * 80)
print("LOCKED ENSEMBLE WEIGHT GRID")
print("=" * 80)


print(
    f"{'ConvNeXt':>10}"
    f"{'YOLO':>10}"
    f"{'Top-1':>12}"
    f"{'Macro Recall':>18}"
    f"{'Macro F1':>15}"
)


for row in ensemble_rows:

    print(
        f"{row['convnext_weight']:>10.2f}"
        f"{row['yolo_weight']:>10.2f}"
        f"{row['top1'] * 100:>11.4f}%"
        f"{row['macro_recall'] * 100:>17.4f}%"
        f"{row['macro_f1'] * 100:>14.4f}%"
    )


# ------------------------------------------------------------
# Print final selected rule
# ------------------------------------------------------------

print()
print("=" * 80)
print("SELECTED F08 ENSEMBLE RULE")
print("=" * 80)


print(
    "ConvNeXt weight :",
    f"{selected['convnext_weight']:.2f}",
)


print(
    "YOLO weight     :",
    f"{selected['yolo_weight']:.2f}",
)


print(
    "Val Top-1       :",
    f"{selected['top1'] * 100:.4f}%",
)


print(
    "Val Macro Recall:",
    f"{selected['macro_recall'] * 100:.4f}%",
)


print(
    "Val Macro F1    :",
    f"{selected['macro_f1'] * 100:.4f}%",
)


print()
print("Probability file:", PROBABILITY_FILE)

print("Comparison table:", VALIDATION_TABLE)

print("Lock file       :", LOCK_FILE)


print()
print("=" * 80)
print("F08 STEP 3 PASSED — FINAL ENSEMBLE WEIGHT LOCKED")
print("=" * 80)


print("Official test   : NOT EVALUATED")

print("Weight search   : CLOSED")

print("Next            : F08 STEP 4")

================================================================================
F08 Step 3 — Validation probability ensemble
================================================================================
Locked weight grid : VERIFIED
Final weight status: not_selected
Validation images   : 1312
Unique filenames    : VERIFIED

F06 validation probabilities: (1312, 20)

F01 flat source     : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/experiments/F08_CONVNEXT_SMALL_HR384_YOLO26M_PROB_ENSEMBLE/f01_validation_flat_source
F01 source images   : 1312
F01 source creation : VERIFIED

F01 images received : 1312
Missing filenames   : 0
Extra filenames     : 0
F01 image set       : VERIFIED
F01 order alignment : ALIGNED BY UNIQUE FILENAME
F01 probability     : (1312, 20)

F06 probability sums: VERIFIED
F01 probability sums: VERIFIED

================================================================================
SOURCE MODEL VALIDATION
================================================================================
Model                 Top-1      Macro Recall       Macro F1
F06                92.9878%          90.6790%       88.5122%
F01                87.8811%          78.2028%       79.0581%

================================================================================
LOCKED ENSEMBLE WEIGHT GRID
================================================================================
  ConvNeXt      YOLO       Top-1      Macro Recall       Macro F1
      0.50      0.50    93.1402%          90.8628%       89.8842%
      0.60      0.40    93.3689%          92.1709%       90.2689%
      0.70      0.30    93.4451%          93.0674%       90.7359%
      0.80      0.20    93.0640%          91.2224%       88.7436%

================================================================================
SELECTED F08 ENSEMBLE RULE
================================================================================
ConvNeXt weight : 0.70
YOLO weight     : 0.30
Val Top-1       : 93.4451%
Val Macro Recall: 93.0674%
Val Macro F1    : 90.7359%

Probability file: /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/experiments/F08_CONVNEXT_SMALL_HR384_YOLO26M_PROB_ENSEMBLE/F08_validation_probabilities.npz
Comparison table: /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/experiments/F08_CONVNEXT_SMALL_HR384_YOLO26M_PROB_ENSEMBLE/F08_validation_weight_comparison.csv
Lock file       : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/experiments/F08_CONVNEXT_SMALL_HR384_YOLO26M_PROB_ENSEMBLE/F08_experiment_lock.json

================================================================================
F08 STEP 3 PASSED — FINAL ENSEMBLE WEIGHT LOCKED
================================================================================
Official test   : NOT EVALUATED
Weight search   : CLOSED
Next            : F08 STEP 4

# F08 Step 4 — Official Unchanged Test Evaluation

## Objective

Evaluate the locked F08 probability-level ensemble on the official unchanged AQUA20 test split.

## Frozen ensemble rule

- F06 ConvNeXt-Small HR384 probability weight: `0.70`
- F01 YOLO26m-cls probability weight: `0.30`

The ensemble weight was selected exclusively using validation Macro F1 in F08 Step 3.

No test-driven weight search is permitted.

## Official test evaluation

Calculate:

- Top-1
- Top-2
- Top-3
- Top-5
- Macro Precision
- Macro Recall
- Macro F1
- Weighted F1

Also evaluate the two source models using the same aligned test-image order for scientific comparison.

Save:

- Raw test probabilities
- Test predictions
- Test metrics comparison

The locked ensemble rule must not be changed after this evaluation.

In [19]:
# ============================================================
# F08 STEP 4 — OFFICIAL UNCHANGED TEST EVALUATION
# ============================================================

from pathlib import Path
import json
import os

import numpy as np
import pandas as pd
import torch

from sklearn.metrics import (
    f1_score,
    precision_score,
    recall_score,
)

from torch.utils.data import DataLoader
from torchvision.datasets import ImageFolder


print("=" * 80)
print("F08 Step 4 — Official unchanged test evaluation")
print("=" * 80)


# ------------------------------------------------------------
# Load frozen F08 rule
# ------------------------------------------------------------

LOCK_FILE = F08_DIR / "F08_experiment_lock.json"

with open(
    LOCK_FILE,
    "r",
    encoding="utf-8",
) as file:
    f08_lock = json.load(file)


assert (
    f08_lock["final_weight_status"]
    == "selected_by_validation"
)

assert (
    f08_lock.get("official_test_evaluated", False)
    is False
)


CONVNEXT_WEIGHT = float(
    f08_lock["selected_weight"]["convnext"]
)

YOLO_WEIGHT = float(
    f08_lock["selected_weight"]["yolo"]
)


assert {
    "convnext": CONVNEXT_WEIGHT,
    "yolo": YOLO_WEIGHT,
} in f08_lock["weight_grid"]


print("Frozen ConvNeXt weight :", f"{CONVNEXT_WEIGHT:.2f}")
print("Frozen YOLO weight     :", f"{YOLO_WEIGHT:.2f}")
print("Weight source          : VALIDATION ONLY")
print("Weight search          : CLOSED")


# ------------------------------------------------------------
# Find official unchanged test split
# ------------------------------------------------------------

test_candidates = [
    PROJECT_ROOT / "official_imagefolder" / "test"
]

test_candidates += list(
    Path("/kaggle/input").rglob(
        "official_imagefolder/test"
    )
)


TEST_DIR = None


for path in test_candidates:

    if not path.exists():
        continue

    candidate_dataset = ImageFolder(path)

    if (
        len(candidate_dataset) == 1612
        and candidate_dataset.classes == EXPECTED_CLASSES
    ):
        TEST_DIR = path
        break


assert TEST_DIR is not None, (
    "Official unchanged test split was not found."
)


test_dataset = ImageFolder(
    TEST_DIR,
    transform=f06_transform,
)


test_loader = DataLoader(
    test_dataset,
    batch_size=16,
    shuffle=False,
    num_workers=2,
    pin_memory=True,
)


test_paths = [
    path
    for path, _ in test_dataset.samples
]


test_filenames = [
    Path(path).name
    for path in test_paths
]


assert len(test_dataset) == 1612
assert len(set(test_filenames)) == 1612


print()
print("Test path              :", TEST_DIR)
print("Test images            :", len(test_dataset))
print("Classes                :", len(EXPECTED_CLASSES))
print("Class order            : VERIFIED")
print("Unique filenames       : VERIFIED")


# ------------------------------------------------------------
# F06 test probabilities
# ------------------------------------------------------------

f06_test_batches = []

test_targets = []


with torch.inference_mode():

    for images, targets in test_loader:

        images = images.to(
            device,
            non_blocking=True,
        )

        with torch.amp.autocast(
            device_type=device.type,
            enabled=(device.type == "cuda"),
        ):

            logits = f06_model(images)


        probabilities = torch.softmax(
            logits.float(),
            dim=1,
        )


        f06_test_batches.append(
            probabilities.cpu().numpy()
        )


        test_targets.extend(
            targets.numpy().tolist()
        )


f06_test_probs = np.concatenate(
    f06_test_batches,
    axis=0,
)


test_targets = np.asarray(
    test_targets,
    dtype=np.int64,
)


assert f06_test_probs.shape == (1612, 20)
assert test_targets.shape == (1612,)


print()
print(
    "F06 test probabilities:",
    f06_test_probs.shape,
)


# ------------------------------------------------------------
# Create flat F01 official-test source
# ------------------------------------------------------------

FLAT_TEST_DIR = (
    F08_DIR
    / "f01_test_flat_source"
)


FLAT_TEST_DIR.mkdir(
    parents=True,
    exist_ok=True,
)


for existing_file in FLAT_TEST_DIR.iterdir():

    if (
        existing_file.is_file()
        or existing_file.is_symlink()
    ):
        existing_file.unlink()


for source_path in test_paths:

    source_path = Path(source_path)

    destination = (
        FLAT_TEST_DIR
        / source_path.name
    )

    os.symlink(
        source_path,
        destination,
    )


flat_test_files = [
    path
    for path in FLAT_TEST_DIR.iterdir()
    if path.is_file()
]


assert len(flat_test_files) == 1612


print()
print("F01 flat test source   :", FLAT_TEST_DIR)
print("F01 source images      :", len(flat_test_files))
print("F01 source creation    : VERIFIED")


# ------------------------------------------------------------
# F01 test probabilities
# ------------------------------------------------------------

f01_prob_by_filename = {}


f01_results = f01_model.predict(
    source=str(FLAT_TEST_DIR),
    imgsz=224,
    batch=64,
    device=0 if torch.cuda.is_available() else "cpu",
    stream=True,
    verbose=False,
)


for result in f01_results:

    filename = Path(result.path).name

    assert filename not in f01_prob_by_filename

    f01_prob_by_filename[filename] = (
        result.probs.data
        .detach()
        .float()
        .cpu()
        .numpy()
    )


expected_filenames = set(
    test_filenames
)

received_filenames = set(
    f01_prob_by_filename
)


missing_filenames = (
    expected_filenames
    - received_filenames
)

extra_filenames = (
    received_filenames
    - expected_filenames
)


print()
print(
    "F01 images received   :",
    len(f01_prob_by_filename),
)

print(
    "Missing filenames     :",
    len(missing_filenames),
)

print(
    "Extra filenames       :",
    len(extra_filenames),
)


assert len(f01_prob_by_filename) == 1612
assert not missing_filenames
assert not extra_filenames


f01_test_probs = np.stack(
    [
        f01_prob_by_filename[
            Path(path).name
        ]
        for path in test_paths
    ],
    axis=0,
)


assert f01_test_probs.shape == (1612, 20)


print("F01 image set         : VERIFIED")
print("F01 order alignment   : ALIGNED BY UNIQUE FILENAME")
print("F01 test probability  :", f01_test_probs.shape)


# ------------------------------------------------------------
# Probability validity
# ------------------------------------------------------------

assert np.allclose(
    f06_test_probs.sum(axis=1),
    1.0,
    atol=1e-5,
)

assert np.allclose(
    f01_test_probs.sum(axis=1),
    1.0,
    atol=1e-5,
)


print()
print("F06 probability sums  : VERIFIED")
print("F01 probability sums  : VERIFIED")


# ------------------------------------------------------------
# Apply only frozen F08 ensemble rule
# ------------------------------------------------------------

f08_test_probs = (
    CONVNEXT_WEIGHT * f06_test_probs
    + YOLO_WEIGHT * f01_test_probs
)


assert f08_test_probs.shape == (1612, 20)

assert np.allclose(
    f08_test_probs.sum(axis=1),
    1.0,
    atol=1e-5,
)


print("F08 ensemble sums     : VERIFIED")


# ------------------------------------------------------------
# Metric function
# ------------------------------------------------------------

def calculate_test_metrics(probabilities):

    predictions = probabilities.argmax(
        axis=1
    )


    sorted_indices = np.argsort(
        probabilities,
        axis=1,
    )[:, ::-1]


    metrics = {}


    for k in [1, 2, 3, 5]:

        topk = sorted_indices[:, :k]

        metrics[f"top{k}"] = float(
            np.mean(
                np.any(
                    topk
                    == test_targets[:, None],
                    axis=1,
                )
            )
        )


    metrics["macro_precision"] = float(
        precision_score(
            test_targets,
            predictions,
            average="macro",
            zero_division=0,
        )
    )


    metrics["macro_recall"] = float(
        recall_score(
            test_targets,
            predictions,
            average="macro",
            zero_division=0,
        )
    )


    metrics["macro_f1"] = float(
        f1_score(
            test_targets,
            predictions,
            average="macro",
            zero_division=0,
        )
    )


    metrics["weighted_f1"] = float(
        f1_score(
            test_targets,
            predictions,
            average="weighted",
            zero_division=0,
        )
    )


    return metrics


# ------------------------------------------------------------
# Calculate source and F08 metrics
# ------------------------------------------------------------

f06_test_metrics = calculate_test_metrics(
    f06_test_probs
)

f01_test_metrics = calculate_test_metrics(
    f01_test_probs
)

f08_test_metrics = calculate_test_metrics(
    f08_test_probs
)


# ------------------------------------------------------------
# Save raw test probabilities
# ------------------------------------------------------------

TEST_PROBABILITY_FILE = (
    F08_DIR
    / "F08_test_probabilities.npz"
)


np.savez_compressed(
    TEST_PROBABILITY_FILE,

    image_paths=np.asarray(
        test_paths,
        dtype=str,
    ),

    targets=test_targets,

    f06_probabilities=f06_test_probs,

    f01_probabilities=f01_test_probs,

    f08_probabilities=f08_test_probs,

    class_names=np.asarray(
        EXPECTED_CLASSES,
        dtype=str,
    ),

    convnext_weight=CONVNEXT_WEIGHT,

    yolo_weight=YOLO_WEIGHT,
)


# ------------------------------------------------------------
# Save F08 predictions
# ------------------------------------------------------------

f08_predictions = f08_test_probs.argmax(
    axis=1
)


prediction_table = pd.DataFrame({

    "image_path": test_paths,

    "true_index": test_targets,

    "true_class": [
        EXPECTED_CLASSES[index]
        for index in test_targets
    ],

    "predicted_index": f08_predictions,

    "predicted_class": [
        EXPECTED_CLASSES[index]
        for index in f08_predictions
    ],

    "top1_confidence": f08_test_probs.max(
        axis=1
    ),

    "correct": (
        f08_predictions == test_targets
    ),
})


PREDICTION_FILE = (
    F08_DIR
    / "F08_test_predictions.csv"
)


prediction_table.to_csv(
    PREDICTION_FILE,
    index=False,
)


# ------------------------------------------------------------
# Save metrics comparison
# ------------------------------------------------------------

metrics_rows = []


for model_name, metrics in [

    ("F06", f06_test_metrics),

    ("F01", f01_test_metrics),

    ("F08", f08_test_metrics),
]:

    metrics_rows.append({
        "model": model_name,
        **metrics,
    })


METRICS_FILE = (
    F08_DIR
    / "F08_test_metrics_comparison.csv"
)


pd.DataFrame(
    metrics_rows
).to_csv(
    METRICS_FILE,
    index=False,
)


# ------------------------------------------------------------
# Close official-test evaluation in lock
# ------------------------------------------------------------

f08_lock["official_test_evaluated"] = True

f08_lock["official_test_metrics"] = (
    f08_test_metrics
)


with open(
    LOCK_FILE,
    "w",
    encoding="utf-8",
) as file:

    json.dump(
        f08_lock,
        file,
        indent=2,
    )


# ------------------------------------------------------------
# Print official comparison
# ------------------------------------------------------------

print()
print("=" * 100)
print("OFFICIAL UNCHANGED TEST RESULTS")
print("=" * 100)


print(
    f"{'Model':<10}"
    f"{'Top-1':>12}"
    f"{'Top-2':>12}"
    f"{'Top-3':>12}"
    f"{'Top-5':>12}"
    f"{'Macro Recall':>18}"
    f"{'Macro F1':>15}"
)


for model_name, metrics in [

    ("F06", f06_test_metrics),

    ("F01", f01_test_metrics),

    ("F08", f08_test_metrics),
]:

    print(
        f"{model_name:<10}"
        f"{metrics['top1'] * 100:>11.4f}%"
        f"{metrics['top2'] * 100:>11.4f}%"
        f"{metrics['top3'] * 100:>11.4f}%"
        f"{metrics['top5'] * 100:>11.4f}%"
        f"{metrics['macro_recall'] * 100:>17.4f}%"
        f"{metrics['macro_f1'] * 100:>14.4f}%"
    )


print()
print("=" * 80)
print("F08 OFFICIAL METRICS")
print("=" * 80)


print(
    "Top-1           :",
    f"{f08_test_metrics['top1'] * 100:.4f}%",
)

print(
    "Top-2           :",
    f"{f08_test_metrics['top2'] * 100:.4f}%",
)

print(
    "Top-3           :",
    f"{f08_test_metrics['top3'] * 100:.4f}%",
)

print(
    "Top-5           :",
    f"{f08_test_metrics['top5'] * 100:.4f}%",
)

print(
    "Macro Precision :",
    f"{f08_test_metrics['macro_precision'] * 100:.4f}%",
)

print(
    "Macro Recall    :",
    f"{f08_test_metrics['macro_recall'] * 100:.4f}%",
)

print(
    "Macro F1        :",
    f"{f08_test_metrics['macro_f1'] * 100:.4f}%",
)

print(
    "Weighted F1     :",
    f"{f08_test_metrics['weighted_f1'] * 100:.4f}%",
)


print()
print("Test probabilities :", TEST_PROBABILITY_FILE)
print("Test predictions   :", PREDICTION_FILE)
print("Metrics comparison :", METRICS_FILE)
print("Lock file          :", LOCK_FILE)


print()
print("=" * 80)
print("F08 STEP 4 PASSED — OFFICIAL TEST EVALUATION COMPLETE")
print("=" * 80)


print(
    "Frozen ensemble :",
    f"F06 {CONVNEXT_WEIGHT:.2f}"
    f" + F01 {YOLO_WEIGHT:.2f}",
)

print("Weight search    : CLOSED")
print("Official test    : EVALUATED")
print("Next             : F08 STEP 5")

================================================================================
F08 Step 4 — Official unchanged test evaluation
================================================================================
Frozen ConvNeXt weight : 0.70
Frozen YOLO weight     : 0.30
Weight source          : VALIDATION ONLY
Weight search          : CLOSED

Test path              : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/official_imagefolder/test
Test images            : 1612
Classes                : 20
Class order            : VERIFIED
Unique filenames       : VERIFIED

F06 test probabilities: (1612, 20)

F01 flat test source   : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/experiments/F08_CONVNEXT_SMALL_HR384_YOLO26M_PROB_ENSEMBLE/f01_test_flat_source
F01 source images      : 1612
F01 source creation    : VERIFIED

F01 images received   : 1612
Missing filenames     : 0
Extra filenames       : 0
F01 image set         : VERIFIED
F01 order alignment   : ALIGNED BY UNIQUE FILENAME
F01 test probability  : (1612, 20)

F06 probability sums  : VERIFIED
F01 probability sums  : VERIFIED
F08 ensemble sums     : VERIFIED

====================================================================================================
OFFICIAL UNCHANGED TEST RESULTS
====================================================================================================
Model            Top-1       Top-2       Top-3       Top-5      Macro Recall       Macro F1
F06           92.1216%    97.9529%    99.2556%    99.7519%          87.4362%       88.1699%
F01           84.6774%    94.2308%    97.3325%    98.9454%          73.9895%       75.9908%
F08           92.2457%    98.0769%    99.3797%    99.8759%          87.0170%       87.9406%

================================================================================
F08 OFFICIAL METRICS
================================================================================
Top-1           : 92.2457%
Top-2           : 98.0769%
Top-3           : 99.3797%
Top-5           : 99.8759%
Macro Precision : 90.6725%
Macro Recall    : 87.0170%
Macro F1        : 87.9406%
Weighted F1     : 92.1750%

Test probabilities : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/experiments/F08_CONVNEXT_SMALL_HR384_YOLO26M_PROB_ENSEMBLE/F08_test_probabilities.npz
Test predictions   : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/experiments/F08_CONVNEXT_SMALL_HR384_YOLO26M_PROB_ENSEMBLE/F08_test_predictions.csv
Metrics comparison : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/experiments/F08_CONVNEXT_SMALL_HR384_YOLO26M_PROB_ENSEMBLE/F08_test_metrics_comparison.csv
Lock file          : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/experiments/F08_CONVNEXT_SMALL_HR384_YOLO26M_PROB_ENSEMBLE/F08_experiment_lock.json

================================================================================
F08 STEP 4 PASSED — OFFICIAL TEST EVALUATION COMPLETE
================================================================================
Frozen ensemble : F06 0.70 + F01 0.30
Weight search    : CLOSED
Official test    : EVALUATED
Next             : F08 STEP 5

# F08 Step 5 — Final Scientific Outputs and Official Package

## Objective

Finalize and package the completed F08 ensemble experiment.

Create:

- Official F08 test metrics summary
- Classification report
- Raw confusion matrix
- Normalized confusion matrix
- Confusion matrix figures
- F06/F01/F08 scientific comparison
- F06 versus F08 delta comparison
- Source checkpoint SHA-256 record
- Validation-selected ensemble rule record
- Final scientific README
- Official F08 ZIP package

## Scientific conclusion

The validation-selected `0.70 F06 + 0.30 F01` probability ensemble improved official-test Top-1, Top-2, Top-3, Top-5, Macro Precision, and Weighted F1 relative to F06.

However, official-test Macro Recall and Macro F1 declined slightly.

Therefore, the ensemble showed useful complementary ranking behavior but did not reproduce the strong validation balanced-class gains on the official unchanged test split.

F08 does not replace F06 as the stronger balanced-class branch.

F08 remains a completed positive ranking-ensemble result.

No new checkpoint was produced because F08 was inference-only.

In [20]:
# ============================================================
# F08 STEP 5 — FINAL OUTPUTS AND OFFICIAL PACKAGE
# ============================================================

from pathlib import Path
import hashlib
import json
import shutil
import zipfile

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
)


print("=" * 80)
print("F08 Step 5 — Create final scientific outputs and package")
print("=" * 80)


# ------------------------------------------------------------
# Directories
# ------------------------------------------------------------

TABLES_DIR = F08_DIR / "tables"
FIGURES_DIR = F08_DIR / "figures"

TABLES_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

FIGURES_DIR.mkdir(
    parents=True,
    exist_ok=True,
)


# ------------------------------------------------------------
# Verify completed F08 lock
# ------------------------------------------------------------

with open(
    LOCK_FILE,
    "r",
    encoding="utf-8",
) as file:
    final_lock = json.load(file)


assert (
    final_lock["final_weight_status"]
    == "selected_by_validation"
)

assert (
    final_lock["official_test_evaluated"]
    is True
)

assert final_lock["selected_weight"] == {
    "convnext": 0.70,
    "yolo": 0.30,
}


# ------------------------------------------------------------
# Source checkpoint hashes
# ------------------------------------------------------------

def sha256_file(path):

    digest = hashlib.sha256()

    with open(path, "rb") as file:

        for block in iter(
            lambda: file.read(1024 * 1024),
            b"",
        ):
            digest.update(block)

    return digest.hexdigest()


F06_SHA256 = sha256_file(F06_CKPT)
F01_SHA256 = sha256_file(F01_CKPT)


assert F06_SHA256 == (
    "d0c225c28b25f09822bc99518a37f9b1fe642b2d01213da7f68e2d76a255832a"
)

assert F01_SHA256 == (
    "aa489def1443a6cdab42a0a20a530b9e341d574dcaaf234bfe6c7983113e8e5a"
)


source_hashes = pd.DataFrame([
    {
        "source": "F06",
        "experiment": (
            "F06_CONVNEXT_SMALL_HR384_GENTLE_CB_FOCAL"
        ),
        "checkpoint": "best_model.pth",
        "sha256": F06_SHA256,
    },
    {
        "source": "F01",
        "experiment": "F01_YOLO26M_CLS_AUG200",
        "checkpoint": "best.pt",
        "sha256": F01_SHA256,
    },
])


SOURCE_HASH_FILE = (
    TABLES_DIR
    / "F08_source_checkpoint_hashes.csv"
)

source_hashes.to_csv(
    SOURCE_HASH_FILE,
    index=False,
)


# ------------------------------------------------------------
# Official F08 metrics summary
# ------------------------------------------------------------

metric_order = [
    ("Top-1", "top1"),
    ("Top-2", "top2"),
    ("Top-3", "top3"),
    ("Top-5", "top5"),
    ("Macro Precision", "macro_precision"),
    ("Macro Recall", "macro_recall"),
    ("Macro F1", "macro_f1"),
    ("Weighted F1", "weighted_f1"),
]


metric_rows = [
    {
        "metric": display_name,
        "value": f08_test_metrics[key],
        "percentage": (
            f08_test_metrics[key] * 100
        ),
    }
    for display_name, key in metric_order
]


METRICS_SUMMARY_FILE = (
    TABLES_DIR
    / "F08_test_metrics_summary.csv"
)

pd.DataFrame(
    metric_rows
).to_csv(
    METRICS_SUMMARY_FILE,
    index=False,
)


# ------------------------------------------------------------
# Classification report
# ------------------------------------------------------------

report = classification_report(
    test_targets,
    f08_predictions,
    target_names=EXPECTED_CLASSES,
    output_dict=True,
    zero_division=0,
)


report_rows = []

for label, values in report.items():

    if isinstance(values, dict):

        report_rows.append({
            "class": label,
            "precision": values["precision"],
            "recall": values["recall"],
            "f1_score": values["f1-score"],
            "support": values["support"],
        })


CLASSIFICATION_REPORT_FILE = (
    TABLES_DIR
    / "F08_classification_report.csv"
)

pd.DataFrame(
    report_rows
).to_csv(
    CLASSIFICATION_REPORT_FILE,
    index=False,
)


# ------------------------------------------------------------
# Confusion matrices
# ------------------------------------------------------------

cm = confusion_matrix(
    test_targets,
    f08_predictions,
)


cm_normalized = cm.astype(
    np.float64
)


row_sums = cm_normalized.sum(
    axis=1,
    keepdims=True,
)


cm_normalized = np.divide(
    cm_normalized,
    row_sums,
    out=np.zeros_like(cm_normalized),
    where=row_sums != 0,
)


CM_FILE = (
    TABLES_DIR
    / "F08_confusion_matrix.csv"
)

CM_NORMALIZED_FILE = (
    TABLES_DIR
    / "F08_confusion_matrix_normalized.csv"
)


pd.DataFrame(
    cm,
    index=EXPECTED_CLASSES,
    columns=EXPECTED_CLASSES,
).to_csv(
    CM_FILE
)


pd.DataFrame(
    cm_normalized,
    index=EXPECTED_CLASSES,
    columns=EXPECTED_CLASSES,
).to_csv(
    CM_NORMALIZED_FILE
)


# ------------------------------------------------------------
# Confusion matrix figures
# ------------------------------------------------------------

def save_cm_figure(
    matrix,
    title,
    output_path,
):

    plt.figure(
        figsize=(15, 13)
    )

    plt.imshow(
        matrix,
        aspect="auto",
    )

    plt.colorbar()

    plt.xticks(
        range(len(EXPECTED_CLASSES)),
        EXPECTED_CLASSES,
        rotation=90,
        fontsize=8,
    )

    plt.yticks(
        range(len(EXPECTED_CLASSES)),
        EXPECTED_CLASSES,
        fontsize=8,
    )

    plt.xlabel("Predicted class")
    plt.ylabel("True class")
    plt.title(title)

    plt.tight_layout()

    plt.savefig(
        output_path,
        dpi=300,
        bbox_inches="tight",
    )

    plt.close()


CM_FIGURE = (
    FIGURES_DIR
    / "F08_confusion_matrix.png"
)

CM_NORMALIZED_FIGURE = (
    FIGURES_DIR
    / "F08_confusion_matrix_normalized.png"
)


save_cm_figure(
    cm,
    "F08 Official Test Confusion Matrix",
    CM_FIGURE,
)


save_cm_figure(
    cm_normalized,
    "F08 Official Test Normalized Confusion Matrix",
    CM_NORMALIZED_FIGURE,
)


# ------------------------------------------------------------
# Scientific source comparison
# ------------------------------------------------------------

comparison_rows = []


for model_name, metrics in [
    ("F06", f06_test_metrics),
    ("F01", f01_test_metrics),
    ("F08", f08_test_metrics),
]:

    comparison_rows.append({
        "model": model_name,
        **metrics,
    })


SCIENTIFIC_COMPARISON_FILE = (
    TABLES_DIR
    / "F08_scientific_model_comparison.csv"
)


pd.DataFrame(
    comparison_rows
).to_csv(
    SCIENTIFIC_COMPARISON_FILE,
    index=False,
)


# ------------------------------------------------------------
# F06 versus F08 delta table
# ------------------------------------------------------------

delta_rows = []


for display_name, key in metric_order:

    f06_value = f06_test_metrics[key]
    f08_value = f08_test_metrics[key]

    delta_rows.append({
        "metric": display_name,
        "F06_percentage": f06_value * 100,
        "F08_percentage": f08_value * 100,
        "delta_percentage_points": (
            f08_value - f06_value
        ) * 100,
    })


DELTA_FILE = (
    TABLES_DIR
    / "F08_vs_F06_test_delta.csv"
)


pd.DataFrame(
    delta_rows
).to_csv(
    DELTA_FILE,
    index=False,
)


# ------------------------------------------------------------
# Validation-selected rule summary
# ------------------------------------------------------------

validation_rule = pd.DataFrame([
    {
        "selection_split": "validation",
        "selection_metric": "Macro F1",
        "convnext_weight": 0.70,
        "yolo_weight": 0.30,
        "validation_top1": (
            final_lock[
                "selected_validation_metrics"
            ]["top1"]
        ),
        "validation_macro_recall": (
            final_lock[
                "selected_validation_metrics"
            ]["macro_recall"]
        ),
        "validation_macro_f1": (
            final_lock[
                "selected_validation_metrics"
            ]["macro_f1"]
        ),
        "official_test_used_for_selection": False,
    }
])


VALIDATION_RULE_FILE = (
    TABLES_DIR
    / "F08_validation_selected_rule.csv"
)


validation_rule.to_csv(
    VALIDATION_RULE_FILE,
    index=False,
)


# ------------------------------------------------------------
# Final scientific README
# ------------------------------------------------------------

top1_delta = (
    f08_test_metrics["top1"]
    - f06_test_metrics["top1"]
) * 100

top5_delta = (
    f08_test_metrics["top5"]
    - f06_test_metrics["top5"]
) * 100

macro_recall_delta = (
    f08_test_metrics["macro_recall"]
    - f06_test_metrics["macro_recall"]
) * 100

macro_f1_delta = (
    f08_test_metrics["macro_f1"]
    - f06_test_metrics["macro_f1"]
) * 100


README_FILE = (
    F08_DIR
    / "README_F08.txt"
)


README_TEXT = f"""
AQUA20 F08 OFFICIAL FINAL EXPERIMENT

Campaign:
04-07-2026 AQUA20 FINAL BEAT BASE PLAN

Experiment:
F08_CONVNEXT_SMALL_HR384_YOLO26M_PROB_ENSEMBLE

STATUS:
COMPLETED
PACKAGED
CLOSED

SCIENTIFIC ROLE
Probability-level ensemble of two completed model families.

TRAINING
None.
F08 was inference-only.
No new checkpoint was produced.

LOCKED SOURCES

F06:
F06_CONVNEXT_SMALL_HR384_GENTLE_CB_FOCAL
Checkpoint: best_model.pth
SHA-256:
{F06_SHA256}

F01:
F01_YOLO26M_CLS_AUG200
Checkpoint: best.pt
SHA-256:
{F01_SHA256}

CLASS ORDER
20 AQUA20 classes.
Identical class-name mapping verified across both source models.

ENSEMBLE METHOD
Weighted arithmetic mean of class probabilities.

PREDEFINED VALIDATION-ONLY WEIGHT GRID
F06 0.50 + F01 0.50
F06 0.60 + F01 0.40
F06 0.70 + F01 0.30
F06 0.80 + F01 0.20

SELECTION METRIC
Validation Macro F1.

LOCKED TIE-BREAK
1. Higher validation Macro F1
2. Higher validation Macro Recall
3. Higher validation Top-1
4. Prefer equal weighting if still tied

SELECTED RULE
F06 ConvNeXt weight: 0.70
F01 YOLO weight: 0.30

SELECTED VALIDATION RESULTS
Top-1:
{final_lock["selected_validation_metrics"]["top1"] * 100:.4f}%

Macro Recall:
{final_lock["selected_validation_metrics"]["macro_recall"] * 100:.4f}%

Macro F1:
{final_lock["selected_validation_metrics"]["macro_f1"] * 100:.4f}%

The final ensemble weight was locked before official-test evaluation.

OFFICIAL UNCHANGED TEST
Images: 1,612
Classes: 20

F08 OFFICIAL TEST RESULTS
Top-1: {f08_test_metrics["top1"] * 100:.4f}%
Top-2: {f08_test_metrics["top2"] * 100:.4f}%
Top-3: {f08_test_metrics["top3"] * 100:.4f}%
Top-5: {f08_test_metrics["top5"] * 100:.4f}%
Macro Precision: {f08_test_metrics["macro_precision"] * 100:.4f}%
Macro Recall: {f08_test_metrics["macro_recall"] * 100:.4f}%
Macro F1: {f08_test_metrics["macro_f1"] * 100:.4f}%
Weighted F1: {f08_test_metrics["weighted_f1"] * 100:.4f}%

F08 VERSUS F06
Top-1 delta: {top1_delta:+.4f} percentage points
Top-5 delta: {top5_delta:+.4f} percentage points
Macro Recall delta: {macro_recall_delta:+.4f} percentage points
Macro F1 delta: {macro_f1_delta:+.4f} percentage points

SCIENTIFIC FINDING
The validation-selected 0.70 F06 + 0.30 F01 probability ensemble
improved official-test Top-1, Top-2, Top-3, Top-5,
Macro Precision, and Weighted F1 relative to F06.

However, the strong validation Macro Recall and Macro F1 gains
did not reproduce on the official unchanged test split.
Official-test Macro Recall and Macro F1 declined slightly.

Therefore, F08 demonstrates useful complementary ranking behaviour
between the F06 ConvNeXt and F01 YOLO model families, but it does
not replace F06 as the stronger balanced-class branch.

F08 is retained as a positive ranking-ensemble result.

BEAT-BASE TARGET
Reference Top-1 target: 92.6800%
F08 Top-1: {f08_test_metrics["top1"] * 100:.4f}%
Difference: {(f08_test_metrics["top1"] * 100) - 92.68:+.4f} percentage points

The 92.68% Top-1 target was not beaten by F08.

TEST-GOVERNANCE NOTE
The official test split was not used to select source checkpoints,
candidate ensemble weights, or the final F08 ensemble rule.

No additional weights were tested after official-test evaluation.
""".strip()


README_FILE.write_text(
    README_TEXT,
    encoding="utf-8",
)


# ------------------------------------------------------------
# Build clean official package
# ------------------------------------------------------------

PACKAGE_STAGE = (
    F08_DIR
    / "official_package"
)


if PACKAGE_STAGE.exists():
    shutil.rmtree(PACKAGE_STAGE)


(PACKAGE_STAGE / "tables").mkdir(
    parents=True
)

(PACKAGE_STAGE / "figures").mkdir(
    parents=True
)

(PACKAGE_STAGE / "probabilities").mkdir(
    parents=True
)

(PACKAGE_STAGE / "protocol").mkdir(
    parents=True
)


shutil.copy2(
    README_FILE,
    PACKAGE_STAGE / "README_F08.txt",
)


for table_file in [
    METRICS_SUMMARY_FILE,
    CLASSIFICATION_REPORT_FILE,
    CM_FILE,
    CM_NORMALIZED_FILE,
    SCIENTIFIC_COMPARISON_FILE,
    DELTA_FILE,
    SOURCE_HASH_FILE,
    VALIDATION_RULE_FILE,
    F08_DIR / "F08_validation_weight_comparison.csv",
    F08_DIR / "F08_test_metrics_comparison.csv",
    F08_DIR / "F08_test_predictions.csv",
]:

    shutil.copy2(
        table_file,
        PACKAGE_STAGE
        / "tables"
        / table_file.name,
    )


for figure_file in [
    CM_FIGURE,
    CM_NORMALIZED_FIGURE,
]:

    shutil.copy2(
        figure_file,
        PACKAGE_STAGE
        / "figures"
        / figure_file.name,
    )


for probability_file in [
    F08_DIR / "F08_validation_probabilities.npz",
    F08_DIR / "F08_test_probabilities.npz",
]:

    shutil.copy2(
        probability_file,
        PACKAGE_STAGE
        / "probabilities"
        / probability_file.name,
    )


shutil.copy2(
    LOCK_FILE,
    PACKAGE_STAGE
    / "protocol"
    / "F08_experiment_lock.json",
)


# ------------------------------------------------------------
# Create official ZIP
# ------------------------------------------------------------

FINAL_ZIP = (
    PROJECT_ROOT
    / "aqua20_f08_convnext_hr384_yolo26m_prob_ensemble_outputs.zip"
)


if FINAL_ZIP.exists():
    FINAL_ZIP.unlink()


with zipfile.ZipFile(
    FINAL_ZIP,
    "w",
    compression=zipfile.ZIP_DEFLATED,
) as archive:

    for file_path in sorted(
        PACKAGE_STAGE.rglob("*")
    ):

        if file_path.is_file():

            archive.write(
                file_path,
                file_path.relative_to(
                    PACKAGE_STAGE
                ),
            )


# ------------------------------------------------------------
# Final package verification
# ------------------------------------------------------------

with zipfile.ZipFile(
    FINAL_ZIP,
    "r",
) as archive:

    package_contents = archive.namelist()


assert "README_F08.txt" in package_contents

assert (
    "tables/F08_test_metrics_summary.csv"
    in package_contents
)

assert (
    "protocol/F08_experiment_lock.json"
    in package_contents
)


print()
print("F08 SCIENTIFIC RESULT")
print("-" * 80)

print(
    "Top-1 delta vs F06    :",
    f"{top1_delta:+.4f} pp",
)

print(
    "Top-5 delta vs F06    :",
    f"{top5_delta:+.4f} pp",
)

print(
    "Macro Recall vs F06   :",
    f"{macro_recall_delta:+.4f} pp",
)

print(
    "Macro F1 delta vs F06 :",
    f"{macro_f1_delta:+.4f} pp",
)


print()
print("Final package :", FINAL_ZIP)

print(
    "ZIP size      :",
    f"{FINAL_ZIP.stat().st_size / 1024**2:.2f} MB",
)


print()
print("PACKAGE CONTENTS")

for item in package_contents:
    print(item)


print()
print("=" * 80)
print("F08 STEP 5 PASSED — OFFICIAL FINAL PACKAGE CREATED")
print("=" * 80)

print("F08 STATUS : COMPLETED")
print("F08 ROLE   : POSITIVE RANKING ENSEMBLE RESULT")
print("BALANCED   : F06 REMAINS STRONGER")
print("DOWNLOAD   :", FINAL_ZIP)

================================================================================
F08 Step 5 — Create final scientific outputs and package
================================================================================

F08 SCIENTIFIC RESULT
--------------------------------------------------------------------------------
Top-1 delta vs F06    : +0.1241 pp
Top-5 delta vs F06    : +0.1241 pp
Macro Recall vs F06   : -0.4192 pp
Macro F1 delta vs F06 : -0.2293 pp

Final package : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/aqua20_f08_convnext_hr384_yolo26m_prob_ensemble_outputs.zip
ZIP size      : 0.96 MB

PACKAGE CONTENTS
README_F08.txt
figures/F08_confusion_matrix.png
figures/F08_confusion_matrix_normalized.png
probabilities/F08_test_probabilities.npz
probabilities/F08_validation_probabilities.npz
protocol/F08_experiment_lock.json
tables/F08_classification_report.csv
tables/F08_confusion_matrix.csv
tables/F08_confusion_matrix_normalized.csv
tables/F08_scientific_model_comparison.csv
tables/F08_source_checkpoint_hashes.csv
tables/F08_test_metrics_comparison.csv
tables/F08_test_metrics_summary.csv
tables/F08_test_predictions.csv
tables/F08_validation_selected_rule.csv
tables/F08_validation_weight_comparison.csv
tables/F08_vs_F06_test_delta.csv

================================================================================
F08 STEP 5 PASSED — OFFICIAL FINAL PACKAGE CREATED
================================================================================
F08 STATUS : COMPLETED
F08 ROLE   : POSITIVE RANKING ENSEMBLE RESULT
BALANCED   : F06 REMAINS STRONGER
DOWNLOAD   : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/aqua20_f08_convnext_hr384_yolo26m_prob_ensemble_outputs.zip

# F09 Step 1 — Verify F01–F08 packages and build raw campaign registry

This step locates the completed official F01–F08 Kaggle input packages and reads
their comparison-ready official metric tables.

The goals are to:

- verify all eight final-campaign experiment packages;
- verify official test support of 1,612 images where recorded;
- preserve only reported official metrics;
- build one raw F01–F08 campaign metric registry.

No final-method selection is performed in this step.

In [21]:
# ============================================================
# F09 STEP 1 — VERIFY F01-F08 AND BUILD RAW METRIC REGISTRY
# ============================================================

from pathlib import Path
import pandas as pd

print("=" * 80)
print("F09 Step 1 — Verify F01-F08 packages and build raw registry")
print("=" * 80)

ALL_CSV = list(Path("/kaggle/input").rglob("*.csv"))

METRIC_FILES = {
    "F01": "F01_test_metrics_summary.csv",
    "F02": "F02_test_metrics_summary.csv",
    "F03": "F03_test_metrics_summary.csv",
    "F04": "F04_test_metrics_summary.csv",
    "F05": "F05_test_metrics_summary.csv",
    "F06": "F06_test_metrics_summary.csv",
    "F07": "F07_official_test_metrics.csv",
    "F08": "F08_test_metrics_summary.csv",
}

registry = []

for exp, metric_filename in METRIC_FILES.items():

    metrics_path = next(
        (
            p for p in ALL_CSV
            if p.name.lower() == metric_filename.lower()
        ),
        None,
    )

    predictions_path = next(
        (
            p for p in ALL_CSV
            if p.name.lower() == f"{exp}_test_predictions.csv".lower()
        ),
        None,
    )

    assert metrics_path is not None, f"{exp}: metrics file not found"
    assert predictions_path is not None, f"{exp}: predictions file not found"

    metrics = pd.read_csv(metrics_path)
    predictions = pd.read_csv(predictions_path)

    assert len(predictions) == 1612, (
        f"{exp}: expected 1612 predictions, found {len(predictions)}"
    )

    cols = {c.lower(): c for c in metrics.columns}

    if "metric" in cols and "value" in cols:
        metric_row = dict(
            zip(
                metrics[cols["metric"]],
                metrics[cols["value"]],
            )
        )
    else:
        metric_row = metrics.iloc[0].to_dict()

    metric_row["Experiment"] = exp
    metric_row["Test Support"] = len(predictions)
    metric_row["Metrics CSV"] = metrics_path.name

    registry.append(metric_row)

    print(
        f"{exp}: VERIFIED | "
        f"source={metrics_path.name} | "
        f"test_support={len(predictions)}"
    )

raw_registry = pd.DataFrame(registry)

first_cols = [
    "Experiment",
    "Test Support",
    "Metrics CSV",
]

raw_registry = raw_registry[
    first_cols
    + [c for c in raw_registry.columns if c not in first_cols]
]

print("\n" + "=" * 80)
print("RAW F01-F08 CAMPAIGN METRIC REGISTRY")
print("=" * 80)

display(raw_registry)

verified_experiments = raw_registry["Experiment"].nunique()

print("\nExperiments verified :", verified_experiments)
print("Expected experiments : 8")

assert verified_experiments == 8

print("\n" + "=" * 80)
print("F09 STEP 1 PASSED — RAW CAMPAIGN REGISTRY BUILT")
print("=" * 80)
print("OFFICIAL TEST SUPPORT : VERIFIED = 1,612 PER EXPERIMENT")
print("FINAL METHOD SELECTION: NOT PERFORMED")

================================================================================
F09 Step 1 — Verify F01-F08 packages and build raw registry
================================================================================
F01: VERIFIED | source=f01_test_metrics_summary.csv | test_support=1612
F02: VERIFIED | source=F02_test_metrics_summary.csv | test_support=1612
F03: VERIFIED | source=F03_test_metrics_summary.csv | test_support=1612
F04: VERIFIED | source=F04_test_metrics_summary.csv | test_support=1612
F05: VERIFIED | source=F05_test_metrics_summary.csv | test_support=1612
F06: VERIFIED | source=F06_test_metrics_summary.csv | test_support=1612
F07: VERIFIED | source=F07_official_test_metrics.csv | test_support=1612
F08: VERIFIED | source=F08_test_metrics_summary.csv | test_support=1612

================================================================================
RAW F01-F08 CAMPAIGN METRIC REGISTRY
================================================================================

,Experiment,Test Support,Metrics CSV,experiment,model,training_strategy,best_epoch,val_top1_pct,val_top5_pct,test_top1_pct,...,Macro Precision,Macro Recall,Macro F1,Weighted F1,num_classes,Top-1,Top-2,Top-3,Top-5,NLL Loss
0,F01,1612,f01_test_metrics_summary.csv,F01_YOLO26M_CLS_AUG200,YOLO26m-cls,Aug-200 train-only balancing,2.0,87.8811,99.390244,84.677419,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,F02,1612,F02_test_metrics_summary.csv,F02,YOLO26s-cls,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,F03,1612,F03_test_metrics_summary.csv,F03,ConvNeXt-Small,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,F04,1612,F04_test_metrics_summary.csv,F04_CONVNEXT_SMALL_AUG200,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,F05,1612,F05_test_metrics_summary.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.897496,0.826547,0.843487,0.909759,NaN,NaN,NaN,NaN,NaN,NaN
5,F06,1612,F06_test_metrics_summary.csv,F06_CONVNEXT_SMALL_HR384_GENTLE_CB_FOCAL,NaN,NaN,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,20.0,NaN,NaN,NaN,NaN,NaN
6,F07,1612,F07_official_test_metrics.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,89.876543,86.532374,87.402551,92.077110,NaN,92.121588,97.890819,99.317618,99.689826,0.248791
7,F08,1612,F08_test_metrics_summary.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.906725,0.870170,0.879406,0.921750,NaN,0.922457,0.980769,0.993797,0.998759,NaN

Experiments verified : 8
Expected experiments : 8

================================================================================
F09 STEP 1 PASSED — RAW CAMPAIGN REGISTRY BUILT
================================================================================
OFFICIAL TEST SUPPORT : VERIFIED = 1,612 PER EXPERIMENT
FINAL METHOD SELECTION: NOT PERFORMED

# F09 Step 2 — Create consolidated F01–F08 campaign comparison

This step normalizes the heterogeneous official metric-table schemas from F01–F08
into one comparison-ready campaign table.

The official comparison metrics are:

- Top-1
- Top-2
- Top-3
- Top-5
- Macro Precision
- Macro Recall
- Macro F1
- Weighted F1

Metrics are converted to percentage scale.

Unavailable metrics remain missing and are not invented.

No final-method selection is performed in this step.

In [23]:
# ============================================================
# F09 STEP 2 — CREATE CONSOLIDATED F01-F08 COMPARISON
# ============================================================

from pathlib import Path
import pandas as pd

print("=" * 80)
print("F09 Step 2 — Consolidated F01-F08 campaign comparison")
print("=" * 80)

METRICS = {
    "Top-1": "top1",
    "Top-2": "top2",
    "Top-3": "top3",
    "Top-5": "top5",
    "Macro Precision": "macroprecision",
    "Macro Recall": "macrorecall",
    "Macro F1": "macrof1",
    "Weighted F1": "weightedf1",
}

METHODS = {
    "F01": "YOLO26m-cls + Aug-200",
    "F02": "YOLO26s-cls + Aug-200",
    "F03": "ConvNeXt-Small + Gentle CB Focal",
    "F04": "ConvNeXt-Small + Aug-200",
    "F05": "ConvNeXt-Small + Aug-200 + Gentle CB Focal",
    "F06": "F03 branch + HR384 fine-tuning",
    "F07": "F06 + horizontal-flip TTA",
    "F08": "F06 + F01 probability ensemble",
}

def clean_name(name):
    return "".join(
        ch for ch in str(name).lower()
        if ch.isalnum()
    )

def to_percentage(value):
    if pd.isna(value):
        return pd.NA

    value = float(value)

    if abs(value) <= 1:
        value *= 100

    return value

def find_metric(row, key):
    candidates = []

    for column, value in row.items():
        if pd.isna(value):
            continue

        name = clean_name(column)

        if key not in name:
            continue

        if "val" in name or "delta" in name:
            continue

        candidates.append((column, value))

    if not candidates:
        return pd.NA

    return to_percentage(candidates[0][1])

comparison_rows = []

for _, row in raw_registry.iterrows():

    exp = row["Experiment"]

    result = {
        "Experiment": exp,
        "Method": METHODS[exp],
    }

    for metric, key in METRICS.items():
        result[metric] = find_metric(row, key)

    comparison_rows.append(result)

campaign_comparison = pd.DataFrame(comparison_rows)

numeric_cols = list(METRICS.keys())

campaign_comparison[numeric_cols] = (
    campaign_comparison[numeric_cols]
    .apply(pd.to_numeric, errors="coerce")
    .round(4)
)

OUTPUT_DIR = Path(
    "/kaggle/working/"
    "AQUA20_FINAL_BEAT_BASE_04072026/"
    "F09_FINAL_METHOD_FREEZE_AND_CAMPAIGN_COMPARISON/"
    "tables"
)

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

OUTPUT_CSV = (
    OUTPUT_DIR
    / "F09_F01_F08_campaign_comparison.csv"
)

campaign_comparison.to_csv(
    OUTPUT_CSV,
    index=False,
)

print("\n" + "=" * 80)
print("CONSOLIDATED F01-F08 CAMPAIGN COMPARISON (%)")
print("=" * 80)

display(campaign_comparison)

print("\nMISSING OFFICIAL METRICS")
print("-" * 80)

missing_metrics = campaign_comparison[
    ["Experiment"] + numeric_cols
].set_index("Experiment").isna()

for exp in missing_metrics.index:
    missing = missing_metrics.columns[
        missing_metrics.loc[exp]
    ].tolist()

    print(
        f"{exp}: "
        + (", ".join(missing) if missing else "NONE")
    )

print("\nSaved :", OUTPUT_CSV)

print("\n" + "=" * 80)
print("F09 STEP 2 PASSED — CONSOLIDATED COMPARISON CREATED")
print("=" * 80)
print("UNAVAILABLE METRICS    : PRESERVED AS MISSING")
print("FINAL METHOD SELECTION : NOT PERFORMED")

================================================================================
F09 Step 2 — Consolidated F01-F08 campaign comparison
================================================================================

================================================================================
CONSOLIDATED F01-F08 CAMPAIGN COMPARISON (%)
================================================================================

,Experiment,Method,Top-1,Top-2,Top-3,Top-5,Macro Precision,Macro Recall,Macro F1,Weighted F1
0,F01,YOLO26m-cls + Aug-200,84.6774,NaN,NaN,98.9454,83.3054,73.9895,75.9908,84.4249
1,F02,YOLO26s-cls + Aug-200,83.4367,NaN,NaN,97.9529,80.9103,65.2565,70.3909,82.8376
2,F03,ConvNeXt-Small + Gentle CB Focal,91.6253,97.7047,99.1315,99.6898,90.7850,86.9302,87.9645,91.5656
3,F04,ConvNeXt-Small + Aug-200,91.3772,97.2705,99.0074,99.6278,89.3241,84.3236,86.0035,91.2641
4,F05,ConvNeXt-Small + Aug-200 + Gentle CB Focal,91.1290,97.4566,98.9454,99.7519,89.7496,82.6547,84.3487,90.9759
5,F06,F03 branch + HR384 fine-tuning,92.1216,97.9529,99.2556,99.7519,90.4312,87.4362,88.1699,92.0810
6,F07,F06 + horizontal-flip TTA,92.1216,97.8908,99.3176,99.6898,89.8765,86.5324,87.4026,92.0771
7,F08,F06 + F01 probability ensemble,92.2457,98.0769,99.3797,99.8759,90.6725,87.0170,87.9406,92.1750

MISSING OFFICIAL METRICS
--------------------------------------------------------------------------------
F01: Top-2, Top-3
F02: Top-2, Top-3
F03: NONE
F04: NONE
F05: NONE
F06: NONE
F07: NONE
F08: NONE

Saved : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/F09_FINAL_METHOD_FREEZE_AND_CAMPAIGN_COMPARISON/tables/F09_F01_F08_campaign_comparison.csv

================================================================================
F09 STEP 2 PASSED — CONSOLIDATED COMPARISON CREATED
================================================================================
UNAVAILABLE METRICS    : PRESERVED AS MISSING
FINAL METHOD SELECTION : NOT PERFORMED

# F09 Step 3 — Compare campaign interventions and scientific effects

This step compares the completed controlled campaign branches using the verified
official-test metrics from F09 Step 2.

The intervention comparisons are:

- Gentle CB Focal versus Aug-200;
- Aug-200 + Gentle CB Focal versus Gentle CB Focal;
- HR384 fine-tuning versus the F03 source branch;
- horizontal-flip TTA versus F06;
- validation-governed cross-family ensemble versus F06.

Metric changes are reported in percentage points.

These comparisons are used to document campaign evidence and intervention effects.
The final reporting hierarchy is not frozen in this step.

In [24]:
# ============================================================
# F09 STEP 3 — INTERVENTION-EFFECT COMPARISON
# ============================================================

import pandas as pd

print("=" * 80)
print("F09 Step 3 — Intervention-effect comparison")
print("=" * 80)

METRIC_COLS = [
    "Top-1",
    "Top-2",
    "Top-3",
    "Top-5",
    "Macro Precision",
    "Macro Recall",
    "Macro F1",
    "Weighted F1",
]

COMPARISONS = [
    (
        "Gentle CB Focal vs Aug-200",
        "F04",
        "F03",
        "Compare isolated imbalance strategies",
    ),
    (
        "Aug-200 + Gentle CB Focal",
        "F03",
        "F05",
        "Test whether Aug-200 complements Gentle CB Focal",
    ),
    (
        "HR384 fine-tuning",
        "F03",
        "F06",
        "Test high-resolution continuation of F03",
    ),
    (
        "Horizontal-flip TTA",
        "F06",
        "F07",
        "Test deterministic two-view TTA",
    ),
    (
        "Cross-family probability ensemble",
        "F06",
        "F08",
        "Test validation-governed ConvNeXt + YOLO ensemble",
    ),
]

indexed = campaign_comparison.set_index("Experiment")

effect_rows = []

for intervention, reference, candidate, role in COMPARISONS:

    row = {
        "Intervention": intervention,
        "Reference": reference,
        "Candidate": candidate,
        "Scientific Role": role,
    }

    for metric in METRIC_COLS:
        ref_value = indexed.loc[reference, metric]
        candidate_value = indexed.loc[candidate, metric]

        row[f"Δ {metric} (pp)"] = (
            candidate_value - ref_value
            if pd.notna(ref_value) and pd.notna(candidate_value)
            else pd.NA
        )

    effect_rows.append(row)

intervention_effects = pd.DataFrame(effect_rows)

delta_cols = [
    column for column in intervention_effects.columns
    if column.startswith("Δ ")
]

intervention_effects[delta_cols] = (
    intervention_effects[delta_cols]
    .apply(pd.to_numeric, errors="coerce")
    .round(4)
)

conclusions = pd.DataFrame([
    {
        "Intervention": "Gentle CB Focal",
        "Conclusion": (
            "F03 outperformed F04 in Top-1, Macro Precision, "
            "Macro Recall, Macro F1, and Weighted F1; it was the "
            "stronger isolated imbalance intervention."
        ),
    },
    {
        "Intervention": "Aug-200",
        "Conclusion": (
            "Aug-200 alone was weaker than the Gentle CB Focal branch "
            "for balanced-class performance."
        ),
    },
    {
        "Intervention": "Aug-200 + Gentle CB Focal",
        "Conclusion": (
            "Adding Aug-200 to the Gentle CB Focal branch reduced "
            "Top-1, Macro Recall, Macro F1, and Weighted F1; the two "
            "interventions were not complementary."
        ),
    },
    {
        "Intervention": "HR384",
        "Conclusion": (
            "HR384 improved F03 in Top-1, Top-2, Top-3, Top-5, "
            "Macro Recall, Macro F1, and Weighted F1."
        ),
    },
    {
        "Intervention": "Horizontal-flip TTA",
        "Conclusion": (
            "TTA left Top-1 unchanged and reduced Macro Precision, "
            "Macro Recall, Macro F1, and Weighted F1 on the official test."
        ),
    },
    {
        "Intervention": "Cross-family ensemble",
        "Conclusion": (
            "F08 improved Top-1, Top-2, Top-3, Top-5, Macro Precision, "
            "and Weighted F1 over F06, but reduced Macro Recall and Macro F1."
        ),
    },
])

EFFECT_CSV = OUTPUT_DIR / "F09_intervention_effect_comparison.csv"
CONCLUSION_CSV = OUTPUT_DIR / "F09_scientific_conclusions.csv"

intervention_effects.to_csv(EFFECT_CSV, index=False)
conclusions.to_csv(CONCLUSION_CSV, index=False)

print("\n" + "=" * 80)
print("INTERVENTION EFFECTS — OFFICIAL TEST DELTAS (PP)")
print("=" * 80)

display(intervention_effects)

print("\n" + "=" * 80)
print("EVIDENCE-BASED SCIENTIFIC CONCLUSIONS")
print("=" * 80)

display(conclusions)

print("\nSaved :", EFFECT_CSV)
print("Saved :", CONCLUSION_CSV)

print("\n" + "=" * 80)
print("F09 STEP 3 PASSED — INTERVENTION EFFECTS DOCUMENTED")
print("=" * 80)
print("FINAL REPORTING HIERARCHY : NOT YET FROZEN")

================================================================================
F09 Step 3 — Intervention-effect comparison
================================================================================

================================================================================
INTERVENTION EFFECTS — OFFICIAL TEST DELTAS (PP)
================================================================================

,Intervention,Reference,Candidate,Scientific Role,Δ Top-1 (pp),Δ Top-2 (pp),Δ Top-3 (pp),Δ Top-5 (pp),Δ Macro Precision (pp),Δ Macro Recall (pp),Δ Macro F1 (pp),Δ Weighted F1 (pp)
0,Gentle CB Focal vs Aug-200,F04,F03,Compare isolated imbalance strategies,0.2481,0.4342,0.1241,0.0620,1.4609,2.6066,1.9610,0.3015
1,Aug-200 + Gentle CB Focal,F03,F05,Test whether Aug-200 complements Gentle CB Focal,-0.4963,-0.2481,-0.1861,0.0621,-1.0354,-4.2755,-3.6158,-0.5897
2,HR384 fine-tuning,F03,F06,Test high-resolution continuation of F03,0.4963,0.2482,0.1241,0.0621,-0.3538,0.5060,0.2054,0.5154
3,Horizontal-flip TTA,F06,F07,Test deterministic two-view TTA,0.0000,-0.0621,0.0620,-0.0621,-0.5547,-0.9038,-0.7673,-0.0039
4,Cross-family probability ensemble,F06,F08,Test validation-governed ConvNeXt + YOLO ensemble,0.1241,0.1240,0.1241,0.1240,0.2413,-0.4192,-0.2293,0.0940

================================================================================
EVIDENCE-BASED SCIENTIFIC CONCLUSIONS
================================================================================

,Intervention,Conclusion
0,Gentle CB Focal,"F03 outperformed F04 in Top-1, Macro Precision..."
1,Aug-200,Aug-200 alone was weaker than the Gentle CB Fo...
2,Aug-200 + Gentle CB Focal,Adding Aug-200 to the Gentle CB Focal branch r...
3,HR384,"HR384 improved F03 in Top-1, Top-2, Top-3, Top..."
4,Horizontal-flip TTA,TTA left Top-1 unchanged and reduced Macro Pre...
5,Cross-family ensemble,"F08 improved Top-1, Top-2, Top-3, Top-5, Macro..."

Saved : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/F09_FINAL_METHOD_FREEZE_AND_CAMPAIGN_COMPARISON/tables/F09_intervention_effect_comparison.csv
Saved : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/F09_FINAL_METHOD_FREEZE_AND_CAMPAIGN_COMPARISON/tables/F09_scientific_conclusions.csv

================================================================================
F09 STEP 3 PASSED — INTERVENTION EFFECTS DOCUMENTED
================================================================================
FINAL REPORTING HIERARCHY : NOT YET FROZEN

# F09 Step 4 — Freeze final reporting hierarchy and campaign methods

This step uses the completed F01–F08 campaign evidence to freeze the final
scientific reporting hierarchy.

The step records:

- primary proposed AQUA20 method;
- complementary final ensemble;
- strongest balanced-class model;
- strongest ranking model;
- best isolated imbalance intervention;
- exact frozen source checkpoints and SHA-256 hashes;
- final comparison with the 92.68% beat-base Top-1 target.

No additional model tuning, ensemble-weight search, TTA search, or official-test
selection is performed.

In [25]:
# ============================================================
# F09 STEP 4 — FREEZE FINAL REPORTING HIERARCHY
# ============================================================

from pathlib import Path
import hashlib
import pandas as pd

print("=" * 100)
print("F09 Step 4 — Freeze final reporting hierarchy")
print("=" * 100)

# -------------------------------------------------------------------------
# Final method selection
# -------------------------------------------------------------------------

final_selection = pd.DataFrame([
    {
        "Reporting Role": "Primary proposed method",
        "Experiment": "F06",
        "Frozen Result": "ConvNeXt-Small + Gentle CB Focal + HR384",
    },
    {
        "Reporting Role": "Complementary final ensemble",
        "Experiment": "F08",
        "Frozen Result": "0.70 F06 + 0.30 F01 probability ensemble",
    },
    {
        "Reporting Role": "Strongest balanced-class model",
        "Experiment": "F06",
        "Frozen Result": "Highest official-test Macro Recall and Macro F1",
    },
    {
        "Reporting Role": "Strongest ranking model",
        "Experiment": "F08",
        "Frozen Result": "Best campaign Top-1 and Top-k ranking metrics",
    },
    {
        "Reporting Role": "Best isolated imbalance intervention",
        "Experiment": "F03",
        "Frozen Result": "Gentle Class-Balanced Focal Loss",
    },
])

# -------------------------------------------------------------------------
# Verify frozen source checkpoints
# -------------------------------------------------------------------------

EXPECTED_HASHES = {
    "F06": (
        "best_model.pth",
        "d0c225c28b25f09822bc99518a37f9b1fe642b2d01213da7f68e2d76a255832a",
        2,
    ),
    "F01": (
        "best.pt",
        "aa489def1443a6cdab42a0a20a530b9e341d574dcaaf234bfe6c7983113e8e5a",
        2,
    ),
}

checkpoint_rows = []

for exp, (filename, expected_hash, best_epoch) in EXPECTED_HASHES.items():

    matches = [
        p for p in Path("/kaggle/input").rglob(filename)
        if exp.lower() in str(p).lower()
    ]

    assert matches, f"{exp}: frozen checkpoint not found"

    checkpoint_path = matches[0]

    sha256 = hashlib.sha256()

    with open(checkpoint_path, "rb") as checkpoint_file:
        for block in iter(
            lambda: checkpoint_file.read(1024 * 1024),
            b"",
        ):
            sha256.update(block)

    actual_hash = sha256.hexdigest()

    assert actual_hash == expected_hash, (
        f"{exp}: checkpoint SHA-256 mismatch"
    )

    checkpoint_rows.append({
        "Experiment": exp,
        "Checkpoint": filename,
        "Best Epoch": best_epoch,
        "SHA-256": actual_hash,
        "Hash Status": "VERIFIED",
    })

checkpoint_freeze = pd.DataFrame(checkpoint_rows)

# -------------------------------------------------------------------------
# Beat-base target comparison
# -------------------------------------------------------------------------

BEAT_BASE_TOP1 = 92.6800

best_row = campaign_comparison.loc[
    campaign_comparison["Top-1"].idxmax()
]

best_top1 = float(best_row["Top-1"])
gap_pp = best_top1 - BEAT_BASE_TOP1

beat_base = pd.DataFrame([{
    "Reference Top-1 (%)": BEAT_BASE_TOP1,
    "Best Campaign Experiment": best_row["Experiment"],
    "Best Campaign Top-1 (%)": best_top1,
    "Gap (pp)": gap_pp,
    "Target Status": "NOT BEATEN",
}])

# -------------------------------------------------------------------------
# Save freeze tables
# -------------------------------------------------------------------------

SELECTION_CSV = OUTPUT_DIR / "F09_final_method_selection.csv"
CHECKPOINT_CSV = OUTPUT_DIR / "F09_source_checkpoint_freeze_record.csv"
TARGET_CSV = OUTPUT_DIR / "F09_beat_base_target_comparison.csv"

final_selection.to_csv(SELECTION_CSV, index=False)
checkpoint_freeze.to_csv(CHECKPOINT_CSV, index=False)
beat_base.to_csv(TARGET_CSV, index=False)

# -------------------------------------------------------------------------
# Clean formatted output
# -------------------------------------------------------------------------

print("\nFINAL REPORTING HIERARCHY")
print("-" * 100)

print(
    final_selection[
        ["Reporting Role", "Experiment"]
    ].to_string(index=False)
)

print("\n" + "=" * 100)
print("FROZEN PRIMARY AND COMPLEMENTARY METHODS")
print("=" * 100)

print(f"{'Primary proposed method':<32}: F06")
print(f"{'Method':<32}: ConvNeXt-Small + Gentle CB Focal + HR384")
print(f"{'Top-1':<32}: {campaign_comparison.loc[5, 'Top-1']:.4f}%")
print(f"{'Macro Recall':<32}: {campaign_comparison.loc[5, 'Macro Recall']:.4f}%")
print(f"{'Macro F1':<32}: {campaign_comparison.loc[5, 'Macro F1']:.4f}%")

print()

print(f"{'Complementary final ensemble':<32}: F08")
print(f"{'Rule':<32}: 0.70 F06 + 0.30 F01")
print(f"{'Top-1':<32}: {campaign_comparison.loc[7, 'Top-1']:.4f}%")
print(f"{'Top-5':<32}: {campaign_comparison.loc[7, 'Top-5']:.4f}%")
print(f"{'Macro Precision':<32}: {campaign_comparison.loc[7, 'Macro Precision']:.4f}%")
print(f"{'Weighted F1':<32}: {campaign_comparison.loc[7, 'Weighted F1']:.4f}%")

print("\n" + "=" * 100)
print("SOURCE CHECKPOINT FREEZE RECORD")
print("=" * 100)

for _, row in checkpoint_freeze.iterrows():

    print(f"\n{row['Experiment']} LOCKED CHECKPOINT")
    print("-" * 100)
    print(f"{'Checkpoint':<20}: {row['Checkpoint']}")
    print(f"{'Best epoch':<20}: {row['Best Epoch']}")
    print(f"{'SHA-256':<20}: {row['SHA-256']}")
    print(f"{'Hash status':<20}: {row['Hash Status']}")

print("\n" + "=" * 100)
print("BEAT-BASE TARGET STATUS")
print("=" * 100)

print(f"{'Reference Top-1 target':<32}: {BEAT_BASE_TOP1:.4f}%")
print(f"{'Best campaign experiment':<32}: {best_row['Experiment']}")
print(f"{'Best campaign Top-1':<32}: {best_top1:.4f}%")
print(f"{'Gap to target':<32}: {gap_pp:+.4f} pp")
print(f"{'Target status':<32}: NOT BEATEN")

print("\nSAVED FINAL-FREEZE TABLES")
print("-" * 100)
print("Method selection       :", SELECTION_CSV)
print("Checkpoint freeze      :", CHECKPOINT_CSV)
print("Beat-base comparison   :", TARGET_CSV)

print("\n" + "=" * 100)
print("F09 STEP 4 PASSED — FINAL REPORTING HIERARCHY FROZEN")
print("=" * 100)
print("PRIMARY PROPOSED METHOD       : F06")
print("COMPLEMENTARY FINAL ENSEMBLE  : F08")
print("STRONGEST BALANCED MODEL      : F06")
print("STRONGEST RANKING MODEL       : F08")
print("BEST ISOLATED IMBALANCE METHOD: F03")
print("92.68% TOP-1 TARGET           : NOT BEATEN")
print("STATUS                         : READY FOR F09 STEP 5")

====================================================================================================
F09 Step 4 — Freeze final reporting hierarchy
====================================================================================================

FINAL REPORTING HIERARCHY
----------------------------------------------------------------------------------------------------
                      Reporting Role Experiment
             Primary proposed method        F06
        Complementary final ensemble        F08
      Strongest balanced-class model        F06
             Strongest ranking model        F08
Best isolated imbalance intervention        F03

====================================================================================================
FROZEN PRIMARY AND COMPLEMENTARY METHODS
====================================================================================================
Primary proposed method         : F06
Method                          : ConvNeXt-Small + Gentle CB Focal + HR384
Top-1                           : 92.1216%
Macro Recall                    : 87.4362%
Macro F1                        : 88.1699%

Complementary final ensemble    : F08
Rule                            : 0.70 F06 + 0.30 F01
Top-1                           : 92.2457%
Top-5                           : 99.8759%
Macro Precision                 : 90.6725%
Weighted F1                     : 92.1750%

====================================================================================================
SOURCE CHECKPOINT FREEZE RECORD
====================================================================================================

F06 LOCKED CHECKPOINT
----------------------------------------------------------------------------------------------------
Checkpoint          : best_model.pth
Best epoch          : 2
SHA-256             : d0c225c28b25f09822bc99518a37f9b1fe642b2d01213da7f68e2d76a255832a
Hash status         : VERIFIED

F01 LOCKED CHECKPOINT
----------------------------------------------------------------------------------------------------
Checkpoint          : best.pt
Best epoch          : 2
SHA-256             : aa489def1443a6cdab42a0a20a530b9e341d574dcaaf234bfe6c7983113e8e5a
Hash status         : VERIFIED

====================================================================================================
BEAT-BASE TARGET STATUS
====================================================================================================
Reference Top-1 target          : 92.6800%
Best campaign experiment        : F08
Best campaign Top-1             : 92.2457%
Gap to target                   : -0.4343 pp
Target status                   : NOT BEATEN

SAVED FINAL-FREEZE TABLES
----------------------------------------------------------------------------------------------------
Method selection       : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/F09_FINAL_METHOD_FREEZE_AND_CAMPAIGN_COMPARISON/tables/F09_final_method_selection.csv
Checkpoint freeze      : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/F09_FINAL_METHOD_FREEZE_AND_CAMPAIGN_COMPARISON/tables/F09_source_checkpoint_freeze_record.csv
Beat-base comparison   : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/F09_FINAL_METHOD_FREEZE_AND_CAMPAIGN_COMPARISON/tables/F09_beat_base_target_comparison.csv

====================================================================================================
F09 STEP 4 PASSED — FINAL REPORTING HIERARCHY FROZEN
====================================================================================================
PRIMARY PROPOSED METHOD       : F06
COMPLEMENTARY FINAL ENSEMBLE  : F08
STRONGEST BALANCED MODEL      : F06
STRONGEST RANKING MODEL       : F08
BEST ISOLATED IMBALANCE METHOD: F03
92.68% TOP-1 TARGET           : NOT BEATEN
STATUS                         : READY FOR F09 STEP 5

# F09 Step 5 — Create final campaign evidence package

This step closes the F09 final-method freeze and campaign consolidation stage.

It creates:

- the complete F01–F08 campaign comparison evidence;
- the eight required final campaign tables;
- validation-versus-test generalization evidence for the locked final-stage methods;
- publication-ready campaign comparison figures;
- the official F09 README;
- the final downloadable F09 ZIP package.

No training, model tuning, ensemble search, TTA search, or additional official-test
selection is performed.

In [26]:
# ============================================================
# F09 STEP 5 — CREATE FINAL CAMPAIGN EVIDENCE PACKAGE
# ============================================================

from pathlib import Path
import zipfile
import pandas as pd
import matplotlib.pyplot as plt

print("=" * 100)
print("F09 Step 5 — Create final campaign evidence package")
print("=" * 100)

BASE_DIR = OUTPUT_DIR.parent
FIGURE_DIR = BASE_DIR / "figures"

FIGURE_DIR.mkdir(parents=True, exist_ok=True)

# -------------------------------------------------------------------------
# Required table 2 — Primary metric comparison
# -------------------------------------------------------------------------

PRIMARY_METRICS = [
    "Top-1",
    "Top-2",
    "Top-3",
    "Top-5",
    "Macro Precision",
    "Macro Recall",
    "Macro F1",
    "Weighted F1",
]

primary_metric_comparison = campaign_comparison[
    ["Experiment"] + PRIMARY_METRICS
].copy()

PRIMARY_METRIC_CSV = (
    OUTPUT_DIR / "F09_primary_metric_comparison.csv"
)

primary_metric_comparison.to_csv(
    PRIMARY_METRIC_CSV,
    index=False,
)

# -------------------------------------------------------------------------
# Required table 4 — Validation versus test generalization
# -------------------------------------------------------------------------

LOCKED_VALIDATION = {
    "F06": {
        "Top-1": 92.9878,
        "Macro Recall": 90.6790,
        "Macro F1": 88.5122,
    },
    "F07": {
        "Top-1": 92.6829,
        "Macro Recall": 91.2771,
        "Macro F1": 88.9836,
    },
    "F08": {
        "Top-1": 93.4451,
        "Macro Recall": 93.0674,
        "Macro F1": 90.7359,
    },
}

indexed = campaign_comparison.set_index("Experiment")

generalization_rows = []

for exp, val_metrics in LOCKED_VALIDATION.items():

    generalization_rows.append({
        "Experiment": exp,

        "Validation Top-1 (%)":
            val_metrics["Top-1"],

        "Test Top-1 (%)":
            indexed.loc[exp, "Top-1"],

        "Top-1 Test-Val Gap (pp)":
            indexed.loc[exp, "Top-1"]
            - val_metrics["Top-1"],

        "Validation Macro Recall (%)":
            val_metrics["Macro Recall"],

        "Test Macro Recall (%)":
            indexed.loc[exp, "Macro Recall"],

        "Macro Recall Test-Val Gap (pp)":
            indexed.loc[exp, "Macro Recall"]
            - val_metrics["Macro Recall"],

        "Validation Macro F1 (%)":
            val_metrics["Macro F1"],

        "Test Macro F1 (%)":
            indexed.loc[exp, "Macro F1"],

        "Macro F1 Test-Val Gap (pp)":
            indexed.loc[exp, "Macro F1"]
            - val_metrics["Macro F1"],
    })

generalization = pd.DataFrame(generalization_rows)

numeric_cols = generalization.select_dtypes(
    include="number"
).columns

generalization[numeric_cols] = (
    generalization[numeric_cols].round(4)
)

GENERALIZATION_CSV = (
    OUTPUT_DIR
    / "F09_validation_vs_test_generalization.csv"
)

generalization.to_csv(
    GENERALIZATION_CSV,
    index=False,
)

# -------------------------------------------------------------------------
# Publication-ready figure 1
# -------------------------------------------------------------------------

plot_data = campaign_comparison.set_index("Experiment")

ax = plot_data[
    ["Top-1", "Macro F1"]
].plot(
    kind="bar",
    figsize=(11, 6),
)

ax.set_title(
    "AQUA20 Final Campaign: Top-1 and Macro F1"
)
ax.set_xlabel("Experiment")
ax.set_ylabel("Performance (%)")
ax.set_ylim(60, 100)
ax.legend(title="Metric")
ax.grid(axis="y", alpha=0.3)

plt.tight_layout()

FIGURE_1 = (
    FIGURE_DIR
    / "F09_campaign_top1_macro_f1.png"
)

plt.savefig(
    FIGURE_1,
    dpi=300,
    bbox_inches="tight",
)

plt.close()

# -------------------------------------------------------------------------
# Publication-ready figure 2
# -------------------------------------------------------------------------

ax = plot_data[
    ["Top-5", "Weighted F1"]
].plot(
    kind="bar",
    figsize=(11, 6),
)

ax.set_title(
    "AQUA20 Final Campaign: Top-5 and Weighted F1"
)
ax.set_xlabel("Experiment")
ax.set_ylabel("Performance (%)")
ax.set_ylim(75, 101)
ax.legend(title="Metric")
ax.grid(axis="y", alpha=0.3)

plt.tight_layout()

FIGURE_2 = (
    FIGURE_DIR
    / "F09_campaign_top5_weighted_f1.png"
)

plt.savefig(
    FIGURE_2,
    dpi=300,
    bbox_inches="tight",
)

plt.close()

# -------------------------------------------------------------------------
# Publication-ready figure 3
# -------------------------------------------------------------------------

effect_plot = intervention_effects.set_index(
    "Intervention"
)[
    [
        "Δ Top-1 (pp)",
        "Δ Macro Recall (pp)",
        "Δ Macro F1 (pp)",
        "Δ Weighted F1 (pp)",
    ]
]

ax = effect_plot.plot(
    kind="bar",
    figsize=(13, 7),
)

ax.set_title(
    "AQUA20 Campaign Intervention Effects"
)
ax.set_xlabel("Intervention")
ax.set_ylabel("Change from reference (percentage points)")
ax.axhline(0, linewidth=1)
ax.legend(title="Metric")
ax.grid(axis="y", alpha=0.3)

plt.xticks(
    rotation=20,
    ha="right",
)

plt.tight_layout()

FIGURE_3 = (
    FIGURE_DIR
    / "F09_intervention_effect_deltas.png"
)

plt.savefig(
    FIGURE_3,
    dpi=300,
    bbox_inches="tight",
)

plt.close()

# -------------------------------------------------------------------------
# Verify eight required final tables
# -------------------------------------------------------------------------

REQUIRED_TABLES = [
    OUTPUT_DIR / "F09_F01_F08_campaign_comparison.csv",
    PRIMARY_METRIC_CSV,
    OUTPUT_DIR / "F09_intervention_effect_comparison.csv",
    GENERALIZATION_CSV,
    OUTPUT_DIR / "F09_final_method_selection.csv",
    OUTPUT_DIR / "F09_beat_base_target_comparison.csv",
    OUTPUT_DIR / "F09_source_checkpoint_freeze_record.csv",
    OUTPUT_DIR / "F09_scientific_conclusions.csv",
]

for table_path in REQUIRED_TABLES:
    assert table_path.exists(), (
        f"Required table missing: {table_path.name}"
    )

# -------------------------------------------------------------------------
# Create final README
# -------------------------------------------------------------------------

README_PATH = BASE_DIR / "README_F09.txt"

README_TEXT = """AQUA20 F09 FINAL METHOD FREEZE AND CAMPAIGN CONSOLIDATION
======================================================================

Official campaign:
04-07-2026 AQUA20 FINAL BEAT BASE PLAN

Experiment:
F09_FINAL_METHOD_FREEZE_AND_CAMPAIGN_COMPARISON

F09 mode:
ANALYSIS
COMPARISON
FINAL METHOD SELECTION
CAMPAIGN FREEZE

Training performed:
NONE

New checkpoint produced:
NONE


FINAL REPORTING HIERARCHY
======================================================================

Primary proposed method:
F06_CONVNEXT_SMALL_HR384_GENTLE_CB_FOCAL

Primary scientific role:
Strongest completed balanced-class method.

F06 official test:
Top-1            : 92.1216%
Top-2            : 97.9529%
Top-3            : 99.2556%
Top-5            : 99.7519%
Macro Precision  : 90.4312%
Macro Recall     : 87.4362%
Macro F1         : 88.1699%
Weighted F1      : 92.0810%


Complementary final ensemble:
F08_CONVNEXT_SMALL_HR384_YOLO26M_PROB_ENSEMBLE

Frozen ensemble rule:
0.70 F06 + 0.30 F01

F08 official test:
Top-1            : 92.2457%
Top-2            : 98.0769%
Top-3            : 99.3797%
Top-5            : 99.8759%
Macro Precision  : 90.6725%
Macro Recall     : 87.0170%
Macro F1         : 87.9406%
Weighted F1      : 92.1750%


FINAL SCIENTIFIC DECISIONS
======================================================================

Primary proposed method:
F06

Complementary final ensemble:
F08

Strongest balanced-class model:
F06

Strongest ranking model:
F08

Best isolated imbalance intervention:
F03 — Gentle Class-Balanced Focal Loss


INTERVENTION FINDINGS
======================================================================

Gentle CB Focal:
Stronger than Aug-200 as an isolated imbalance intervention.

Aug-200:
Weaker than the Gentle CB Focal branch for balanced-class performance.

Aug-200 + Gentle CB Focal:
The two interventions were not complementary.

HR384:
Improved the F03 branch and produced the strongest balanced-class model.

Horizontal-flip TTA:
Did not improve the official-test balanced-class metrics.

Cross-family probability ensemble:
Improved Top-1, Top-2, Top-3, Top-5, Macro Precision, and Weighted F1
over F06, but reduced Macro Recall and Macro F1.


SOURCE CHECKPOINT FREEZE
======================================================================

F06 checkpoint:
best_model.pth

F06 best epoch:
2

F06 SHA-256:
d0c225c28b25f09822bc99518a37f9b1fe642b2d01213da7f68e2d76a255832a


F01 checkpoint:
best.pt

F01 best epoch:
2

F01 SHA-256:
aa489def1443a6cdab42a0a20a530b9e341d574dcaaf234bfe6c7983113e8e5a


BEAT-BASE TARGET STATUS
======================================================================

Reference Top-1 target:
92.6800%

Best final-campaign Top-1:
92.2457%

Best Top-1 experiment:
F08

Gap:
-0.4343 percentage points

Target status:
NOT BEATEN

The 92.68% Top-1 target must not be reported as beaten.


FINAL CAMPAIGN INTERPRETATION
======================================================================

The completed controlled campaign shows that Gentle Class-Balanced Focal
Loss was the strongest isolated imbalance intervention.

High-resolution 384 x 384 fine-tuning positively improved this branch and
produced F06, the strongest completed balanced-class model.

Deterministic horizontal-flip TTA did not improve the official-test
balanced metrics.

The validation-governed F06 + F01 probability ensemble improved overall
ranking and top-k performance, producing the strongest campaign ranking
result, but did not improve official-test Macro Recall or Macro F1 over F06.

Therefore F06 is frozen as the primary proposed AQUA20 method, while F08
is retained as a complementary ranking ensemble result.

F09 is closed.
"""

README_PATH.write_text(
    README_TEXT,
    encoding="utf-8",
)

# -------------------------------------------------------------------------
# Create official ZIP
# -------------------------------------------------------------------------

ZIP_PATH = Path(
    "/kaggle/working/"
    "AQUA20_FINAL_BEAT_BASE_04072026/"
    "aqua20_f09_final_method_freeze_campaign_outputs.zip"
)

with zipfile.ZipFile(
    ZIP_PATH,
    "w",
    zipfile.ZIP_DEFLATED,
) as zip_file:

    zip_file.write(
        README_PATH,
        README_PATH.name,
    )

    for file_path in sorted(OUTPUT_DIR.glob("*.csv")):
        zip_file.write(
            file_path,
            Path("tables") / file_path.name,
        )

    for file_path in sorted(FIGURE_DIR.glob("*.png")):
        zip_file.write(
            file_path,
            Path("figures") / file_path.name,
        )

# -------------------------------------------------------------------------
# Clean final output
# -------------------------------------------------------------------------

table_count = len(list(OUTPUT_DIR.glob("*.csv")))
figure_count = len(list(FIGURE_DIR.glob("*.png")))

print("\nFINAL F09 EVIDENCE SUMMARY")
print("-" * 100)

print(f"{'Required final tables':<34}: 8 / 8 VERIFIED")
print(f"{'CSV tables in package':<34}: {table_count}")
print(f"{'Publication-ready figures':<34}: {figure_count}")
print(f"{'README':<34}: {README_PATH.name}")
print(f"{'Training performed':<34}: NONE")
print(f"{'New checkpoint produced':<34}: NONE")

print("\nVALIDATION VS TEST GENERALIZATION")
print("-" * 100)

print(
    generalization.to_string(
        index=False
    )
)

print("\nOFFICIAL PACKAGE CONTENTS")
print("-" * 100)

with zipfile.ZipFile(ZIP_PATH, "r") as zip_file:
    for name in zip_file.namelist():
        print(name)

print("\nPACKAGE DETAILS")
print("-" * 100)

print(f"{'Final package':<20}: {ZIP_PATH}")
print(
    f"{'ZIP size':<20}: "
    f"{ZIP_PATH.stat().st_size / 1024**2:.2f} MB"
)

print("\n" + "=" * 100)
print("F09 STEP 5 PASSED — OFFICIAL FINAL CAMPAIGN PACKAGE CREATED")
print("=" * 100)
print("F09 STATUS                     : COMPLETED")
print("PRIMARY PROPOSED METHOD        : F06")
print("COMPLEMENTARY FINAL ENSEMBLE   : F08")
print("92.68% TOP-1 TARGET            : NOT BEATEN")
print("CAMPAIGN REPORTING HIERARCHY   : FROZEN")
print("DOWNLOAD                       :", ZIP_PATH)

====================================================================================================
F09 Step 5 — Create final campaign evidence package
====================================================================================================

FINAL F09 EVIDENCE SUMMARY
----------------------------------------------------------------------------------------------------
Required final tables             : 8 / 8 VERIFIED
CSV tables in package             : 8
Publication-ready figures         : 3
README                            : README_F09.txt
Training performed                : NONE
New checkpoint produced           : NONE

VALIDATION VS TEST GENERALIZATION
----------------------------------------------------------------------------------------------------
Experiment  Validation Top-1 (%)  Test Top-1 (%)  Top-1 Test-Val Gap (pp)  Validation Macro Recall (%)  Test Macro Recall (%)  Macro Recall Test-Val Gap (pp)  Validation Macro F1 (%)  Test Macro F1 (%)  Macro F1 Test-Val Gap (pp)
       F06               92.9878         92.1216                  -0.8662                      90.6790                87.4362                         -3.2428                  88.5122            88.1699                     -0.3423
       F07               92.6829         92.1216                  -0.5613                      91.2771                86.5324                         -4.7447                  88.9836            87.4026                     -1.5810
       F08               93.4451         92.2457                  -1.1994                      93.0674                87.0170                         -6.0504                  90.7359            87.9406                     -2.7953

OFFICIAL PACKAGE CONTENTS
----------------------------------------------------------------------------------------------------
README_F09.txt
tables/F09_F01_F08_campaign_comparison.csv
tables/F09_beat_base_target_comparison.csv
tables/F09_final_method_selection.csv
tables/F09_intervention_effect_comparison.csv
tables/F09_primary_metric_comparison.csv
tables/F09_scientific_conclusions.csv
tables/F09_source_checkpoint_freeze_record.csv
tables/F09_validation_vs_test_generalization.csv
figures/F09_campaign_top1_macro_f1.png
figures/F09_campaign_top5_weighted_f1.png
figures/F09_intervention_effect_deltas.png

PACKAGE DETAILS
----------------------------------------------------------------------------------------------------
Final package       : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/aqua20_f09_final_method_freeze_campaign_outputs.zip
ZIP size            : 0.34 MB

====================================================================================================
F09 STEP 5 PASSED — OFFICIAL FINAL CAMPAIGN PACKAGE CREATED
====================================================================================================
F09 STATUS                     : COMPLETED
PRIMARY PROPOSED METHOD        : F06
COMPLEMENTARY FINAL ENSEMBLE   : F08
92.68% TOP-1 TARGET            : NOT BEATEN
CAMPAIGN REPORTING HIERARCHY   : FROZEN
DOWNLOAD                       : /kaggle/working/AQUA20_FINAL_BEAT_BASE_04072026/aqua20_f09_final_method_freeze_campaign_outputs.zip

# X01 Step 1 — Input and Scientific Lock Verification

This step verifies the frozen F06 primary proposed model, official F09 campaign decision, F06 checkpoint SHA-256, official test predictions, class count, and AQUA20 test split.

The X01 output structure is also prepared.

**No XAI sample selection is performed in this step.**

**No Grad-CAM is generated in this step.**

In [8]:
# ============================================================
# X01 STEP 1 — INPUT AND SCIENTIFIC LOCK VERIFICATION
# ============================================================

from pathlib import Path
import hashlib
import zipfile
import pandas as pd

INPUT_ROOT = Path("/kaggle/input")
WORK_ROOT = Path("/kaggle/working/X01_F06_FINAL_GRADCAM")
CACHE_ROOT = WORK_ROOT / "_verified_inputs"

F06_ID = "F06_CONVNEXT_SMALL_HR384_GENTLE_CB_FOCAL"
EXPECTED_SHA = "d0c225c28b25f09822bc99518a37f9b1fe642b2d01213da7f68e2d76a255832a"

IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}

print("=" * 100)
print("X01 STEP 1 — INPUT AND SCIENTIFIC LOCK VERIFICATION")
print("=" * 100)


# ------------------------------------------------------------
# Small helpers
# ------------------------------------------------------------

def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for block in iter(lambda: f.read(1024 * 1024), b""):
            h.update(block)
    return h.hexdigest()


def find_named_file(filename):
    target = filename.lower()

    for path in INPUT_ROOT.rglob("*"):
        if path.is_file() and path.name.lower() == target:
            return path

    CACHE_ROOT.mkdir(parents=True, exist_ok=True)

    for zip_path in INPUT_ROOT.rglob("*.zip"):
        with zipfile.ZipFile(zip_path) as zf:
            for member in zf.namelist():
                if Path(member).name.lower() == target:
                    out_path = CACHE_ROOT / filename
                    with zf.open(member) as src, open(out_path, "wb") as dst:
                        dst.write(src.read())
                    return out_path

    raise FileNotFoundError(f"Could not locate: {filename}")


# ------------------------------------------------------------
# Locate official files
# ------------------------------------------------------------

pred_path = find_named_file("F06_test_predictions.csv")
report_path = find_named_file("F06_classification_report.csv")
selection_path = find_named_file("F09_final_method_selection.csv")
freeze_path = find_named_file("F09_source_checkpoint_freeze_record.csv")

print("\nOFFICIAL FILE DISCOVERY")
print("-" * 100)
print(f"{'F06 predictions':32} : {pred_path}")
print(f"{'F06 classification report':32} : {report_path}")
print(f"{'F09 method selection':32} : {selection_path}")
print(f"{'F09 checkpoint freeze record':32} : {freeze_path}")


# ------------------------------------------------------------
# Verify F09 primary-method decision
# ------------------------------------------------------------

selection_df = pd.read_csv(selection_path)
selection_rows = selection_df.astype(str).agg(" | ".join, axis=1)

f06_rows = selection_rows[
    selection_rows.str.contains(F06_ID, case=False, regex=False)
]

primary_ok = (
    len(f06_rows) > 0
    and f06_rows.str.contains("primary", case=False, regex=False).any()
)

assert primary_ok, "F09 does not verify F06 as the primary method."


# ------------------------------------------------------------
# Locate and verify frozen F06 checkpoint
# ------------------------------------------------------------

checkpoint_path = None
checkpoint_sha = None

for path in INPUT_ROOT.rglob("*"):
    if path.is_file() and path.name.lower() == "best_model.pth":
        file_sha = sha256_file(path)
        if file_sha == EXPECTED_SHA:
            checkpoint_path = path
            checkpoint_sha = file_sha
            break

if checkpoint_path is None:
    CACHE_ROOT.mkdir(parents=True, exist_ok=True)

    for zip_path in INPUT_ROOT.rglob("*.zip"):
        with zipfile.ZipFile(zip_path) as zf:
            for member in zf.namelist():
                if Path(member).name.lower() == "best_model.pth":
                    out_path = CACHE_ROOT / "best_model.pth"

                    with zf.open(member) as src, open(out_path, "wb") as dst:
                        dst.write(src.read())

                    file_sha = sha256_file(out_path)

                    if file_sha == EXPECTED_SHA:
                        checkpoint_path = out_path
                        checkpoint_sha = file_sha
                        break

        if checkpoint_path is not None:
            break

assert checkpoint_path is not None, "Frozen F06 checkpoint SHA-256 not found."


# ------------------------------------------------------------
# Verify official F06 test predictions
# ------------------------------------------------------------

pred_df = pd.read_csv(pred_path)

true_candidates = [
    "true_class",
    "true_label",
    "ground_truth",
    "actual_class",
    "y_true",
]

true_col = next(
    (col for col in pred_df.columns if col.lower() in true_candidates),
    None,
)

assert true_col is not None, (
    f"Could not identify true-class column. Columns: {list(pred_df.columns)}"
)

test_predictions = len(pred_df)
num_classes = pred_df[true_col].nunique()

assert test_predictions == 1612, (
    f"Expected 1,612 test predictions, found {test_predictions}."
)

assert num_classes == 20, (
    f"Expected 20 classes, found {num_classes}."
)


# ------------------------------------------------------------
# Verify original AQUA20 test split
# ------------------------------------------------------------

test_candidates = []

for path in INPUT_ROOT.rglob("*"):
    if path.is_dir() and path.name.lower() == "test":
        image_count = sum(
            1 for p in path.rglob("*")
            if p.is_file() and p.suffix.lower() in IMAGE_EXTS
        )

        if image_count == 1612:
            test_candidates.append(path)

assert test_candidates, "Official 1,612-image AQUA20 test split not found."

test_root = test_candidates[0]


# ------------------------------------------------------------
# Create official X01 output structure
# ------------------------------------------------------------

output_dirs = [
    WORK_ROOT / "tables",
    WORK_ROOT / "gradcam" / "originals",
    WORK_ROOT / "gradcam" / "heatmaps",
    WORK_ROOT / "gradcam" / "overlays",
    WORK_ROOT / "figures",
]

for folder in output_dirs:
    folder.mkdir(parents=True, exist_ok=True)


# ------------------------------------------------------------
# Final verification summary
# ------------------------------------------------------------

print("\nSCIENTIFIC LOCK VERIFICATION")
print("-" * 100)
print(f"{'Official stage':32} : X01_F06_FINAL_GRADCAM")
print(f"{'Primary model':32} : {F06_ID}")
print(f"{'F09 primary-method lock':32} : VERIFIED")
print(f"{'Checkpoint':32} : {checkpoint_path}")
print(f"{'Checkpoint SHA-256':32} : {checkpoint_sha}")
print(f"{'Checkpoint SHA status':32} : VERIFIED")
print(f"{'Official test predictions':32} : {test_predictions}")
print(f"{'Classes':32} : {num_classes}")
print(f"{'Official test split':32} : {test_root}")
print(f"{'Official test images':32} : 1,612")
print(f"{'X01 output root':32} : {WORK_ROOT}")

print("\nXAI STATUS")
print("-" * 100)
print(f"{'Sample selection':32} : NOT STARTED")
print(f"{'Grad-CAM generation':32} : NOT STARTED")
print(f"{'Training':32} : NONE")
print(f"{'New checkpoint':32} : NONE")

print("\n" + "=" * 100)
print("X01 STEP 1 PASSED — INPUTS AND SCIENTIFIC LOCK VERIFIED")
print("=" * 100)
print(f"{'STATUS':32} : READY FOR X01 STEP 2")

====================================================================================================
X01 STEP 1 — INPUT AND SCIENTIFIC LOCK VERIFICATION
====================================================================================================

FileNotFoundError: Could not locate: F09_final_method_selection.csv